window.__examLoadCallback({
  "title": "Compiler Design - Syntax Directed Translation",
  "duration": 47,
  "sections": [
    {
      "name": "Syntax Directed Translation",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"590\"></a><div itemprop=\"text\"><p>Write syntax directed definitions (semantic rules) for the following grammar to add the type of each identifier to its entry in the symbol table during semantic analysis. Rewriting the grammar is not permitted and semantic rules are to be added to the ends of productions only.</p>\n\n<ul>\n\t<li>\\( D \\rightarrow TL; \\)</li>\n\t<li>\\( T \\rightarrow \\text{int} \\)</li>\n\t<li>\\( T \\rightarrow \\text{real} \\)</li>\n\t<li>\\( L \\rightarrow L,id \\)</li>\n\t<li>\\( L \\rightarrow id \\)</li>\n</ul></div><br><br><b>GATE CSE 1992 | Question: 11a</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "N/A",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/590/gate-cse-1992-question-11a\" target=\"_blank\">https://gateoverflow.in/590/gate-cse-1992-question-11a</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"2622\"></a><div itemprop=\"text\"><p>A shift reduce parser carries out the actions specified within braces immediately after reducing with the corresponding rule of grammar</p>\n\n<ul>\n\t<li>\\( S \\rightarrow xxW&nbsp;\\;\\text{{print“1\"}} \\)</li>\n\t<li>\\( S \\rightarrow y \\;\\text{{print“2\"}} \\)</li>\n\t<li>\\( W \\rightarrow Sz\\; \\text{{print“3\"}} \\)</li>\n</ul>\n\n<p>What is the translation of \\( xxxxyzz \\) using the syntax directed translation scheme described by the above rules?</p>\n\n</div><br><br><b>GATE CSE 1995 | Question: 2.10</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 23131 \\)</p>",
            "<p>\\( 11233 \\)</p>",
            "<p>\\( 11231 \\)</p>",
            "<p>\\( 33211 \\)</p>"
          ],
          "correct_answer": "<p>\\( 23131 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/2622/gate-cse-1995-question-2-10\" target=\"_blank\">https://gateoverflow.in/2622/gate-cse-1995-question-2-10</a></p>"
        },
        {
          "id": 3,
          "question": "<p><a name=\"2772\"></a><div itemprop=\"text\"><p>Consider the syntax-directed translation schema (SDTS) shown below:</p>\n\n<ul>\n\t<li>\\( E\\rightarrow E + E \\) {print “+”}</li>\n\t<li>\\( E\\rightarrow E * E \\) {print “.”}</li>\n\t<li>\\( E\\rightarrow id \\) {print id.name}</li>\n\t<li>\\( E\\rightarrow (E) \\)</li>\n</ul>\n\n<p>An LR-parser executes the actions associated with the productions immediately after a reduction by the corresponding production. Draw the parse tree and write the translation for the sentence.</p>\n\n<p>\\( (a+b)*(c+d) \\), using SDTS given above.</p></div><br><br><b>GATE CSE 1996 | Question: 20</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "N/A",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/2772/gate-cse-1996-question-20\" target=\"_blank\">https://gateoverflow.in/2772/gate-cse-1996-question-20</a></p>"
        },
        {
          "id": 4,
          "question": "<p><a name=\"1738\"></a><div itemprop=\"text\"><p>Let the attribute ‘\\( val \\)’ give the value of a binary number generated by \\( S \\) in the following grammar:</p>\n\n<ul>\n\t<li>\\( S \\rightarrow L.L \\mid L \\)</li>\n\t<li>\\( L \\rightarrow LB \\mid B \\)</li>\n\t<li>\\( B \\rightarrow 0 \\mid 1 \\)</li>\n</ul>\n\n<p>For example, an input \\( 101.101 \\) gives \\( S.val = 5.625 \\)</p>\n\n<p>Construct a syntax directed translation scheme using only synthesized attributes, to determine \\( S.val \\).</p></div><br><br><b>GATE CSE 1998 | Question: 23</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "N/A",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/1738/gate-cse-1998-question-23\" target=\"_blank\">https://gateoverflow.in/1738/gate-cse-1998-question-23</a></p>"
        },
        {
          "id": 5,
          "question": "<p><a name=\"690\"></a><div itemprop=\"text\"><p>Consider the syntax directed translation scheme \\( \\textsf{(SDTS)} \\) given in the following. Assume attribute evaluation with bottom-up parsing, i.e., attributes are&nbsp;evaluated immediately after a reduction.</p>\n\n<ul>\n\t<li>\\( E\\rightarrow&nbsp;&nbsp;E_{1}&nbsp;* T \\qquad \\{E.val = E_{1}.val * T.val\\} \\)</li>\n\t<li>\\( E\\rightarrow&nbsp;&nbsp;T \\qquad&nbsp;\\qquad \\{E.val = T.val\\} \\)</li>\n\t<li>\\( T\\rightarrow&nbsp;&nbsp;F - T_{1}\\qquad \\{T.val = F.val - T_{1}.val\\} \\)</li>\n\t<li>\\( T\\rightarrow&nbsp;F&nbsp;\\qquad \\qquad \\{T.val = F.val\\} \\)</li>\n\t<li>\\( F\\rightarrow 2&nbsp;\\qquad \\qquad \\{F.val = 2\\} \\)</li>\n\t<li>\\( F\\rightarrow 4 \\qquad \\qquad \\{F.val = 4\\} \\)</li>\n</ul>\n\n</div><br><br><b>GATE CSE 2000 | Question: 19</b></p>",
          "type": "numeric",
          "options": [
            "<p>Using this \\( \\textsf{SDTS}, \\)&nbsp;construct a parse tree for the expression \\( 4 - 2 - 4 * 2 \\)&nbsp; and also compute its \\( E.val \\).</p>",
            "<p>It is required to compute the total number of reductions performed to parse&nbsp;a given input. Using synthesized attributes only, modify the \\( \\textsf{SDTS} \\) given, without changing the&nbsp;grammar, to find \\( E.red \\), the number of reductions&nbsp;performed while reducing an input to \\( E \\).</p>"
          ],
          "correct_answer": "N/A",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/690/gate-cse-2000-question-19\" target=\"_blank\">https://gateoverflow.in/690/gate-cse-2000-question-19</a></p>"
        },
        {
          "id": 6,
          "question": "<p><a name=\"758\"></a><div itemprop=\"text\">The syntax of the repeat-until statement is given by the following grammar<br>\n<br>\n\\( S \\rightarrow\\text{ repeat }S_1\\text{ until }E \\)<br>\n<br>\nwhere E stands for expressions, \\( S \\) and \\( S_1 \\) stand for statements. The non-terminals \\( S \\) and \\( S_1 \\) have an attribute code that represents generated code. The non-terminal E has two attributes. The attribute code represents generated code to evaluate the expression and store its value in a &nbsp;distinct variable, and the attribute varName contains the name of the variable in which the truth value is stored. The truth-value stored in the variable is 1 if E is true, 0 if E is false.<br>\n<br>\nGive a syntax-directed definition to generate three-address code for the repeat-until statement. Assume that you can call a function newlabel() that returns a distinct label for a statement. Use the operator '\\\\' to concatenate two strings and the function gen(s) to generate a line containing the string s.</div><br><br><b>GATE CSE 2001 | Question: 17</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "N/A",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/758/gate-cse-2001-question-17\" target=\"_blank\">https://gateoverflow.in/758/gate-cse-2001-question-17</a></p>"
        },
        {
          "id": 7,
          "question": "<p><a name=\"908\"></a><div itemprop=\"text\"><p>In a bottom-up evaluation of a syntax directed definition, inherited attributes can</p>\n\n</div><br><br><b>GATE CSE 2003 | Question: 18</b></p>",
          "type": "single",
          "options": [
            "<p>always be evaluated</p>",
            "<p>be evaluated only if the definition is L-attributed</p>",
            "<p>be evaluated only if the definition has synthesized attributes</p>",
            "<p>never be evaluated</p>"
          ],
          "correct_answer": "<p>be evaluated only if the definition is L-attributed</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/908/gate-cse-2003-question-18\" target=\"_blank\">https://gateoverflow.in/908/gate-cse-2003-question-18</a></p>"
        },
        {
          "id": 8,
          "question": "<p><a name=\"947\"></a><div itemprop=\"text\"><p>Consider the syntax directed definition shown below.\\[ \\begin{array}{ll}<br>S \\rightarrow \\mathbf{&nbsp;id :=}&nbsp;E&amp;\\qquad&nbsp;\\{gen(\\mathbf{&nbsp;id}.place = E.place;);\\}\\\\<br>E \\rightarrow E_1 + E_2 &amp;\\qquad \\{t =&nbsp;newtemp();\\\\<br>&amp;\\qquad gen(t = E_1.place + E_2.place;);\\\\<br>&amp;\\qquad E.place =&nbsp;t;\\}\\\\<br>E \\rightarrow&nbsp;id&amp;\\qquad \\{E.place = \\mathbf{id}.place;\\}<br>\\end{array} \\]Here, \\( gen \\) is a function that generates the output code, and \\( newtemp \\) is a function that returns the name of a new temporary variable on every call. Assume that \\( t_i' \\)s are the temporary variable names generated by \\( newtemp \\). For the statement \\( \\text{‘}X : = Y + Z\\text{'}, \\) the \\( 3 \\)-address code sequence generated by this definition is</p></div><br><br><b>GATE CSE 2003 | Question: 59</b></p>",
          "type": "single",
          "options": [
            "<p>\\( X = Y + Z \\)</p>",
            "<p>\\( t_1 = Y+Z; X=t_1 \\)</p>",
            "<p>\\( t_1 =Y; t_2=t_1 +Z; X=t_2 \\)</p>",
            "<p>\\( t_1&nbsp;=Y; t_2=Z; t_3=t_1+t_2;&nbsp;X=t_3 \\)</p>"
          ],
          "correct_answer": "<p>\\( t_1 = Y+Z; X=t_1 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/947/gate-cse-2003-question-59\" target=\"_blank\">https://gateoverflow.in/947/gate-cse-2003-question-59</a></p>"
        },
        {
          "id": 9,
          "question": "<p><a name=\"39700\"></a><div itemprop=\"text\"><p>Consider the following Syntax Directed Translation Scheme \\( ( SDTS ) \\), with non-terminals \\( \\{S,A \\} \\) and terminals \\( \\{a,b \\} \\).</p>\n\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; \\( S \\to aA &nbsp;\\quad \\{\\text{print }1\\} \\)</p>\n\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;\\( S \\to a &nbsp; &nbsp;\\quad &nbsp; \\{\\text{print }2\\} \\)</p>\n\n<p>&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;\\( A \\to Sb &nbsp;\\quad \\{\\text{print }3\\} \\)</p>\n\n<p>Using the above \\( SDTS \\) , the output printed by a bottom-up parser, for the input \\( aab \\) is:</p>\n\n</div><br><br><b>GATE CSE 2016 Set 1 | Question: 46</b></p>",
          "type": "single",
          "options": [
            "<p>&nbsp;\\( 1 \\ 3 \\ 2  \\)&nbsp;</p>",
            "<p>&nbsp;\\( 2 \\ 2 \\ 3 &nbsp; \\)&nbsp;</p>",
            "<p>&nbsp;\\( 2 \\ 3 \\ 1  \\)&nbsp;</p>",
            "<p>&nbsp;syntax error</p>"
          ],
          "correct_answer": "<p>&nbsp;\\( 2 \\ 3 \\ 1  \\)&nbsp;</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/39700/gate-cse-2016-set-1-question-46\" target=\"_blank\">https://gateoverflow.in/39700/gate-cse-2016-set-1-question-46</a></p>"
        },
        {
          "id": 10,
          "question": "<p><a name=\"302812\"></a><div itemprop=\"text\"><p>Consider the following grammar and the semantic actions to support the&nbsp;inherited type declaration attributes. Let \\( X_1, X_2, X_3, X_4, X_5 \\), and \\( X_6 \\) be the placeholders for the non-terminals \\( D, T, L \\) or \\( L_1 \\) in the following table:</p>\n\n<p>\\[ \\begin{array}{|l|l|} \\hline&nbsp; \\text{Production rule} &amp; \\text{Semantic action} \\\\ \\hline D \\rightarrow T L &amp; X_1.\\text{type} = X_2.\\text{type} \\\\ \\hline T \\rightarrow&nbsp;\\text{int} &amp; T.\\text{type} =&nbsp;\\text{int} \\\\ \\hline T \\rightarrow&nbsp;\\text{float} &amp; T.\\text{type} = \\text{float} \\\\ \\hline<br>\nL \\rightarrow L_1, id &amp; X_3.\\text{type}= X_4.\\text{type} &nbsp;\\\\&nbsp;<br>\n&amp;\\text{addType}(id.&nbsp;\\text{entry}, X_5.\\text{type})\\\\ \\hline<br>\nL \\rightarrow id &amp;&nbsp;\\text{addType}(id.&nbsp;\\text{entry}, X_6.\\text{type}) \\\\ \\hline \\end{array} \\]</p>\n\n<p>Which one of the following are appropriate choices for \\( X_1, X_2, X_3 \\) and \\( X_4 \\)?</p>\n\n</div><br><br><b>GATE CSE 2019 | Question: 36</b></p>",
          "type": "single",
          "options": [
            "<p>\\( X_1=L, \\: X_2=T, \\: X_3=L_1, \\: X_4 = L \\)</p>",
            "<p>\\( X_1=T, \\: X_2=L, \\: X_3=L_1, \\: X_4 = T \\)</p>",
            "<p>\\( X_1=L, \\: X_2=L, \\: X_3=L_1, \\: X_4 = T \\)</p>",
            "<p>\\( X_1=T, \\: X_2=L, \\: X_3=T, \\: X_4 = L_1 \\)</p>"
          ],
          "correct_answer": "<p>\\( X_1=L, \\: X_2=T, \\: X_3=L_1, \\: X_4 = L \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/302812/gate-cse-2019-question-36\" target=\"_blank\">https://gateoverflow.in/302812/gate-cse-2019-question-36</a></p>"
        },
        {
          "id": 11,
          "question": "<p><a name=\"333198\"></a><div itemprop=\"text\"><p>Consider the productions \\( A \\rightarrow&nbsp;PQ \\) and \\( A \\rightarrow&nbsp;&nbsp;XY \\). Each of the five non-terminals \\( A, P, Q, X, \\)&nbsp;and \\( Y \\) has two attributes: \\( s \\) is a synthesized attribute, and \\( i \\) is an inherited attribute. Consider the following rules.</p>\n\n<ul>\n\t<li>Rule \\( 1: P . i&nbsp;= A.i&nbsp;+ 2, \\: Q.i&nbsp;= P. i&nbsp;+ A.i, \\)&nbsp;and \\( A.s&nbsp;= P.s&nbsp;+Q. s \\)</li>\n\t<li>Rule \\( 2: X.i&nbsp;= A.i&nbsp;+ Y.s \\)&nbsp;and \\( Y. i&nbsp;= X. s&nbsp;+A .i \\)</li>\n</ul>\n\n<p>Which one of the following is TRUE?</p>\n\n</div><br><br><b>GATE CSE 2020 | Question: 33</b></p>",
          "type": "single",
          "options": [
            "<p>Both Rule \\( 1 \\) and Rule \\( 2 \\) are \\( L \\)-attributed.</p>",
            "<p>Only Rule \\( 1 \\) is \\( L \\)-attributed.</p>",
            "<p>Only Rule \\( 2 \\) is \\( L \\)-attributed.</p>",
            "<p>Neither Rule \\( 1 \\) nor Rule \\( 2 \\) is \\( L \\)-attributed.</p>"
          ],
          "correct_answer": "<p>Only Rule \\( 1 \\) is \\( L \\)-attributed.</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/333198/gate-cse-2020-question-33\" target=\"_blank\">https://gateoverflow.in/333198/gate-cse-2020-question-33</a></p>"
        },
        {
          "id": 12,
          "question": "<p><a name=\"357425\"></a><div itemprop=\"text\"><p>​​​Consider the following grammar (that admits a series of declarations, followed by expressions) and the associated syntax directed translation \\( \\text{(SDT)} \\) actions, given as pseudo-code</p>\n\n<p>\\( \\begin{array}{lll} P &amp; \\rightarrow&nbsp;&amp; D^* E^* \\\\ D &amp; \\rightarrow&nbsp;&amp; \\textsf{int ID} \\{ \\text{record that } \\textsf{ID.} \\text{lexeme is of type} \\textsf{ int\\}} \\\\&nbsp; D &amp; \\rightarrow&nbsp;&amp; \\textsf{bool&nbsp;ID} \\{ \\text{record that } \\textsf{ID.} \\text{lexeme is of type} \\textsf{ bool\\}}&nbsp; \\\\ E&amp; \\rightarrow&nbsp;&amp; E_1 +E_2 \\{ \\text{check that } E_1. \\text{type}=E_2. \\text{type} = \\textsf{int}; \\text{set }&nbsp; E.\\text{type }:= \\textsf{int} \\} \\\\ E &amp; \\rightarrow &amp; !E_1 \\{ \\text{check that } E_1. \\text{type} = \\textsf{bool}; \\text{ set } E.\\text{type} := \\textsf{bool} \\} \\\\ E &amp; \\rightarrow &amp; \\textsf{ID} \\{ \\text{set } E. \\text{type } := \\textsf{int} \\} \\end{array} \\)</p>\n\n<p>With respect to the above grammar, which one of the following choices is correct?</p>\n\n</div><br><br><b>GATE CSE 2021 Set 1 | Question: 26</b></p>",
          "type": "single",
          "options": [
            "<p>The actions can be used to correctly type-check any syntactically correct program</p>",
            "<p>The actions can be used to type-check syntactically correct integer variable declarations and integer expressions</p>",
            "<p>The actions can be used to type-check syntactically correct boolean variable declarations and boolean expressions.</p>",
            "<p>The actions will lead to an infinite loop</p>"
          ],
          "correct_answer": "<p>The actions can be used to type-check syntactically correct integer variable declarations and integer expressions</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/357425/gate-cse-2021-set-1-question-26\" target=\"_blank\">https://gateoverflow.in/357425/gate-cse-2021-set-1-question-26</a></p>"
        },
        {
          "id": 13,
          "question": "<p><a name=\"371881\"></a><div itemprop=\"text\">Consider the following grammar along with translation rules.<br>\n\\[ \\begin{aligned} &amp; S \\rightarrow S_{1} \\# T \\qquad \\{S._{\\text{val}} =S_{1}. _{\\text{val}} \\; ^{\\ast} T._{\\text{val}}\\}\\\\ &amp; S \\rightarrow T \\qquad \\qquad \\{S._{\\text{val}} = T._{\\text{val}}\\}\\\\ &nbsp;&amp; T \\rightarrow T_{1} \\% R \\qquad &nbsp;\\{T._{\\text{val}} =T_{1}._{\\text{val}} ÷ R._{\\text{val}}\\}\\\\ &nbsp;&amp; T \\rightarrow R \\qquad \\qquad \\{T._{\\text{val}} = R._{\\text{val}}\\} \\\\ &amp; R \\rightarrow \\text{id} \\qquad \\qquad \\{R._{\\text{val}} = \\text{id}._{\\text{val}}\\} \\end{aligned} \\]<br>\nHere \\( \\# \\) and \\( \\% \\) are operators and \\( \\text{id} \\) is a token that represents an integer and \\( \\text{id}._{\\text{val}} \\) represents the corresponding integer value. The set of non-terminals is \\( \\{\\text{S, T, R, P}\\} \\) and a subscripted non-terminal indicates an instance of the non-terminal.<br>\n<br>\nUsing this translation scheme, the computed value of \\( S._{\\text{val}} \\) for root of the parse tree for the expression \\( 20 \\# 10 \\% 5 \\# 8 \\% 2 \\% 2 \\) is ________________.</div><br><br><b>GATE CSE 2022 | Question: 55</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "80",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/371881/gate-cse-2022-question-55\" target=\"_blank\">https://gateoverflow.in/371881/gate-cse-2022-question-55</a></p>"
        },
        {
          "id": 14,
          "question": "<p><a name=\"399261\"></a><div itemprop=\"text\">Consider the syntax directed translation given by the following grammar and semantic rules. Here \\( N, I, F \\) and \\( B \\) are non-terminals. \\( N \\) is the starting non-terminal, and \\( \\#, \\mathbf{0} \\) and \\( \\mathbf{1} \\) are lexical tokens corresponding to input letters \\( \\text{“#\", “0\" and “1\"}, \\) respectively. \\( X.val \\) denotes the synthesized attribute (a numeric value) associated with a non-terminal \\( X. \\;I_{1} \\) and \\( F_{1} \\) denote occurrences of \\( I \\) and \\( F \\) on the right hand side of a production, respectively. For the tokens \\( \\mathbf{0} \\) and \\( \\mathbf{1}, \\mathbf{0} . v a l=0 \\) and \\( \\mathbf{1}.val =1 \\).<br>\n\\[<br>\n\\begin{array}{ll}<br>\nN \\rightarrow I \\# F &amp; &nbsp;N.val =I . v a l+F . v a l \\\\<br>\nI\\rightarrow I_{1} B &amp; &nbsp;I.val =\\left(2 I_{1} . v a l\\right)+B.val &nbsp;\\\\<br>\nI \\rightarrow &nbsp;B &amp; I.val =\\text { B.val } \\\\<br>\nF \\rightarrow B F_{1} &amp; F.val =\\frac{1}{2}\\left(B . v a l+F_{1} . v a l\\right) \\\\<br>\nF \\rightarrow B &amp; \\text { F.val }=\\frac{1}{2} B.val &nbsp;\\\\<br>\nB \\rightarrow \\mathbf{0} &amp; B . v a l=\\mathbf{0} . v a l \\\\<br>\nB \\rightarrow \\mathbf{1} &nbsp;&amp; B . v a l=\\mathbf{1} . v a l \\\\<br>\n\\end{array}<br>\n\\]<br>\nThe value computed by the translation scheme for the input string<br>\n\\[ 10\\#011 \\]<br>\nis ____________. (Rounded off to three decimal places)</div><br><br><b>GATE CSE 2023 | Question: 50</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "2.375",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/399261/gate-cse-2023-question-50\" target=\"_blank\">https://gateoverflow.in/399261/gate-cse-2023-question-50</a></p>"
        },
        {
          "id": 15,
          "question": "<p><a name=\"422815\"></a><div itemprop=\"text\"><p>​Consider the following syntax-directed definition \\( \\text{(SDD)} \\).</p><p>\\[ \\begin{array}{|l|l|} \\hline&nbsp; \\text{\\( S \\rightarrow D H T U \\)} &amp; \\text{\\( &nbsp;\\left\\{S.v a l =&nbsp;D.val + H.val + T.val + U.val;\\right\\} \\)} \\\\ \\hline D \\rightarrow ^{\"} \\mathrm{M}^{\"}&nbsp;D_1&nbsp;&amp; \\left\\{D.val&nbsp;=5+D_{1}.val; \\right\\}&nbsp;\\\\ \\hline D \\rightarrow \\epsilon&nbsp;&amp; \\left\\{D.val = -5; \\right\\}&nbsp;\\\\ \\hline H \\rightarrow ^{\"}\\mathrm{L}^{\"} H_1&nbsp;&amp; \\left\\{H.val = 5^{*} 10+H_{1}.v a l;\\right\\}&nbsp;\\\\ \\hline<br>H \\rightarrow \\epsilon&nbsp;&amp;&nbsp; \\left\\{H.val = -10; \\right\\}&nbsp;\\\\ \\hline<br>T \\rightarrow \\text {\"C\" }&nbsp;T_1&nbsp;&amp; \\left\\{T.v a l=5^{*} 100+T_{1}. val;\\right\\}&nbsp;\\\\ \\hline&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; T \\rightarrow \\epsilon&nbsp;&amp; \\left\\{T . v a l= - 5;\\right\\}&nbsp;\\\\ \\hline&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; U \\rightarrow \\text{\"K\"}&nbsp;&amp;&nbsp;\\left\\{U . v a l=&nbsp; 5;\\right\\}&nbsp;\\\\ \\hline&nbsp;\\end{array} \\]</p><p>Given \\( \\text{\"MMLK\"} \\) as the input, which one of the following options is the \\( \\text{CORRECT} \\) value computed by the \\( \\text{SDD} \\) (in the attribute<em>&nbsp;\\( S.val \\)</em>)?</p></div><br><br><b>GATE CSE 2024 | Set 1 | Question: 27</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 45 \\)</p>",
            "<p>\\( 50 \\)</p>",
            "<p>\\( 55 \\)</p>",
            "<p>\\( 65 \\)&nbsp;</p>"
          ],
          "correct_answer": "<p>\\( 45 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/422815/gate-cse-2024-set-1-question-27\" target=\"_blank\">https://gateoverflow.in/422815/gate-cse-2024-set-1-question-27</a></p>"
        },
        {
          "id": 16,
          "question": "<p><a name=\"422878\"></a><div itemprop=\"text\"><p>​​​​​Which of the following statements is/are FALSE?</p></div><br><br><b>GATE CSE 2024 | Set 2 | Question: 19</b></p>",
          "type": "multiple",
          "options": [
            "<p>An attribute grammar is a syntax-directed definition \\( \\text{(SDD)} \\) in which the functions in the semantic rules have no side effects</p>",
            "<p>The attributes in a \\( \\text{L} \\)-attributed definition cannot always be evaluated in a depth-first order</p>",
            "<p>Synthesized attributes can be evaluated by a bottom-up parser as the input is parsed</p>",
            "<p>All \\( \\text{L} \\)-attributed definitions based on \\( \\text{LR(1)} \\) grammar can be evaluated using a bottom-up parsing strategy</p>"
          ],
          "correct_answer": [
            "<p>The attributes in a \\( \\text{L} \\)-attributed definition cannot always be evaluated in a depth-first order</p>",
            "<p>All \\( \\text{L} \\)-attributed definitions based on \\( \\text{LR(1)} \\) grammar can be evaluated using a bottom-up parsing strategy</p>"
          ],
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/422878/gate-cse-2024-set-2-question-19\" target=\"_blank\">https://gateoverflow.in/422878/gate-cse-2024-set-2-question-19</a></p>"
        },
        {
          "id": 17,
          "question": "<p><a name=\"460823\"></a><div itemprop=\"text\"><p>​​Given the following syntax directed translation rules:</p><ul><li>Rule 1: \\( R \\rightarrow A B\\{B . i=R . i-1 ; A . i=B . i ; R . i=A . i+1 ;\\} \\)</li><li>Rule 2: \\( P \\rightarrow C D\\{P . i=C . i+D . i ; D . i=C . i+2 ;\\} \\)</li><li>Rule 3: \\( Q \\rightarrow E F\\{Q . i=E . i+F . i ;\\} \\)</li></ul><div>Which ONE is the CORRECT option among the following?</div></div><br><br><b>GATE CSE 2025 | Set 2 | Question: 12</b></p>",
          "type": "single",
          "options": [
            "<p>Rule \\( 1 \\) is \\( S \\)-attributed and \\( L \\)-attributed; Rule \\( 2 \\) is \\( S \\)-attributed and not \\( L \\)-attributed; Rule \\( 3 \\) is neither \\( S \\)-attributed nor \\( L \\)-attributed.</p>",
            "<p>Rule \\( 1 \\) is neither \\( S \\)-attributed not \\( L \\)-attributed; Rule \\( 2 \\) is \\( S \\)-attributed and \\( L \\)-attributed; Rule \\( 3 \\) is \\( S \\)-attributed and \\( L \\)-attributed.</p>",
            "<p>Rule \\( 1 \\) is neither \\( S \\)-attributed nor \\( L \\)-attributed; Rule \\( 2 \\) is not \\( S \\)-attributed and is \\( L \\)-attributed; Rule \\( 3 \\) is&nbsp;\\( S \\)-attributed and \\( L \\)-attributed.</p>",
            "<p>Rule \\( 1 \\) is \\( S \\)-attributed and not \\( L \\)-attributed; Rule \\( 2 \\) is not \\( S \\)-attributed and is \\( L \\)-attributed; Rule \\( 3 \\) is \\( S \\)-attributed and \\( L \\)-attributed.</p>"
          ],
          "correct_answer": "<p>Rule \\( 1 \\) is neither \\( S \\)-attributed nor \\( L \\)-attributed; Rule \\( 2 \\) is not \\( S \\)-attributed and is \\( L \\)-attributed; Rule \\( 3 \\) is&nbsp;\\( S \\)-attributed and \\( L \\)-attributed.</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/460823/gate-cse-2025-set-2-question-12\" target=\"_blank\">https://gateoverflow.in/460823/gate-cse-2025-set-2-question-12</a></p>"
        }
      ]
    }
  ]
});
