window.__examLoadCallback({
  "title": "Digital_Logic - Boolean_Algebra",
  "duration": 91,
  "sections": [
    {
      "name": "Boolean_Algebra",
      "questions": [
        {
          "id": 1,
          "question": "<p>The following circuit compares two 2-bit binary numbers, X and Y represented by \\(X_{1}X_{0}\\) and \\(Y_{1}Y_{0}\\) respectively. (\\(X_{0}\\) and \\(Y_{0}\\) represent Least Significant Bits)<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Boolean_Algebra\\q66_f241f6da.jpg\"><br>Under what conditions Z will be 1? <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>X &gt; Y</p>",
            "<b>B.</b> <p>X &lt; Y</p>",
            "<b>C.</b> <p>X=Y</p>",
            "<b>D.</b> <p>X!=Y</p>"
          ],
          "correct_answer": "<b>A.</b> <p>X &gt; Y</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331492/isro2020-66\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>If ABCD is a 4-bit binary number, then what is the code generated by the following circuit?<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Boolean_Algebra\\q12_ecd1ed47.jpg\"><br> <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>BCD code</p>",
            "<b>B.</b> <p>Gray code</p>",
            "<b>C.</b> <p>8421 code</p>",
            "<b>D.</b> <p>Excess-3 code</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Gray code</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331372/isro2020-12\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Minimum number of NAND gates required to implement the following binary equation\\(Y=(\\bar{A}+\\bar{B})(C+D)\\) <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>4</p>",
            "<b>B.</b> <p>5</p>",
            "<b>C.</b> <p>3</p>",
            "<b>D.</b> <p>6</p>"
          ],
          "correct_answer": "<b>A.</b> <p>4</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331369/isro2020-11\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>Any set of Boolean operation that is sufficient to represent all Boolean expression is said to be complete. Which of the following is not complete ? <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>{AND, OR}</p>",
            "<b>B.</b> <p>{AND, NOT}</p>",
            "<b>C.</b> <p>{NOT, OR}</p>",
            "<b>D.</b> <p>{NOR}</p>"
          ],
          "correct_answer": "<b>A.</b> <p>{AND, OR}</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213526/isro2018-62\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Boolean_Algebra\\q9_7cd2ae9c.jpg\"><br>  In the diagram above, the inverter (NOT gate) and the AND-gates labeled 1 and 2 have delays of 9, 10 and 12 nanoseconds (ns), respectively. Wire delays are negligible. For certain values a and c, together with certain transition of b, a glitch (spurious output) is generated for a short time, after which the output assumes its correct value. The duration of glitch is: <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>7 ns</p>",
            "<b>B.</b> <p>9 ns</p>",
            "<b>C.</b> <p>11 ns</p>",
            "<b>D.</b> <p>13 ns</p>"
          ],
          "correct_answer": "<b>A.</b> <p>7 ns</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213579/isro2018-9\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>The 2-input XOR has a high output only when the input values are <br><br><strong>(ISRO CSE 2017)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>low</p>",
            "<b>B.</b> <p>high</p>",
            "<b>C.</b> <p>same</p>",
            "<b>D.</b> <p>different</p>"
          ],
          "correct_answer": "<b>D.</b> <p>different</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/128642/isro-2017-25\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>What is the minimum number of two-input NAND gates used to perform the function of two-input OR gate? <br><br><strong>(ISRO CSE 2017)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>One</p>",
            "<b>B.</b> <p>Two</p>",
            "<b>C.</b> <p>Three</p>",
            "<b>D.</b> <p>Four</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Three</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/129118/isro2017-23\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>The simplified SOP (Sum of Product) from the Boolean expression<br>\\((P + \\bar{Q} + \\bar{R}) . (P + {Q} + R) . (P + Q +\\bar{R})\\)<br>is <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((\\bar{P}.Q+\\bar{R})\\)</p>",
            "<b>B.</b> <p>\\((P+{Q}.\\bar{R})\\)</p>",
            "<b>C.</b> <p>\\(({P}.\\bar{Q}+R)\\)</p>",
            "<b>D.</b> <p>\\((P.Q+R)\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\((P+{Q}.\\bar{R})\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55660/isro2016-16\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>Consider the following gate network<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Boolean_Algebra\\q10_1f8baeab.jpg\"><br>Which one of the following gates is redundant? <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Gate No. 1</p>",
            "<b>B.</b> <p>Gate No. 2</p>",
            "<b>C.</b> <p>Gate No. 3</p>",
            "<b>D.</b> <p>Gate No. 4</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Gate No. 2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55959/isro2016-10\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>The minimum Boolean expression for the following circuit is<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Boolean_Algebra\\q8_ae4ca5cf.jpg\"><br> <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>AB+AC+BC</p>",
            "<b>B.</b> <p>A+BC</p>",
            "<b>C.</b> <p>A+B</p>",
            "<b>D.</b> <p>A+B+C</p>"
          ],
          "correct_answer": "<b>A.</b> <p>AB+AC+BC</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55951/isro2016-8\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>The minimum number of \\(\\text{NAND}\\) gates required to implement the Boolean function \\(A + A\\bar{B} + A\\bar{B}C\\) is equal to <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0 (Zero)</p>",
            "<b>B.</b> <p>1</p>",
            "<b>C.</b> <p>4</p>",
            "<b>D.</b> <p>7</p>"
          ],
          "correct_answer": "<b>A.</b> <p>0 (Zero)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/41842/isro2016-7\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>The boolean expression \\(A B+A B^{\\prime}+A^{\\prime} C+A C\\) is independent of the boolean variable <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A</p>",
            "<b>B.</b> <p>B</p>",
            "<b>C.</b> <p>C</p>",
            "<b>D.</b> <p>None of these</p>"
          ],
          "correct_answer": "<b>B.</b> <p>B</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/51074/isro2015-10\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>The complement of the Boolean expression \\(A B(\\bar{B} C+A C)\\) is <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((\\bar{A}+\\bar{B})+(B+\\bar{C}) \\cdot(\\bar{A}+\\bar{C})\\)</p>",
            "<b>B.</b> <p>\\((\\bar{A} \\cdot \\bar{B})+(B \\bar{C}+\\bar{A} \\bar{C})\\)</p>",
            "<b>C.</b> <p>\\((\\bar{A}+\\bar{B}) \\cdot(B+\\bar{C})+(A+\\bar{C})\\)</p>",
            "<b>D.</b> <p>\\((A+B) \\cdot(\\bar{B}+C)(A+C)\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\((\\bar{A}+\\bar{B})+(B+\\bar{C}) \\cdot(\\bar{A}+\\bar{C})\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50778/isro2015-5\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>Which of the following is not valid Boolean algebra rule ? <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(X . X=X\\)</p>",
            "<b>B.</b> <p>\\((X+Y) . X=X\\)</p>",
            "<b>C.</b> <p>\\(\\bar{X}+X Y=Y\\)</p>",
            "<b>D.</b> <p>\\((X+Y) \\cdot(X+Z)=X+Y Z\\)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(\\bar{X}+X Y=Y\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/52781/isro2014-56\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>Consider the logic circuit given below.<br><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Boolean_Algebra\\q53_ae983511.jpg\"><br>The inverter, AND and OR gates have delays of 6, 10 and 11 nanoseconds respectively. Assuming that wire delays are negligible, what is the duration of glitch for Q before it becomes stable? <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>5</p>",
            "<b>B.</b> <p>11</p>",
            "<b>C.</b> <p>16</p>",
            "<b>D.</b> <p>27</p>"
          ],
          "correct_answer": "<b>A.</b> <p>5</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55003/isro2014-53\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 16,
          "question": "<p>The output of a tristate buffer when the enable input in 0 is <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Always 0</p>",
            "<b>B.</b> <p>Always 1</p>",
            "<b>C.</b> <p>Retains the last value when enable input was high</p>",
            "<b>D.</b> <p>Disconnected state</p>"
          ],
          "correct_answer": "<b>D.</b> <p>Disconnected state</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/54950/isro2014-26\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 17,
          "question": "<p>Consider the logic circuit given below:<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Boolean_Algebra\\q15_4b90dfc8.jpg\"><br>Q=__________? <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\bar{A} C+B \\bar{C}+C D\\)</p>",
            "<b>B.</b> <p>\\(A B C+\\bar{C} D\\)</p>",
            "<b>C.</b> <p>\\(A B+B \\bar{C}+B \\bar{D}\\)</p>",
            "<b>D.</b> <p>\\(A \\bar{B}+A \\bar{C}+\\bar{C} D\\)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(A B+B \\bar{C}+B \\bar{D}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/54948/isro2014-15\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 18,
          "question": "<p>The most simplified form of the Boolean function<br>\n\\(x (A, B, C, D) = \\sum (7, 8, 9, 10, 11, 12, 13, 14, 15)\\)<br>\n(expressed in sum of minterms) is? <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A + A'BCD</p>",
            "<b>B.</b> <p>AB + CD</p>",
            "<b>C.</b> <p>A + BCD</p>",
            "<b>D.</b> <p>ABC + D</p>"
          ],
          "correct_answer": "<b>C.</b> <p>A + BCD</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43963/isro-2013-28\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 19,
          "question": "<p>Any set of Boolean operators that is sufficient to represent all Boolean expressions is said to be complete. Which of the following is not complete ? <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>{NOT, OR}</p>",
            "<b>B.</b> <p>{NOR}</p>",
            "<b>C.</b> <p>{AND, OR}</p>",
            "<b>D.</b> <p>{AND, NOT}</p>"
          ],
          "correct_answer": "<b>C.</b> <p>{AND, OR}</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43845/isro-2013-22\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 20,
          "question": "<p>The output expression of the following gate network is <br><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Boolean_Algebra\\q47_ff3adc84.jpg\"><br> <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(X.Y + \\bar{X} . \\bar{Y}\\)</p>",
            "<b>B.</b> <p>X.Y + X.Y</p>",
            "<b>C.</b> <p>X.Y</p>",
            "<b>D.</b> <p>X+Y</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(X.Y + \\bar{X} . \\bar{Y}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/52572/isro2011-47\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 21,
          "question": "<p>In Boolean algebra, rule \\(\\left ( X+Y \\right )\\left ( X+Z \\right ) =\\) <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Y+XZ</p>",
            "<b>B.</b> <p>X+YZ</p>",
            "<b>C.</b> <p>XY+Z</p>",
            "<b>D.</b> <p>XZ+Y</p>"
          ],
          "correct_answer": "<b>B.</b> <p>X+YZ</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/52477/isro2011-30\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 22,
          "question": "<p>Evaluate (X xor Y) xor Y? <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>All 1's</p>",
            "<b>B.</b> <p>All 0's</p>",
            "<b>C.</b> <p>X</p>",
            "<b>D.</b> <p>Y</p>"
          ],
          "correct_answer": "<b>C.</b> <p>X</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/19328/isro2011-6\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 23,
          "question": "<p>Consider the following boolean function of four variables \\(f(w,x,y,z) = \\Sigma(1,3,4,6,9,11,12,14)\\), the function is <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Independent of one variable</p>",
            "<b>B.</b> <p>Independent of two variables</p>",
            "<b>C.</b> <p>Independent of three variables</p>",
            "<b>D.</b> <p>Dependent on all variables</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Independent of two variables</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50345/isro2009-20\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 24,
          "question": "<p>The switching expression corresponding to \\(f(A, B, C, D) = \\Sigma(1, 4, 5, 9, 11, 12)\\) is <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>BC'D' + A'C'D + AB'D</p>",
            "<b>B.</b> <p>ABC' + ACD + B'C'D</p>",
            "<b>C.</b> <p>ACD' + A'BC' + AC'D'</p>",
            "<b>D.</b> <p>A'BD + ACD' + BCD'</p>"
          ],
          "correct_answer": "<b>A.</b> <p>BC'D' + A'C'D + AB'D</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48039/isro2009-19\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 25,
          "question": "<p>Which of the following is not a valid rule of XOR? <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0 XOR 0=0</p>",
            "<b>B.</b> <p>1 XOR 1=1</p>",
            "<b>C.</b> <p>1 XOR 0=1</p>",
            "<b>D.</b> <p>B XOR B=0</p>"
          ],
          "correct_answer": "<b>B.</b> <p>1 XOR 1=1</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49907/isro2008-28\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 26,
          "question": "<p>The output Y of the given circuit<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Boolean_Algebra\\q27_a307e416.jpg\"><br> <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>1</p>",
            "<b>B.</b> <p>0</p>",
            "<b>C.</b> <p>X</p>",
            "<b>D.</b> <p>X'</p>"
          ],
          "correct_answer": "<b>C.</b> <p>X</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49905/isro2008-27\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 27,
          "question": "<p>In the expression \\(\\bar{A}(\\bar{A}+\\bar{B})\\)by writing the first term A as A+0, the expression is best simplified as <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A+AB</p>",
            "<b>B.</b> <p>AB</p>",
            "<b>C.</b> <p>A</p>",
            "<b>D.</b> <p>A+B</p>"
          ],
          "correct_answer": "<b>C.</b> <p>A</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49899/isro2008-25\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 28,
          "question": "<p>The Boolean expression \\((A+\\bar{C})(\\bar{B} + \\bar{C})\\) simplifies to <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\bar{C} + A \\bar{B}\\)</p>",
            "<b>B.</b> <p>\\(\\bar{C} (\\bar{A} +B)\\)</p>",
            "<b>C.</b> <p>\\(\\bar{B}\\bar{C} + A\\bar{B}\\)</p>",
            "<b>D.</b> <p>None of these</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(\\bar{C} + A \\bar{B}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49896/isro2008-24\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 29,
          "question": "<p>The Boolean theorem \\(AB+\\bar{A}C +BC = AB + \\bar{A}C\\) corresponds to <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((A+B) \\bullet (\\bar{A} +C) \\bullet (B+C) = (A+B) \\bullet (\\bar{A} +C)\\)</p>",
            "<b>B.</b> <p>\\(AB+\\bar{A}C +BC =AB+BC\\)</p>",
            "<b>C.</b> <p>\\(AB+\\bar{A}C +BC =(A+B) \\bullet (\\bar{A} +C) \\bullet (B+C)\\)</p>",
            "<b>D.</b> <p>\\((A+B) \\bullet (\\bar{A} +C) \\bullet (B+C) = AB + \\bar{A}C\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\((A+B) \\bullet (\\bar{A} +C) \\bullet (B+C) = (A+B) \\bullet (\\bar{A} +C)\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49677/isro2008-11\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 30,
          "question": "<p>The output 0 and 1 level for TTL Logic family is approximately <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0.1 and 5V</p>",
            "<b>B.</b> <p>0.6 and 3.5 V</p>",
            "<b>C.</b> <p>0.9 and 1.75 V</p>",
            "<b>D.</b> <p>-1.75 and 0.9 V</p>"
          ],
          "correct_answer": "<b>B.</b> <p>0.6 and 3.5 V</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49510/isro2007-35\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 31,
          "question": "<p>The circuit shown in the given figure is a <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Boolean_Algebra\\q3_2cdef408.jpg\"><br> <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>full adder</p>",
            "<b>B.</b> <p>full subtracter</p>",
            "<b>C.</b> <p>shift register</p>",
            "<b>D.</b> <p>decade counter</p>"
          ],
          "correct_answer": "<b>B.</b> <p>full subtracter</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48451/isro2007-03\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 32,
          "question": "<p>The circuit shown in the following figure realizes the function. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Boolean_Algebra\\q2_6dcd75de.jpg\"><br> <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((\\overline{A+B}+C)(\\bar{D}\\bar{E})\\)</p>",
            "<b>B.</b> <p>\\((\\overline{A+B}+C)(D\\bar{E})\\)</p>",
            "<b>C.</b> <p>\\((A+ \\overline{B+C})(\\bar{D}E)\\)</p>",
            "<b>D.</b> <p>\\((A+ B+\\bar{C})(\\bar{D} \\bar{E})\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\((\\overline{A+B}+C)(\\bar{D}\\bar{E})\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48446/isro2007-02\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 33,
          "question": "<p>The Boolean expression \\(Y=(A+\\bar{B}+\\bar{A}B)\\bar{C}\\) is given by <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(A\\bar{C}\\)</p>",
            "<b>B.</b> <p>\\(B\\bar{C}\\)</p>",
            "<b>C.</b> <p>\\(\\bar{C}\\)</p>",
            "<b>D.</b> <p>AB</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(\\bar{C}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48443/isro2007-01\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
