window.__examLoadCallback({
  "title": "Network_Layer_Protocol - Network_Layer_Protocol - Slot 4",
  "duration": 42,
  "sections": [
    {
      "name": "Network_Layer_Protocol",
      "questions": [
        {
          "id": 1,
          "question": "<p>An IP router with a Maximum Transmission Unit (MTU) of 1500 bytes has received an IP packet of size 4404 bytes with an IP header of length 20 bytes. The values of the relevant fields in the header of the third IP fragment generated by the router for this packet are <br><br><strong>(GATE CSE 2014 SET-3)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>MF bit: 0, Datagram Length: 1444; Offset: 370</p>",
            "<b>B.</b> <p>MF bit: 1, Datagram Length: 1424; Offset: 185</p>",
            "<b>C.</b> <p>MF bit: 1, Datagram Length: 1500; Offset: 370</p>",
            "<b>D.</b> <p>MF bit: 0, Datagram Length: 1424; Offset: 2960</p>"
          ],
          "correct_answer": "<b>A.</b> <p>MF bit: 0, Datagram Length: 1444; Offset: 370</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/2062/gate2014-3-28#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Every host in an IPv4 network has a 1-second resolution real-time clock with battery backup. Each host needs to generate up to 1000 unique identifiers per second. Assume that each host has a globally unique IPv4 address. Design a 50-bit globally unique ID for this purpose. After what period (in seconds) will the identifiers generated by a host wrap around? <br><br><strong>(GATE CSE 2014 SET-3)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "256",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/2061/gate2014-3-27#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>An IP router implementing Classless Inter-domain routing (CIDR) receives a packet with address 131.23.151.76. The router's routing table has the following entries:  <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Network_Layer_Protocol\\q26_07b51d41.jpg\">  <br> The identifier of the output interface on which this packet will be forwarded is _____. <br><br><strong>(GATE CSE 2014 SET-3)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "1",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/2060/gate2014-3-26#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>Host A (on TCP/IP v4 network A) sends an IP datagram D to host B (also on TCP/IP V4\nnetwork B). Assume that no error occurred during the transmission of D. When D reaches B, which of the following IP header field(s) may be different from that of the original datagram D?<br>\n(i) TTL <br>(ii) Checksum <br> (iii) Fragment Offset <br><br><strong>(GATE CSE 2014 SET-3)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>(i) only</p>",
            "<b>B.</b> <p>(i) and (ii) only</p>",
            "<b>C.</b> <p>(ii) and (iii) only</p>",
            "<b>D.</b> <p>(i), (ii) and (iii)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>(i), (ii) and (iii)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2059/gate2014-3-25#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>In the diagram shown below, L1 is an Ethernet LAN and L2 is a Token-Ring LAN. An IP\npacket originates from sender S and traverses to R, as shown. The links within each ISP and\nacross the two ISPs, are all point-to-point' optical links. The initial value of the TTL field is\n32. The maximum possible value of the TTL field when R receives the datagram is\n____________. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Network_Layer_Protocol\\q25_4b42d41a.jpg\"> <br><br><strong>(GATE CSE 2014 SET-2)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "26",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/1983/gate2014-2-25#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Which one of the following is TRUE about the interior gateway routing protocols - Routing\nInformation Protocol (RIP) and Open Shortest Path First (OSPF)? <br><br><strong>(GATE CSE 2014 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>RIP uses distance vector routing and OSPF uses link state routing</p>",
            "<b>B.</b> <p>OSPF uses distance vector routing and RIP uses link state routing</p>",
            "<b>C.</b> <p>Both RIP and OSPF use link state routing</p>",
            "<b>D.</b> <p>Both RIP and OSPF use distance vector routing</p>"
          ],
          "correct_answer": "<b>A.</b> <p>RIP uses distance vector routing and OSPF uses link state routing</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1981/gate2014-2-23#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>Consider the following three statements about link state and distance vector routing protocols,\nfor a large network with 500 network nodes and 4000 links <br>\n[S1] The computational overhead in link state protocols is higher than in distance vector\nprotocols. <br>\n[S2] A distance vector protocol (with split horizon) avoids persistent routing loops, but not\na link state protocol. <br>\n[S3] After a topology change, a link state protocol will converge faster than a distance\nvector protocol. <br>\nWhich one of the following is correct about S1, S2, and S3? <br><br><strong>(GATE CSE 2014 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>S1, S2, and S3 are all true</p>",
            "<b>B.</b> <p>S1, S2, and S3 are all false.</p>",
            "<b>C.</b> <p>S1 and S2 are true, but S3 is false</p>",
            "<b>D.</b> <p>S1 and S3 are true, but S2 is false.</p>"
          ],
          "correct_answer": "<b>D.</b> <p>S1 and S3 are true, but S2 is false.</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1790/gate2014-1-23#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>What is IP class and number of sub-networks if the subnet mask is 255.224.0.0? <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Class A, 3</p>",
            "<b>B.</b> <p>Class A, 8</p>",
            "<b>C.</b> <p>Class B, 3</p>",
            "<b>D.</b> <p>Class B, 32</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Class A, 8</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43984/isro-2013-43\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>IPv6 does not support which of the following addressing modes? <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Unicast addressing</p>",
            "<b>B.</b> <p>Multicast addressing</p>",
            "<b>C.</b> <p>Broadcast addressing</p>",
            "<b>D.</b> <p>Anycast addressing</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Broadcast addressing</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43982/isro-2013-42\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>In an IPv4 datagram, the M bit is 0, the value of HLEN is 10, the value of total length is 400 and\nthe fragment offset value is 300. The position of the datagram, the sequence numbers of the first\nand the last bytes of the payload, respectively are <br><br><strong>(GATE CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Last fragment, 2400 and 2789</p>",
            "<b>B.</b> <p>First fragment, 2400 and 2759</p>",
            "<b>C.</b> <p>Last fragment, 2400 and 2759</p>",
            "<b>D.</b> <p>Middle fragment, 300 and 689</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Last fragment, 2400 and 2759</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/1548/gate2013-37#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>Assume that source S and destination D are connected through two intermediate routers labeled R.\nDetermine how many times each packet has to visit the network layer and the data link layer during\na transmission from S to D. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Network_Layer_Protocol\\q14_d877ec30.jpg\"> <br><br><strong>(GATE CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Network layer - 4 times and Data link layer - 4 times</p>",
            "<b>B.</b> <p>Network layer - 4 times and Data link layer - 3 times</p>",
            "<b>C.</b> <p>Network layer - 4 times and Data link layer - 6 times</p>",
            "<b>D.</b> <p>Network layer - 2 times and Data link layer - 6 times</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Network layer - 4 times and Data link layer - 6 times</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1436/gate2013-14#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>An Internet Service Provider (ISP) has the following chunk of CIDR-based IP addresses available\nwith it: 245.248.128.0/20. The ISP wants to give half of this chunk of addresses to Organization A,\nand a quarter to Organization B, while retaining the remaining with itself. Which of the following is\na valid allocation of addresses to A and B? <br><br><strong>(GATE CSE 2012)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>245.248.136.0/21 and 245.248.128.0/22</p>",
            "<b>B.</b> <p>245.248.128.0/21 and 245.248.128.0/22</p>",
            "<b>C.</b> <p>245.248.132.0/22 and 245.248.132.0/21</p>",
            "<b>D.</b> <p>245.248.136.0/24 and 245.248.132.0/21</p>"
          ],
          "correct_answer": "<b>A.</b> <p>245.248.136.0/21 and 245.248.128.0/22</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/1752/gate2012-34#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>In the IPv4 addressing format, the number of networks allowed under Class C addresses is <br><br><strong>(GATE CSE 2012)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(2^{14}\\)</p>",
            "<b>B.</b> <p>\\(2^{7}\\)</p>",
            "<b>C.</b> <p>\\(2^{21}\\)</p>",
            "<b>D.</b> <p>\\(2^{24}\\)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(2^{21}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1606/gate2012-23#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>Lightweight Directory Access protocol is used for <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Routing the packets</p>",
            "<b>B.</b> <p>Authentication</p>",
            "<b>C.</b> <p>obtaining IP address</p>",
            "<b>D.</b> <p>domain name resolving</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Authentication</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/18149/isro2011-69\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>The broadcast address for IP network 172.16.0.0 with subnet mask 255.255.0.0 is <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>172.16.0.255</p>",
            "<b>B.</b> <p>172.16.255.255</p>",
            "<b>C.</b> <p>255.255.255.255</p>",
            "<b>D.</b> <p>172.255.255.255</p>"
          ],
          "correct_answer": "<b>B.</b> <p>172.16.255.255</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/51337/isro2011-45\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
