window.__examLoadCallback({
  "title": "Compiler_Design - Compiler_Design - Slot 3",
  "duration": 25,
  "sections": [
    {
      "name": "Compiler_Design",
      "questions": [
        {
          "id": 1,
          "question": "<p>Number of comparisons required for an unsuccessful search of an element in a sequential search organized, fixed length, symbol table of length L is <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>L</p>",
            "<b>B.</b> <p>L/2</p>",
            "<b>C.</b> <p>(L+1)/2</p>",
            "<b>D.</b> <p>2L</p>"
          ],
          "correct_answer": "<b>A.</b> <p>L</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/18148/isro2011-70\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Which of the following sentences can be generated by <br>\n\\(S -&gt; aS \\mid bA\\)<br>\n\\(A -&gt; d \\mid cA\\) <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>bccdd</p>",
            "<b>B.</b> <p>abbcca</p>",
            "<b>C.</b> <p>abcabc</p>",
            "<b>D.</b> <p>abcd</p>"
          ],
          "correct_answer": "<b>D.</b> <p>abcd</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/52864/isro2011-68\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Which variable does not drive a terminal string in grammar?<br>\nS -&gt; AB<br>\nA -&gt; a<br>\nB -&gt; b<br>\nB -&gt; C<br> <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A</p>",
            "<b>B.</b> <p>B</p>",
            "<b>C.</b> <p>C</p>",
            "<b>D.</b> <p>S</p>"
          ],
          "correct_answer": "<b>C.</b> <p>C</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/51695/isro2011-43\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>Which of the following statements about peephole optimization is False? <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>It is applied to a small part of the code</p>",
            "<b>B.</b> <p>It can be used to optimize intermediate code</p>",
            "<b>C.</b> <p>To get the best out of this, it has to be applied repeatedly</p>",
            "<b>D.</b> <p>It can be applied to the portion of the code that is not contiguous</p>"
          ],
          "correct_answer": "<b>D.</b> <p>It can be applied to the portion of the code that is not contiguous</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/52264/isro2011-13\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>In compiler terminology reduction in strength means <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Replacing run time computation by compile time computation</p>",
            "<b>B.</b> <p>Removing loop invariant computation</p>",
            "<b>C.</b> <p>Removing common subexpressions</p>",
            "<b>D.</b> <p>replacing a costly operation by a relatively cheaper one</p>"
          ],
          "correct_answer": "<b>D.</b> <p>replacing a costly operation by a relatively cheaper one</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50567/isro2011-3\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Which of the following class of statement usually produces no executable code when compiled? <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>declaration</p>",
            "<b>B.</b> <p>assignment statements</p>",
            "<b>C.</b> <p>input and output statements</p>",
            "<b>D.</b> <p>structural statements</p>"
          ],
          "correct_answer": "<b>D.</b> <p>structural statements</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/17249/isro2008-68\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>In a resident - OS computer, which of the following systems must reside in the main memory under all situations? <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Assembler</p>",
            "<b>B.</b> <p>Linker</p>",
            "<b>C.</b> <p>Loader</p>",
            "<b>D.</b> <p>Compiler</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Loader</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1662/gate1998-1-25-isro2008-41\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>Relative to the program translated by a compiler, the same program when interpreted runs <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Faster</p>",
            "<b>B.</b> <p>Slower</p>",
            "<b>C.</b> <p>At the same speed</p>",
            "<b>D.</b> <p>May be faster or slower</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Slower</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/18495/isro2008-38\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>Consider the grammar<br>\n\\(S \\rightarrow ABCc \\mid bc\\)<br>\n\\(BA \\rightarrow AB\\)<br>\n\\(Bb \\rightarrow bb\\)<br>\n\\(Ab \\rightarrow ab\\)<br>\n\\(Aa \\rightarrow aa\\)<br>\nWhich of the following sentences can be derived by this grammar? <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>abc</p>",
            "<b>B.</b> <p>aab</p>",
            "<b>C.</b> <p>abcc</p>",
            "<b>D.</b> <p>abbc</p>"
          ],
          "correct_answer": "<b>A.</b> <p>abc</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49668/isro2008-7\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
