window.__examLoadCallback({
  "title": "Data_Link_Layer - Data_Link_Layer - Slot 6",
  "duration": 42,
  "sections": [
    {
      "name": "Data_Link_Layer",
      "questions": [
        {
          "id": 1,
          "question": "<p>Suppose that it takes 1 unit of time to transmit a packet (of fixed size) on a communication link. The link layer uses a window flow control protocol with a window size of N packets. Each packet causes an ack or a nak to be generated by the receiver, and ack/nak transmission times are negligible. Further, the round trip time on the link is equal to N units. Consider time i &gt; N. If only acks have been received till time i(no naks), then the goodput evaluated at the transmitter at time i(in packets per unit time) is <br><br><strong>(GATE IT 2006)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(1- \\dfrac{ N}{i}\\)</p>",
            "<b>B.</b> <p>\\(\\dfrac{i}{(N + i)}\\)</p>",
            "<b>C.</b> <p>1</p>",
            "<b>D.</b> <p>\\(1 - e^{\\left(\\frac{i}{N}\\right)}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(1- \\dfrac{ N}{i}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3608/gate2006-it-64\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Which of the following statements is TRUE? <br><br><strong>(GATE IT 2006)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Both Ethernet frame and IP packet include checksum fields</p>",
            "<b>B.</b> <p>Ethernet frame includes a checksum field and IP packet includes a CRC field</p>",
            "<b>C.</b> <p>Ethernet frame includes a CRC field and IP packet includes a checksum field</p>",
            "<b>D.</b> <p>Both Ethernet frame and IP packet include CRC fields</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Ethernet frame includes a CRC field and IP packet includes a checksum field</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3558/gate2006-it-19\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Consider the diagram shown below where a number of LANs are connected by (transparent) bridges. In order to avoid packets looping through circuits in the graph, the bridges organize themselves in a spanning tree. First, the root bridge is identified as the bridge with the least serial number. Next, the root sends out (one or more) data units to enable the setting up of the spanning tree of shortest paths from the root bridge to each bridge. <br><br> Each bridge identifies a port (the root port) through which it will forward frames to the root bridge. Port conflicts are always resolved in favour of the port with the lower index value. When there is a possibility of multiple bridges forwarding to the same LAN (but not through the root port), ties are broken as follows: bridges closest to the root get preference and between such bridges, the one with the lowest serial number is preferred.  <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Data_Link_Layer\\q82_4a10130c.jpg\"><br>Let host H1 send\nout a broadcast ping packet. Which of the following options represents the correct for forwarding table on B3? <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Data_Link_Layer\\q83_f09ad486.jpg\"> <br><br><strong>(GATE CSE 2006)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A</p>",
            "<b>B.</b> <p>B</p>",
            "<b>C.</b> <p>C</p>",
            "<b>D.</b> <p>D</p>"
          ],
          "correct_answer": "<b>C.</b> <p>C</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/79790/gate2006-83#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>Consider the diagram shown below where a number of LANs are connected by (transparent) bridges. In order to avoid packets looping through circuits in the graph, the bridges organize themselves in a spanning tree. First, the root bridge is identified as the bridge with the least serial number. Next, the root sends out (one or more) data units to enable the setting up of the spanning tree of shortest paths from the root bridge to each bridge. <br><br> Each bridge identifies a port (the root port) through which it will forward frames to the root bridge. Port conflicts are always resolved in favour of the port with the lower index value. When there is a possibility of multiple bridges forwarding to the same LAN (but not through the root port), ties are broken as follows: bridges closest to the root get preference and between such bridges, the one with the lowest serial number is preferred.  <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Data_Link_Layer\\q82_4a10130c.jpg\"><br> For the given connection of LANs by bridges, which one of the following choices represents the depth first traversal of the spanning tree of bridges? <br><br><strong>(GATE CSE 2006)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>B1, B5, B3, B4, B2</p>",
            "<b>B.</b> <p>B1, B3, B5, B2, B4</p>",
            "<b>C.</b> <p>B1, B5, B2, B3, B4</p>",
            "<b>D.</b> <p>B1, B3, B4, B5, B2</p>"
          ],
          "correct_answer": "<b>A.</b> <p>B1, B5, B3, B4, B2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1855/gate2006-82#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Station A needs to send a message consisting of 9 packets to Station B using a\nsiding window (window size 3) and go-back-n error control strategy. All packets\nare ready and immediately available for transmission. If every 5th packet that A\ntransmits gets lost (but no acks from B ever get lost), then what is the number\nof packets that A will transmit for sending the message to B ? <br><br><strong>(GATE CSE 2006)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>12</p>",
            "<b>B.</b> <p>14</p>",
            "<b>C.</b> <p>16</p>",
            "<b>D.</b> <p>18</p>"
          ],
          "correct_answer": "<b>C.</b> <p>16</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1822/gate2006-46#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Station A uses 32 byte packets to transmit messages to Station B using a sliding\nwindow protocol. The round trip delay between A and B is 80 milliseconds and\nthe bottleneck bankwidth on the path between A and B is 128 kbps. What is the\noptimal window size that A should use ? <br><br><strong>(GATE CSE 2006)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>20</p>",
            "<b>B.</b> <p>40</p>",
            "<b>C.</b> <p>160</p>",
            "<b>D.</b> <p>320</p>"
          ],
          "correct_answer": "<b>B.</b> <p>40</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1820/gate2006-44#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>Consider the following message M = 1010001101. The cyclic redundancy check (CRC) for this message using the divisor polynomial \\(x^5+x^4+x^2+1\\) is : <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>01110</p>",
            "<b>B.</b> <p>01011</p>",
            "<b>C.</b> <p>10101</p>",
            "<b>D.</b> <p>10110</p>"
          ],
          "correct_answer": "<b>A.</b> <p>01110</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3842/gate2005-it-78\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>In a TDM medium access control bus LAN, each station is assigned one time slot per cycle for transmission. Assume that the length of each time slot is the time to transmit \\(100 \\text{bits}\\) plus the end-to-end propagation delay. Assume a propagation speed of  \\(2 \\times 10^8 m/sec\\). The length of the LAN is 1 km with a bandwidth of \\(10 \\text{Mbps}\\). The maximum number of stations that can be allowed in the LAN so that the throughput of each station can be \\(2/3 \\text{Mbps}\\)is <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>3</p>",
            "<b>B.</b> <p>5</p>",
            "<b>C.</b> <p>10</p>",
            "<b>D.</b> <p>20</p>"
          ],
          "correct_answer": "<b>C.</b> <p>10</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3838/gate2005-it-75\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>A channel has a bit rate of 4 kbps and one-way propagation delay of 20 ms. The channel uses stop and wait protocol. The transmission time of the acknowledgment frame is negligible. To get a channel efficiency of at least 50%, the minimum frame size should be <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>80 bytes</p>",
            "<b>B.</b> <p>80 bits</p>",
            "<b>C.</b> <p>160 bytes</p>",
            "<b>D.</b> <p>160 bits</p>"
          ],
          "correct_answer": "<b>D.</b> <p>160 bits</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3835/gate2005-it-72\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>A network with CSMA/CD protocol in the MAC layer is running at 1Gbps over a 1km cable with no repeaters. The signal speed in the cable is \\(2 \\times 10^{8}\\text{m/sec}\\). The minimum frame size for this network should be: <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>10000bits</p>",
            "<b>B.</b> <p>10000bytes</p>",
            "<b>C.</b> <p>5000 bits</p>",
            "<b>D.</b> <p>5000bytes</p>"
          ],
          "correct_answer": "<b>A.</b> <p>10000bits</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3834/gate2005-it-71\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>Which of the following statements is FALSE regarding a bridge? <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Bridge is a layer 2 device</p>",
            "<b>B.</b> <p>Bridge reduces collision domain</p>",
            "<b>C.</b> <p>Bridge is used to connect two or more LAN segments</p>",
            "<b>D.</b> <p>Bridge reduces broadcast domain</p>"
          ],
          "correct_answer": "<b>D.</b> <p>Bridge reduces broadcast domain</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3774/gate2005-it-28\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>Which of the following statements is TRUE about CSMA/CD: <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>IEEE 802.11 wireless LAN runs CSMA/CD protocol</p>",
            "<b>B.</b> <p>Ethernet is not based on CSMA/CD protocol</p>",
            "<b>C.</b> <p>CSMA/CD is not suitable for a high propagation delay network like satellite network</p>",
            "<b>D.</b> <p>There is no contention in a CSMA/CD network</p>"
          ],
          "correct_answer": "<b>C.</b> <p>CSMA/CD is not suitable for a high propagation delay network like satellite network</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3773/gate2005-it-27\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>Suppose the round trip propagation delay for a 10 Mbps Ethernet having 48-bit jamming signal is 46.4 \\(\\mu s\\). The minimum frame size is <br><br><strong>(GATE CSE 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>94</p>",
            "<b>B.</b> <p>416</p>",
            "<b>C.</b> <p>464</p>",
            "<b>D.</b> <p>512</p>"
          ],
          "correct_answer": "<b>D.</b> <p>512</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1397/gate2005-74#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>In a packet switching network, packets are routed from source to destination along a single path having two intermediate nodes. If the message size is 24 bytes and each packet contains a header of 3 bytes, then the optimum packet size is: <br><br><strong>(GATE CSE 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>4</p>",
            "<b>B.</b> <p>6</p>",
            "<b>C.</b> <p>7</p>",
            "<b>D.</b> <p>9</p>"
          ],
          "correct_answer": "<b>D.</b> <p>9</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1396/gate2005-73#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>The maximum window size for data transmission using the selective reject protocol with n-bit frame sequence numbers is: <br><br><strong>(GATE CSE 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(2^{n}\\)</p>",
            "<b>B.</b> <p>\\(2^{n-1}\\)</p>",
            "<b>C.</b> <p>\\(2^{n}-1\\)</p>",
            "<b>D.</b> <p>\\(2^{n-2}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(2^{n-1}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1361/gate2005-25#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
