window.__examLoadCallback({
  "title": "Theory_of_Computation - Theory_of_Computation - Slot 8",
  "duration": 42,
  "sections": [
    {
      "name": "Theory_of_Computation",
      "questions": [
        {
          "id": 1,
          "question": "<p>Consider the following context-free grammars:<br><br>\nG1: S\\(\\rightarrow\\)aS|B,<br> B\\(\\rightarrow\\)b|bB <br>\nG2: S\\(\\rightarrow\\)aA|bB, <br> A\\(\\rightarrow\\)aA|B|\\(\\varepsilon\\), <br>  B\\(\\rightarrow\\)bB|\\(\\varepsilon\\) <br><br> Which one of the following pair of languages is generated by G1 and G2, respectively? <br><br><strong>(GATE CSE 2016 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\{a^{m}b^{n}|m \\gt 0 \\; or \\;  n \\gt 0\\} \\) and \\(\\{a^{m}b^{n}|m\\gt 0  \\;  and  \\;  n\\gt 0\\}\\)</p>",
            "<b>B.</b> <p>\\(\\{a^{m}b^{n}|m\\gt 0  \\; or \\;  n\\gt 0\\}\\) and  \\(\\{a^{m}b^{n}|m\\gt 0  \\; and  \\; n \\geq  0\\}\\)</p>",
            "<b>C.</b> <p>\\(\\{a^{m}b^{n}|m\\geq 0  \\;  or   \\; n\\gt 0\\} \\) and \\(\\{a^{m}b^{n}|m\\gt 0  \\;  and  \\;  n\\gt  0\\}\\)</p>",
            "<b>D.</b> <p>\\(\\{a^{m}b^{n}|m\\geq 0  \\; and  \\;  n\\gt 0\\} \\) and \\(\\{a^{m}b^{n}|m\\gt 0  \\;  or  \\;  n\\gt 0\\}\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(\\{a^{m}b^{n}|m\\geq 0  \\; and  \\;  n\\gt 0\\} \\) and \\(\\{a^{m}b^{n}|m\\gt 0  \\;  or  \\;  n\\gt 0\\}\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/39705/gate2016-1-42#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Which one of the following regular expressions represents the language: the set of all binary strings having two consecutive 0s and two consecutive 1s? <br><br><strong>(GATE CSE 2016 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>(0+1)*0011(0+1)*+(0+1)*1100(0+1)*</p>",
            "<b>B.</b> <p>(0+1)*(00(0+1)*11+11(0+1)*00)(0+1)*</p>",
            "<b>C.</b> <p>(0+1)*00(0+1)*+(0+1)*11(0+1)*</p>",
            "<b>D.</b> <p>00(0+1)*11+11(0+1)*00</p>"
          ],
          "correct_answer": "<b>B.</b> <p>(0+1)*(00(0+1)*11+11(0+1)*00)(0+1)*</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/39647/gate2016-1-18#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Which  of the following decision problems are undecidable?<br>\nI. Given NFAs N1 and N2, is L(N1)\\(\\cap\\)L(N2) = \\(\\phi\\)?<br>\nII. Given a CFG G = (N,\\(\\Sigma \\),P,S)  and a string  \\(x \\in\\Sigma ^*\\), does  \\(x \\in\\) L(G)?<br>\nIII. Given CFGs G1 and G2, is L(G1) = L(G2)?<br>\nIV. Given a TM M, is L(M) = \\(\\phi\\)? <br><br><strong>(GATE CSE 2016 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>I and IV only</p>",
            "<b>B.</b> <p>II and III only</p>",
            "<b>C.</b> <p>III and IV only</p>",
            "<b>D.</b> <p>II and IV only</p>"
          ],
          "correct_answer": "<b>C.</b> <p>III and IV only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/39651/gate2016-1-17#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>Which of the following languages is generated by the given grammar?<br> \\(S\\rightarrow aS|bS|\\varepsilon\\) <br><br><strong>(GATE CSE 2016 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\{a^{n}b^{m}|n,m\\geq 0 \\}\\)</p>",
            "<b>B.</b> <p>{\\(\\{w\\in \\{a,b\\}^*| w \\) has equal number of a's and b's}</p>",
            "<b>C.</b> <p>\\(\\{a^{n}|n\\geq 0\\}\\cup \\{b^{n}|n\\geq 0\\}\\cup \\{a^{n}b^{n}\\geq 0\\}\\)</p>",
            "<b>D.</b> <p>{a,b}*</p>"
          ],
          "correct_answer": "<b>D.</b> <p>{a,b}*</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/39640/gate2016-1-16#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Let \\(R_{1}\\) and \\(R_{2}\\) be regular sets defined over the alphabet, then <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(R_{1} \\cap R_{2}\\)  is not regular</p>",
            "<b>B.</b> <p>\\(R_{1} \\cup R_{2}\\)  is not regular</p>",
            "<b>C.</b> <p>\\(\\Sigma^{*}-R_{1}\\)  is regular</p>",
            "<b>D.</b> <p>\\(R_{1}^{*}\\)  is not regular</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(\\Sigma^{*}-R_{1}\\)  is regular</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/51701/isro2015-43\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Which of the following languages are context-free? <br>\\(L_{1}=\\{a^{m}b^{n}a^{n}b^{m}|m,n\\geq 1\\}\\) <br>   \\(L_{2}=\\{a^{m}b^{n}a^{m}b^{n}|m,n\\geq 1\\}\\) <br>  \\(L_{3}=\\{a^{m}b^{n}|m=2n+1\\}\\) <br><br><strong>(GATE CSE 2015 SET-3)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>L1 and L2 only</p>",
            "<b>B.</b> <p>L1 and L3 only</p>",
            "<b>C.</b> <p>L2 and L3 only</p>",
            "<b>D.</b> <p>L3 only</p>"
          ],
          "correct_answer": "<b>B.</b> <p>L1 and L3 only</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/8489/gate2015-3-34#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>Let L be the language represented by the regular expression \\(\\Sigma ^{*}0011\\Sigma ^{*}\\) where \\(\\Sigma\\)={0,1}. What is the minimum number of states in a DFA that recognizes \\(\\bar{L}\\) (complement of L)? <br><br><strong>(GATE CSE 2015 SET-3)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>4</p>",
            "<b>B.</b> <p>5</p>",
            "<b>C.</b> <p>6</p>",
            "<b>D.</b> <p>8</p>"
          ],
          "correct_answer": "<b>B.</b> <p>5</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/8415/gate2015-3-22#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>Consider the alphabet \\(\\Sigma\\)={0, 1}, the null/empty string  \\(\\lambda\\) and the sets of strings \\(X_{0}, X_{1}, \\; and \\; X_{2}\\) generated by the corresponding non-terminals of a regular grammar. \\(X_{0}, X_{1}, \\; and \\; X_{2}\\)  are related as follows. <br>   \\(X_{0}=1X_{1}\\) <br> \\(X_{1},=0X_{1}+1 X_{2}\\) <br> \\(X_{2}=0X_{1}+  \\{\\lambda\\}\\)<br>   Which one of the following choices precisely represents the strings in \\(X_{0}\\)? <br><br><strong>(GATE CSE 2015 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>10(0* + (10)*)1</p>",
            "<b>B.</b> <p>10(0* + (10)*)*1</p>",
            "<b>C.</b> <p>1(0 + 10)*1</p>",
            "<b>D.</b> <p>10(0 + 10)*1 + 110(0 + 10)*1</p>"
          ],
          "correct_answer": "<b>C.</b> <p>1(0 + 10)*1</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/8159/gate2015-2-50#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>Which of the following languages is/are regular? <br> \\(L_{1}:\\{wxw^{R}|w,x \\in  \\{a,b\\}^{*} \\; and \\; |w|,|x| \\gt 0 \\}, w^{R}\\) is the reverse of string w <br>\\(L_{2}:\\{a^{n}b^{m}|m\\neq n \\; and \\; m,n\\geq 0\\}\\)<br> \\(L_{3}:\\{a^{p}b^{q}c^{r}|p,q,r\\geq 0\\}\\) <br><br><strong>(GATE CSE 2015 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>L1 and L3 only</p>",
            "<b>B.</b> <p>L2 only</p>",
            "<b>C.</b> <p>L2 and L3 only</p>",
            "<b>D.</b> <p>L3 only</p>"
          ],
          "correct_answer": "<b>A.</b> <p>L1 and L3 only</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/8254/gate2015-2-36#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>The number of states in the minimal deterministic finite automaton corresponding to the regular expression (0+1)*(10) is __________. <br><br><strong>(GATE CSE 2015 SET-2)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "3",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/8256/gate2015-2-35#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>Consider the following statements.<br>\nI. The complement of every Turing decidable language is Turing decidable <br>\nII. There exists some language which is in NP but is not Turing decidable <br>\nIII. If L is a language in NP, L is Turing decidable <br><br>\nWhich of the above statements is/are true? <br><br><strong>(GATE CSE 2015 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Only II</p>",
            "<b>B.</b> <p>Only III</p>",
            "<b>C.</b> <p>Only I and II</p>",
            "<b>D.</b> <p>Only I and III</p>"
          ],
          "correct_answer": "<b>D.</b> <p>Only I and III</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/8111/gate2015-2-10#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>Consider the NPDA \\(\\langle Q=\\{q_{0},q_{1},q_{2}\\},\\) \\(\\Sigma  =\\{0,1\\},\\) \\(\\Gamma =\\{0,1,\\perp \\},\\delta ,q_{0},\\perp ,\\) \\(F=\\{q_{2}\\} \\rangle\\), where (as per usual convention) Q is the set of states,  \\(\\Sigma\\) is the input alphabet, \\(\\Gamma\\) is the stack alphabet, \\(\\delta\\) is the state transition function, \\(q_{0}\\)  is the initial state, \\(\\perp\\) is the initial stack symbol, and \\(F\\) is the set of accepting states. The state transition is as follows:<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Theory_of_Computation\\q40_d8080bd1.jpg\"><br> Which one of the following sequences must follow the string 101100 so that the overall string is accepted by the automaton? <br><br><strong>(GATE CSE 2015 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(10110\\)</p>",
            "<b>B.</b> <p>\\(10010\\)</p>",
            "<b>C.</b> <p>\\(01010\\)</p>",
            "<b>D.</b> <p>\\(01001\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(10010\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/8357/gate2015-1-40#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Theory_of_Computation\\q39_1ab3952a.jpg\"> <br>Consider the DFAs M and N given above. The number of states in a minimal DFA that accepts the language L(M)\\(\\cap\\) L(N) is___________ <br><br><strong>(GATE CSE 2015 SET-1)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "1",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/8362/gate2015-1-39#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>For any two languages L1 and L2 such that L1 is context-free and L2 is recursively enumerable but not recursive, which of the following is/are necessarily true?<br>\nI. \\(\\bar{L_{1}}\\) (complement of L1) is recursive <br>\nII. \\( \\bar{L_{2}}\\) (complement of L2) is recursive <br>\nIII. \\(\\bar{L_{1}}\\) is context-free <br>\nIV. \\(\\bar{L_{1}} \\cup L_{2}\\) is recursively enumerable <br><br><strong>(GATE CSE 2015 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>I only</p>",
            "<b>B.</b> <p>III only</p>",
            "<b>C.</b> <p>III and IV only</p>",
            "<b>D.</b> <p>I and IV only</p>"
          ],
          "correct_answer": "<b>D.</b> <p>I and IV only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/8019/gate2015-1-18#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>Consider the following Deterministic Finite Automaton M.<br><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Theory_of_Computation\\q79_655f330d.jpg\"><br>Let S denote the set of eight bit strings whose second, third, sixth and seventh bits are 1. The number of strings in S that are accepted by M is <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0</p>",
            "<b>B.</b> <p>1</p>",
            "<b>C.</b> <p>2</p>",
            "<b>D.</b> <p>3</p>"
          ],
          "correct_answer": "<b>C.</b> <p>2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55100/isro2014-79\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
