window.__examLoadCallback({
  "title": "Theory of Computation - Pushdown Automata",
  "duration": 14,
  "sections": [
    {
      "name": "Pushdown Automata",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"60451\"></a><div itemprop=\"text\">\n<p>The pushdown automation \\( M=(\\left\\{q_{0}, q_{1}, q_{2}\\right\\}, \\left\\{a, b\\right\\}, \\left\\{0, 1\\right\\}, \\delta, q_{0}, 0, \\left\\{q_{0}\\right\\}) \\)&nbsp;with</p>\n\n<p>\\( \\delta (q_{0}, a, 0)= \\left\\{(q_{1}, 10)\\right\\} \\)</p>\n\n<p>\\( \\delta (q_{1}, a, 1)= \\left\\{(q_{1}, 11)\\right\\} \\)</p>\n\n<p>\\( \\delta (q_{1}, b, 1)= \\left\\{(q_{2}, \\lambda)\\right\\} \\)</p>\n\n<p>\\( \\delta (q_{2}, b, 1)= \\left\\{(q_{2}, \\lambda)\\right\\} \\)</p>\n\n<p>\\( \\delta (q_{2}, \\lambda, 0)= \\left\\{(q_{0}, \\lambda)\\right\\} \\)</p>\n\n<p>Accepts the language</p>\n\n\n</div><br><br><b>Theory of Computation: UGC NET CSE | December 2014 | Part 3 | Question: 22</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L=\\left\\{a^{n}b^{m} | n, m \\geq 0\\right\\} \\)</p>",
            "<p>\\( L=\\left\\{a^{n}b^{n} | n \\geq 0\\right\\} \\)</p>",
            "<p>\\( L=\\left\\{a^{n}b^{m} | n, m &gt; 0\\right\\} \\)</p>",
            "<p>\\( L=\\left\\{a^{n}b^{n} | n &gt; 0\\right\\} \\)</p>"
          ],
          "correct_answer": "<p>\\( L=\\left\\{a^{n}b^{n} | n \\geq 0\\right\\} \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/60451/ugc-net-cse-december-2014-part-3-question-22\" target=\"_blank\">https://gateoverflow.in/60451/ugc-net-cse-december-2014-part-3-question-22</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"225853\"></a><div itemprop=\"text\"><p>A pushdown automata behaves like a Turing machine when the number of auxiliary memory is</p>\n\n</div><br><br><b>Theory of Computation: UGC NET CSE | July 2018 | Part 2 | Question: 33</b></p>",
          "type": "numeric",
          "options": [
            "<p>0</p>",
            "<p>1</p>",
            "<p>1 or more</p>",
            "<p>2 or more</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/225853/ugc-net-cse-july-2018-part-2-question-33\" target=\"_blank\">https://gateoverflow.in/225853/ugc-net-cse-july-2018-part-2-question-33</a></p>"
        },
        {
          "id": 3,
          "question": "<p><a name=\"225852\"></a><div itemprop=\"text\"><p>Pushdown automata can recognize language generated by _______</p>\n\n</div><br><br><b>Theory of Computation: UGC NET CSE | July 2018 | Part 2 | Question: 34</b></p>",
          "type": "numeric",
          "options": [
            "<p>Only context free grammar</p>",
            "<p>Only regular grammar</p>",
            "<p>Context free grammar or regular grammar</p>",
            "<p>Only context sensitive grammar</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/225852/ugc-net-cse-july-2018-part-2-question-34\" target=\"_blank\">https://gateoverflow.in/225852/ugc-net-cse-july-2018-part-2-question-34</a></p>"
        },
        {
          "id": 4,
          "question": "<p><a name=\"58499\"></a><div itemprop=\"text\">\n<p>A pushdown automation \\( M=(Q, \\Sigma, \\Gamma, &nbsp;\\delta , q_0, z, F) \\) is set to be deterministic subject to which of the following condition(s), for every \\( q \\in Q, a \\in \\Sigma \\cup \\{\\lambda\\} \\text{ and } b \\in \\Gamma \\)</p>\n\n<p>&nbsp;(s1) \\( \\delta(q, a, b) \\) contains at most one element</p>\n\n<p>(s2) if \\( \\delta(q, \\lambda, b) \\) is not empty then \\( \\delta(q, c, b) \\) must be empty for every \\( c \\in \\Sigma \\)</p>\n\n\n</div><br><br><b>Theory of Computation: UGC NET CSE | June 2013 | Part 3 | Question: 37</b></p>",
          "type": "single",
          "options": [
            "<p>only s1</p>",
            "<p>only s2</p>",
            "<p>both s1 and s2</p>",
            "<p>neither s1 nor s2</p>"
          ],
          "correct_answer": "<p>both s1 and s2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/58499/ugc-net-cse-june-2013-part-3-question-37\" target=\"_blank\">https://gateoverflow.in/58499/ugc-net-cse-june-2013-part-3-question-37</a></p>"
        },
        {
          "id": 5,
          "question": "<p><a name=\"59527\"></a><div itemprop=\"text\"><p>Non-deterministic pushdown automaton that accepts the language generated by the grammar: \\( S \\rightarrow aSS \\mid ab \\) is</p>\n\n</div><br><br><b>Theory of Computation: UGC NET CSE | September 2013 | Part 3 | Question: 22</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\delta (q_0, \\lambda , z)= \\{ (q_1, z) \\}; &nbsp;\\delta(q_0, a, S) = \\{ (q_1, SS) \\}, (q_1, B) \\} &nbsp;&nbsp;\\delta (q_0, b, B) = \\{ (q_1, \\lambda) \\}, &nbsp;&nbsp;\\delta (q_1, \\lambda , z) = \\{ (q_f, \\lambda ) \\}  \\)</p>",
            "<p>\\( \\delta (q_0, \\lambda , z)= \\{ (q_1, Sz) \\}; \\delta(q_0, a, S) = \\{ (q_1, SS) \\}, (q_1, B) \\} \\delta (q_0, b, B) = \\{ (q_1, \\lambda) \\}, &nbsp;\\delta (q_1, \\lambda , z) = \\{ (q_f, \\lambda ) \\} \\)</p>",
            "<p>\\( \\delta (q_0, \\lambda , z)= \\{ (q_1, Sz) \\}; \\delta(q_0, a, S) = \\{ (q_1, S) \\}, (q_1, B) \\} \\delta (q_0, b, \\lambda) = \\{ (q_1, B) \\}, \\delta (q_1, \\lambda , z) = \\{( q_f, \\lambda ) \\} \\)</p>",
            "<p>\\( \\delta (q_0, \\lambda , z)= \\{ (q_1, z) \\}; \\delta(q_0, a, S) = \\{ (q_1, SS) \\}, (q_1, B) \\} \\delta (q_0, b, \\lambda) = \\{ (q_1,B) \\}, \\delta (q_1, \\lambda , z) = \\{ (q_f, \\lambda ) \\} \\)</p>"
          ],
          "correct_answer": "<p>\\( \\delta (q_0, \\lambda , z)= \\{ (q_1, Sz) \\}; \\delta(q_0, a, S) = \\{ (q_1, SS) \\}, (q_1, B) \\} \\delta (q_0, b, B) = \\{ (q_1, \\lambda) \\}, &nbsp;\\delta (q_1, \\lambda , z) = \\{ (q_f, \\lambda ) \\} \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/59527/ugc-net-cse-september-2013-part-3-question-22\" target=\"_blank\">https://gateoverflow.in/59527/ugc-net-cse-september-2013-part-3-question-22</a></p>"
        }
      ]
    }
  ]
});
