window.__examLoadCallback({
  "title": "CO and Architecture - Addressing Modes",
  "duration": 30,
  "sections": [
    {
      "name": "Addressing Modes",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"70747\"></a><div itemprop=\"text\"><p>In _____&nbsp;addressing mode, the operands are stored in the memory. The address of the corresponding memory location is given in a register which is specified in the instruction.</p>\n\n</div><br><br><b>CO & Architecture: UGC NET CSE | August 2016 | Part 3 | Question: 5</b></p>",
          "type": "numeric",
          "options": [
            "<p>Register direct</p>",
            "<p>Register indirect</p>",
            "<p>Base indexed</p>",
            "<p>Displacement</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/70747/ugc-net-cse-august-2016-part-3-question-5\" target=\"_blank\">https://gateoverflow.in/70747/ugc-net-cse-august-2016-part-3-question-5</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"155362\"></a><div itemprop=\"text\"><p>In which addressing mode, the effective address of the operand is generated by adding a constant value to the contents of register ?</p>\n\n</div><br><br><b>CO & Architecture: UGC NET CSE | December 2008 | Part 2 | Question: 38</b></p>",
          "type": "single",
          "options": [
            "<p>absolute mode&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>",
            "<p>immediate mode&nbsp; &nbsp; &nbsp;</p>",
            "<p>indirect mode&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>",
            "<p>index mode</p>"
          ],
          "correct_answer": "<p>index mode</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/155362/ugc-net-cse-december-2008-part-2-question-38\" target=\"_blank\">https://gateoverflow.in/155362/ugc-net-cse-december-2008-part-2-question-38</a></p>"
        },
        {
          "id": 3,
          "question": "<p><a name=\"66911\"></a><div itemprop=\"text\"><p>The register or main memory location which contains the effective address of the operand is known as</p>\n\n</div><br><br><b>CO & Architecture: UGC NET CSE | December 2010 | Part 2 | Question: 34</b></p>",
          "type": "numeric",
          "options": [
            "<p>Pointer</p>",
            "<p>Special location</p>",
            "<p>Indexed register</p>",
            "<p>None of the above</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/66911/ugc-net-cse-december-2010-part-2-question-34\" target=\"_blank\">https://gateoverflow.in/66911/ugc-net-cse-december-2010-part-2-question-34</a></p>"
        },
        {
          "id": 4,
          "question": "<p><a name=\"60730\"></a><div itemprop=\"text\"><p>Match the following:</p>\n\n<p>\\( \\begin{array}{} &nbsp;{} &amp; {\\textbf{List -I}}&nbsp; &amp; {} &amp; {\\textbf{List-II}} \\\\ &nbsp;\\text{a.} &amp;&nbsp; \\text{Indexed addressing} &amp; \\text{i.} &amp;&nbsp; \\text{is not used when an operand is moved }\\\\&amp;&amp;&amp; \\text{from memory into a register or from a }\\\\&nbsp; &amp; &amp; &amp;&nbsp; \\text{register to memory} \\\\ &nbsp;\\text{b.} &amp;&nbsp; \\text{Direct&nbsp;addressing} &amp; \\text{ii.} &amp;&nbsp; \\text{Memory address is computed by adding}\\\\&amp;&amp;&amp; \\text{up two registers plus an (optional) offset} \\\\&nbsp;&nbsp;\\text{c.} &amp; \\text{Register addressing} &amp; \\text{iii.} &amp; \\text{Addressing memory by giving a register} \\\\ &amp;&amp;&amp; \\text{ plus a content offset} \\\\ &nbsp;\\text{d.} &amp; \\text{Base indexed addressing} &amp; \\text{iv.} &amp; \\text{can only be used to access global variables}\\\\ &amp;&amp;&amp; \\text{whose address is known at compile time }\\\\&nbsp;&nbsp;\\end{array} \\)</p>\n\n<p><strong>Codes:</strong></p>\n\n</div><br><br><b>CO & Architecture: UGC NET CSE | December 2013 | Part 3 | Question: 49</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\text{a-ii, b-i, c-iv, d-iii} \\)</p>",
            "<p>\\( \\text{a-ii, b-iv, c-i, d-iii} \\)</p>",
            "<p>\\( \\text{a-iii, b-iv, c-i, d-ii} \\)</p>",
            "<p>\\( \\text{a-iii, b-i, c-iv, d-ii} \\)</p>"
          ],
          "correct_answer": "<p>\\( \\text{a-iii, b-iv, c-i, d-ii} \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/60730/ugc-net-cse-december-2013-part-3-question-49\" target=\"_blank\">https://gateoverflow.in/60730/ugc-net-cse-december-2013-part-3-question-49</a></p>"
        },
        {
          "id": 5,
          "question": "<p><a name=\"335234\"></a><div itemprop=\"text\"><p>Match the following :</p>\n\n<p>\\( \\begin{array}{clcl} &nbsp;&amp; {\\textbf{Addressing Mode}}&nbsp; &amp; {} &amp; {\\textbf{Location of operand}} \\\\ \\text{a.} &amp;&nbsp; \\text{Implied} &amp; \\text{i.} &amp;&nbsp; \\text{Registers which are in CPU}\\\\ &nbsp;\\text{b.} &amp; \\text{Immediate} &amp; \\text{ii.} &amp; \\text{Register specifies the address}\\\\&amp;&amp; &amp;\\text{of the operand&nbsp;} \\\\&nbsp;&nbsp;\\text{c.} &amp; \\text{Register} &amp; \\text{iii.} &amp; \\text{Specified in the register} \\\\ &nbsp;\\text{d.} &amp; \\text{Register Indirect } &amp; \\text{iv.} &amp; \\text{Specified&nbsp; implicitly in the definition}\\\\&amp;&amp;&amp; \\text{&nbsp; of instruction }\\\\&nbsp;\\end{array} \\)</p>\n\n<p>&nbsp;\\( \\textbf{Codes :} \\)</p>\n\n</div><br><br><b>CO & Architecture: UGC NET CSE | January 2017 | Part 3 | Question: 4</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\text{a-iv, b-iii, c-i, d-ii} \\)</p>",
            "<p>\\( \\text{a-iv, b-i, c-iii, d-ii} \\)</p>",
            "<p>\\( \\text{a-iv, b-ii, c-i, d-iii} \\)</p>",
            "<p>\\( \\text{a-iv, b-iii, c-ii, d-i} \\)</p>"
          ],
          "correct_answer": "<p>\\( \\text{a-iv, b-iii, c-i, d-ii} \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/335234/ugc-net-cse-january-2017-part-3-question-4\" target=\"_blank\">https://gateoverflow.in/335234/ugc-net-cse-january-2017-part-3-question-4</a></p>"
        },
        {
          "id": 6,
          "question": "<p><a name=\"57097\"></a><div itemprop=\"text\"><p>The ____ addressing mode is similar to register indirect addressing mode, except that an offset is added to the contents of the register. The offset and register are specified in the instruction.</p>\n\n</div><br><br><b>CO & Architecture: UGC NET CSE | July 2016 | Part 3 | Question: 5</b></p>",
          "type": "single",
          "options": [
            "<p>Base indexed</p>",
            "<p>Base indexed plus displacement</p>",
            "<p>Indexed</p>",
            "<p>Displacement</p>"
          ],
          "correct_answer": "<p>Displacement</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/57097/ugc-net-cse-july-2016-part-3-question-5\" target=\"_blank\">https://gateoverflow.in/57097/ugc-net-cse-july-2016-part-3-question-5</a></p>"
        },
        {
          "id": 7,
          "question": "<p><a name=\"154133\"></a><div itemprop=\"text\"><p>In which addressing mode the operand is given explicitly in the instruction itself ?</p>\n\n</div><br><br><b>CO & Architecture: UGC NET CSE | June 2009 | Part 2 | Question: 33</b></p>",
          "type": "numeric",
          "options": [
            "<p>Absolute mode&nbsp; &nbsp;&nbsp;</p>",
            "<p>Immediate mode&nbsp;&nbsp;&nbsp;</p>",
            "<p>Indirect mode&nbsp; &nbsp;&nbsp;</p>",
            "<p>Index mode</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/154133/ugc-net-cse-june-2009-part-2-question-33\" target=\"_blank\">https://gateoverflow.in/154133/ugc-net-cse-june-2009-part-2-question-33</a></p>"
        },
        {
          "id": 8,
          "question": "<p><a name=\"56229\"></a><div itemprop=\"text\"><p>Identify the addressing modes of the below instructions and match them :</p>\n\n<p>\\( \\begin{array}{}&nbsp;\\text{(a)} &amp; \\text{ADI} &amp; \\text{(i)}&nbsp;&amp; \\text{Immediate addressing} \\\\ &nbsp;\\text{(b)} &amp; \\text{STA}&nbsp;&amp; \\text{(ii)}&nbsp;&amp; \\text{Direct Addressing} \\\\ &nbsp;\\text{(c)}&amp;&nbsp; \\text{CMA} &amp; \\text{(iii)}&amp; \\text{Implied Addressing} \\\\ &nbsp;\\text{(d)} &amp; \\text{SUB} &amp; \\text{(iv)}&amp; \\text{Register addressing}&nbsp;\\\\ \\end{array} \\)</p>\n\n</div><br><br><b>CO & Architecture: UGC NET CSE | June 2012 | Part 3 | Question: 27</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\text{a-i, b-ii, c-iii, d-iv} \\)</p>",
            "<p>\\( \\text{a-ii, b-i, c-iv, d-iii} \\)</p>",
            "<p>\\( \\text{a-iii, b-ii, c-i, d-iv} \\)</p>",
            "<p>\\( \\text{a-iv, b-iii, c-ii, d-i} \\)</p>"
          ],
          "correct_answer": "<p>\\( \\text{a-i, b-ii, c-iii, d-iv} \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/56229/ugc-net-cse-june-2012-part-3-question-27\" target=\"_blank\">https://gateoverflow.in/56229/ugc-net-cse-june-2012-part-3-question-27</a></p>"
        },
        {
          "id": 9,
          "question": "<p><a name=\"57016\"></a><div itemprop=\"text\">\n<p>The advantage of _______ is that it can reference memory without paying the price of having a full memory address in the instruction.&nbsp;</p>\n\n\n</div><br><br><b>CO & Architecture: UGC NET CSE | June 2014 | Part 3 | Question: 40</b></p>",
          "type": "single",
          "options": [
            "<p>Direct addressing</p>",
            "<p>Indexed addressing</p>",
            "<p>Register addressing&nbsp;</p>",
            "<p>Register Indirect addressing &nbsp;</p>"
          ],
          "correct_answer": "<p>Register Indirect addressing &nbsp;</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/57016/ugc-net-cse-june-2014-part-3-question-40\" target=\"_blank\">https://gateoverflow.in/57016/ugc-net-cse-june-2014-part-3-question-40</a></p>"
        },
        {
          "id": 10,
          "question": "<p><a name=\"316268\"></a><div itemprop=\"text\"><p>Which type of addressing mode, less number of memory references are required?</p>\n\n</div><br><br><b>CO & Architecture: UGC NET CSE | June 2019 | Part 2 | Question: 11</b></p>",
          "type": "numeric",
          "options": [
            "<p>Immediate</p>",
            "<p>Implied</p>",
            "<p>Register</p>",
            "<p>Indexed</p>"
          ],
          "correct_answer": "X",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/316268/ugc-net-cse-june-2019-part-2-question-11\" target=\"_blank\">https://gateoverflow.in/316268/ugc-net-cse-june-2019-part-2-question-11</a></p>"
        },
        {
          "id": 11,
          "question": "<p><a name=\"166380\"></a><div itemprop=\"text\"><p>Which of the following addressing mode is best suited to access elements of an array of contiguous memory locations?</p>\n\n</div><br><br><b>CO & Architecture: UGC NET CSE | November 2017 | Part 3 | Question: 4</b></p>",
          "type": "single",
          "options": [
            "<p>Indexed addressing mode &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>",
            "<p>Base Register addressing mode</p>",
            "<p>Relative address mode &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>",
            "<p>Displacement mode</p>"
          ],
          "correct_answer": "<p>Indexed addressing mode &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/166380/ugc-net-cse-november-2017-part-3-question-4\" target=\"_blank\">https://gateoverflow.in/166380/ugc-net-cse-november-2017-part-3-question-4</a></p>"
        }
      ]
    }
  ]
});
