window.__examLoadCallback({
  "title": "Operating System - NIELIT 2017 DEC Scientific Assistant A - Section B",
  "duration": 14,
  "sections": [
    {
      "name": "NIELIT 2017 DEC Scientific Assistant A - Section B",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"336788\"></a><div itemprop=\"text\"><p>Page fault frequency in an operating system is reduced when the :</p>\n\n</div><br><br><b>Operating System: NIELIT 2017 DEC Scientific Assistant A</b></p>",
          "type": "single",
          "options": [
            "<p>Process tend to be I/O&nbsp;bound</p>",
            "<p>Locality of reference is applicable to the process</p>",
            "<p>Size of pages is reduced</p>",
            "<p>Processes tend to be CPU&nbsp;bound</p>"
          ],
          "correct_answer": "<p>Locality of reference is applicable to the process</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/336788/nielit-2017-dec-scientific-assistant-a-section-b-58\" target=\"_blank\">https://gateoverflow.in/336788/nielit-2017-dec-scientific-assistant-a-section-b-58</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"336798\"></a><div itemprop=\"text\"><p>The process of loading the operating system into memory is called :&nbsp;</p>\n\n</div><br><br><b>Operating System: NIELIT 2017 DEC Scientific Assistant A</b></p>",
          "type": "single",
          "options": [
            "<p>Booting</p>",
            "<p>Spooling</p>",
            "<p>Thrashing</p>",
            "<p>Formatting</p>"
          ],
          "correct_answer": "<p>Booting</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/336798/nielit-2017-dec-scientific-assistant-a-section-b-48\" target=\"_blank\">https://gateoverflow.in/336798/nielit-2017-dec-scientific-assistant-a-section-b-48</a></p>"
        },
        {
          "id": 3,
          "question": "<p><a name=\"336887\"></a><div itemprop=\"text\"><p>&nbsp;</p>\n\n<p>The address sequence generated by tracing a&nbsp;particular program executing in a pure demand paging system with \\( 100 \\) records per page, with \\( 1 \\) free main memory frame is recorded as follows. What is the number of Page Faults?</p>\n\n<p>\\( 0100,0200,0430,0510,0530,0560,0120,0220,0240,0260,0320,0370. \\)</p>\n\n</div><br><br><b>Operating System: NIELIT 2017 OCT Scientific Assistant A (CS)</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 15,4 \\)</p>",
            "<p>\\( 6,4 \\)</p>",
            "<p>\\( 7,2 \\)</p>",
            "<p>\\( 4,6 \\)</p>"
          ],
          "correct_answer": "<p>\\( 7,2 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/336887/nielit-2017-oct-scientific-assistant-a-cs-section-b-33\" target=\"_blank\">https://gateoverflow.in/336887/nielit-2017-oct-scientific-assistant-a-cs-section-b-33</a></p>"
        },
        {
          "id": 4,
          "question": "<p><a name=\"336987\"></a><div itemprop=\"text\"><p>The address sequence generated by tracing a&nbsp;particular program executing in a pure demand paging system with \\( 100 \\) records per page, with \\( 1 \\) free main memory frame is recorded as follows. What is the number of Page Faults?</p>\n\n<p>\\( 0100,0200,0430,0499,0510,0530,0560,0120,0220,0240,0260,0320,0370. \\)</p>\n\n</div><br><br><b>Operating System: NIELIT 2017 OCT Scientific Assistant A (IT)</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 15,4 \\)</p>",
            "<p>\\( 6,4 \\)</p>",
            "<p>\\( 7,2 \\)</p>",
            "<p>\\( 4,6 \\)</p>"
          ],
          "correct_answer": "<p>\\( 7,2 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/336987/nielit-2017-oct-scientific-assistant-a-it-section-c-10\" target=\"_blank\">https://gateoverflow.in/336987/nielit-2017-oct-scientific-assistant-a-it-section-c-10</a></p>"
        },
        {
          "id": 5,
          "question": "<p><a name=\"351612\"></a><div itemprop=\"text\"><p>On computers where there are multiple operating system, the decision to load a particular one is done by ________.</p>\n\n</div><br><br><b>Operating System: NIELIT Scientist B 2020 November: 70</b></p>",
          "type": "single",
          "options": [
            "<p>\\( PCB \\)</p>",
            "<p>Inode</p>",
            "<p>File Control Block</p>",
            "<p>Boot Loader</p>"
          ],
          "correct_answer": "<p>Boot Loader</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/351612/nielit-scientist-b-2020-november-70\" target=\"_blank\">https://gateoverflow.in/351612/nielit-scientist-b-2020-november-70</a></p>"
        }
      ]
    }
  ]
});
