window.__examLoadCallback({
  "title": "Computer_Organization - Computer_Organization - Slot 13",
  "duration": 42,
  "sections": [
    {
      "name": "Computer_Organization",
      "questions": [
        {
          "id": 1,
          "question": "<p>The microinstructions stored in the control memory of a processor have a width of 26 bits. Each microinstruction is divided into three fields. a micro operation field of 13 bits, a next address field (X), and a MUX select field (Y). There are 8 status bits in the inputs of the MUX. How many bits are there in the X and Y fields, and what is the size of the control memory in number of words? <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>10, 3, 1024</p>",
            "<b>B.</b> <p>8, 5, 256</p>",
            "<b>C.</b> <p>5, 8, 2048</p>",
            "<b>D.</b> <p>10, 3, 512</p>"
          ],
          "correct_answer": "<b>A.</b> <p>10, 3, 1024</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48055/isro2009-34\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>The process of organizing the memory into two banks to allow 8-and 16-bit data operation is called <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Bank switching</p>",
            "<b>B.</b> <p>Indexed mapping</p>",
            "<b>C.</b> <p>Two-way memory interleaving</p>",
            "<b>D.</b> <p>Memory segmentation</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Two-way memory interleaving</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48046/isro2009-23\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>A certain microprocessor requires 4.5 microseconds to respond to an interrupt. Assuming that the three interrupts\\(I_1\\), \\(I_2\\) and \\(I_3\\) require the following execution time after the interrupt is recognized:<br>\nI.   \\(I_1\\) requires 25 microseconds<br>\nII.  \\(I_2\\) requires 35 microseconds<br>\nIII. \\(I_3\\) requires 20 microseconds<br>\n\\(I_1\\) has the highest priority and \\(I_3\\) has the lowest. What is the possible range of time for \\(I_3\\) to be executed assuming that it may or may not occur simultaneously with other interrupts? <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>24.5 microseconds to 39.5 microseconds</p>",
            "<b>B.</b> <p>24.5 microseconds to 93.5 microseconds</p>",
            "<b>C.</b> <p>4.5 microseconds to 24.5 microseconds</p>",
            "<b>D.</b> <p>29.5 microseconds 93.5 microseconds</p>"
          ],
          "correct_answer": "<b>B.</b> <p>24.5 microseconds to 93.5 microseconds</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48044/isro2009-22\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>In which addressing mode, the effectives address of the operand is generated by adding a constant value to the content of a register? <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Absolute mode</p>",
            "<b>B.</b> <p>Indirect mode</p>",
            "<b>C.</b> <p>Immediate mode</p>",
            "<b>D.</b> <p>Index mode</p>"
          ],
          "correct_answer": "<b>D.</b> <p>Index mode</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48041/isro2009-21-ugcnet-dec2012-ii-12\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Which of the following statements about synchronous and asynchronous I/O is NOT true? <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>An ISR is invoked on completion of I/O in synchronous I/O but not in asynchronous I/O</p>",
            "<b>B.</b> <p>In both synchronous and asynchronous I/O, an ISR (Interrupt Service Routine) is invoked after completion of the I/O</p>",
            "<b>C.</b> <p>A process making a synchronous I/O call waits until I/O is complete, but a process making an asynchronous I/O call does not wait for completion of the I/O</p>",
            "<b>D.</b> <p>In the case of synchronous I/O, the process waiting for the completion of I/O is woken up by the ISR that is invoked after the completion of I/O</p>"
          ],
          "correct_answer": "<b>B.</b> <p>In both synchronous and asynchronous I/O, an ISR (Interrupt Service Routine) is invoked after completion of the I/O</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/487/gate2008-64-isro2009-13\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>A hard disk has 63 sectors per track, 10 platters each with 2 recording surfaces\nand 1000 cylinders. The address of a sector is given as a triple (c,h,s), where c is the cylinder number, h is the surface number and s is the sector number. Thus, the \\(0^{th}\\) sector is addressed as (0,0,0), the \\(1^{st}\\) sector as (0,0,1), and so on <br><br>The address of the \\(1039^{th}\\) sector is <br><br><strong>(GATE CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>(0,15,31)</p>",
            "<b>B.</b> <p>(0,16,30)</p>",
            "<b>C.</b> <p>(0,16,31)</p>",
            "<b>D.</b> <p>(0,17,31)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>(0,16,31)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/43477/gate2009-52#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>A hard disk has 63 sectors per track, 10 platters each with 2 recording surfaces\nand 1000 cylinders. The address of a sector is given as a triple (c,h,s), where c is the cylinder number, h is the surface number and s is the sector number. Thus, the \\(0^{th}\\) sector is addressed as (0,0,0), the \\(1^{st}\\) sector as (0,0,1), and so on <br><br> The address (400, 16, 29) corresponds to sector number: <br><br><strong>(GATE CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>505035</p>",
            "<b>B.</b> <p>505036</p>",
            "<b>C.</b> <p>505037</p>",
            "<b>D.</b> <p>505038</p>"
          ],
          "correct_answer": "<b>C.</b> <p>505037</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/1337/gate2009-51#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>Consider a 4-way set associative cache (initially empty) with total 16 cache\nblocks. The main memory consists of 256 blocks and the request for memory\nblocks is in the following order: <br><br>\n0, 255, 1, 4, 3, 8, 133, 159, 216, 129, 63, 8, 48, 32, 73, 92, 155. <br><br>\nWhich one of the following memory block will NOT be in cache if LRU replacement\npolicy is used? <br><br><strong>(GATE CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>3</p>",
            "<b>B.</b> <p>8</p>",
            "<b>C.</b> <p>129</p>",
            "<b>D.</b> <p>216</p>"
          ],
          "correct_answer": "<b>D.</b> <p>216</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/1315/gate2009-29#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>Consider a 4 stage pipeline processor. The number of cycles needed by the four\ninstructions I1, I2, I3, I4 in stages S1, S2, S3, S4 is shown below:  <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Computer_Organization\\q28_52a82c1b.jpg\"><br> What is the number of cycles needed to execute the following loop? <br> For (i=1 to 2) {I1; I2; I3; I4;} <br><br><strong>(GATE CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>16</p>",
            "<b>B.</b> <p>23</p>",
            "<b>C.</b> <p>28</p>",
            "<b>D.</b> <p>30</p>"
          ],
          "correct_answer": "<b>B.</b> <p>23</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/1314/gate2009-28#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>A CPU generally handles an interrupt by executing an interrupt service routine <br><br><strong>(GATE CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>As soon as an interrupt is raised</p>",
            "<b>B.</b> <p>By checking the interrupt register at the end of fetch cycle.</p>",
            "<b>C.</b> <p>By checking the interrupt register after finishing the execution of the current instruction.</p>",
            "<b>D.</b> <p>By checking the interrupt register at fixed time intervals.</p>"
          ],
          "correct_answer": "<b>C.</b> <p>By checking the interrupt register after finishing the execution of the current instruction.</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1300/gate2009-8#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>How many 32K x 1 RAM chips are needed to provide a memory capacity of 256Kbytes? <br><br><strong>(GATE CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>8</p>",
            "<b>B.</b> <p>32</p>",
            "<b>C.</b> <p>64</p>",
            "<b>D.</b> <p>128</p>"
          ],
          "correct_answer": "<b>C.</b> <p>64</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1299/gate2009-7#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>Which of the following is an example of spooled device? <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A line printer used to print the output of a number of jobs</p>",
            "<b>B.</b> <p>A terminal used to enter input data to a running program</p>",
            "<b>C.</b> <p>A secondary storage device in a virtual memory system</p>",
            "<b>D.</b> <p>A graphic display device</p>"
          ],
          "correct_answer": "<b>A.</b> <p>A line printer used to print the output of a number of jobs</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2724/gate1996-1-20-isro2008-56\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>The Memory Address Register <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>is a hardware memory device which denotes the location of the current instruction being executed.</p>",
            "<b>B.</b> <p>is a group of electrical ckt, that performs the intent of instructions fetched from memory</p>",
            "<b>C.</b> <p>contains the address of the memory location that is to be read from or stored into</p>",
            "<b>D.</b> <p>contains a copy of the designated memory location specified by the MAR after a \"read\" or the new contents of the memory prior to a \"write\"</p>"
          ],
          "correct_answer": "<b>C.</b> <p>contains the address of the memory location that is to be read from or stored into</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49998/isro2008-55\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>The total time to prepare a disk drive mechanism for a block of data to be read from it is <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>seek time</p>",
            "<b>B.</b> <p>latency</p>",
            "<b>C.</b> <p>latency plus seek time</p>",
            "<b>D.</b> <p>transmission time</p>"
          ],
          "correct_answer": "<b>C.</b> <p>latency plus seek time</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/17263/isro2008-49\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>Raid configurations of the disks are used to provide <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Fault-tolerance</p>",
            "<b>B.</b> <p>High speed</p>",
            "<b>C.</b> <p>High data density</p>",
            "<b>D.</b> <p>(A) &amp; (B)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>(A) &amp; (B)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1496/gate1999-2-18-isro2008-46\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
