window.__examLoadCallback({
  "title": "English Language - Appropriate Word",
  "duration": 246,
  "sections": [
    {
      "name": "Appropriate Word",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"4244\"></a><div itemprop=\"text\"><p>Fill in the blanks</p>\n\n<p>Real friends, genuinely wanting the best for the organisation, _________ different garbs.</p>\n\n</div><br><br><b>English Language: CAT 1994 | Question: 30</b></p>",
          "type": "single",
          "options": [
            "<p>come in&nbsp;</p>",
            "<p>clad in</p>",
            "<p>dressed in&nbsp;</p>",
            "<p>clothed in</p>"
          ],
          "correct_answer": "<p>come in&nbsp;</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/4244/cat-1994-question-30\" target=\"_blank\">https://aptitude.gateoverflow.in/4244/cat-1994-question-30</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"1061\"></a><div itemprop=\"text\"><p><strong>For the capitalized and bolded word a sentence is given, you have to find out the option which represents the similar meaning to the given word</strong>.</p>\n\n<p><strong>OPPROBRIUM </strong>– The police has to bear the opprobrium generated by their blatant partisan conduct.</p>\n\n</div><br><br><b>English Language: CAT 2002 | Question: 46</b></p>",
          "type": "numeric",
          "options": [
            "<p>Harsh criticism</p>",
            "<p>Acute distrust</p>",
            "<p>Bitter enmity</p>",
            "<p>Stark oppressiveness</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1061/cat-2002-question-46\" target=\"_blank\">https://aptitude.gateoverflow.in/1061/cat-2002-question-46</a></p>"
        },
        {
          "id": 3,
          "question": "<p><a name=\"1062\"></a><div itemprop=\"text\"><p><strong>For the capitalized word a sentence is given, you have to find out the option which represents the similar meaning to the given word.</strong></p>\n\n<p><strong>PORTENDS </strong>– it appears to many that US “war on terrorism” portends trouble in Gulf.</p>\n\n</div><br><br><b>English Language: CAT 2002 | Question: 47</b></p>",
          "type": "numeric",
          "options": [
            "<p>Introduces</p>",
            "<p>Bodes</p>",
            "<p>Spells</p>",
            "<p>Evokes</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1062/cat-2002-question-47\" target=\"_blank\">https://aptitude.gateoverflow.in/1062/cat-2002-question-47</a></p>"
        },
        {
          "id": 4,
          "question": "<p><a name=\"1063\"></a><div itemprop=\"text\"><p><strong>For the capitalized word a sentence is given, you have to find out the option which represents the similar meaning to the given word.</strong></p>\n\n<p><strong>PREVARICATE </strong>– When her video tape recording was shown to her and asked to explain her presence, she started prevaricating.</p>\n\n</div><br><br><b>English Language: CAT 2002 | Question: 48</b></p>",
          "type": "numeric",
          "options": [
            "<p>Speaking evasively</p>",
            "<p>Speaking violently</p>",
            "<p>Lying furiously</p>",
            "<p>Throwing a tantrum</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1063/cat-2002-question-48\" target=\"_blank\">https://aptitude.gateoverflow.in/1063/cat-2002-question-48</a></p>"
        },
        {
          "id": 5,
          "question": "<p><a name=\"1064\"></a><div itemprop=\"text\"><p><strong>For the capitalized word a sentence is given, you have to find out the option which represents the similar meaning to the given word.</strong></p>\n\n<p><strong>RESTIVE </strong>– The waiting public started getting restive when the leader got late for the speech.</p>\n\n</div><br><br><b>English Language: CAT 2002 | Question: 49</b></p>",
          "type": "numeric",
          "options": [
            "<p>Angry</p>",
            "<p>Violent</p>",
            "<p>Restless</p>",
            "<p>Distressed</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1064/cat-2002-question-49\" target=\"_blank\">https://aptitude.gateoverflow.in/1064/cat-2002-question-49</a></p>"
        },
        {
          "id": 6,
          "question": "<p><a name=\"1065\"></a><div itemprop=\"text\"><p><strong>For the capitalized word a sentence is given, you have to find out the option which represents the similar meaning to the given word.</strong></p>\n\n<p><strong>OSTENSIBLE </strong>– The watchmen’s ostensible job is to guard this building.</p>\n\n</div><br><br><b>English Language: CAT 2002 | Question: 50</b></p>",
          "type": "numeric",
          "options": [
            "<p>Blatant</p>",
            "<p>Ostentatious</p>",
            "<p>Insidious</p>",
            "<p>Apparent</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1065/cat-2002-question-50\" target=\"_blank\">https://aptitude.gateoverflow.in/1065/cat-2002-question-50</a></p>"
        },
        {
          "id": 7,
          "question": "<p><a name=\"971\"></a><div itemprop=\"text\"><p><strong>In the question, the word at the top of the table is used in four different ways, numbered 1 to 4. Choose the option in which the usage of word is INCORRECT or INAPPROPRIATE.</strong></p>\n\n<p><strong>BUNDLE</strong></p>\n\n<ol start=\"1\" style=\"list-style-type:decimal\">\n\t<li>The new born baby was a bundle of joy for the family.</li>\n\t<li>Mobile operators are offering a bundle of additional benefits.</li>\n\t<li>He made a bundle in the share market.</li>\n\t<li>It was sheet luck that brought a bundle of boy-scouts to where I was lying wounded.</li>\n</ol></div><br><br><b>English Language: CAT 2003 | Question: 1</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/971/cat-2003-question-1-41\" target=\"_blank\">https://aptitude.gateoverflow.in/971/cat-2003-question-1-41</a></p>"
        },
        {
          "id": 8,
          "question": "<p><a name=\"972\"></a><div itemprop=\"text\"><p><strong>In the question, the word at the top of the table is used in four different ways, numbered 1 to 4. Choose the option in which the usage of word is INCORRECT or INAPPROPRIATE.</strong></p>\n\n<p><strong><u>Distinct</u></strong></p>\n\n<ol start=\"1\" style=\"list-style-type:decimal\">\n\t<li>He is distinct about what is right and what is wrong</li>\n\t<li>Mars became distinct on the horizon in the months of August</li>\n\t<li>The distinct strains of Ravi's violin could be heard above the general din.</li>\n\t<li>Ghoshbabu's is a distinct case of water rising above its own level.</li>\n</ol></div><br><br><b>English Language: CAT 2003 | Question: 1</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/972/cat-2003-question-1-42\" target=\"_blank\">https://aptitude.gateoverflow.in/972/cat-2003-question-1-42</a></p>"
        },
        {
          "id": 9,
          "question": "<p><a name=\"973\"></a><div itemprop=\"text\"><p><strong>In the question, the word at the top of the table is used in four different ways, numbered 1 to 4. Choose the option in which the usage of word is INCORRECT or INAPPROPRIATE.</strong></p>\n\n<p><strong><u>Implication:</u></strong></p>\n\n<ol start=\"1\" style=\"list-style-type:decimal\">\n\t<li>Everyone appreciated the Headmaster's implication in raising flood relief in the village.</li>\n\t<li>This letter would lead to the implication of several industrialists in the share market scam.</li>\n\t<li>Several members of the audience missed the implication of the minister's promise.</li>\n\t<li>Death, by implication, is the only solution the poem offers the reader.</li>\n</ol></div><br><br><b>English Language: CAT 2003 | Question: 1</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/973/cat-2003-question-1-43\" target=\"_blank\">https://aptitude.gateoverflow.in/973/cat-2003-question-1-43</a></p>"
        },
        {
          "id": 10,
          "question": "<p><a name=\"974\"></a><div itemprop=\"text\"><p><strong>In the question, the word at the top of the table is used in four different ways, numbered 1 to 4. Choose the option in which the usage of word is INCORRECT or INAPPROPRIATE.</strong></p>\n\n<p><strong><u>Host</u></strong></p>\n\n<ol start=\"1\" style=\"list-style-type:decimal\">\n\t<li>If you host the party, who will foot the bill?</li>\n\t<li>Kerala's forests are host to a range of snakes.</li>\n\t<li>Ranchi will play the host to the next national film festival.</li>\n\t<li>A virus has infected the host computer.</li>\n</ol></div><br><br><b>English Language: CAT 2003 | Question: 1</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/974/cat-2003-question-1-44\" target=\"_blank\">https://aptitude.gateoverflow.in/974/cat-2003-question-1-44</a></p>"
        },
        {
          "id": 11,
          "question": "<p><a name=\"975\"></a><div itemprop=\"text\"><p><strong>In the question, the word at the top of the table is used in four different ways, numbered 1 to 4. Choose the option in which the usage of word is INCORRECT or INAPPROPRIATE.</strong></p>\n\n<p><strong><u>Sort</u></strong></p>\n\n<ol start=\"1\" style=\"list-style-type:decimal\">\n\t<li>What sort of cheese do you use in pizza?</li>\n\t<li>Farmers of all sort attended the rally.</li>\n\t<li>They serve tea of a sort on these rains.</li>\n\t<li>Let's sort these boys into four groups.</li>\n</ol></div><br><br><b>English Language: CAT 2003 | Question: 1</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/975/cat-2003-question-1-45\" target=\"_blank\">https://aptitude.gateoverflow.in/975/cat-2003-question-1-45</a></p>"
        },
        {
          "id": 12,
          "question": "<p><a name=\"1941\"></a><div itemprop=\"text\"><p><strong>In the question, the word at the top of the table is used in four different ways, numbered 1 to 4. Choose the option in which the usage of the word is INCORRECT or INAPPROPRIATE.</strong><br>\n<strong>Help</strong></p>\n\n<table border=\"1\" cellpadding=\"1\" style=\"width:500px\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>1</td>\n\t\t\t<td>This syrup will help your cold.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>2</td>\n\t\t\t<td>I can't help the colour of my skin.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>3</td>\n\t\t\t<td>Ranjit may help himself with the beer in the fridge.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>4</td>\n\t\t\t<td>Do you really expect me to help you out with cash?</td>\n\t\t</tr>\n\t</tbody>\n</table></div><br><br><b>English Language: CAT 2003 | Question: 2</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1941/cat-2003-question-2-17\" target=\"_blank\">https://aptitude.gateoverflow.in/1941/cat-2003-question-2-17</a></p>"
        },
        {
          "id": 13,
          "question": "<p><a name=\"1942\"></a><div itemprop=\"text\"><p><strong>In the question, the word at the top of the table is used in four different ways, numbered 1 to 4. Choose the option in which the usage of the word is INCORRECT or INAPPROPRIATE.</strong><br>\n<strong>Reason</strong></p>\n\n<table border=\"1\" cellpadding=\"1\" style=\"width:500px; border-spacing: 1px;\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>1</td>\n\t\t\t<td>Your stand is beyond all reason.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>2</td>\n\t\t\t<td>Has she given you any reason for her resignation?</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>3</td>\n\t\t\t<td>There is little reason in your pompous advice.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>4</td>\n\t\t\t<td>How do you deal with a friend who doesn't listen to a reason?</td>\n\t\t</tr>\n\t</tbody>\n</table></div><br><br><b>English Language: CAT 2003 | Question: 2</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1942/cat-2003-question-2-18\" target=\"_blank\">https://aptitude.gateoverflow.in/1942/cat-2003-question-2-18</a></p>"
        },
        {
          "id": 14,
          "question": "<p><a name=\"1943\"></a><div itemprop=\"text\"><p><strong>In the question, the word at the top of the table is used in four different ways, numbered 1 to 4. Choose the option in which the usage of the word is INCORRECT or INAPPROPRIATE.<br>\nPaper</strong><br>\nYour suggestions look great on</p>\n\n<table border=\"1\" cellpadding=\"1\" style=\"width:500px; border-spacing: 1px;\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>1</td>\n\t\t\t<td>the paper, but are absolutely impractical.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>2</td>\n\t\t\t<td>Do you know how many trees are killed to make a truckload of paper?</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>3</td>\n\t\t\t<td>So far I have been able to paper over the disagreements among my brothers.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>4</td>\n\t\t\t<td>Dr. Malek will read a paper on criminalization of politic.</td>\n\t\t</tr>\n\t</tbody>\n</table></div><br><br><b>English Language: CAT 2003 | Question: 2</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1943/cat-2003-question-2-19\" target=\"_blank\">https://aptitude.gateoverflow.in/1943/cat-2003-question-2-19</a></p>"
        },
        {
          "id": 15,
          "question": "<p><a name=\"1944\"></a><div itemprop=\"text\"><p><strong>In the question, the word at the top of the table is used in four different ways, numbered 1 to 4. Choose the option in which the usage of the word is INCORRECT or INAPPROPRIATE.<br>\nBusiness</strong><br>\n&nbsp;</p>\n\n<table border=\"1\" cellpadding=\"1\" style=\"width:500px; border-spacing: 1px;\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>1</td>\n\t\t\t<td>I want to do an MBA before going into business.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>2</td>\n\t\t\t<td>My wife runs profitable business in this suburb.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>3</td>\n\t\t\t<td>If we advertise we will get twice as much business as we have now.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>4</td>\n\t\t\t<td>How you spend your money is as much my business as yours.</td>\n\t\t</tr>\n\t</tbody>\n</table></div><br><br><b>English Language: CAT 2003 | Question: 2</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1944/cat-2003-question-2-20\" target=\"_blank\">https://aptitude.gateoverflow.in/1944/cat-2003-question-2-20</a></p>"
        },
        {
          "id": 16,
          "question": "<p><a name=\"1945\"></a><div itemprop=\"text\"><p><strong>In the question, the word at the top of the table is used in four different ways, numbered 1 to 4. Choose the option in which the usage of the word is INCORRECT or INAPPROPRIATE.<br>\nService</strong></p>\n\n<table border=\"1\" cellpadding=\"1\" style=\"width:500px; border-spacing: 1px;\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>1</td>\n\t\t\t<td>Customers have to service themselves at this canteen.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>2</td>\n\t\t\t<td>It's a service lift; don't get into it.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>3</td>\n\t\t\t<td>I'm not making enough even to service the loan.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>4</td>\n\t\t\t<td>Jyoti's husband has been on active service for three months.</td>\n\t\t</tr>\n\t</tbody>\n</table></div><br><br><b>English Language: CAT 2003 | Question: 2</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1945/cat-2003-question-2-21\" target=\"_blank\">https://aptitude.gateoverflow.in/1945/cat-2003-question-2-21</a></p>"
        },
        {
          "id": 17,
          "question": "<p><a name=\"892\"></a><div itemprop=\"text\"><p>In the question, the word at the top of the table is used in four different ways, numbered \\( 1 \\) to \\( 4. \\) Choose the option in which the usage of the word is INCORRECT or INAPPROPRIATE.</p>\n\n<p><strong>BOLT</strong></p>\n\n<p>\\( \\begin{array} {|c|l|} \\hline 1. &amp; \\text{The shopkeeper showed us a bolt of fine silk} \\\\\\hline 2. &amp; \\text{As he could not move, he made a bolt for the gate} \\\\\\hline&nbsp;&nbsp;3. &amp; \\text{Could you please bolt the door?} \\\\\\hline 4. &amp; \\text{The thief was arrested before he could bolt from the scene of the crime} \\\\\\hline \\end{array} \\)</p></div><br><br><b>English Language: CAT 2004 | Question: 90</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/892/cat-2004-question-90\" target=\"_blank\">https://aptitude.gateoverflow.in/892/cat-2004-question-90</a></p>"
        },
        {
          "id": 18,
          "question": "<p><a name=\"893\"></a><div itemprop=\"text\"><p>In the question, the word at the top of the table is used in four different ways, numbered \\( 1 \\) to \\( 4. \\) Choose the option in which the usage of the word is INCORRECT or INAPPROPRIATE.</p>\n\n<p><strong>PASSING</strong></p>\n\n<p>\\( \\begin{array} {|c|l|} \\hline 1. &amp; \\text{She did not have passing marks in mathematics} \\\\\\hline 2. &amp; \\text{The mad woman was cursing everybody passing her on the road} \\\\\\hline 3. &amp; \\text{At the birthday party all the children enjoyed a game of passing the parcel} \\\\\\hline&nbsp;4. &amp;&nbsp; \\text{A passing taxi was stopped to rush the accident victim to hospital} \\\\\\hline \\end{array} \\)</p></div><br><br><b>English Language: CAT 2004 | Question: 91</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>B</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/893/cat-2004-question-91\" target=\"_blank\">https://aptitude.gateoverflow.in/893/cat-2004-question-91</a></p>"
        },
        {
          "id": 19,
          "question": "<p><a name=\"894\"></a><div itemprop=\"text\"><p>In the question, the word at the top of the table is used in four different ways, numbered \\( 1 \\) to \\( 4. \\) Choose the option in which the usage of the word is INCORRECT or INAPPROPRIATE.</p>\n\n<p><strong>FALLOUT</strong></p>\n\n<p>\\( \\begin{array} {|c|l|} \\hline 1. &amp; \\text{Nagasaki suffered from the fallout of nuclear radiation} \\\\\\hline 2. &amp; \\text{People believed that the political fallout of the scandal would be significant} \\\\\\hline 3. &amp; \\text{Who can predict the environmental fallout of the WTO agreement?} \\\\\\hline 4. &amp; \\text{The headmaster could not understand the fallout of several of his} \\\\&nbsp; &amp; \\text{good students at the public examination}&nbsp;\\\\\\hline \\end{array} \\)</p></div><br><br><b>English Language: CAT 2004 | Question: 92</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/894/cat-2004-question-92\" target=\"_blank\">https://aptitude.gateoverflow.in/894/cat-2004-question-92</a></p>"
        },
        {
          "id": 20,
          "question": "<p><a name=\"787\"></a><div itemprop=\"text\"><p>The following question has a paragraph with one word italicized and underlined word that does not make sense. Choose the most <u>appropriate</u> replacement for that word from the options given below the paragraph.</p>\n\n<p>Intelligent design derive from an early \\( 19 \\)th century explanation of the natural world given by an English clergyman, William Paley. Paley was the populariser of the famous watchmaker analogy. Proponents of intelligent design are <em><u>crupping </u></em>Paley’s argument with a new gloss from molecular biology.</p>\n\n</div><br><br><b>English Language: CAT 2005 | Question: 57</b></p>",
          "type": "numeric",
          "options": [
            "<p>destroying</p>",
            "<p>testing</p>",
            "<p>resurrecting</p>",
            "<p>questioning</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/787/cat-2005-question-57\" target=\"_blank\">https://aptitude.gateoverflow.in/787/cat-2005-question-57</a></p>"
        },
        {
          "id": 21,
          "question": "<p><a name=\"788\"></a><div itemprop=\"text\"><p>The following question has a paragraph with one word italicized and underlined word that does not make sense. Choose the most <u>appropriate</u> replacement for that word from the options given below the paragraph.</p>\n\n<p>Women squat, heads covered, beside huge piles of limp fodder and <em><u>blunk </u></em>oil lamps, and just about all the cows in the three towns converge upon this spot. Sinner, supplicant and yes, even scallywags hand over a few coins for a crack at redemption and a handful of grass.</p>\n\n</div><br><br><b>English Language: CAT 2005 | Question: 58</b></p>",
          "type": "numeric",
          "options": [
            "<p>shining</p>",
            "<p>bright</p>",
            "<p>sputtering</p>",
            "<p>effulgent</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/788/cat-2005-question-58\" target=\"_blank\">https://aptitude.gateoverflow.in/788/cat-2005-question-58</a></p>"
        },
        {
          "id": 22,
          "question": "<p><a name=\"789\"></a><div itemprop=\"text\"><p>The following question has a paragraph with one word italicized and underlined word that does not make sense. Choose the most <u>appropriate</u> replacement for that word from the options given below the paragraph.</p>\n\n<p>It is <em><u>klang </u></em>to a sensitive traveler who walks through this great town, when he sees the streets, the roads, and cabin doors crowded with beggars, mostly women, followed by three, four or six children, all in rags and importuning every passenger for alms.</p>\n\n</div><br><br><b>English Language: CAT 2005 | Question: 59</b></p>",
          "type": "numeric",
          "options": [
            "<p>amusing</p>",
            "<p>irritating</p>",
            "<p>disgusting</p>",
            "<p>distressing</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/789/cat-2005-question-59\" target=\"_blank\">https://aptitude.gateoverflow.in/789/cat-2005-question-59</a></p>"
        },
        {
          "id": 23,
          "question": "<p><a name=\"790\"></a><div itemprop=\"text\"><p>The following question has a paragraph with one word italicized and underlined word that does not make sense. Choose the most <u>appropriate</u> replacement for that word from the options given below the paragraph.</p>\n\n<p>Or there is a most <em><u>fungummy</u></em> diplomatic note on record: when a Philip of Macedon wrote to the Spartans that, if he came within their borders, he would leave not one stone of their city, they wrote back the one word – “if”.</p>\n\n</div><br><br><b>English Language: CAT 2005 | Question: 60</b></p>",
          "type": "numeric",
          "options": [
            "<p>witty</p>",
            "<p>rude</p>",
            "<p>simple</p>",
            "<p>terse</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/790/cat-2005-question-60\" target=\"_blank\">https://aptitude.gateoverflow.in/790/cat-2005-question-60</a></p>"
        },
        {
          "id": 24,
          "question": "<p><a name=\"551\"></a><div itemprop=\"text\"><p>In the below question, a word has been used in sentences in five different ways. Choose the option corresponding to the sentence in which the usage of word is <strong>incorrect or inappropriate.</strong></p>\n\n<p><strong>Run</strong></p>\n\n</div><br><br><b>English Language: CAT 2008 | Question: 55</b></p>",
          "type": "numeric",
          "options": [
            "<p><strong>​</strong>I must run fast to catch up with him.</p>",
            "<p>Our team scored a goal against the run of play.</p>",
            "<p>You can’t run over him like that.</p>",
            "<p>The newly released book is enjoying a popular run.</p>",
            "<p>This film is a run-of-the-mill production.</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/551/cat-2008-question-55\" target=\"_blank\">https://aptitude.gateoverflow.in/551/cat-2008-question-55</a></p>"
        },
        {
          "id": 25,
          "question": "<p><a name=\"1711\"></a><div itemprop=\"text\"><p>In the below question, a word has been used in sentences in five different ways. Choose the option corresponding to the sentence in which the usage of word is&nbsp;<strong>incorrect or inappropriate.</strong></p>\n\n<p><strong>Round</strong></p>\n\n</div><br><br><b>English Language: CAT 2008 | Question: 56</b></p>",
          "type": "numeric",
          "options": [
            "<p>The police fired a round of tear gas shells.</p>",
            "<p>The shop is located round the corner</p>",
            "<p>We took a ride on the merry-go-round.</p>",
            "<p>The doctor is on a hospital round.</p>",
            "<p>I shall proceed further only after you come round to admitting it.</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1711/cat-2008-question-56\" target=\"_blank\">https://aptitude.gateoverflow.in/1711/cat-2008-question-56</a></p>"
        },
        {
          "id": 26,
          "question": "<p><a name=\"1712\"></a><div itemprop=\"text\"><p>In the below question, a word has been used in sentences in five different ways. Choose the option corresponding to the sentence in which the usage of word is&nbsp;<strong>incorrect or inappropriate.</strong></p>\n\n<p><strong>Buckle</strong></p>\n\n</div><br><br><b>English Language: CAT 2008 | Question: 57</b></p>",
          "type": "numeric",
          "options": [
            "<p><strong>​</strong>After the long hike our knees were beginning to buckle.</p>",
            "<p>The horse suddenly broke into a buckle.</p>",
            "<p>The accused did not buckle under police interrogation.</p>",
            "<p>Sometimes, an earthquake can make a bridge buckle.</p>",
            "<p>People should learn to buckle up as soon as they get into a car.</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1712/cat-2008-question-57\" target=\"_blank\">https://aptitude.gateoverflow.in/1712/cat-2008-question-57</a></p>"
        },
        {
          "id": 27,
          "question": "<p><a name=\"1713\"></a><div itemprop=\"text\"><p>In the below question, a word has been used in sentences in five different ways. Choose the option corresponding to the sentence in which the usage of word is&nbsp;<strong>incorrect or inappropriate.</strong></p>\n\n<p><strong>File</strong></p>\n\n</div><br><br><b>English Language: CAT 2008 | Question: 58</b></p>",
          "type": "numeric",
          "options": [
            "<p><strong>​</strong>You will find the paper in the file under C.</p>",
            "<p>I need to file an insurance claim.</p>",
            "<p>The cadets were marching in a single file.</p>",
            "<p>File your nails before you apply nail polish.</p>",
            "<p>When the parade was on, a soldier broke the file.</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/1713/cat-2008-question-58\" target=\"_blank\">https://aptitude.gateoverflow.in/1713/cat-2008-question-58</a></p>"
        },
        {
          "id": 28,
          "question": "<p><a name=\"840\"></a><div itemprop=\"text\"><p>In each question, the word at the top is used in four different ways, numbered (a) to (d). Choose the option in which the usage of the word is Incorrect or Inappropriate.</p>\n\n<p>SORT</p>\n\n<ol style=\"list-style-type:lower-alpha\">\n\t<li>Let's sort these boys into four groups.</li>\n\t<li>They serve tea of a sort on these trains.</li>\n\t<li>Farmers of all sort attended the rally.</li>\n\t<li>What sort of cheese do you use in pizza?</li>\n</ol>\n\n<p>&nbsp;</p></div><br><br><b>English Language: CAT 2009 | Question: 56</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/840/cat-2009-question-56\" target=\"_blank\">https://aptitude.gateoverflow.in/840/cat-2009-question-56</a></p>"
        },
        {
          "id": 29,
          "question": "<p><a name=\"841\"></a><div itemprop=\"text\"><p>In each question, the word at the top is used in four different ways, numbered (a) to (d). Choose the option in which the usage of the word is Incorrect or Inappropriate.</p>\n\n<p>HOST</p>\n\n<ol style=\"list-style-type:lower-alpha\">\n\t<li>A virus has infected the host computer.</li>\n\t<li>Ranchi will play the host to the next national film festival.</li>\n\t<li>Kerala's forests are host to a range of snakes.</li>\n\t<li>If you host the party, who will foot the bill.</li>\n</ol></div><br><br><b>English Language: CAT 2009 | Question: 57</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/841/cat-2009-question-57\" target=\"_blank\">https://aptitude.gateoverflow.in/841/cat-2009-question-57</a></p>"
        },
        {
          "id": 30,
          "question": "<p><a name=\"5012\"></a><div itemprop=\"text\"><p>The colour black is an example of</p>\n\n</div><br><br><b>English Language: CAT 2010 | Question: 22</b></p>",
          "type": "numeric",
          "options": [
            "<p>A surface colour</p>",
            "<p>An achromatic colour</p>",
            "<p>An organic colour</p>",
            "<p>A diffuse colour</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5012/cat-2010-question-22\" target=\"_blank\">https://aptitude.gateoverflow.in/5012/cat-2010-question-22</a></p>"
        },
        {
          "id": 31,
          "question": "<p><a name=\"5011\"></a><div itemprop=\"text\"><p>Paint is an example of a substance containing</p>\n\n</div><br><br><b>English Language: CAT 2010 | Question: 23</b></p>",
          "type": "numeric",
          "options": [
            "<p>Inorganic material</p>",
            "<p>Body colours</p>",
            "<p>Surface colours</p>",
            "<p>Metallic colours</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5011/cat-2010-question-23\" target=\"_blank\">https://aptitude.gateoverflow.in/5011/cat-2010-question-23</a></p>"
        },
        {
          "id": 32,
          "question": "<p><a name=\"5009\"></a><div itemprop=\"text\"><p>As per Mayo’s perspective, which of the following best defines the phrase “scientific explanation”?</p>\n\n</div><br><br><b>English Language: CAT 2010 | Question: 25</b></p>",
          "type": "numeric",
          "options": [
            "<p>One which is most detailed in its explanation of natural phenomena.</p>",
            "<p>One which survives examination better than other explanations.</p>",
            "<p>One which has been thoroughly tested by scientific experts.</p>",
            "<p>One which refutes other explanations convincingly,</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5009/cat-2010-question-25\" target=\"_blank\">https://aptitude.gateoverflow.in/5009/cat-2010-question-25</a></p>"
        },
        {
          "id": 33,
          "question": "<p><a name=\"5008\"></a><div itemprop=\"text\"><p>The author’s&nbsp; use of Snell’s law of refraction to illustrate Mayo’s perspective can best said to be</p>\n\n</div><br><br><b>English Language: CAT 2010 | Question: 26</b></p>",
          "type": "numeric",
          "options": [
            "<p>Contrived</p>",
            "<p>Premediated</p>",
            "<p>Superfluous</p>",
            "<p>Illustrative</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5008/cat-2010-question-26\" target=\"_blank\">https://aptitude.gateoverflow.in/5008/cat-2010-question-26</a></p>"
        },
        {
          "id": 34,
          "question": "<p><a name=\"5007\"></a><div itemprop=\"text\"><p>Biotic disturbances in the context means</p>\n\n</div><br><br><b>English Language: CAT 2010 | Question: 27</b></p>",
          "type": "numeric",
          "options": [
            "<p>Attacks from other living things, animals, etc.</p>",
            "<p>The disturbances caused by the natives on&nbsp;seeing the strange foreigners.</p>",
            "<p>The political disturbances causing the closedown of the parks.</p>",
            "<p>Disturbances caused by the wild animals on seeing the tourists.</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5007/cat-2010-question-27\" target=\"_blank\">https://aptitude.gateoverflow.in/5007/cat-2010-question-27</a></p>"
        },
        {
          "id": 35,
          "question": "<p><a name=\"5006\"></a><div itemprop=\"text\"><p>By using the expression “environmentally destructive tourism” the author means</p>\n\n</div><br><br><b>English Language: CAT 2010 | Question: 28</b></p>",
          "type": "numeric",
          "options": [
            "<p>The preservation of the wild beasts.</p>",
            "<p>Destruction of the wildlife and sancturies.</p>",
            "<p>Destroying the attractive sources of wild animals and birds.</p>",
            "<p>The maintenance of the flora and fauna of the country</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5006/cat-2010-question-28\" target=\"_blank\">https://aptitude.gateoverflow.in/5006/cat-2010-question-28</a></p>"
        },
        {
          "id": 36,
          "question": "<p><a name=\"5005\"></a><div itemprop=\"text\"><p>To implement the most scientific ways of tourism, we should</p>\n\n</div><br><br><b>English Language: CAT 2010 | Question: 29</b></p>",
          "type": "numeric",
          "options": [
            "<p>Get industries and talented persons trained in the field.</p>",
            "<p>From a commission and a plan out how to implement the suggestions.</p>",
            "<p>Send a group of scientists abroad to learn more about tourism.</p>",
            "<p>Speed as much finance as possible to better the suggestions made.</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5005/cat-2010-question-29\" target=\"_blank\">https://aptitude.gateoverflow.in/5005/cat-2010-question-29</a></p>"
        },
        {
          "id": 37,
          "question": "<p><a name=\"4995\"></a><div itemprop=\"text\"><ol start=\"1\" style=\"list-style-type:upper-roman\">\n\t<li>Indict to</li>\n\t<li>Intrigue on</li>\n\t<li>Endow with</li>\n\t<li>Trample on</li>\n</ol>\n\n<p>&nbsp;</p>\n\n</div><br><br><b>English Language: CAT 2010 | Question: 39</b></p>",
          "type": "numeric",
          "options": [
            "<p>I and IV</p>",
            "<p>I and III</p>",
            "<p>I, III and IV</p>",
            "<p>None of the above</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/4995/cat-2010-question-39\" target=\"_blank\">https://aptitude.gateoverflow.in/4995/cat-2010-question-39</a></p>"
        },
        {
          "id": 38,
          "question": "<p><a name=\"4994\"></a><div itemprop=\"text\"><ol start=\"1\" style=\"list-style-type:upper-roman\">\n\t<li>Trace to</li>\n\t<li>Sparing of</li>\n\t<li>Replete with</li>\n\t<li>wonder at</li>\n</ol>\n\n<p>&nbsp;</p>\n\n</div><br><br><b>English Language: CAT 2010 | Question: 40</b></p>",
          "type": "numeric",
          "options": [
            "<p>I and III</p>",
            "<p>I, II and III</p>",
            "<p>II, III and IV</p>",
            "<p>None of the above</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/4994/cat-2010-question-40\" target=\"_blank\">https://aptitude.gateoverflow.in/4994/cat-2010-question-40</a></p>"
        },
        {
          "id": 39,
          "question": "<p><a name=\"5091\"></a><div itemprop=\"text\"><p><strong>Find the incorrect usage of the word in the following questions:</strong></p>\n\n<p><strong>SLAM</strong></p>\n\n</div><br><br><b>English Language: CAT 2012 | Question: 36</b></p>",
          "type": "numeric",
          "options": [
            "<p>I heard the door slam behind him</p>",
            "<p>She slammed down the phone angrily</p>",
            "<p>She slammed his face hard</p>",
            "<p>The ear skidded and slammed into a tree</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5091/cat-2012-question-36\" target=\"_blank\">https://aptitude.gateoverflow.in/5091/cat-2012-question-36</a></p>"
        },
        {
          "id": 40,
          "question": "<p><a name=\"5092\"></a><div itemprop=\"text\"><p><strong>Find the incorrect usage of the word in the following questions:</strong></p>\n\n<p><strong>STOP</strong></p>\n\n</div><br><br><b>English Language: CAT 2012 | Question: 37</b></p>",
          "type": "numeric",
          "options": [
            "<p>The car stopped at the traffic light</p>",
            "<p>Shantaram immediately stopped what he was doing</p>",
            "<p>We need more laws to stop pollution</p>",
            "<p>He is stopped by law from holding a licence</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5092/cat-2012-question-37\" target=\"_blank\">https://aptitude.gateoverflow.in/5092/cat-2012-question-37</a></p>"
        },
        {
          "id": 41,
          "question": "<p><a name=\"5093\"></a><div itemprop=\"text\"><p><strong>Find the incorrect usage of the word in the following questions</strong></p>\n\n<p><strong>TIME</strong></p>\n\n</div><br><br><b>English Language: CAT 2012 | Question: 38</b></p>",
          "type": "numeric",
          "options": [
            "<p>I can remember very few times when we had to cancel due to ill health</p>",
            "<p>This is the first time that I have been to London</p>",
            "<p>The train arrived right on time</p>",
            "<p>The changing seasons mark the passing of time</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5093/cat-2012-question-38\" target=\"_blank\">https://aptitude.gateoverflow.in/5093/cat-2012-question-38</a></p>"
        },
        {
          "id": 42,
          "question": "<p><a name=\"5094\"></a><div itemprop=\"text\"><p><strong>Find the incorrect usage of the word in the following questions</strong></p>\n\n<p><strong>SOMBRE</strong></p>\n\n</div><br><br><b>English Language: CAT 2012 | Question: 39</b></p>",
          "type": "numeric",
          "options": [
            "<p>He was dressed in sombre shades of grey and black</p>",
            "<p>Paul was in a sombre mood</p>",
            "<p>The year ended on a sombre note</p>",
            "<p>He is in the sombre position of not having to worry about money</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5094/cat-2012-question-39\" target=\"_blank\">https://aptitude.gateoverflow.in/5094/cat-2012-question-39</a></p>"
        },
        {
          "id": 43,
          "question": "<p><a name=\"5095\"></a><div itemprop=\"text\"><p><strong>Find the incorrect usage of the word in the following questions:</strong></p>\n\n<p><strong>CALL</strong></p>\n\n</div><br><br><b>English Language: CAT 2012 | Question: 40</b></p>",
          "type": "numeric",
          "options": [
            "<p>She payed him a call from the pay phone near her home</p>",
            "<p>I will call on you tomorrow evening at \\( 7 \\) pm</p>",
            "<p>Vikram decided to call a meeting to discuss the trade fair</p>",
            "<p>She felt the call of religion early in her life</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5095/cat-2012-question-40\" target=\"_blank\">https://aptitude.gateoverflow.in/5095/cat-2012-question-40</a></p>"
        },
        {
          "id": 44,
          "question": "<p><a name=\"5301\"></a><div itemprop=\"text\"><p>The word in capitals is used in four different ways. Choose the option in which the usage of the word is INCORRECT or INAPPROPRIATE.</p>\n\n<p>MELT</p>\n\n</div><br><br><b>English Language: CAT 2013 | Question: 41</b></p>",
          "type": "numeric",
          "options": [
            "<p>The crowd melted away after the prayer meeting.</p>",
            "<p>Even the sternest mother's heart melts at the sight of her baby crying.</p>",
            "<p>His anxiety melted away when he received an SMS from his daughter confirming that&nbsp;she had reached her destination safely.</p>",
            "<p>The cries of opposition suddenly melted to cheers when the principal agreed to the&nbsp;demands of the students.</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5301/cat-2013-question-41\" target=\"_blank\">https://aptitude.gateoverflow.in/5301/cat-2013-question-41</a></p>"
        },
        {
          "id": 45,
          "question": "<p><a name=\"5292\"></a><div itemprop=\"text\"><p><strong>PULL –&nbsp;</strong>The word at the top is used in four different ways, numbered A to D. Choose the option in which the usage of the word is INCORRECT or INAPPROPRIATE.</p>\n\n</div><br><br><b>English Language: CAT 2013 | Question: 50</b></p>",
          "type": "numeric",
          "options": [
            "<p>Pull aside the curtains and let in some fresh air.</p>",
            "<p>I decided to pull away from the venture due to differences of opinion with my&nbsp;partners.</p>",
            "<p>Being a charismatic leader that he is, he can certainly pull the crowds.</p>",
            "<p>The municipal corporation has decided to pull down all illegal constructions in the city.</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/5292/cat-2013-question-50\" target=\"_blank\">https://aptitude.gateoverflow.in/5292/cat-2013-question-50</a></p>"
        },
        {
          "id": 46,
          "question": "<p><a name=\"943\"></a><div itemprop=\"text\"><p>In each of the following questions, a part of a sentence is left blank. Choose from among the four options given below each question, the one which would best fill the blanks. When we call others dogmatic, what we really object to is______.</p>\n\n<ol style=\"list-style-type:lower-alpha\">\n\t<li>Their giving the dog a bad name&nbsp;</li>\n\t<li>Their holding beliefs that are different from our own&nbsp;</li>\n\t<li>The extremism that goes along with it&nbsp;</li>\n\t<li>The subversion of whatever they actually believe in concomitantly</li>\n</ol></div><br><br><b>English Language: CAT 2014 | Question: 14</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/943/cat-2014-question-14\" target=\"_blank\">https://aptitude.gateoverflow.in/943/cat-2014-question-14</a></p>"
        },
        {
          "id": 47,
          "question": "<p><a name=\"4292\"></a><div itemprop=\"text\"><p>Choose the word or phrase that is <strong>most nearly opposite</strong> in meaning to the word in capital letters.</p>\n\n<p>Since some questions require you to distinguish fine shades of meaning, be sure before deciding which one is best.</p>\n\n<p>INTEGRAL : ____________.</p>\n\n<ol>\n\t<li>liminal</li>\n\t<li>peripheral</li>\n\t<li>crucial</li>\n\t<li>impartial</li>\n\t<li>constituent</li>\n</ol>\n\n<p>ABET : ____________.</p>\n\n<ol>\n\t<li>mollify</li>\n\t<li>uncover</li>\n\t<li>encourage</li>\n\t<li>frustrate</li>\n\t<li>capture</li>\n</ol>\n\n<p>&nbsp;</p>\n\n<ol>\n</ol></div><br><br><b>English Language: Choose the lettered word or phrase that is most nearly opposite in meaning</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/4292/choose-lettered-word-phrase-that-most-nearly-opposite-meaning\" target=\"_blank\">https://aptitude.gateoverflow.in/4292/choose-lettered-word-phrase-that-most-nearly-opposite-meaning</a></p>"
        },
        {
          "id": 48,
          "question": "<p><a name=\"383\"></a><div itemprop=\"text\"><p>Each questions below consist of a word printed in capital letters, followed by five lettered word or phrases. Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</p><p>Since some of the questions require you to distinguish fine shades of meaning, be sure to consider all the choices before deciding which one is best.</p><p>ADULTERATION : ______________.</p><ol><li>Consternation</li><li>Purification</li><li>Normalization</li><li>Approximation</li><li>Rejuvenation</li></ol></div><br><br><b>English Language: Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>B</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/383/choose-lettered-phrase-nearly-opposite-meaning-capital-letters\" target=\"_blank\">https://aptitude.gateoverflow.in/383/choose-lettered-phrase-nearly-opposite-meaning-capital-letters</a></p>"
        },
        {
          "id": 49,
          "question": "<p><a name=\"381\"></a><div itemprop=\"text\"><p>Each questions below consist of word printed in capital letters, followed by five lettered word or phrases. Choose the word or phrase that is most nearly opposite in meaning to the word in capital letters.</p><p>Since some questions require you to distinguish fine shades of meaning, be sure before deciding which one is best.</p><p>BOYCOTT : ____________.</p><ol><li>Extort</li><li>Underwrite</li><li>Underbid</li><li>Stipulate</li><li>Patronize.</li></ol></div><br><br><b>English Language: Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/381/choose-lettered-phrase-nearly-opposite-meaning-capital-letters\" target=\"_blank\">https://aptitude.gateoverflow.in/381/choose-lettered-phrase-nearly-opposite-meaning-capital-letters</a></p>"
        },
        {
          "id": 50,
          "question": "<p><a name=\"402\"></a><div itemprop=\"text\"><p>Each question below consist of word in printed capital letters, followed by five lettered word or phrases. Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</p><p>Since some of the questions require you to distinguish fine shades of meaning, be sure to consider all the choices before deciding which one is best.</p><p>VENERATION : ____________.</p><ol><li>Derision</li><li>Blame</li><li>Avoidance</li><li>Ostracism</li><li>Defiance.</li></ol></div><br><br><b>English Language: Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>A</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/402/choose-lettered-phrase-nearly-opposite-meaning-capital-letters\" target=\"_blank\">https://aptitude.gateoverflow.in/402/choose-lettered-phrase-nearly-opposite-meaning-capital-letters</a></p>"
        },
        {
          "id": 51,
          "question": "<p><a name=\"378\"></a><div itemprop=\"text\"><p>Each question below consist of word printed in capital letters, followed by five lettered word or phrase. Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</p><p>Since some of the questions require you to distinguish fine shades of meaning, be sure to consider all choices before deciding which one is best.</p><p>DIVULGE : _______________.</p><ol><li>Keep secret</li><li>Evaluate by one self</li><li>Refine</li><li>Restore</li><li>Copy</li></ol></div><br><br><b>English Language: Choose the lettered word or phrase that is most nearly opposite in meaning.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>A</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/378/choose-lettered-word-phrase-that-most-nearly-opposite-meaning\" target=\"_blank\">https://aptitude.gateoverflow.in/378/choose-lettered-word-phrase-that-most-nearly-opposite-meaning</a></p>"
        },
        {
          "id": 52,
          "question": "<p><a name=\"388\"></a><div itemprop=\"text\"><p>Each question below consists of a word printed in capital letters, followed by five lettered words or phrases. Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</p><p>Since some of the questions require you to distinguish fine shades of meaning, be sure to consider all the choices before deciding which one is best.</p><p>DEPOSITION : ______________.</p><ol><li>Process of congealing</li><li>Process of distilling</li><li>Process of eroding</li><li>Process of evolving</li><li>Process of condensing.</li></ol></div><br><br><b>English Language: Choose the the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "E",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/388/choose-lettered-phrase-nearly-opposite-meaning-capital-letters\" target=\"_blank\">https://aptitude.gateoverflow.in/388/choose-lettered-phrase-nearly-opposite-meaning-capital-letters</a></p>"
        },
        {
          "id": 53,
          "question": "<p><a name=\"391\"></a><div itemprop=\"text\"><p>Each questions below consists of a word printed in capital letters, followed by five lettered words or phrases. Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</p><p>Since some questions require you to distinguish fine shades of meaning, be sure to consider all the choices before deciding which one is best.</p><p>LOQUACIOUS :______________.</p><ol><li>Tranquil</li><li>Skeptical</li><li>Morose</li><li>Taciturn</li><li>Witty.</li></ol></div><br><br><b>English Language: Each questions below consist of a word or phrase printed in capital letters.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>D</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/391/each-questions-below-consist-phrase-printed-capital-letters\" target=\"_blank\">https://aptitude.gateoverflow.in/391/each-questions-below-consist-phrase-printed-capital-letters</a></p>"
        },
        {
          "id": 54,
          "question": "<p><a name=\"397\"></a><div itemprop=\"text\"><p>Each questions below consists of a word printed in capital letters, followed by five lettered words or phrases. Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</p><p>Since some of the questions require you to distinguish fine shades of meaning, be sure to consider all the choices before deciding which one is best.</p><p>REPINE : ____________.</p><ol><li>Intensify</li><li>Excuse</li><li>Express joy</li><li>Feel sure</li><li>Rush forward.</li></ol></div><br><br><b>English Language: Each questions below consist of a word or phrase printed in capital letters.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>C</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/397/each-questions-below-consist-phrase-printed-capital-letters\" target=\"_blank\">https://aptitude.gateoverflow.in/397/each-questions-below-consist-phrase-printed-capital-letters</a></p>"
        },
        {
          "id": 55,
          "question": "<p><a name=\"390\"></a><div itemprop=\"text\"><p>Each questions below consist of a word printed in capital letters, followed by five letter or phrase. Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</p><p>Since some of the questions require you to distinguish fine shades of meaning, be sure to consider all the choices before deciding which one is best.</p><p>ENERVATE : ____________.</p><ol><li>Recuperate</li><li>Resurrect</li><li>Renovate</li><li>Gather</li><li>strengthen.</li></ol></div><br><br><b>English Language: Each questions below consist of a word or phrase printed in capital letters.</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "E",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/390/each-questions-below-consist-phrase-printed-capital-letters\" target=\"_blank\">https://aptitude.gateoverflow.in/390/each-questions-below-consist-phrase-printed-capital-letters</a></p>"
        },
        {
          "id": 56,
          "question": "<p><a name=\"376\"></a><div itemprop=\"text\"><p>Each questions below consist of a word printed in capital letters, followed by five lettered words or phrases. Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</p><p>Since some of the questions require you to distinguish fine shades of meaning, be sure to consider all the choices before deciding which one is best.</p><p>FALLACY : _____________</p><ol><li>Personal philosophy</li><li>Imaginative idea</li><li>Unconfirmed theory</li><li>Tentative opinion</li><li>Valid argument.</li></ol></div><br><br><b>English Language: Each questions below consist of a word printed in a capital letters, followed by five lettered words or phrases.</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "E",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/376/questions-consist-printed-letters-followed-lettered-phrases\" target=\"_blank\">https://aptitude.gateoverflow.in/376/questions-consist-printed-letters-followed-lettered-phrases</a></p>"
        },
        {
          "id": 57,
          "question": "<p><a name=\"403\"></a><div itemprop=\"text\"><p>Each question below consist of a word printed in capital letters, followed by five lettered word or phrases. Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</p><p>Since some of the questions require you to distinguish fine shades of meaning, be sure to consider all the choices before deciding which one is best.</p><p>INVETERATE : _____________.</p><ol><li>Casual</li><li>Public</li><li>Satisfactory</li><li>Trustworthy</li><li>Sophisticated.</li></ol></div><br><br><b>English Language: Each questions below consist of a word printed in capital letters followed by five letters word or phrases.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>A</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/403/questions-printed-capital-letters-followed-letters-phrases\" target=\"_blank\">https://aptitude.gateoverflow.in/403/questions-printed-capital-letters-followed-letters-phrases</a></p>"
        },
        {
          "id": 58,
          "question": "<p><a name=\"404\"></a><div itemprop=\"text\"><p>Each question below consist of a word printed in capital letters, followed by five lettered word or phrases. Choose the lettered word or phrase that is most nearly opposite in meaning to the word in capital letters.</p><p>Since some of the questions require you to distinguish fine shades of meaning, be sure to consider all the choices before &nbsp;deciding which one is best.</p><p>UNDERMINE : ____________.</p><ol><li>Submerge</li><li>Supersede</li><li>Overhaul</li><li>Under grid</li><li>Intersperse.</li></ol></div><br><br><b>English Language: Each questions below consist of a word printed in capital letters followed by five letters word or phrases.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>C</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/404/questions-printed-capital-letters-followed-letters-phrases\" target=\"_blank\">https://aptitude.gateoverflow.in/404/questions-printed-capital-letters-followed-letters-phrases</a></p>"
        },
        {
          "id": 59,
          "question": "<p><a name=\"41\"></a><div itemprop=\"text\"><p>I. When you play your radio at high _______, it disturbs others.<br>II. We have just received a latest ______ of this encyclopedia.</p><p>&nbsp;</p><ol><li>edition</li><li>volume</li><li>channel</li><li>frequency</li><li>pitch</li></ol><p>&nbsp;</p></div><br><br><b>English Language: English Language</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>B</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/41/english-language-fill-in-the-blanks-with-appropriate-word\" target=\"_blank\">https://aptitude.gateoverflow.in/41/english-language-fill-in-the-blanks-with-appropriate-word</a></p>"
        },
        {
          "id": 60,
          "question": "<p><a name=\"369\"></a><div itemprop=\"text\"><p>In each of the following questions, a related pair of words or phrases is followed by five lettered pairs of words or phrases. Select the lettered pair that best expresses a relationship similar to that expressed in the original pair.</p>\n\n<p>STYGIAN : DARK</p>\n\n<ol>\n\t<li>Abysmal, low</li>\n\t<li>Cogent, contentious</li>\n\t<li>Fortuitous, accidental</li>\n\t<li>Reckless, threatening</li>\n\t<li>Cataclysmic, doomed.</li>\n</ol></div><br><br><b>English Language: In each of the following question,  a related pair of words or phrases is followed by five lettered word.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>C</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/369/following-question-related-words-phrases-followed-lettered\" target=\"_blank\">https://aptitude.gateoverflow.in/369/following-question-related-words-phrases-followed-lettered</a></p>"
        },
        {
          "id": 61,
          "question": "<p><a name=\"370\"></a><div itemprop=\"text\"><p>In each of the following questions, a related pairs of words or phrases is followed by five lettered pairs of words or phrases. Select the lettered pair that best expresses a relationship similar to that expresses in the original pair.</p><p>WORSHIP : SACRIFICE</p><ol><li>Generation, pyre</li><li>Burial, mortuary</li><li>Weapon, centurion</li><li>Massacre, invasion</li><li>Prediction, augury.</li></ol></div><br><br><b>English Language: In each of the following question,  a related pair of words or phrases is followed by five lettered word.</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "E",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/370/following-question-related-words-phrases-followed-lettered\" target=\"_blank\">https://aptitude.gateoverflow.in/370/following-question-related-words-phrases-followed-lettered</a></p>"
        },
        {
          "id": 62,
          "question": "<p><a name=\"371\"></a><div itemprop=\"text\"><p>In each of the following questions, a related pair of words or phrases is followed by five lettered pairs of words or phrases. Select the lettered pair that best expresses a relationship similar to that expressed in the original pair.</p><p>EVANESCENT : DISAPPEAR</p><ol><li>Transparent, penetrate</li><li>Onerous, struggle</li><li>Feckless, succeed</li><li>Illusory, exceed</li><li>Pliant, yield.&nbsp;</li></ol></div><br><br><b>English Language: In each of the following question,  a related pair of words or phrases is followed by five lettered word.</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/371/following-question-related-words-phrases-followed-lettered\" target=\"_blank\">https://aptitude.gateoverflow.in/371/following-question-related-words-phrases-followed-lettered</a></p>"
        },
        {
          "id": 63,
          "question": "<p><a name=\"362\"></a><div itemprop=\"text\"><p>In each of the following questions, a related pair of words or phrases is followed by five lettered pairs of words or phrases. Select the lettered pair that best express a relationship similar to that expressed in the original pair.</p>\n\n<p>SEDATIVE : DROWSINESS</p>\n\n<ol>\n\t<li>Epidemic, contagiousness</li>\n\t<li>Vaccine, virus</li>\n\t<li>Laxative, drug</li>\n\t<li>Anesthetic, numbness</li>\n\t<li>Therapy, psychosis.</li>\n</ol></div><br><br><b>English Language: In each of the following questions, a related pair of words or phrases is followed by five letter word.</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/362/following-questions-related-words-phrases-followed-letter\" target=\"_blank\">https://aptitude.gateoverflow.in/362/following-questions-related-words-phrases-followed-letter</a></p>"
        },
        {
          "id": 64,
          "question": "<p><a name=\"363\"></a><div itemprop=\"text\"><p>In each of the following questions,a related pair of words or phrases is followed by five lettered pair of words or phrases. Select the lettered pair that best expresses a relationship similar to that expressed in the original pair.</p><p>LAWYER : COURTROOM</p><ol><li>Participant, team</li><li>Commuter, train</li><li>Gladiator, arena</li><li>Senator, caucus</li><li>Patient, ward</li></ol></div><br><br><b>English Language: In each of the following questions, a related pair of words or phrases is followed by five letter word.</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/363/following-questions-related-words-phrases-followed-letter\" target=\"_blank\">https://aptitude.gateoverflow.in/363/following-questions-related-words-phrases-followed-letter</a></p>"
        },
        {
          "id": 65,
          "question": "<p><a name=\"365\"></a><div itemprop=\"text\"><p>In each of the following questions, a related pair of words or phrases is followed by five lettered pairs of words or phrases. Select the lettered pair that best expresses a relationship similar to that expressed in the original pair.</p>\n\n<p>FRUGAL : MISERLY</p>\n\n<ol>\n\t<li>Confident, arrogant</li>\n\t<li>Courageous, pugnacious</li>\n\t<li>Famous, aggressive</li>\n\t<li>Rash, foolhardy</li>\n\t<li>Quiet, timid.</li>\n</ol></div><br><br><b>English Language: In each of the following questions, a related pair of words or phrases is followed by five letter word.</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/365/following-questions-related-words-phrases-followed-letter\" target=\"_blank\">https://aptitude.gateoverflow.in/365/following-questions-related-words-phrases-followed-letter</a></p>"
        },
        {
          "id": 66,
          "question": "<p><a name=\"364\"></a><div itemprop=\"text\"><p>In each of the following questions, a related pair of words or phrases is followed by five letter pair of words or phrases. Select the letter paired that best expresses a relationship similar to that expressed in the original pair.</p><p>CURIOSITY :KNOW</p><ol><li>Temptation, conquer</li><li>Starvation, eat</li><li>Wanderlust, travel</li><li>Humor, laugh</li><li>Survival, live</li></ol></div><br><br><b>English Language: In each of the following questions, a related pair of words or phrases is followed by five letter word.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>C</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/364/following-questions-related-words-phrases-followed-letter\" target=\"_blank\">https://aptitude.gateoverflow.in/364/following-questions-related-words-phrases-followed-letter</a></p>"
        },
        {
          "id": 67,
          "question": "<p><a name=\"375\"></a><div itemprop=\"text\"><p>In each of the following questions, a related pair of words or phrases is followed by five lettered pairs of words or phrases. Select the lettered pair that best expresses a relationship similar to that expressed in the original pair.</p><p>UPBRAID : REPROACH</p><ol><li>Dote, like</li><li>Lag, stray</li><li>Vex, please</li><li>Earn, desire</li><li>Recast, explain.</li></ol></div><br><br><b>English Language: In each of the following questions, a related pair of words or phrases is followed by five lettered pairs</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>A</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/375/following-questions-related-phrases-followed-lettered-pairs\" target=\"_blank\">https://aptitude.gateoverflow.in/375/following-questions-related-phrases-followed-lettered-pairs</a></p>"
        },
        {
          "id": 68,
          "question": "<p><a name=\"368\"></a><div itemprop=\"text\"><p>In each of the following questions, a related pair of words or phrases is followed by five lettered pairs of words or phrases. Select the lettered pair that best expresses a relationship similar to that expressed in the original pair.</p>\n\n<p>ANTIDOTE : POISON</p>\n\n<ol>\n\t<li>Cure, recovery</li>\n\t<li>Narcotic, sleep</li>\n\t<li>Stimulant, relapse</li>\n\t<li>Tonic, lethargy</li>\n\t<li>Resuscitation, breathing.</li>\n</ol></div><br><br><b>English Language: In each of the following questions, a related pair of words or phrases is followed by five lettered pairs.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>D</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/368/following-questions-related-phrases-followed-lettered-pairs\" target=\"_blank\">https://aptitude.gateoverflow.in/368/following-questions-related-phrases-followed-lettered-pairs</a></p>"
        },
        {
          "id": 69,
          "question": "<p><a name=\"253\"></a><div itemprop=\"text\"><p>In each of the questions below, a word with its usage is given. Select as your answers, the word that is INAPPROPRIATE as a replacement to the question word in the sentence.</p><p>UNCONSCIONABLE: The unconscionable delay on the part of the government in offering relief measures to the flood victims drew flask from the opposition</p><ol><li>inexplicable&nbsp;</li><li>inordinate</li><li>unwarranted&nbsp;</li><li>undue</li></ol><p>DEMUR: The government acceded to the demands of the opposition party without demur</p><ol><li>protestation</li><li>qualms</li><li>rebuff</li><li>objection</li></ol></div><br><br><b>English Language: In each of the questions below, a word with its usage is given.</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/253/in-each-of-the-questions-below-a-word-with-its-usage-is-given\" target=\"_blank\">https://aptitude.gateoverflow.in/253/in-each-of-the-questions-below-a-word-with-its-usage-is-given</a></p>"
        },
        {
          "id": 70,
          "question": "<p><a name=\"357\"></a><div itemprop=\"text\"><p>Choose the word or set of words for each blank that best fits the meaning of the sentence as whole.</p>\n\n<p>It was her view that the country's problem had been&nbsp;___________ &nbsp; by foreign technocrats, so that to invite them to come back would be counterproductive.</p>\n\n<ol>\n\t<li>Foreseen</li>\n\t<li>Attacked</li>\n\t<li>Ascertained</li>\n\t<li>Exacerbated</li>\n\t<li>Analyzed.</li>\n</ol></div><br><br><b>English Language: It was her view that the country's problems had been_____ by foreign technocrats.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>D</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/357/view-that-countrys-problems-been_____-foreign-technocrats\" target=\"_blank\">https://aptitude.gateoverflow.in/357/view-that-countrys-problems-been_____-foreign-technocrats</a></p>"
        },
        {
          "id": 71,
          "question": "<p><a name=\"6429\"></a><div itemprop=\"text\"><p>In the following question, out of the four alternatives, choose the one which best expresses the meaning of the given word.</p>\n\n<p>&nbsp;Camouflage</p>\n\n</div><br><br><b>English Language: NIELIT 2016 DEC Scientist B</b></p>",
          "type": "single",
          "options": [
            "<p>Disguise</p>",
            "<p>Cover</p>",
            "<p>Demonstrate</p>",
            "<p>Fabric</p>"
          ],
          "correct_answer": "<p>Disguise</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6429/nielit-2016-dec-scientist-b-section-a-3\" target=\"_blank\">https://aptitude.gateoverflow.in/6429/nielit-2016-dec-scientist-b-section-a-3</a></p>"
        },
        {
          "id": 72,
          "question": "<p><a name=\"6395\"></a><div itemprop=\"text\"><p>In the following question, the first two words have definite relationship. Choose one word out of the given four alternatives which will fill in the blank space and show the same relationship with the third word as between the first two.</p>\n\n<p>Memorise is to Amnesia as Movement is to _______________.</p>\n\n</div><br><br><b>English Language: NIELIT 2016 DEC Scientist B</b></p>",
          "type": "single",
          "options": [
            "<p>Lubrication</p>",
            "<p>Lethargy</p>",
            "<p>Paralysis</p>",
            "<p>Hermit</p>"
          ],
          "correct_answer": "<p>Paralysis</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6395/nielit-2016-dec-scientist-b-section-a-37\" target=\"_blank\">https://aptitude.gateoverflow.in/6395/nielit-2016-dec-scientist-b-section-a-37</a></p>"
        },
        {
          "id": 73,
          "question": "<p><a name=\"6428\"></a><div itemprop=\"text\"><p>In the following question, out of the four alternatives, choose the one which best expresses the meaning of the given word.</p>\n\n<p>Yearn</p>\n\n</div><br><br><b>English Language: NIELIT 2016 DEC Scientist B</b></p>",
          "type": "single",
          "options": [
            "<p>Deny</p>",
            "<p>Accept</p>",
            "<p>Confront</p>",
            "<p>Crave</p>"
          ],
          "correct_answer": "<p>Crave</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6428/nielit-2016-dec-scientist-b-section-a-4\" target=\"_blank\">https://aptitude.gateoverflow.in/6428/nielit-2016-dec-scientist-b-section-a-4</a></p>"
        },
        {
          "id": 74,
          "question": "<p><a name=\"6504\"></a><div itemprop=\"text\"><p>Have a word followed by four answer choices. You will choose the word that is a necessary part of the word.</p>\n\n<p>party</p>\n\n</div><br><br><b>English Language: NIELIT 2017 DEC Scientific Assistant A</b></p>",
          "type": "single",
          "options": [
            "<p>celebration</p>",
            "<p>tuxedo</p>",
            "<p>appetizer</p>",
            "<p>orator</p>"
          ],
          "correct_answer": "<p>celebration</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6504/nielit-2017-dec-scientific-assistant-a-section-a-1\" target=\"_blank\">https://aptitude.gateoverflow.in/6504/nielit-2017-dec-scientific-assistant-a-section-a-1</a></p>"
        },
        {
          "id": 75,
          "question": "<p><a name=\"6321\"></a><div itemprop=\"text\"><p>Choose the most appropriate words from the options given below to complete the following sentence ;<br>\nFemale sparrows and immatures are _____, while the typical adult male sparrow is _____ by its markings; a black bib, a grey cap, and white lines trailing down from the mouth.</p>\n\n</div><br><br><b>English Language: NIELIT 2017 July Scientist B</b></p>",
          "type": "single",
          "options": [
            "<p>somewhat nondescript, easily recognized</p>",
            "<p>difficult to spot, better camouflaged</p>",
            "<p>considered to be endangered, characterized</p>",
            "<p>comparatively small, made more conspicuous</p>"
          ],
          "correct_answer": "<p>somewhat nondescript, easily recognized</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6321/nielit-2017-july-scientist-b-section-a-51\" target=\"_blank\">https://aptitude.gateoverflow.in/6321/nielit-2017-july-scientist-b-section-a-51</a></p>"
        },
        {
          "id": 76,
          "question": "<p><a name=\"6317\"></a><div itemprop=\"text\"><p>Choose the appropriate answer to complete the following sentence:</p>\n\n<p>To those of us who had always thought him timid, his ________came as a surprise.</p>\n\n</div><br><br><b>English Language: NIELIT 2017 July Scientist B</b></p>",
          "type": "single",
          "options": [
            "<p>inability</p>",
            "<p>inevitability</p>",
            "<p>intrepidity</p>",
            "<p>inertness</p>"
          ],
          "correct_answer": "<p>intrepidity</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6317/nielit-2017-july-scientist-b-section-a-55\" target=\"_blank\">https://aptitude.gateoverflow.in/6317/nielit-2017-july-scientist-b-section-a-55</a></p>"
        },
        {
          "id": 77,
          "question": "<p><a name=\"6776\"></a><div itemprop=\"text\"><p>Find the word which is closest in meaning to the phrase or sentences given below :</p>\n\n<p>Exhausted by lucubration :</p>\n\n</div><br><br><b>English Language: NIELIT 2019 Feb Scientist D</b></p>",
          "type": "single",
          "options": [
            "<p>Long walks</p>",
            "<p>Lecturing</p>",
            "<p>Exposure</p>",
            "<p>Laborious study</p>"
          ],
          "correct_answer": "<p>Laborious study</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6776/nielit-2019-feb-scientist-d-section-b-15\" target=\"_blank\">https://aptitude.gateoverflow.in/6776/nielit-2019-feb-scientist-d-section-b-15</a></p>"
        },
        {
          "id": 78,
          "question": "<p><a name=\"6775\"></a><div itemprop=\"text\"><p>Find the word which is closest in meaning to the phrase or sentences given below :</p>\n\n<p>Read with avidity :</p>\n\n</div><br><br><b>English Language: NIELIT 2019 Feb Scientist D</b></p>",
          "type": "single",
          "options": [
            "<p>Understanding</p>",
            "<p>Fear</p>",
            "<p>Eagerness</p>",
            "<p>Complaint</p>"
          ],
          "correct_answer": "<p>Eagerness</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6775/nielit-2019-feb-scientist-d-section-b-16\" target=\"_blank\">https://aptitude.gateoverflow.in/6775/nielit-2019-feb-scientist-d-section-b-16</a></p>"
        },
        {
          "id": 79,
          "question": "<p><a name=\"6774\"></a><div itemprop=\"text\"><p>Find the word which is closest in meaning to the phrase or sentences given below :</p>\n\n<p>A sumptuous house :</p>\n\n</div><br><br><b>English Language: NIELIT 2019 Feb Scientist D</b></p>",
          "type": "single",
          "options": [
            "<p>Luxurious</p>",
            "<p>Ornate</p>",
            "<p>Old-fashioned</p>",
            "<p>Artistic</p>"
          ],
          "correct_answer": "<p>Luxurious</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6774/nielit-2019-feb-scientist-d-section-b-17\" target=\"_blank\">https://aptitude.gateoverflow.in/6774/nielit-2019-feb-scientist-d-section-b-17</a></p>"
        },
        {
          "id": 80,
          "question": "<p><a name=\"6773\"></a><div itemprop=\"text\"><p>Find the word which is closest in meaning to the phrase or sentences given below :</p>\n\n<p>A cognate language :</p>\n\n</div><br><br><b>English Language: NIELIT 2019 Feb Scientist D</b></p>",
          "type": "single",
          "options": [
            "<p>Difficult</p>",
            "<p>Universal</p>",
            "<p>Ancient</p>",
            "<p>Kindred</p>"
          ],
          "correct_answer": "<p>Universal</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6773/nielit-2019-feb-scientist-d-section-b-18\" target=\"_blank\">https://aptitude.gateoverflow.in/6773/nielit-2019-feb-scientist-d-section-b-18</a></p>"
        },
        {
          "id": 81,
          "question": "<p><a name=\"6772\"></a><div itemprop=\"text\"><p>Each of the following sentences has a blank space and four words given after it. Select the word which consider most appropriate for the blank space and indicate your choice.</p>\n\n<p>'Please' and 'Thank you' are the little courtesies by which we keep the __________ of life oiled and running smoothly.</p>\n\n</div><br><br><b>English Language: NIELIT 2019 Feb Scientist D</b></p>",
          "type": "single",
          "options": [
            "<p>Path</p>",
            "<p>Machine</p>",
            "<p>Garden</p>",
            "<p>River</p>"
          ],
          "correct_answer": "<p>Machine</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6772/nielit-2019-feb-scientist-d-section-b-19\" target=\"_blank\">https://aptitude.gateoverflow.in/6772/nielit-2019-feb-scientist-d-section-b-19</a></p>"
        },
        {
          "id": 82,
          "question": "<p><a name=\"6771\"></a><div itemprop=\"text\"><p>Each of the following sentences has a blank space and four words given after it. Select the word which consider most appropriate for the blank space and indicate your choice.</p>\n\n<p>If negotiations are to prove fruitful, there must not only be sincerity on each side, but there must also be __________ in sincerity of the other side.</p>\n\n</div><br><br><b>English Language: NIELIT 2019 Feb Scientist D</b></p>",
          "type": "single",
          "options": [
            "<p>Faith</p>",
            "<p>Belief</p>",
            "<p>Substance</p>",
            "<p>Certainty</p>"
          ],
          "correct_answer": "<p>Faith</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6771/nielit-2019-feb-scientist-d-section-b-20\" target=\"_blank\">https://aptitude.gateoverflow.in/6771/nielit-2019-feb-scientist-d-section-b-20</a></p>"
        },
        {
          "id": 83,
          "question": "<p><a name=\"6770\"></a><div itemprop=\"text\"><p>Each of the following sentences has a blank space and four words given after it. Select the word which consider most appropriate for the blank space and indicate your choice.</p>\n\n<p>The criminal seems to have acted in __________ with three others.</p>\n\n</div><br><br><b>English Language: NIELIT 2019 Feb Scientist D</b></p>",
          "type": "single",
          "options": [
            "<p>Collusion</p>",
            "<p>Coalition</p>",
            "<p>Collision</p>",
            "<p>Cohesion</p>"
          ],
          "correct_answer": "<p>Collusion</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6770/nielit-2019-feb-scientist-d-section-b-21\" target=\"_blank\">https://aptitude.gateoverflow.in/6770/nielit-2019-feb-scientist-d-section-b-21</a></p>"
        },
        {
          "id": 84,
          "question": "<p><a name=\"6769\"></a><div itemprop=\"text\"><p>Each of the following sentences has a blank space and four words given after it. Select the word which consider most appropriate for the blank space and indicate your choice.</p>\n\n<p>If someone deliberately damages your property, he is __________&nbsp;to pay for the cost of repairs.</p>\n\n</div><br><br><b>English Language: NIELIT 2019 Feb Scientist D</b></p>",
          "type": "single",
          "options": [
            "<p>Liable</p>",
            "<p>Forced</p>",
            "<p>Requested</p>",
            "<p>Compelled</p>"
          ],
          "correct_answer": "<p>Liable</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/6769/nielit-2019-feb-scientist-d-section-b-22\" target=\"_blank\">https://aptitude.gateoverflow.in/6769/nielit-2019-feb-scientist-d-section-b-22</a></p>"
        },
        {
          "id": 85,
          "question": "<p><a name=\"353\"></a><div itemprop=\"text\"><p>Choose the set of words for each blank that best fits meaning of the sentence as whole<br>\n<br>\nNon-violent demonstration often create such tension that a community that has constantly refused to___________ &nbsp;&nbsp;its injustices is forced to correct them: the injustices can no longer be____________.</p>\n\n</div><br><br><b>English Language: Non violent demonstration often create such such tensions that a community</b></p>",
          "type": "single",
          "options": [
            "<p>Acknowledge, ignored</p>",
            "<p>Decrease, verified</p>",
            "<p>Tolerate, accepted</p>",
            "<p>Address, eliminated</p>",
            "<p>Explain, discussed.</p>"
          ],
          "correct_answer": "<p>Acknowledge, ignored</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/353/violent-demonstration-often-create-such-tensions-community\" target=\"_blank\">https://aptitude.gateoverflow.in/353/violent-demonstration-often-create-such-tensions-community</a></p>"
        },
        {
          "id": 86,
          "question": "<p><a name=\"354\"></a><div itemprop=\"text\"><p>Choose the set &nbsp;of words for each blank that best fits the meaning of the sentence as a whole.</p><p>Since 1813 reaction to Jane Austen's novels has oscillated between _______________ and condescension; but in general later writers have&nbsp;esteemed her works more highly than did most of her literary _____________.</p><ol><li>Dismissal, admirers</li><li>Adoration, contemporaries</li><li>Disapproval, readers</li><li>Indifference, followers</li><li>Approbation, precursors.</li></ol></div><br><br><b>English Language: Since 1813 reaction to Jane Austen's novels has oscillated between.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>B</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/354/since-1813-reaction-jane-austens-novels-oscillated-between\" target=\"_blank\">https://aptitude.gateoverflow.in/354/since-1813-reaction-jane-austens-novels-oscillated-between</a></p>"
        },
        {
          "id": 87,
          "question": "<p><a name=\"355\"></a><div itemprop=\"text\"><p>Choose the word or set of words for each blank that best fits the meaning of the sentence as a whole.</p><p>There are as yet no vegetation types or ecosystem whose study has been ____________ to the extent that they no longer ____________ ecologists.</p><ol><li>Perfected, hinder</li><li>Exhausted, interest</li><li>Prolonged, require</li><li>Prevented, challenge</li><li>Delayed, benefit.</li></ol></div><br><br><b>English Language: There, are as yet no vegetation types or ecosystem whose study..</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>B</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/355/there-are-as-yet-no-vegetation-types-or-ecosystem-whose-study\" target=\"_blank\">https://aptitude.gateoverflow.in/355/there-are-as-yet-no-vegetation-types-or-ecosystem-whose-study</a></p>"
        },
        {
          "id": 88,
          "question": "<p><a name=\"356\"></a><div itemprop=\"text\"><p>Choose the word or set of words for each blank that best fits the meaning of the sentence as whole.</p>\n\n<p>Under ethical guidelines recently adopted by the national institutes of health, human genes are to be manipulated only to correct diseases for which _________________ treatments are unsatisfactory.</p>\n\n<ol>\n\t<li>Similar</li>\n\t<li>Most</li>\n\t<li>Dangerous</li>\n\t<li>Uncommon</li>\n\t<li>Alternative.</li>\n</ol></div><br><br><b>English Language: Under ethical guidelines recently adopted by the national institutes of health.</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "E",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/356/ethical-guidelines-recently-adopted-national-institutes\" target=\"_blank\">https://aptitude.gateoverflow.in/356/ethical-guidelines-recently-adopted-national-institutes</a></p>"
        },
        {
          "id": 89,
          "question": "<p><a name=\"358\"></a><div itemprop=\"text\"><p>Choose the word or the set of words for each blank that best fits the meaning of the sentence as a whole.</p>\n\n<p>Winsor McCay, the cartoonist, could draw with incredible ____________ his comic strip about little Nemo was characterized by marvelous draftsmanship and sequencing.</p>\n\n<ol>\n\t<li>Sincerity</li>\n\t<li>Efficiency</li>\n\t<li>Virtuosity</li>\n\t<li>Rapidity</li>\n\t<li>Energy</li>\n</ol></div><br><br><b>English Language: Winsor McCay, the cartoonist, could draw with incredible______________.</b></p>",
          "type": "single",
          "options": [],
          "correct_answer": "<p>C</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://aptitude.gateoverflow.in/358/winsor-mccay-cartoonist-could-incredible______________\" target=\"_blank\">https://aptitude.gateoverflow.in/358/winsor-mccay-cartoonist-could-incredible______________</a></p>"
        }
      ]
    }
  ]
});
