window.__examLoadCallback({
  "title": "Computer Networks - IP Packet",
  "duration": 30,
  "sections": [
    {
      "name": "IP Packet",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"884\"></a><div itemprop=\"text\"><p>For which one of the following reasons does internet protocol(IP) use the time-to-live(TTL) field in IP datagram header?</p>\n\n</div><br><br><b>GATE CSE 2006 | Question: 5</b></p>",
          "type": "single",
          "options": [
            "<p>Ensure packets reach destination within that time</p>",
            "<p>Discard packets that reach later than that time</p>",
            "<p>Prevent packets from looping indefinitely</p>",
            "<p>Limit the time for which a packet gets queued in intermediate routers</p>"
          ],
          "correct_answer": "<p>Prevent packets from looping indefinitely</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/884/gate-cse-2006-question-5\" target=\"_blank\">https://gateoverflow.in/884/gate-cse-2006-question-5</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"2188\"></a><div itemprop=\"text\"><p>One of the header fields in an IP datagram is the Time-to-Live (TTL) field. Which of the following statements best explains the need for this field?</p>\n\n</div><br><br><b>GATE CSE 2010 | Question: 15. PGEE 2018</b></p>",
          "type": "single",
          "options": [
            "<p>It can be used to prioritize packets.</p>",
            "<p>It can be used to reduce delays.</p>",
            "<p>It can be used to optimize throughput.</p>",
            "<p>It can be used to prevent packet looping.</p>"
          ],
          "correct_answer": "<p>It can be used to prevent packet looping.</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/2188/gate-cse-2010-question-15-pgee-2018\" target=\"_blank\">https://gateoverflow.in/2188/gate-cse-2010-question-15-pgee-2018</a></p>"
        },
        {
          "id": 3,
          "question": "<p><a name=\"2059\"></a><div itemprop=\"text\"><p>Host A (on TCP/IP v4 network A) sends an IP datagram D to host B (also on TCP/IP v4 network B). Assume that no error occurred during the transmission of D. When D reaches B, which of the following IP header field(s) may be different from that of the original datagram D?</p>\n\n<ol style=\"list-style-type:lower-roman\">\n\t<li>TTL</li>\n\t<li>Checksum</li>\n\t<li>Fragment Offset</li>\n</ol>\n\n</div><br><br><b>GATE CSE 2014 Set 3 | Question: 25</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\text{i} \\) only</p>",
            "<p>\\( \\text{i} \\) and \\( \\text{ii} \\) only</p>",
            "<p>\\( \\text{ii} \\) and \\( \\text{iii} \\) only</p>",
            "<p>\\( \\text{i, ii} \\) and \\( \\text{iii} \\)</p>"
          ],
          "correct_answer": "<p>\\( \\text{i, ii} \\) and \\( \\text{iii} \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/2059/gate-cse-2014-set-3-question-25\" target=\"_blank\">https://gateoverflow.in/2059/gate-cse-2014-set-3-question-25</a></p>"
        },
        {
          "id": 4,
          "question": "<p><a name=\"2062\"></a><div itemprop=\"text\"><p>An \\( IP \\) router with a \\( \\text{Maximum Transmission Unit (MTU)} \\) of \\( 1500 \\) bytes has received an \\( IP \\) packet of size \\( 4404\\text{ bytes} \\) with an \\( IP \\) header of length \\( 20\\text{ bytes} \\). The values of the relevant fields in the header of the third \\( IP \\) fragment generated by the router for this packet are:</p>\n\n</div><br><br><b>GATE CSE 2014 Set 3 | Question: 28</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\text{MF bit} \\): \\( 0, \\)&nbsp;Datagram Length:\\( 1444; \\) Offset\\( : 370 \\)</p>",
            "<p>\\( \\text{MF bit} \\): \\( 1, \\)&nbsp;Datagram Length\\( : 1424; \\) Offset\\( : 185 \\)</p>",
            "<p>\\( \\text{MF bit} \\): \\( 1, \\)&nbsp;Datagram Length\\( : 1500; \\) Offset\\( : 370 \\)</p>",
            "<p>\\( \\text{MF bit} \\): \\( 0, \\)&nbsp;Datagram Length\\( : 1424; \\) Offset\\( : 2960 \\)</p>"
          ],
          "correct_answer": "<p>\\( \\text{MF bit} \\): \\( 0, \\)&nbsp;Datagram Length:\\( 1444; \\) Offset\\( : 370 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/2062/gate-cse-2014-set-3-question-28\" target=\"_blank\">https://gateoverflow.in/2062/gate-cse-2014-set-3-question-28</a></p>"
        },
        {
          "id": 5,
          "question": "<p><a name=\"8220\"></a><div itemprop=\"text\">\n<p>Which of the following fields of an IP header is NOT modified by a typical IP router?</p>\n\n\n</div><br><br><b>GATE CSE 2015 Set 1 | Question: 22</b></p>",
          "type": "single",
          "options": [
            "<p>Check sum</p>",
            "<p>Source address</p>",
            "<p>Time to Live (TTL)</p>",
            "<p>Length</p>"
          ],
          "correct_answer": "<p>Source address</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/8220/gate-cse-2015-set-1-question-22\" target=\"_blank\">https://gateoverflow.in/8220/gate-cse-2015-set-1-question-22</a></p>"
        },
        {
          "id": 6,
          "question": "<p><a name=\"8255\"></a><div itemprop=\"text\"><p>\\( \\text{Host A} \\) sends a \\( \\text{UDP} \\)&nbsp;datagram containing \\( 8880\\text{ bytes} \\) of user data to \\( \\text{host B} \\) over an \\( \\text{Ethernet LAN}. \\) Ethernet frames may carry data up to \\( 1500\\text{ bytes (i.e. MTU = 1500 bytes)}. \\) Size of \\( \\text{UDP} \\) header is \\( 8\\text{ bytes} \\) and size of \\( \\text{IP} \\) header is \\( 20\\text{ bytes}. \\) There is no option field in \\( \\text{IP} \\) header. How many total number of \\( \\text{IP} \\) fragments will be transmitted and what will be the contents of offset field in the last fragment?</p>\n\n</div><br><br><b>GATE CSE 2015 Set 2 | Question: 52</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 6 \\) and \\( 925 \\)</p>",
            "<p>\\( 6 \\) and \\( 7400 \\)</p>",
            "<p>\\( 7 \\) and \\( 1110 \\)</p>",
            "<p>\\( 7 \\) and \\( 8880 \\)</p>"
          ],
          "correct_answer": "<p>\\( 7 \\) and \\( 1110 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/8255/gate-cse-2015-set-2-question-52\" target=\"_blank\">https://gateoverflow.in/8255/gate-cse-2015-set-2-question-52</a></p>"
        },
        {
          "id": 7,
          "question": "<p><a name=\"39712\"></a><div itemprop=\"text\">An IP datagram of size \\( 1000 \\) \\( \\text{bytes } \\)arrives at a router. The router has to forward this packet on a link whose MTU (maximum transmission unit) is \\( 100 \\) \\( \\text{bytes } \\). Assume that the size of the IP header is \\( 20 \\) \\( \\text{bytes }. \\)<br>\n<br>\nThe number of fragments that the IP datagram will be divided into for transmission is________.</div><br><br><b>GATE CSE 2016 Set 1 | Question: 53</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "13",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/39712/gate-cse-2016-set-1-question-53\" target=\"_blank\">https://gateoverflow.in/39712/gate-cse-2016-set-1-question-53</a></p>"
        },
        {
          "id": 8,
          "question": "<p><a name=\"422821\"></a><div itemprop=\"text\"><p>Which of the following fields is/are modified in the \\( \\text{IP} \\) header of a packet going out of a network address translation \\( \\text{(NAT)} \\) device from an internal network to an external network?</p></div><br><br><b>GATE CSE 2024 | Set 1 | Question: 21</b></p>",
          "type": "multiple",
          "options": [
            "<p>Source \\( \\text{IP} \\)</p>",
            "<p>Destination \\( \\text{IP} \\)</p>",
            "<p>Header Checksum</p>",
            "<p>Total Length&nbsp;</p>"
          ],
          "correct_answer": [
            "<p>Source \\( \\text{IP} \\)</p>",
            "<p>Header Checksum</p>"
          ],
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/422821/gate-cse-2024-set-1-question-21\" target=\"_blank\">https://gateoverflow.in/422821/gate-cse-2024-set-1-question-21</a></p>"
        },
        {
          "id": 9,
          "question": "<p><a name=\"422879\"></a><div itemprop=\"text\"><p>​​​​​Which of the following statements about \\( \\text{IPv4} \\) fragmentation is/are TRUE?</p></div><br><br><b>GATE CSE 2024 | Set 2 | Question: 18</b></p>",
          "type": "multiple",
          "options": [
            "<p>The fragmentation of an \\( \\text{IP} \\) datagram is performed <em>only </em>at the source of the datagram</p>",
            "<p>The fragmentation of an \\( \\text{IP} \\)&nbsp;&nbsp;datagram is performed at any \\( \\text{IP} \\)&nbsp;&nbsp;router which finds that the size of the datagram to be transmitted exceeds the \\( \\text{MTU} \\)</p>",
            "<p>The reassembly of fragments is performed <em>only </em>at the destination of the datagram</p>",
            "<p>The reassembly of fragments is performed at all intermediate routers along the path from the source to the destination</p>"
          ],
          "correct_answer": [
            "<p>The fragmentation of an \\( \\text{IP} \\)&nbsp;&nbsp;datagram is performed at any \\( \\text{IP} \\)&nbsp;&nbsp;router which finds that the size of the datagram to be transmitted exceeds the \\( \\text{MTU} \\)</p>",
            "<p>The reassembly of fragments is performed <em>only </em>at the destination of the datagram</p>"
          ],
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/422879/gate-cse-2024-set-2-question-18\" target=\"_blank\">https://gateoverflow.in/422879/gate-cse-2024-set-2-question-18</a></p>"
        },
        {
          "id": 10,
          "question": "<p><a name=\"422875\"></a><div itemprop=\"text\"><p>​​​​Which of the following fields of an \\( \\text{IP} \\) header is/are <em>always </em>modified by any router before it forwards the \\( \\text{IP} \\) packet?</p></div><br><br><b>GATE CSE 2024 | Set 2 | Question: 22</b></p>",
          "type": "multiple",
          "options": [
            "<p>Source \\( \\text{IP} \\) Address</p>",
            "<p>Protocol</p>",
            "<p>Time to Live \\( \\text{(TTL)} \\)</p>",
            "<p>Header Checksum</p>"
          ],
          "correct_answer": [
            "<p>Time to Live \\( \\text{(TTL)} \\)</p>",
            "<p>Header Checksum</p>"
          ],
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/422875/gate-cse-2024-set-2-question-22\" target=\"_blank\">https://gateoverflow.in/422875/gate-cse-2024-set-2-question-22</a></p>"
        },
        {
          "id": 11,
          "question": "<p><a name=\"3730\"></a><div itemprop=\"text\"><p>In the TCP/IP protocol suite, which one of the following is NOT part of the IP header?</p></div><br><br><b>GATE IT 2004 | Question: 86</b></p>",
          "type": "single",
          "options": [
            "<p>Fragment Offset</p>",
            "<p>Source IP address</p>",
            "<p>Destination IP address</p>",
            "<p>Destination port number</p>"
          ],
          "correct_answer": "<p>Destination port number</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/3730/gate-it-2004-question-86\" target=\"_blank\">https://gateoverflow.in/3730/gate-it-2004-question-86</a></p>"
        }
      ]
    }
  ]
});
