window.__examLoadCallback({
  "title": "Digital_Logic - Digital_Logic - Slot 7",
  "duration": 42,
  "sections": [
    {
      "name": "Digital_Logic",
      "questions": [
        {
          "id": 1,
          "question": "<p>Consider the following circuit involving three D-type flip-flops used in a certain type of counter configuration. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q50_9b1eb674.jpg\"> <br> If all the flip-flops were reset to 0 at power on, what is the total number of\ndistinct outputs (states) represented by PQR generated by the counter? <br><br><strong>(GATE CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>3</p>",
            "<b>B.</b> <p>4</p>",
            "<b>C.</b> <p>5</p>",
            "<b>D.</b> <p>6</p>"
          ],
          "correct_answer": "<b>B.</b> <p>4</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/43318/gate2011-51#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Consider the following circuit involving three D-type flip-flops used in a certain type of counter configuration. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q50_9b1eb674.jpg\"> <br>If at some instance prior to the occurrence of the clock edge, P. Q and R have a\nvalue 0, 1 and 0 respectively, what shall be the value of PQR after the clock\nedge? <br><br><strong>(GATE CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(000\\)</p>",
            "<b>B.</b> <p>\\(001\\)</p>",
            "<b>C.</b> <p>\\(010\\)</p>",
            "<b>D.</b> <p>\\(011\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(011\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/2157/gate2011-50#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>The minimum number of D flip-flops needed to design a mod-258 counter is <br><br><strong>(GATE CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>9</p>",
            "<b>B.</b> <p>8</p>",
            "<b>C.</b> <p>512</p>",
            "<b>D.</b> <p>258</p>"
          ],
          "correct_answer": "<b>A.</b> <p>9</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2117/gate2011-15#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>The simplified SOP (Sum of Product) form of the Boolean Algebra \\((P+\\bar{Q}+\\bar{R})\\cdot (P+\\bar{Q}+R)\\cdot (P+Q+\\bar{R})\\) is <br><br><strong>(GATE CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((\\bar{P}Q+\\bar{R})\\)</p>",
            "<b>B.</b> <p>\\((P+\\bar{Q}\\bar{R})\\)</p>",
            "<b>C.</b> <p>\\((\\bar{P}Q+R)\\)</p>",
            "<b>D.</b> <p>(PQ+R)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\((P+\\bar{Q}\\bar{R})\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2116/gate2011-14#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Which one of the following circuits is NOT equivalent to a 2-input XNOR\n(exclusive NOR) gate? <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q2_aea01d42.jpg\"> <br><br><strong>(GATE CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A</p>",
            "<b>B.</b> <p>B</p>",
            "<b>C.</b> <p>C</p>",
            "<b>D.</b> <p>D</p>"
          ],
          "correct_answer": "<b>D.</b> <p>D</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2115/gate2011-13#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>In the sequential circuit shown below, if the initial value of the output \\(Q_{1}Q_{0}\\) is 00,\nwhat are the next four values of  \\(Q_{1}Q_{0}\\) ? <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q32_3fa4a72d.jpg\"> <br><br><strong>(GATE CSE 2010)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>11,10,01,00</p>",
            "<b>B.</b> <p>10,11,01,00</p>",
            "<b>C.</b> <p>10,00,01,11</p>",
            "<b>D.</b> <p>11,10,00,01</p>"
          ],
          "correct_answer": "<b>A.</b> <p>11,10,01,00</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/2206/gate2010-32#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>What is the Boolean Algebra for the output f of the combinational logic circuit\nof NOR gates given below? <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q31_95d89936.jpg\"> <br><br><strong>(GATE CSE 2010)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\overline{Q+R}\\)</p>",
            "<b>B.</b> <p>\\(\\overline{P+Q}\\)</p>",
            "<b>C.</b> <p>\\(\\overline{P+R}\\)</p>",
            "<b>D.</b> <p>\\(\\overline{P+Q+R}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(\\overline{Q+R}\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/2205/gate2010-31#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>The Boolean expression for the output f of the multiplexer shown below is <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q9_a0a5ecab.jpg\"> <br><br><strong>(GATE CSE 2010)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\overline{P\\bigoplus Q\\bigoplus R}\\)</p>",
            "<b>B.</b> <p>\\(P\\bigoplus Q\\bigoplus R\\)</p>",
            "<b>C.</b> <p>P+Q+R</p>",
            "<b>D.</b> <p>\\(\\overline{P+Q+R}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(P\\bigoplus Q\\bigoplus R\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2182/gate2010-9#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>P is a 16-bit signed integer. The 2's complement representation of P is \\((F87B)_{16}\\).\nThe 2's complement representation of 8*P is <br><br><strong>(GATE CSE 2010)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((C3D8)_{16}\\)</p>",
            "<b>B.</b> <p>\\((187B)_{16}\\)</p>",
            "<b>C.</b> <p>\\((F878)_{16}\\)</p>",
            "<b>D.</b> <p>\\((987B)_{16}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\((C3D8)_{16}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2179/gate2010-8#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>The minterm expansion of f(P,Q,R)=PQ+QR'+PR' is <br><br><strong>(GATE CSE 2010)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(m_{2}+m_{4}+m_{6}+m_{7}\\)</p>",
            "<b>B.</b> <p>\\(m_{0}+m_{1}+m_{3}+m_{5}\\)</p>",
            "<b>C.</b> <p>\\(m_{0}+m_{1}+m_{6}+m_{7}\\)</p>",
            "<b>D.</b> <p>\\(m_{2}+m_{3}+m_{4}+m_{5}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(m_{2}+m_{4}+m_{6}+m_{7}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2177/gate2010-6#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>The binary operation \\(\\square\\) is defined as follows <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q24_d4377443.jpg\"> <br> Which one of the following is equivalent to \\(P\\vee Q\\)? <br><br><strong>(GATE CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\neg Q\\square \\neg P\\)</p>",
            "<b>B.</b> <p>\\(P  \\square \\neg Q\\)</p>",
            "<b>C.</b> <p>\\(\\neg P\\square Q\\)</p>",
            "<b>D.</b> <p>\\(\\neg P\\square \\neg Q\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(P  \\square \\neg Q\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/801/gate2009-24#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>What is the minimum number of gates required to implement the Boolean\nfunction (AB+C) if we have to use only 2-input NOR gates? <br><br><strong>(GATE CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>2</p>",
            "<b>B.</b> <p>3</p>",
            "<b>C.</b> <p>4</p>",
            "<b>D.</b> <p>5</p>"
          ],
          "correct_answer": "<b>B.</b> <p>3</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1298/gate2009-6#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>\\((1217)_{8}\\) is equivalent to <br><br><strong>(GATE CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((1217)_{16}\\)</p>",
            "<b>B.</b> <p>\\((028F)_{16}\\)</p>",
            "<b>C.</b> <p>\\((2297)_{10}\\)</p>",
            "<b>D.</b> <p>\\((0B17)_{16}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\((028F)_{16}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1297/gate2009-5#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>The two numbers given below are multiplied using the Booth's algorithm.<br>\nMultiplicand :                            0101 1010 1110 1110<br>\nMultiplier:                                  0111 0111 1011 1101<br>\nHow many additions/Subtractions are required for the multiplication of the above two numbers? <br><br><strong>(GATE IT 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>6</p>",
            "<b>B.</b> <p>8</p>",
            "<b>C.</b> <p>10</p>",
            "<b>D.</b> <p>12</p>"
          ],
          "correct_answer": "<b>B.</b> <p>8</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/3352/gate2008-it-42\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>Consider the following state diagram and its realization by a JK flip flop <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q37_1826100b.jpg\"><br>The combinational circuit generates J and K in terms of x, y and Q.<br>The Boolean expressions for J and K are : <br><br><strong>(GATE IT 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\overline {x \\oplus y} \\text{ and }\\overline {x \\oplus y}\\)</p>",
            "<b>B.</b> <p>\\(\\overline {x \\oplus y} \\text{ and }{x \\oplus y}\\)</p>",
            "<b>C.</b> <p>\\({x \\oplus y} \\text{ and }\\overline {x \\oplus y}\\)</p>",
            "<b>D.</b> <p>\\({x \\oplus y} \\text{ and } {x \\oplus y}\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\({x \\oplus y} \\text{ and } {x \\oplus y}\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/3347/gate2008-it-37\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
