window.__examLoadCallback({
  "title": "Theory of Computation - Decidability",
  "duration": 6,
  "sections": [
    {
      "name": "Decidability",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"336302\"></a><div itemprop=\"text\"><p>Which of the following are undecidable?</p>\n\n<p>\\( P1 \\): The language generated by some CFG contains any words of length less than some given number \\( n \\).</p>\n\n<p>\\( P2 \\): Let \\( L1 \\) be CFL and \\( L2 \\) be regular, to determine whether \\( L1 \\) and \\( L2 \\) have common elements</p>\n\n<p>\\( P3 \\): Any given CFG is ambiguous or not.</p>\n\n<p>\\( P4 \\): For any given CFG&nbsp;\\( G \\), to determine whether epsilon belongs to \\( L(G) \\)</p>\n\n</div><br><br><b>Theory of Computation: NIELIT 2017 DEC Scientist B</b></p>",
          "type": "single",
          "options": [
            "<p>\\( P2 \\) only</p>",
            "<p>\\( P1 \\) and \\( P2 \\) only</p>",
            "<p>\\( P2 \\) and \\( P3 \\) only</p>",
            "<p>\\( P3 \\) only</p>"
          ],
          "correct_answer": "<p>\\( P3 \\) only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/336302/nielit-2017-dec-scientist-b-section-b-11\" target=\"_blank\">https://gateoverflow.in/336302/nielit-2017-dec-scientist-b-section-b-11</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"373730\"></a><div itemprop=\"text\"><p>Consider the following problem \\( \\text{X} \\).<br>\nGiven a Turing machine \\( \\text{M} \\) over the input alphabet \\( \\Sigma \\), any state \\( q \\) of \\( \\text{M} \\) and a word \\( w \\in \\Sigma^{\\ast} \\), does the computation of \\( \\text{M} \\) on \\( w \\)&nbsp;visit the state of \\( q \\) ?<br>\nWhich of the following statements about \\( \\text{X} \\) is correct?</p>\n\n</div><br><br><b>Theory of Computation: NIELIT 2022 April Scientist B | Section B | Question: 108</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\text{X} \\) is decidable</p>",
            "<p>\\( \\text{X} \\) is undecidable but partially decidable</p>",
            "<p>\\( \\text{X} \\) is undecidable and not even &nbsp;partially decidable</p>",
            "<p>\\( \\text{X} \\) is not a decision problem</p>"
          ],
          "correct_answer": "<p>\\( \\text{X} \\) is undecidable but partially decidable</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/373730/nielit-2022-april-scientist-b-section-b-question-108\" target=\"_blank\">https://gateoverflow.in/373730/nielit-2022-april-scientist-b-section-b-question-108</a></p>"
        }
      ]
    }
  ]
});
