window.__examLoadCallback({
  "title": "Theory of Computation - Regular Expression",
  "duration": 50,
  "sections": [
    {
      "name": "Regular Expression",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"69956\"></a><div itemprop=\"text\"><p>The number of strings of length 4 that are generated by the regular expression \\( (0^+ 1^+ | \\,2^+ 3^+ )^{*} \\), where | is an alternation character and \\( {+, ^{*}} \\) are quantification characters, is :</p></div><br><br><b>Theory of Computation: UGC NET CSE | August 2016 | Part 2 | Question: 31</b></p>",
          "type": "numeric",
          "options": [
            "<p>\\( 08 \\)</p>",
            "<p>\\( 09 \\)</p>",
            "<p>\\( 10 \\)</p>",
            "<p>\\( 12 \\)</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/69956/ugc-net-cse-august-2016-part-2-question-31\" target=\"_blank\">https://gateoverflow.in/69956/ugc-net-cse-august-2016-part-2-question-31</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"70926\"></a><div itemprop=\"text\"><p>Consider the following identities for regular expressions :</p>\n\n<p>(a) (r + s)* = (s + r)*</p>\n\n<p>(b) (r*)* = r*</p>\n\n<p>(c) (r* s*)* = (r + s)*</p>\n\n<p>Which of the above identities are true ?</p>\n\n</div><br><br><b>Theory of Computation: UGC NET CSE | August 2016 | Part 3 | Question: 24</b></p>",
          "type": "numeric",
          "options": [
            "<p>(a) and (b) only</p>",
            "<p>(b) and (c) only</p>",
            "<p>(c) and (a) only</p>",
            "<p>(a), (b) and (c)</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/70926/ugc-net-cse-august-2016-part-3-question-24\" target=\"_blank\">https://gateoverflow.in/70926/ugc-net-cse-august-2016-part-3-question-24</a></p>"
        },
        {
          "id": 3,
          "question": "<p><a name=\"335503\"></a><div itemprop=\"text\"><p>Regular expression \\( a+b \\) denotes the set :</p>\n\n</div><br><br><b>Theory of Computation: UGC NET CSE | December 2005 | Part 2 | Question: 5</b></p>",
          "type": "numeric",
          "options": [
            "<p>{\\( a \\)}</p>",
            "<p>{\\( \\in, a, b \\)}</p>",
            "<p>{\\( a, b \\)}</p>",
            "<p>None of these</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/335503/ugc-net-cse-december-2005-part-2-question-5\" target=\"_blank\">https://gateoverflow.in/335503/ugc-net-cse-december-2005-part-2-question-5</a></p>"
        },
        {
          "id": 4,
          "question": "<p><a name=\"13365\"></a><div itemprop=\"text\"><p>&nbsp;Regular expression for the complement of language \\( L=\\left\\{a^{n}b^{m} \\mid n \\geq 4, m \\leq 3\\right\\} \\) is&nbsp;</p>\n\n</div><br><br><b>Theory of Computation: UGC NET CSE | December 2014 | Part 3 | Question: 24</b></p>",
          "type": "single",
          "options": [
            "<p>\\( (a + b)^{*} ba(a + b)^{*} \\)&nbsp;</p>",
            "<p>\\( a^{*} bbbbb^{*} \\)&nbsp;</p>",
            "<p>\\( (\\lambda + a + aa + aaa)b^{*} + (a + b)^{*} ba(a + b)^{*} \\)</p>",
            "<p>None of the above&nbsp;</p>"
          ],
          "correct_answer": "<p>None of the above&nbsp;</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/13365/ugc-net-cse-december-2014-part-3-question-24\" target=\"_blank\">https://gateoverflow.in/13365/ugc-net-cse-december-2014-part-3-question-24</a></p>"
        },
        {
          "id": 5,
          "question": "<p><a name=\"335132\"></a><div itemprop=\"text\"><p>Which of the following strings would match the regular expression : \\( p+ [3-5] *&nbsp;&nbsp;[xyz] \\)?</p><ol style=\"list-style-type:upper-roman\" type=\"I\"><li>\\( p443y \\)</li><li>\\( p6y \\)</li><li>\\( 3xyz \\)</li><li>\\( p35z \\)</li><li>\\( p353535x \\)</li><li>\\( ppp5 \\)</li></ol></div><br><br><b>Theory of Computation: UGC NET CSE | January 2017 | Part 2 | Question: 31</b></p>",
          "type": "single",
          "options": [
            "<p>I, IlI and VI&nbsp;only</p>",
            "<p>IV, V&nbsp;and VI&nbsp;only</p>",
            "<p>II, IV&nbsp;and V&nbsp;only</p>",
            "<p>I, IV&nbsp;and V&nbsp;only</p>"
          ],
          "correct_answer": "<p>I, IV&nbsp;and V&nbsp;only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/335132/ugc-net-cse-january-2017-part-2-question-31\" target=\"_blank\">https://gateoverflow.in/335132/ugc-net-cse-january-2017-part-2-question-31</a></p>"
        },
        {
          "id": 6,
          "question": "<p><a name=\"63440\"></a><div itemprop=\"text\"><p>The number of strings of length 4 that are generated by the regular expression \\[ (0 \\mid \\epsilon ) 1^+ 2^{*}(3 \\mid \\epsilon) \\], where \\( \\mid \\) is an alternation character, \\( \\{+, *\\} \\) are quantification characters, and \\( \\epsilon \\) is the null string, is:</p></div><br><br><b>Theory of Computation: UGC NET CSE | July 2016 | Part 2 | Question: 31</b></p>",
          "type": "single",
          "options": [
            "<p>08</p>",
            "<p>10</p>",
            "<p>11</p>",
            "<p>12</p>"
          ],
          "correct_answer": "<p>12</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/63440/ugc-net-cse-july-2016-part-2-question-31\" target=\"_blank\">https://gateoverflow.in/63440/ugc-net-cse-july-2016-part-2-question-31</a></p>"
        },
        {
          "id": 7,
          "question": "<p><a name=\"57156\"></a><div itemprop=\"text\"><p>The regular expression for the complement of the language \\( L=\\{a^nb^m \\mid n \\geq 4, m \\leq 3\\} \\) is:</p></div><br><br><b>Theory of Computation: UGC NET CSE | July 2016 | Part 3 | Question: 23</b></p>",
          "type": "single",
          "options": [
            "<p>\\( (\\lambda +a+aa+aaa)b^*+a^*bbbb^*+(a+b)^*ba(a+b)^* \\)</p>",
            "<p>\\( (\\lambda +a+aa+aaa)b^*+a^*bbbbb^*+(a+b)^*ab(a+b)^* \\)</p>",
            "<p>\\( (\\lambda +a+aa+aaa)+a^*bbbbb^*+(a+b)^*ab(a+b)^* \\)</p>",
            "<p>\\( (\\lambda +a+aa+aaa)b^*+a^*bbbbb^*+(a+b)^*ba(a+b)^* \\)</p>"
          ],
          "correct_answer": "<p>\\( (\\lambda +a+aa+aaa)b^*+a^*bbbbb^*+(a+b)^*ba(a+b)^* \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/57156/ugc-net-cse-july-2016-part-3-question-23\" target=\"_blank\">https://gateoverflow.in/57156/ugc-net-cse-july-2016-part-3-question-23</a></p>"
        },
        {
          "id": 8,
          "question": "<p><a name=\"57141\"></a><div itemprop=\"text\"><p>Consider the following two languages:</p><p>\\( L_1=\\{0^i1^j \\mid ged (i,j)=1 \\} \\)</p><p>\\( L_2 \\) is any subset of 0*</p><p>Which of the following is correct?</p></div><br><br><b>Theory of Computation: UGC NET CSE | July 2016 | Part 3 | Question: 24</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L_1 \\) is regular and \\( L_2* \\) is not regular</p>",
            "<p>\\( L_1 \\) is not regular and \\( L_2* \\) is regular</p>",
            "<p>Both&nbsp;\\( L_1 \\) and \\( L_2* \\) are regular languages</p>",
            "<p>Both&nbsp;\\( L_1 \\) and \\( L_2* \\) are not regular languages</p>"
          ],
          "correct_answer": "<p>\\( L_1 \\) is not regular and \\( L_2* \\) is regular</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/57141/ugc-net-cse-july-2016-part-3-question-24\" target=\"_blank\">https://gateoverflow.in/57141/ugc-net-cse-july-2016-part-3-question-24</a></p>"
        },
        {
          "id": 9,
          "question": "<p><a name=\"63980\"></a><div itemprop=\"text\"><p>Let L be the language generated by regular expression 0*10* and accepted by the deterministic finite automata M. Consider the relation \\( R_M \\) defined by M as all states that are reachable from the start state. \\( R_M \\) has ___ equivalence classes.</p></div><br><br><b>Theory of Computation: UGC NET CSE | July 2016 | Part 3 | Question: 55</b></p>",
          "type": "single",
          "options": [
            "<p>2</p>",
            "<p>4</p>",
            "<p>5</p>",
            "<p>6</p>"
          ],
          "correct_answer": "<p>6</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/63980/ugc-net-cse-july-2016-part-3-question-55\" target=\"_blank\">https://gateoverflow.in/63980/ugc-net-cse-july-2016-part-3-question-55</a></p>"
        },
        {
          "id": 10,
          "question": "<p><a name=\"67606\"></a><div itemprop=\"text\"><p>\"My Laughter Machine (MLM) recognizes the following strings :</p><p>(i) \\( a \\)</p><p>(ii) \\( aba \\)</p><p>(iii) \\( abaabaaba \\)</p><p>(iv) \\( abaabaabaabaabaabaabaabaaba \\)</p><p>Using this as an information, how would you compare the following regular expressions ?</p><p>(i) \\( (aba)^{3x} \\)&nbsp;</p><p>(ii) \\( a.(baa)3^{x}–1.ba \\)&nbsp;</p><p>(iii) \\( ab.(aab).^{3x - 1}.a \\)&nbsp;</p></div><br><br><b>Theory of Computation: UGC NET CSE | June 2010 | Part 2 | Question: 3</b></p>",
          "type": "numeric",
          "options": [
            "<p>\\( (ii) \\) and \\( (iii) \\) are same, \\( (i) \\) is different.</p>",
            "<p>\\( (ii) \\) and \\( (iii) \\) are not same.</p>",
            "<p>\\( (i), (ii) \\) and \\( (iii) \\) are different.</p>",
            "<p>\\( (i), (ii) \\) and \\( (iii) \\) are same.</p>"
          ],
          "correct_answer": "Q-Q",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/67606/ugc-net-cse-june-2010-part-2-question-3\" target=\"_blank\">https://gateoverflow.in/67606/ugc-net-cse-june-2010-part-2-question-3</a></p>"
        },
        {
          "id": 11,
          "question": "<p><a name=\"56266\"></a><div itemprop=\"text\"><p>Consider the regular expression (a+b)(a+b) ..... (a+b) (n-times). The minimum number of states in finite automaton that recognizes the language represented by this regular expression contains</p></div><br><br><b>Theory of Computation: UGC NET CSE | June 2012 | Part 3 | Question: 35</b></p>",
          "type": "single",
          "options": [
            "<p>n states</p>",
            "<p>n+1 states</p>",
            "<p>n+2 states</p>",
            "<p>2\\( ^n \\) states</p>"
          ],
          "correct_answer": "<p>n+1 states</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/56266/ugc-net-cse-june-2012-part-3-question-35\" target=\"_blank\">https://gateoverflow.in/56266/ugc-net-cse-june-2012-part-3-question-35</a></p>"
        },
        {
          "id": 12,
          "question": "<p><a name=\"56282\"></a><div itemprop=\"text\"><p>The regular expression for the following DFA</p><p><img alt=\"\" width=\"360\" src=\"https://gateoverflow.in/?qa=blob&amp;qa_blobid=4321473721608392735\"></p></div><br><br><b>Theory of Computation: UGC NET CSE | June 2012 | Part 3 | Question: 43</b></p>",
          "type": "single",
          "options": [
            "<p>ab*(b+aa*b)*</p>",
            "<p>a*b(b+aa*b)*</p>",
            "<p>a*b(b*+aa*b)</p>",
            "<p>a*b(b+aa*b)*</p>"
          ],
          "correct_answer": "<p>a*b(b+aa*b)*</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/56282/ugc-net-cse-june-2012-part-3-question-43\" target=\"_blank\">https://gateoverflow.in/56282/ugc-net-cse-june-2012-part-3-question-43</a></p>"
        },
        {
          "id": 13,
          "question": "<p><a name=\"61229\"></a><div itemprop=\"text\"><p>The regular expression corresponding to the language L where \\( L=\\{ x \\in \\{0,1\\}^* \\mid x \\text{ ends with 1 and does not contain substring 00}  \\) is</p></div><br><br><b>Theory of Computation: UGC NET CSE | Junet 2015 | Part 3 | Question: 20</b></p>",
          "type": "single",
          "options": [
            "<p>(1+01)* (10+01)</p>",
            "<p><span style=\"line-height: 20.8px;\">(1+01)* 01</span></p>",
            "<p><span style=\"line-height: 20.8px;\">(1+01)* (1+01)</span></p>",
            "<p>(10+01)* 01</p>"
          ],
          "correct_answer": "<p><span style=\"line-height: 20.8px;\">(1+01)* (1+01)</span></p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/61229/ugc-net-cse-junet-2015-part-3-question-20\" target=\"_blank\">https://gateoverflow.in/61229/ugc-net-cse-junet-2015-part-3-question-20</a></p>"
        },
        {
          "id": 14,
          "question": "<p><a name=\"166267\"></a><div itemprop=\"text\"><p>Which of the following regular expressions, each describing a language of binary numbers (MSB to LSB) that represents non-negative decimal values, does <strong>not</strong> include even values?</p>\n\n\n\n<p>Where \\( \\{+,\\ * \\} \\) are quantification characters.</p></div><br><br><b>Theory of Computation: UGC NET CSE | November 2017 | Part 2 | Question: 33</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 0^*1^+0^*1^* \\)</p>",
            "<p>\\( 0^*1^*0^+1^* \\)</p>",
            "<p>\\( 0^*1^*0^*1^+ \\)</p>",
            "<p>\\( 0^+1^*0^*1^* \\)</p>"
          ],
          "correct_answer": "<p>\\( 0^*1^*0^*1^+ \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/166267/ugc-net-cse-november-2017-part-2-question-33\" target=\"_blank\">https://gateoverflow.in/166267/ugc-net-cse-november-2017-part-2-question-33</a></p>"
        },
        {
          "id": 15,
          "question": "<p><a name=\"349645\"></a><div itemprop=\"text\"><p>Let \\( L_1 \\) and \\( L_2 \\) be languages over \\( \\Sigma = \\{a,b\\} \\) represented by the regular expressions \\( (a^* +b)^* \\) and \\( (a+b)^* \\) respectively.</p><p>Which of the following is true with respect to the two languages?</p></div><br><br><b>Theory of Computation: UGC NET CSE | October 2020 | Part 2 | Question: 28</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L_1 \\subset L_2 \\)</p>",
            "<p>\\( L_2 \\subset L_1 \\)</p>",
            "<p>\\( L_1 = L_2 \\)</p>",
            "<p>\\( L_1 \\cap L_2 = \\phi \\)</p>"
          ],
          "correct_answer": "<p>\\( L_1 = L_2 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/349645/ugc-net-cse-october-2020-part-2-question-28\" target=\"_blank\">https://gateoverflow.in/349645/ugc-net-cse-october-2020-part-2-question-28</a></p>"
        },
        {
          "id": 16,
          "question": "<p><a name=\"349594\"></a><div itemprop=\"text\"><p>Consider the following regular expressions:</p>\n\n<ol start=\"1\" style=\"list-style-type:lower-roman\" type=\"i\">\n\t<li>\\( r=a(b+a)^* \\)</li>\n\t<li>\\( s=a(a+b)^* \\)</li>\n\t<li>\\( t=aa^*b \\)</li>\n</ol>\n\n<p>Choose the correct answer from the options given below based on the relation between the languages generated by the regular expressions above:</p>\n\n</div><br><br><b>Theory of Computation: UGC NET CSE | October 2020 | Part 2 | Question: 79</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L(r) \\subseteq L(s) \\subseteq L(t) \\)</p>",
            "<p>\\( L(r) \\supseteq L(s) \\supseteq L(t) \\)</p>",
            "<p>\\( L(r) \\supseteq L(t) \\supseteq L(s) \\)</p>",
            "<p>\\( L(s) \\supseteq L(t) \\supseteq L(r) \\)</p>"
          ],
          "correct_answer": "<p>\\( L(r) \\supseteq L(s) \\supseteq L(t) \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/349594/ugc-net-cse-october-2020-part-2-question-79\" target=\"_blank\">https://gateoverflow.in/349594/ugc-net-cse-october-2020-part-2-question-79</a></p>"
        },
        {
          "id": 17,
          "question": "<p><a name=\"59033\"></a><div itemprop=\"text\"><p>Regular expression for the language \\( L=w \\in \\{0,1\\}* \\mid w \\) has no pair of consecutive zeros \\( \\} \\) is</p></div><br><br><b>Theory of Computation: UGC NET CSE | September 2013 | Part 2 | Question: 14</b></p>",
          "type": "single",
          "options": [
            "<p>\\( (1+010)* \\)</p>",
            "<p>\\( (01+10)* \\)</p>",
            "<p>\\( (1+010)*(0+ \\lambda) \\)</p>",
            "<p>\\( (1+01)* (0+\\lambda) \\)</p>"
          ],
          "correct_answer": "<p>\\( (1+01)* (0+\\lambda) \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/59033/ugc-net-cse-september-2013-part-2-question-14\" target=\"_blank\">https://gateoverflow.in/59033/ugc-net-cse-september-2013-part-2-question-14</a></p>"
        },
        {
          "id": 18,
          "question": "<p><a name=\"59068\"></a><div itemprop=\"text\"><p>Consider the following two languages:</p><p>\\( L_1 =\\{a^n b^l a^k \\mid n+l+k &gt; 5\\} \\)</p><p>\\( L_2 =\\{a^n b^l a^k \\mid n&gt; 5, l&gt;3, k \\leq l \\} \\)</p><p>Which one of the following is true?</p></div><br><br><b>Theory of Computation: UGC NET CSE | September 2013 | Part 2 | Question: 15</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L_1 \\) is regular language and \\( L_2 \\) is not regular language</p>",
            "<p>Both \\( L_1 \\) and \\( L_2 \\) are regular language</p>",
            "<p>Both \\( L_1 \\) and \\( L_2 \\) are not regular language</p>",
            "<p>\\( L_1 \\) is not regular language and \\( L_2 \\) is regular language</p>"
          ],
          "correct_answer": "<p>\\( L_1 \\) is regular language and \\( L_2 \\) is not regular language</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/59068/ugc-net-cse-september-2013-part-2-question-15\" target=\"_blank\">https://gateoverflow.in/59068/ugc-net-cse-september-2013-part-2-question-15</a></p>"
        }
      ]
    }
  ]
});
