window.__examLoadCallback({
  "title": "Theory of Computation - Context Free Grammar",
  "duration": 14,
  "sections": [
    {
      "name": "Context Free Grammar",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"213561\"></a><div itemprop=\"text\">\n\n<p>A \\( CFG \\) (Context Free Grammar) is said to be in Chomsky Normal Form \\( (CNF) \\), if all the productions are of the form A\\( \\to \\) BC or A\\( \\to \\) a. Let \\( G \\) be a \\( CFG \\) in \\( CNF \\). To derive a string of terminals of length x, the number of products to be used is:</p>\n\n</div><br><br><b>Theory of Computation: ISRO CSE 2018 | Question: 27</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 2x-1 \\)</p>",
            "<p>\\( 2x \\)</p>",
            "<p>\\( 2x+1 \\)</p>",
            "<p>\\( 2^{x} \\)</p>"
          ],
          "correct_answer": "<p>\\( 2x-1 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/213561/isro-cse-2018-question-27\" target=\"_blank\">https://gateoverflow.in/213561/isro-cse-2018-question-27</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"331445\"></a><div itemprop=\"text\"><p>The language which is generated by the grammar \\( S \\rightarrow aSa \\mid bSb \\mid a \\mid b \\) over the alphabet of \\( \\{a,b\\} \\) is the set of</p>\n\n</div><br><br><b>Theory of Computation: ISRO CSE 2020 | Question: 39</b></p>",
          "type": "single",
          "options": [
            "<p>Strings that begin and end with the same symbol</p>",
            "<p>All odd and even length palindromes</p>",
            "<p>All odd length palindromes</p>",
            "<p>All even length palindromes</p>"
          ],
          "correct_answer": "<p>All odd length palindromes</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/331445/isro-cse-2020-question-39\" target=\"_blank\">https://gateoverflow.in/331445/isro-cse-2020-question-39</a></p>"
        },
        {
          "id": 3,
          "question": "<p><a name=\"435362\"></a><div itemprop=\"text\"><p>Consider the context-free grammar \\( \\text{G} \\) below. Here \\( \\text{S} \\) is the starting non-terminal symbol, while \\( a \\) and \\( b \\) are terminal symbols.<br>\\[<br>\\begin{array}{l}<br>S \\rightarrow a S b \\mid T \\\\<br>T \\rightarrow b T \\mid b<br>\\end{array}<br>\\]<br><br>The language generated by G is:</p></div><br><br><b>Theory of Computation: ISRO CSE 2023 | Question: 34</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\left\\{a^{m}b^{n} : 0 \\leq m &lt; n \\right\\} \\)</p>",
            "<p>\\( \\left\\{a^{m}b^{n} : 0 &lt;&nbsp;m &lt; n \\right\\} \\)</p>",
            "<p>\\( \\left\\{a^{m}b^{n} : 0 &lt; m&nbsp;\\leq&nbsp;n \\right\\} \\)</p>",
            "<p>\\( \\left\\{a^{n}b^{n} : n \\geq 0&nbsp;\\right\\} \\)</p>"
          ],
          "correct_answer": "<p>\\( \\left\\{a^{m}b^{n} : 0 \\leq m &lt; n \\right\\} \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/435362/isro-cse-2023-question-34\" target=\"_blank\">https://gateoverflow.in/435362/isro-cse-2023-question-34</a></p>"
        },
        {
          "id": 4,
          "question": "<p><a name=\"182072\"></a><div itemprop=\"text\"><p>Consider the grammar with productions</p>\n\n<p>\\( S\\rightarrow aSb\\mid SS \\mid \\varepsilon \\)</p>\n\n<p>This grammar is&nbsp;</p>\n\n</div><br><br><b>Theory of Computation: ISRO</b></p>",
          "type": "single",
          "options": [
            "<p>not context-free, not linear</p>",
            "<p>not context-free, linear</p>",
            "<p>context-free, not linear</p>",
            "<p>context-free, linear</p>"
          ],
          "correct_answer": "<p>context-free, not linear</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/182072/isro-dec2017-22\" target=\"_blank\">https://gateoverflow.in/182072/isro-dec2017-22</a></p>"
        },
        {
          "id": 5,
          "question": "<p><a name=\"182073\"></a><div itemprop=\"text\"><p>Identify the language generated by the following grammar<br>\n\\( S\\rightarrow AB\\\\ A\\rightarrow aAb\\mid \\varepsilon\\\\ B\\rightarrow bB\\mid b \\)</p>\n\n</div><br><br><b>Theory of Computation: ISRO</b></p>",
          "type": "numeric",
          "options": [
            "<p>\\( \\{a^m b^n\\mid n\\geq m,m&gt;0\\} \\)<br>\n\t&nbsp;</p>",
            "<p>\\( \\{a^m b^n\\mid n\\geq m,m\\geq0\\} \\)<br>\n\t&nbsp;</p>",
            "<p>\\( \\{a^m b^n\\mid n&gt; m,m&gt;0\\} \\)<br>\n\t&nbsp;</p>",
            "<p>\\( \\{a^m b^m\\mid n&gt; m,m\\geq0\\} \\)</p>"
          ],
          "correct_answer": "X",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/182073/isro-dec2017-23\" target=\"_blank\">https://gateoverflow.in/182073/isro-dec2017-23</a></p>"
        }
      ]
    }
  ]
});
