window.__examLoadCallback({
  "title": "Graph_Theory - Graph_Theory - Slot 1",
  "duration": 42,
  "sections": [
    {
      "name": "Graph_Theory",
      "questions": [
        {
          "id": 1,
          "question": "<p>The chromatic number of a graph is the minimum number of colours used in a\nproper colouring of the graph. The chromatic number of the following graph\nis _______<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Graph_Theory\\q50_6bd60b4f.webp\"><br> <br><br><strong>(GATE CSE 2024 SET-2)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "2",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/422847/gate-cse-2024-set-2-question-50#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Let \\( A  \\) be the adjacency matrix of a simple undirected graph \\(G\\). Suppose \\(A\\) is its own inverse. Which one of the following statements is always TRUE? <br><br><strong>(GATE CSE 2024 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(G\\) is a cycle</p>",
            "<b>B.</b> <p>\\(G\\) is a perfect matching</p>",
            "<b>C.</b> <p>\\(G\\) is a complete graph</p>",
            "<b>D.</b> <p>There is no such graph \\(G\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(G\\) is a perfect matching</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/422890/gate-cse-2024-set-2-question-7#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>The number of edges present in the forest generated by the DFS traversal of an undirected graph \\( G \\) with 100 vertices is 40 . The number of connected components in \\( G \\) is ____ <br><br><strong>(GATE CSE 2024 SET-1)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "60",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/422792/gate-cse-2024-set-1-question-50#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>The chromatic number of a graph is the minimum number of colours used in a proper colouring of the graph. Let \\( G \\) be any graph with \\( n \\) vertices and chromatic number \\( k \\). Which of the following statements is/are always TRUE? <br><br><strong>(GATE CSE 2024 SET-1)</strong></p>",
          "type": "multiple",
          "options": [
            "<b>A.</b> <p>\\(G\\) contains a complete subgraph with \\(k\\) vertices</p>",
            "<b>B.</b> <p>\\(G\\) contains an independent set of size at least \\(n/k\\)</p>",
            "<b>C.</b> <p>\\(G\\) contains at least \\(k(k - 1)/2\\) edges</p>",
            "<b>D.</b> <p>\\(G\\) contains a vertex of degree at least \\(k\\)</p>"
          ],
          "correct_answer": [
            "<b>B.</b> <p>\\(G\\) contains an independent set of size at least \\(n/k\\)</p>",
            "<b>C.</b> <p>\\(G\\) contains at least \\(k(k - 1)/2\\) edges</p>"
          ],
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/422801/gate-cse-2024-set-1-question-41#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Let \\( G \\) be a directed graph and \\( T \\) a depth first search (DFS) spanning tree in \\( G \\) that is rooted at a vertex \\( v \\). Suppose \\( T \\) is also a breadth first search (BFS) tree in \\( G \\), rooted at \\( v \\). Which of the following statements is/are TRUE for every such graph \\( G \\) and tree \\( T \\) ? <br><br><strong>(GATE CSE 2024 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>There are no back-edges in \\( G \\) with respect to the tree \\( T \\)</p>",
            "<b>B.</b> <p>There are no cross-edges in \\( G \\) with respect to the tree \\( T \\)</p>",
            "<b>C.</b> <p>There are no forward-edges in \\( G \\) with respect to the tree \\( T \\)</p>",
            "<b>D.</b> <p>The only edges in \\( G \\) are the edges in \\( T \\)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>There are no forward-edges in \\( G \\) with respect to the tree \\( T \\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/422807/gate-cse-2024-set-1-question-35#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Let \\(G\\) be a simple, finite, undirected graph with vertex set \\( \\{v_1,...,v_n\\}\\). Let \\( \\Delta (G)\\)\ndenote the maximum degree of  \\(G\\) and let \\( N=\\{1,2,...\\} \\)  denote the set of all possible\ncolors. Color the vertices of  \\(G\\) using the following greedy strategy:\nfor \\(i = 1,...,n\\)<br> \\(color(v_i)\\leftarrow min\\{ j \\in N: \\text{  no neighbour of } v_i \\text{ is colored } j\\}\\)    <br>Which of the following statements is/are TRUE? <br><br><strong>(GATE CSE 2023)</strong></p>",
          "type": "multiple",
          "options": [
            "<b>A.</b> <p>This procedure results in a proper vertex coloring of \\(G\\).</p>",
            "<b>B.</b> <p>The number of colors used is at most \\( \\Delta (G)+1\\).</p>",
            "<b>C.</b> <p>The number of colors used is at most\\( \\Delta (G)\\).</p>",
            "<b>D.</b> <p>The number of colors used is equal to the chromatic number of \\(G\\).</p>"
          ],
          "correct_answer": [
            "<b>A.</b> <p>This procedure results in a proper vertex coloring of \\(G\\).</p>",
            "<b>B.</b> <p>The number of colors used is at most \\( \\Delta (G)+1\\).</p>"
          ],
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/399266/gate-cse-2023-question-45#a_list_title\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>Which of the properties hold for the adjacency matrix \\(A\\) of a simple undirected unweighted graph having \\(n\\) vertices? <br><br><strong>(GATE CSE 2022)</strong></p>",
          "type": "multiple",
          "options": [
            "<b>A.</b> <p>The diagonal entries of \\(A^2\\) are the degrees of the vertices of the graph.</p>",
            "<b>B.</b> <p>If the graph is connected, then none of the entries of \\(A^{n-1}+I_n\\)can be zero.</p>",
            "<b>C.</b> <p>If the sum of all the elements of \\(A\\) is at most 2(n-1), then the graph must be acyclic.</p>",
            "<b>D.</b> <p>If there is at least a 1 in each of A's rows and columns, then the graph must be connected.</p>"
          ],
          "correct_answer": [
            "<b>A.</b> <p>The diagonal entries of \\(A^2\\) are the degrees of the vertices of the graph.</p>"
          ],
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/371894/Gate-cse-2022-question-42#a_list_title\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>The following simple undirected graph is referred to as the Peterson graph.<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Graph_Theory\\q40_76105ee1.jpg\"><br>Which of the following statements is/are TRUE? <br><br><strong>(GATE CSE 2022)</strong></p>",
          "type": "multiple",
          "options": [
            "<b>A.</b> <p>The chromatic number of the graph is 3.</p>",
            "<b>B.</b> <p>The graph has a Hamiltonian path.</p>",
            "<b>C.</b> <p>The following graph is isomorphic to the Peterson graph.<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Graph_Theory\\a40_5106ff0c.jpg\"><br></p>",
            "<b>D.</b> <p>The size of the largest independent set of the given graph is 3. (A subset of vertices of a graph form an independent set if no two vertices of the subset are adjacent.)</p>"
          ],
          "correct_answer": [
            "<b>A.</b> <p>The chromatic number of the graph is 3.</p>",
            "<b>B.</b> <p>The graph has a Hamiltonian path.</p>",
            "<b>C.</b> <p>The following graph is isomorphic to the Peterson graph.<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Graph_Theory\\a40_5106ff0c.jpg\"><br></p>"
          ],
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/371896/Gate-cse-2022-question-40#a_list_title\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>Consider a simple undirected unweighted graph with at least three vertices. If \\(A\\) is the adjacency matrix of the graph, then the number of 3-cycles in the graph is given by the trace of <br><br><strong>(GATE CSE 2022)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(A^3\\)</p>",
            "<b>B.</b> <p>\\(A^3\\) divided by 2</p>",
            "<b>C.</b> <p>\\(A^3\\) divided by 3</p>",
            "<b>D.</b> <p>\\(A^3\\) divided by 6</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(A^3\\) divided by 6</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/371909/Gate-cse-2022-question-27#a_list_title\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>Consider a simple undirected graph of 10 vertices. If the graph is disconnected, then the maximum number of edges it can have is . <br><br><strong>(GATE CSE 2022)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "36",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/371916/Gate-cse-2022-question-20#a_list_title\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>In a directed acyclic graph with a source vertex s, the quality-score of a directed path is defined to be the product of the weights of the edges on the path. Further, for a vertex v other than s, the quality-score of v is defined to be the maximum among the quality-scores of all the paths from s to v. The quality-score of s is assumed to be 1.\n<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Graph_Theory\\q55_d153f985.jpg\"><br>\nThe sum of the quality-scores of all vertices on the graph shown above is ______ <br><br><strong>(GATE CSE 2021 SET-2)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "929",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/357482/gate-cse-2021-set-2-question-55#a_list_title\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>Consider the following directed graph:<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Graph_Theory\\q46_8d8f4d68.jpg\"><br>\nWhich of the following is/are correct about the graph? <br><br><strong>(GATE CSE 2021 SET-2)</strong></p>",
          "type": "multiple",
          "options": [
            "<b>A.</b> <p>The graph does not have a topological order</p>",
            "<b>B.</b> <p>A depth-first traversal starting at vertex S classifies three directed edges as back edges</p>",
            "<b>C.</b> <p>The graph does not have a strongly connected component</p>",
            "<b>D.</b> <p>For each pair of vertices u and v, there is a directed path from u to v</p>"
          ],
          "correct_answer": [
            "<b>A.</b> <p>The graph does not have a topological order</p>",
            "<b>B.</b> <p>A depth-first traversal starting at vertex S classifies three directed edges as back edges</p>"
          ],
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/357494/gate-cse-2021-set-2-question-46#a_list_title\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>An articulation point in a connected graph is a vertex such that removing the vertex and its incident edges disconnects the graph into two or more connected components.\n<br>\nLet T be a DFS tree obtained by doing DFS in a connected undirected graph G.\n<br>\nWhich of the following options is/are correct? <br><br><strong>(GATE CSE 2021 SET-1)</strong></p>",
          "type": "multiple",
          "options": [
            "<b>A.</b> <p>Root of T can never be an articulation point in G.</p>",
            "<b>B.</b> <p>Root of T is an articulation point in G if and only if it has 2 or more children.</p>",
            "<b>C.</b> <p>A leaf of T can be an articulation point in G.</p>",
            "<b>D.</b> <p>If u is an articulation point in G such that x is an ancestor of u in T and y is a descendent of u in T, then all paths from x to y in G must pass through u.</p>"
          ],
          "correct_answer": [
            "<b>B.</b> <p>Root of T is an articulation point in G if and only if it has 2 or more children.</p>"
          ],
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/357410/gate-cse-2021-set-1-question-41#a_list_title\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>G  is an undirected graph with vertex set {v1, v2, v3, v4, v5, v6, v7} and edge set {v1v2, v1v3, v1v4 ,v2v4, v2v5, v3v4, v4v5, v4v6, v5v6, v6v7 }. A breadth first search of the graph is performed with v1 as the root node. Which of the following is a tree edge? <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>v2v4</p>",
            "<b>B.</b> <p>v1v4</p>",
            "<b>C.</b> <p>v4v5</p>",
            "<b>D.</b> <p>v3v4</p>"
          ],
          "correct_answer": "<b>B.</b> <p>v1v4</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331350/isro2020-32\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>Graph G is obtained by adding vertex s to \\(K_{3,4}\\) and making s adjacent to every vertex of \\(K_{3,4}\\). The minimum number of colours required to edge-colour G is _______ <br><br><strong>(GATE CSE 2020)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "7",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/333179/gate2020-cs-52#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
