window.__examLoadCallback({
  "title": "Year_Wise - GATE_IT_2006",
  "duration": 180,
  "sections": [
    {
      "name": "GATE_IT_2006",
      "questions": [
        {
          "id": 1,
          "question": "<p>In a certain town, the probability that it will rain in the afternoon is known to be 0.6. Moreover, meteorological data indicates that if the temperature at noon is less than or equal to \\(25^{\\circ}C\\), the probability that it will rain in the afternoon is 0.4. The temperature at noon is equally likely to be above \\(25^{\\circ}C\\), or at/below \\(25^{\\circ}C\\). What is the probability that it will rain in the afternoon on a day when the temperature at noon is above \\(25^{\\circ}C\\)?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0.4</p>",
            "<b>B.</b> <p>0.6</p>",
            "<b>C.</b> <p>0.8</p>",
            "<b>D.</b> <p>0.9</p>"
          ],
          "correct_answer": "<b>C.</b> <p>0.8</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3538/gate2006-it-1\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>For the set N of natural numbers and a binary operation \\(f : N \\times N \\to N\\), an element \\(z \\in N\\) is called an identity for f, if f (a, z) = a = f(z, a), for all \\(a \\in N\\). Which of the following binary operations have an identity?<br>\ni. \\(f (x, y) = x + y - 3\\)<br>\nii. \\(f (x, y) = \\max(x, y)\\)<br>\niii. \\(f (x, y) = x^y\\)<br></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>I and II only</p>",
            "<b>B.</b> <p>II and III only</p>",
            "<b>C.</b> <p>I and III only</p>",
            "<b>D.</b> <p>None of these</p>"
          ],
          "correct_answer": "<b>A.</b> <p>I and II only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3539/gate2006-it-2\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>In the automaton below, s is the start state and t is the only final state.<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\yearWiseImages\\GATE_IT_2006\\q3_da00c87d.jpg\"><br>\nConsider the strings \\(u = abbaba, v = bab, \\text{ and } w = aabb\\). Which of the following statements is true?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>The automaton accepts u and v but not w</p>",
            "<b>B.</b> <p>The automaton accepts each of u, v, and w</p>",
            "<b>C.</b> <p>The automaton rejects each of u, v, and w</p>",
            "<b>D.</b> <p>The automaton accepts u but rejects v and w</p>"
          ],
          "correct_answer": "<b>D.</b> <p>The automaton accepts u but rejects v and w</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3542/gate2006-it-3\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>In the context-free grammar below, S is the start symbol, a and b are terminals, and\\(\\epsilon\\) denotes the empty string <br>\n\\(S \\rightarrow aSa \\mid bSb \\mid a \\mid b \\mid \\epsilon\\)<br>\nWhich of the following strings is NOT generated by the grammar?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>aaaa</p>",
            "<b>B.</b> <p>baba</p>",
            "<b>C.</b> <p>abba</p>",
            "<b>D.</b> <p>babaaabab</p>"
          ],
          "correct_answer": "<b>B.</b> <p>baba</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3543/gate2006-it-4\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Which regular expression best describes the language accepted by the non-deterministic automaton below?\n<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\yearWiseImages\\GATE_IT_2006\\q5_1a0e53b1.jpg\"><br></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((a + b)^* \\ a(a + b)b\\)</p>",
            "<b>B.</b> <p>\\((abb)^*\\)</p>",
            "<b>C.</b> <p>\\((a + b)^* \\ a(a + b)^* \\ b(a + b)^*\\)</p>",
            "<b>D.</b> <p>\\((a + b)^*\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\((a + b)^* \\ a(a + b)b\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3544/gate2006-it-5\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Given a boolean function f \\((x_1, x_2, \\ldots, x_n)\\), which of the following equations is NOT true?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(f (x_1, x_2, \\ldots, x_n) = x_1'f(x_1, x_2, \\ldots, x_n) + x_1f(x_1, x_2, \\ldots, x_n)\\)</p>",
            "<b>B.</b> <p>\\(f (x_1, x_2, \\ldots, x_n) = x_2f(x_1, x_2, \\ldots , x_n) + x_2'f(x_1, x_2, \\ldots ,x_n)\\)</p>",
            "<b>C.</b> <p>\\(f (x_1, x_2, \\ldots, x_n) = x_n'f(x_1, x_2, \\ldots, 0) + x_nf(x_1, x_2, \\ldots,1)\\)</p>",
            "<b>D.</b> <p>\\(f (x_1, x_2, \\ldots , x_n) = f(0, x_2,  \\ldots , x_n) + f(1, x_2, \\ldots, x_n)\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(f (x_1, x_2, \\ldots , x_n) = f(0, x_2,  \\ldots , x_n) + f(1, x_2, \\ldots, x_n)\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3545/gate2006-it-6\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>The addition of 4-bit, two's complement, binary numbers 1101 and 0100 results in</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0001 and an overflow</p>",
            "<b>B.</b> <p>1001 and no overflow</p>",
            "<b>C.</b> <p>0001 and no overflow</p>",
            "<b>D.</b> <p>1001 and an overflow</p>"
          ],
          "correct_answer": "<b>C.</b> <p>0001 and no overflow</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3546/gate2006-it-7-isro2009-41\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>Which of the following DMA transfer modes and interrupt handling mechanisms will enable the highest I/O band-width?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Transparent DMA and Polling interrupts</p>",
            "<b>B.</b> <p>Cycle-stealing and Vectored interrupts</p>",
            "<b>C.</b> <p>Block transfer and Vectored interrupts</p>",
            "<b>D.</b> <p>Block transfer and Polling interrupts</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Block transfer and Vectored interrupts</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3547/gate2006-it-8\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>In a binary tree, the number of internal nodes of degree 1 is 5, and the number of internal nodes of degree 2 is 10. The number of leaf nodes in the binary tree is</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>10</p>",
            "<b>B.</b> <p>11</p>",
            "<b>C.</b> <p>12</p>",
            "<b>D.</b> <p>15</p>"
          ],
          "correct_answer": "<b>B.</b> <p>11</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3548/gate2006-it-9\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>A problem in NP is NP-complete if</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>it can be reduced to the 3-SAT problem in polynomial time</p>",
            "<b>B.</b> <p>the 3-SAT problem can be reduced to it in polynomial time</p>",
            "<b>C.</b> <p>it can be reduced to any other problem in NP in polynomial time</p>",
            "<b>D.</b> <p>some problem in NP can be reduced to it in polynomial time</p>"
          ],
          "correct_answer": "<b>B.</b> <p>the 3-SAT problem can be reduced to it in polynomial time</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3549/gate2006-it-10\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>If all the edge weights of an undirected graph are positive, then any subset of edges that connects all the vertices and has minimum total weight is a</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Hamiltonian cycle</p>",
            "<b>B.</b> <p>grid</p>",
            "<b>C.</b> <p>hypercube</p>",
            "<b>D.</b> <p>tree</p>"
          ],
          "correct_answer": "<b>D.</b> <p>tree</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3550/gate2006-it-11\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>In the working-set strategy, which of the following is done by the operating system to prevent thrashing?<br><br>\nI. It initiates another process if there are enough extra frames.<br>\nII. It selects a process to suspend if the sum of the sizes of the working-sets exceeds the total number of available frames.</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>I only</p>",
            "<b>B.</b> <p>II only</p>",
            "<b>C.</b> <p>Neither I nor II</p>",
            "<b>D.</b> <p>Both I and II</p>"
          ],
          "correct_answer": "<b>D.</b> <p>Both I and II</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3551/gate2006-it-12\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>The process state transition diagram of an operating system is as given below.\nWhich of the following must be FALSE about the above operating system?<br><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\yearWiseImages\\GATE_IT_2006\\q13_276c7f2d.jpg\"><br></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>It is a multiprogrammed operating system</p>",
            "<b>B.</b> <p>It uses preemptive scheduling</p>",
            "<b>C.</b> <p>It uses non-preemptive scheduling</p>",
            "<b>D.</b> <p>It is a multi-user operating system</p>"
          ],
          "correct_answer": "<b>B.</b> <p>It uses preemptive scheduling</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3552/gate2006-it-13\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>Consider the relations r1(P, Q, R) and r2(R, S, T) with primary keys P and R respectively. The relation \\(r_{1}\\) contains 2000 tuples and \\(r_{2}\\) contains 2500 tuples. The maximum size of the join \\(r_{1} \\Join r_{2}\\) is :</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>2000</p>",
            "<b>B.</b> <p>2500</p>",
            "<b>C.</b> <p>4500</p>",
            "<b>D.</b> <p>5000</p>"
          ],
          "correct_answer": "<b>A.</b> <p>2000</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3553/gate2006-it-14\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>Which of the following relational query languages have the same expressive power?<br>\nI.   Relational algebra<br>\nII.  Tuple relational calculus restricted to safe expressions<br>\nIII. Domain relational calculus restricted to safe expressions</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>II and III only</p>",
            "<b>B.</b> <p>I and II only</p>",
            "<b>C.</b> <p>I and III only</p>",
            "<b>D.</b> <p>I, II and III</p>"
          ],
          "correct_answer": "<b>D.</b> <p>I, II and III</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3554/gate2006-it-15\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 16,
          "question": "<p>The cyclomatic complexity of the flow graph of a program provides</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>an upper bound for the number of tests that must be conducted to ensure that all statements have been executed at most once</p>",
            "<b>B.</b> <p>a lower bound for the number of tests that must be conducted to ensure that all statements have been executed at most once</p>",
            "<b>C.</b> <p>an upper bound for the number of tests that must be conducted to ensure that all statements have been executed at least once</p>",
            "<b>D.</b> <p>a lower bound for the number of tests that must be conducted to ensure that all statements have been executed at least once</p>"
          ],
          "correct_answer": "<b>C.</b> <p>an upper bound for the number of tests that must be conducted to ensure that all statements have been executed at least once</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3555/gate2006-it-16\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 17,
          "question": "<p>With respect to software testing, consider a flow graph G with one connected component. Let E be the number of edges, N be the number of nodes, and P be the number of predicate nodes of G. Consider the following four expressions:<br><br>\nI. E - N + P<br>\nII. E - N + 2<br>\nIII. P +  2<br>\nIV. P + 1<br><br>\nThe cyclomatic complexity of G is given by</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>I or III</p>",
            "<b>B.</b> <p>II or III</p>",
            "<b>C.</b> <p>II or IV</p>",
            "<b>D.</b> <p>I or IV</p>"
          ],
          "correct_answer": "<b>C.</b> <p>II or IV</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3556/gate2006-it-17\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 18,
          "question": "<p>HELO and PORT, respectively, are commands from the protocols:</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>FTP and HTTP</p>",
            "<b>B.</b> <p>TELNET and POP3</p>",
            "<b>C.</b> <p>HTTP and TELNET</p>",
            "<b>D.</b> <p>SMTP and FTP</p>"
          ],
          "correct_answer": "<b>D.</b> <p>SMTP and FTP</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3557/gate2006-it-18\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 19,
          "question": "<p>Which of the following statements is TRUE?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Both Ethernet frame and IP packet include checksum fields</p>",
            "<b>B.</b> <p>Ethernet frame includes a checksum field and IP packet includes a CRC field</p>",
            "<b>C.</b> <p>Ethernet frame includes a CRC field and IP packet includes a checksum field</p>",
            "<b>D.</b> <p>Both Ethernet frame and IP packet include CRC fields</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Ethernet frame includes a CRC field and IP packet includes a checksum field</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3558/gate2006-it-19\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 20,
          "question": "<p>Which of the following statement(s) is TRUE?<br><br>\nI.  A hash function takes a message of arbitrary length and generates a fixed length code.<br>\nII. A hash function takes a message of fixed length and generates a code of variable length.<br>\nIII. A hash function may give the same hash value for distinct messages.</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>I only</p>",
            "<b>B.</b> <p>II and III only</p>",
            "<b>C.</b> <p>I and III only</p>",
            "<b>D.</b> <p>II only</p>"
          ],
          "correct_answer": "<b>C.</b> <p>I and III only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3559/gate2006-it-20\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 21,
          "question": "<p>Consider the following first order logic formula in which R is a binary relation symbol.<br>\n\\(\\forall x \\forall y(R(x, y) \\Longrightarrow R(y, x))\\),<br>The formula is</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>satisfiable and valid</p>",
            "<b>B.</b> <p>satisfiable and so is its negation</p>",
            "<b>C.</b> <p>unsatisfiable but its negation is valid</p>",
            "<b>D.</b> <p>satisfiable but its negation is unsatisfiable</p>"
          ],
          "correct_answer": "<b>B.</b> <p>satisfiable and so is its negation</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3560/gate2006-it-21\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 22,
          "question": "<p>When a coin is tossed, the probability of getting a Head is p, 0 &lt; p &lt; 1. Let N be the random variable denoting the number of tosses till the first Head appears, including the toss where the Head appears. Assuming that successive tosses are independent, the expected value of N is</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\dfrac{1}{p}\\)</p>",
            "<b>B.</b> <p>\\(\\dfrac{1}{(1 - p)}\\)</p>",
            "<b>C.</b> <p>\\(\\dfrac{1}{p^{2}}\\)</p>",
            "<b>D.</b> <p>\\(\\dfrac{1}{(1 - p^{2})}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(\\dfrac{1}{p}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3561/gate2006-it-22\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 23,
          "question": "<p>Let P, Q and R be sets, let \\(\\triangle \\) denote the symmetric difference operator defined as \\(P\\triangle Q=(P \\cup Q) - (P \\cap Q)\\). Using Venn diagrams, determine which of the following is/are TRUE?<br><br>\nI. \\(P \\Delta(Q \\cap R)=(P \\Delta Q) \\cap(P \\Delta R)\\)<br>\nII. \\(P \\cap(Q \\cap R)=(P \\cap Q) \\Delta(P \\Delta R)\\)</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>I only</p>",
            "<b>B.</b> <p>II only</p>",
            "<b>C.</b> <p>Neither I nor II</p>",
            "<b>D.</b> <p>Both I and II</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Neither I nor II</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3562/gate2006-it-23\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 24,
          "question": "<p>What is the cardinality of the set of integers X defined below?<br>\n\\(X=\\{n \\mid 1 \\leq n \\leq 123\\), n is not divisible by either 2, 3 or 5}</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>28</p>",
            "<b>B.</b> <p>33</p>",
            "<b>C.</b> <p>37</p>",
            "<b>D.</b> <p>44</p>"
          ],
          "correct_answer": "<b>B.</b> <p>33</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3563/gate2006-it-24\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 25,
          "question": "<p>Consider the undirected graph G defined as follows. The vertices of G are bit strings of length n. We have an edge between vertex u and vertex v if and only if u and v differ in exactly one bit position (in other words, v can be obtained from u by flipping a single bit). The ratio of the chromatic number of G to the diameter of G is,</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\frac{1}{\\left(2^{n-1}\\right)}\\)</p>",
            "<b>B.</b> <p>\\(\\left(\\frac{1}{n}\\right)\\)</p>",
            "<b>C.</b> <p>\\(\\left(\\frac{2}{n}\\right)\\)</p>",
            "<b>D.</b> <p>\\(\\left(\\frac{3}{n}\\right)\\)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(\\left(\\frac{2}{n}\\right)\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3564/gate2006-it-25\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 26,
          "question": "<p>What are the eigenvalues of the matrix P given below <br>\\(P= \\begin{pmatrix} a &amp;1 &amp;0 \\\\ 1&amp; a&amp; 1\\\\ 0&amp;1 &amp;a \\end{pmatrix}\\)</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(a, a -\\sqrt2, a + \\sqrt2\\)</p>",
            "<b>B.</b> <p>a, a, a</p>",
            "<b>C.</b> <p>0, a, 2a</p>",
            "<b>D.</b> <p>-a, 2a, 2a</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(a, a -\\sqrt2, a + \\sqrt2\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3565/gate2006-it-26\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 27,
          "question": "<p>Match the following iterative methods for solving algebraic equations and their orders of convergence.<br>\\(\\begin{array}{|l|l|l|l|} \\hline &amp; \\text { Method } &amp; &amp; \\text { Order of Convergence } \\\\ \\hline \\text { 1. } &amp; \\text { Bisection } &amp; \\text { P. } &amp; \\text { 2 or more } \\\\ \\hline \\text { 2. } &amp; \\text { Newton-Raphson } &amp; \\text { Q. } &amp; 1.62 \\\\ \\hline \\text { 3. } &amp; \\text { Secant } &amp; \\text { R. } &amp; 1 \\\\ \\hline \\text { 4. } &amp; \\text { Regula falsi } &amp; \\text { S. } &amp; 1 \\text { bit per iteration } \\\\ \\hline \\end{array}\\)</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>I-R, II-S, III-P, IV-Q</p>",
            "<b>B.</b> <p>I-S, II-R, III-Q, IV-P</p>",
            "<b>C.</b> <p>I-S, II-Q, III-R, IV-P</p>",
            "<b>D.</b> <p>I-S, II-P, III-Q, IV-R</p>"
          ],
          "correct_answer": "<b>D.</b> <p>I-S, II-P, III-Q, IV-R</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3566/gate2006-it-27\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 28,
          "question": "<p>The following definite integral evaluates to <br>\\(\\int_{-\\infty}^{0} e^ {-\\left(\\frac{x^2}{20} \\right )}dx\\)</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\frac{1}{2}\\)</p>",
            "<b>B.</b> <p>\\(\\pi \\sqrt{10}\\)</p>",
            "<b>C.</b> <p>\\(\\sqrt{10}\\)</p>",
            "<b>D.</b> <p>\\(\\pi\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(\\frac{1}{2}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3567/gate2006-it-28\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 29,
          "question": "<p>Consider the regular grammar below <br>\n\\(S \\rightarrow bS \\mid aA \\mid \\epsilon\\)<br>\n\\(A \\rightarrow aS \\mid bA\\)<br>\nThe Myhill-Nerode equivalence classes for the language generated by the grammar are</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\{w \\in (a + b)^* \\mid \\#a(w) \\text{ is even) and} \\{w \\in (a + b)^* \\mid \\#a(w) \\text{ is odd}\\}\\)</p>",
            "<b>B.</b> <p>\\(\\{w \\in (a + b)^* \\mid \\#a(w) \\text{ is even) and} \\{w \\in (a + b)^* \\mid \\#b(w) \\text{ is odd}\\}\\)</p>",
            "<b>C.</b> <p>\\(\\{w \\in (a + b)^* \\mid \\#a(w) = \\#b(w) \\text{and }\\{w \\in (a + b)^* \\mid \\#a(w) \\neq \\#b(w)\\}\\)</p>",
            "<b>D.</b> <p>\\(\\{\\epsilon\\},\\{wa \\mid w \\in (a + b)^* \\text{and} \\{wb \\mid w \\in (a + b)^*\\}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(\\{w \\in (a + b)^* \\mid \\#a(w) \\text{ is even) and} \\{w \\in (a + b)^* \\mid \\#a(w) \\text{ is odd}\\}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3568/gate2006-it-29\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 30,
          "question": "<p>Which of the following statements about regular languages is NOT true ?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Every language has a regular superset</p>",
            "<b>B.</b> <p>Every language has a regular subset</p>",
            "<b>C.</b> <p>Every subset of a regular language is regular</p>",
            "<b>D.</b> <p>Every subset of a finite language is regular</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Every subset of a regular language is regular</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3569/gate2006-it-30\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 31,
          "question": "<p>Which of the following languages is accepted by a non-deterministic pushdown automaton (PDA) but NOT by a deterministic PDA?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\{a^nb^nc^n \\mid n \\geq 0\\}\\)</p>",
            "<b>B.</b> <p>\\(\\{a^lb^mc^n \\mid l \\neq m \\text{ or } m \\neq n\\}\\)</p>",
            "<b>C.</b> <p>\\(\\{a^nb^n \\mid n \\geq 0\\}\\)</p>",
            "<b>D.</b> <p>\\(\\{a^mb^n \\mid m, n \\geq 0\\}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(\\{a^lb^mc^n \\mid l \\neq m \\text{ or } m \\neq n\\}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3570/gate2006-it-31\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 32,
          "question": "<p>Let L be a context-free language and M a regular language. Then the language \\(L \\cap M\\) is</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>always regular</p>",
            "<b>B.</b> <p>never regular</p>",
            "<b>C.</b> <p>always a deterministic context-free language</p>",
            "<b>D.</b> <p>always a context-free language</p>"
          ],
          "correct_answer": "<b>D.</b> <p>always a context-free language</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3571/gate2006-it-32\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 33,
          "question": "<p>Consider the pushdown automaton (PDA) below which runs over the input alphabet (a, b, c). It has the stack alphabet \\(\\{Z_0, X\\}\\) where \\(Z_0\\) is the bottom-of-stack marker. The set of states of the PDA is (s, t, u, f} where s is the start state and f is the final state. The PDA accepts by final state. The transitions of the PDA given below are depicted in a standard manner. For example, the transition \\((s, b, X) \\rightarrow (t, XZ_0)\\) means that if the PDA is in state s and the symbol on the top of the stack is X, then it can read b from the input and move to state t after popping the top of stack and pushing the symbols \\(Z_0\\) and X (in that order) on the stack. <br>\n\\((s, a, Z_0) \\rightarrow (s, XXZ_0)\\)<br>\n\\((s, \\epsilon, Z_0) \\rightarrow (f, \\epsilon)\\)<br>\n\\((s, a, X) \\rightarrow (s, XXX)\\)<br>\n\\((s, b, X) \\rightarrow (t, \\epsilon)\\)<br>\n\\((t, b, X) \\rightarrow (t,\\epsilon)\\)<br>\n\\((t, c, X) \\rightarrow (u, \\epsilon)\\)<br>\n\\((u, c, X) \\rightarrow (u, \\epsilon)\\)<br>\n\\((u, \\epsilon, Z_0) \\rightarrow (f, \\epsilon)\\)<br>\nThe language accepted by the PDA is</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\{a^lb^mc^n \\mid l = m = n\\}\\)</p>",
            "<b>B.</b> <p>\\(\\{a^l b^m c^n \\mid l = m\\}\\)</p>",
            "<b>C.</b> <p>\\(\\{a^lb^mc^n \\mid 2l = m + n\\}\\)</p>",
            "<b>D.</b> <p>\\(\\{a^lb^mc^n \\mid m = n\\}\\)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(\\{a^lb^mc^n \\mid 2l = m + n\\}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3572/gate2006-it-33\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 34,
          "question": "<p>In the context-free grammar below, S is the start symbol, a and b are terminals, and \\(\\epsilon\\) denotes the empty string.<br>\n\\(S \\to aSAb \\mid \\epsilon\\)<br>\n\\(A \\to bA \\mid \\epsilon\\)<br>\nThe grammar generates the language</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(((a + b)^* b)\\)</p>",
            "<b>B.</b> <p>\\(\\{a^mb^n \\mid m \\leq n\\}\\)</p>",
            "<b>C.</b> <p>\\(\\{a^mb^n \\mid m = n)\\)</p>",
            "<b>D.</b> <p>\\(a^* b^*\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(\\{a^mb^n \\mid m \\leq n\\}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3573/gate2006-it-34\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 35,
          "question": "<p>The boolean function for a combinational circuit with four inputs is represented by the following Karnaugh map.<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\yearWiseImages\\GATE_IT_2006\\q35_73871bb5.jpg\"><br>Which of the product terms given below is an essential prime implicant of the function?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>QRS</p>",
            "<b>B.</b> <p>PQS</p>",
            "<b>C.</b> <p>PQ'S'</p>",
            "<b>D.</b> <p>Q'S'</p>"
          ],
          "correct_answer": "<b>D.</b> <p>Q'S'</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3574/gate2006-it-35\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 36,
          "question": "<p>The majority function is a Boolean function f(x,y,z) that takes the value 1 whenever a majority of the variables x,y,z are 1. In the circuit diagram for the majority function shown below, the logic gates for the boxes labeled P and Q are, respectively, <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\yearWiseImages\\GATE_IT_2006\\q36_3b292458.jpg\"><br></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>XOR, AND</p>",
            "<b>B.</b> <p>XOR, XOR</p>",
            "<b>C.</b> <p>OR, OR</p>",
            "<b>D.</b> <p>OR, AND</p>"
          ],
          "correct_answer": "<b>D.</b> <p>OR, AND</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3575/gate2006-it-36\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 37,
          "question": "<p>For a state machine with the following state diagram the expression for the next state \\(S^+\\) in terms of the current state S and the input variables x and y is <br><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\yearWiseImages\\GATE_IT_2006\\q37_9146a2c1.jpg\"><br></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(S^+ = S' . y' + S . x\\)</p>",
            "<b>B.</b> <p>\\(S^+ = S. x . y' + S' . y . x'\\)</p>",
            "<b>C.</b> <p>\\(S^+ = x . y'\\)</p>",
            "<b>D.</b> <p>\\(S^+ = S' . y + S . x'\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(S^+ = S' . y' + S . x\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3576/gate2006-it-37\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 38,
          "question": "<p>When multiplicand Y is multiplied by multiplier \\(X = x_{n - 1}x_{n-2} \\dots x_0\\) using bit-pair recoding in Booth's algorithm, partial products are generated according to the following table.<br>\n\\(\\begin{array}{c|ccc|c}\\hline \\textbf{Row}&amp; \\bf{ x_{i+1}}&amp;\\bf { x_i}&amp;\\bf{ x_{i-1}}&amp; \\textbf{Partial Product} \\\\\\hline 1&amp;0&amp;0&amp;0&amp;0 \\\\ 2&amp;0&amp;0&amp;1&amp; \\text{Y} \\\\ 3&amp;0&amp;1&amp;0&amp; \\text{Y} \\\\ 4&amp;0&amp;1&amp;1&amp; \\text{2Y} \\\\ 5&amp;1&amp;0&amp;0&amp; \\text{?} \\\\ 6&amp;1&amp;0&amp;1&amp; \\text{-Y} \\\\ 7&amp;1&amp;1&amp;0&amp; \\text{-Y} \\\\ 8&amp;1&amp;1&amp;1&amp; \\text{?} \\\\ \\hline \\end{array}\\)<br>\nThe partial products for rows 5 and 8 are</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>2Y and Y</p>",
            "<b>B.</b> <p>-2Y and 2Y</p>",
            "<b>C.</b> <p>-2Y and 0</p>",
            "<b>D.</b> <p>0 and Y</p>"
          ],
          "correct_answer": "<b>C.</b> <p>-2Y and 0</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3577/gate2006-it-38\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 39,
          "question": "<p>Which of the following statements about relative addressing mode is FALSE?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>It enables reduced instruction size</p>",
            "<b>B.</b> <p>It allows indexing of array element with same instruction</p>",
            "<b>C.</b> <p>It enables easy relocation of data</p>",
            "<b>D.</b> <p>It enables faster address calculation than absolute addressing</p>"
          ],
          "correct_answer": "<b>D.</b> <p>It enables faster address calculation than absolute addressing</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3578/gate2006-it-39-isro2009-42\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 40,
          "question": "<p>The memory locations 1000,1001 and 1020 have data values 18,1 and 16 respectively before the following program is executed.<br><br>\n\\(\\begin{array}{llll} \\text{MOVI} &amp; \\text{$R_s, 1$} &amp;&amp; \\text{; Move immediate} \\\\ \\text{LOAD} &amp; \\text{$R_d, 1000(R_s)$} &amp;&amp; \\text{; Load from memory}\\\\ \\text{ADDI} &amp; \\text{$ R_d, 1000$} &amp;&amp; \\text{; Add immediate}\\\\ \\text{STOREI} &amp; \\text{$0(R_d), 20$} &amp;&amp; \\text{; Store immediate} \\end{array}\\)<br><br>\nWhich of the statements below is TRUE after the program is executed ?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Memory location 1000 has value 20</p>",
            "<b>B.</b> <p>Memory location 1020 has value 20</p>",
            "<b>C.</b> <p>Memory location 1021 has value 20</p>",
            "<b>D.</b> <p>Memory location 1001 has value 20</p>"
          ],
          "correct_answer": "<b>D.</b> <p>Memory location 1001 has value 20</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3581/gate2006-it-40\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 41,
          "question": "<p>The data path shown in the figure computes the number of 1s in the 32-bit input word corresponding to an unsigned even integer stored in the shift register. <br>\nThe unsigned counter, initially zero, is incremented if the most significant bit of the shift register is 1. <br><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\yearWiseImages\\GATE_IT_2006\\q41_0ce010b4.jpg\"><br>\nThe microprogram for the control is shown in the table below with missing control words for microinstructions \\(I_1, I_2, \\ldots I_n\\). <br>\n\\(\\begin{array}{|l|c|c|c|} \\hline \\textbf {Microinstruction} &amp; \\textbf{Reset Counter}&amp; \\textbf{Shift left} &amp; \\textbf{Load output} \\\\\\hline \\text{BEGIN} &amp; \\text{1} &amp; \\text{0} &amp; \\text{0} \\\\\\hline \\text{I1}&amp; \\text{$?$} &amp; \\text{$?$} &amp; \\text{$?$} \\\\\\hline \\text{:} &amp; \\text{:} &amp; \\text{:} &amp; \\text{:} \\\\\\hline \\text{In} &amp; \\text{$?$} &amp; \\text{$?$} &amp; \\text{$?$} \\\\\\hline \\text{END} &amp; \\text{0} &amp; \\text{0} &amp; \\text{1} \\\\\\hline \\end{array}\\)<br>\nThe counter width (k), the number of missing microinstructions (n), and the control word for microinstructions \\(I_1, I_2, \\ldots I_n\\) are, respectively,</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>32,5,010</p>",
            "<b>B.</b> <p>5,32,010</p>",
            "<b>C.</b> <p>5,31,011</p>",
            "<b>D.</b> <p>5,31,010</p>"
          ],
          "correct_answer": "<b>D.</b> <p>5,31,010</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3584/gate2006-it-41\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 42,
          "question": "<p>A cache line is 64 bytes. The main memory has latency 32 ns and bandwidth 1 GBytes/s. The time required to fetch the entire cache line from the main memory is:</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>32 ns</p>",
            "<b>B.</b> <p>64 ns</p>",
            "<b>C.</b> <p>96 ns</p>",
            "<b>D.</b> <p>128 ns</p>"
          ],
          "correct_answer": "<b>C.</b> <p>96 ns</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3585/gate2006-it-42\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 43,
          "question": "<p>A computer system has a level-1 instruction cache (1-cache), a level-1 data cache (D-cache) and a level-2 cache (L2-cache) with the following specifications: <br>\\(\\begin{array}{|l|c|c|c|} \\hline \\text {} &amp; \\textbf{Capacity }&amp; \\textbf{Mapping Method} &amp; \\textbf{Block Size}\\\\\\hline \\text{$I$-Cache} &amp; \\text{$4K$ words}&amp; \\text{Direct mapping} &amp; \\text{$4$ words} \\\\\\hline \\text{$D$-Cache} &amp; \\text{$4K$ words}&amp; \\text{$2$ -way set associative mapping} &amp; \\text{$4$ words}\\\\\\hline \\text{$L2$-Cache} &amp; \\text{$64K$ words}&amp; \\text{$4$-way set associative mapping} &amp; \\text{$16$ words} \\\\\\hline \\end{array}\\)\n<br>\nThe length of the physical address of a word in the main memory is 30 bits. The capacity of the tag memory in the I-cache, D-cache and L2-cache is, respectively,</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>1 K x 18-bit, 1 K x 19-bit, 4 K x 16-bit</p>",
            "<b>B.</b> <p>1 K x 16-bit, 1 K x 19-bit, 4 K x 18-bit</p>",
            "<b>C.</b> <p>1 K x 16-bit, 512 x 18-bit, 1 K x 16-bit</p>",
            "<b>D.</b> <p>1 K x 18-bit, 512 x 18-bit, 1 K x 18-bit</p>"
          ],
          "correct_answer": "<b>A.</b> <p>1 K x 18-bit, 1 K x 19-bit, 4 K x 16-bit</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3586/gate2006-it-43\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 44,
          "question": "<p>Which of the following sequences of array elements forms a heap?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>{23,17,14,6,13,10,1,12,7,5}</p>",
            "<b>B.</b> <p>{23,17,14,6,13,10,1,5,7,12}</p>",
            "<b>C.</b> <p>{23,17,14,7,13,10,1,5,6,12}</p>",
            "<b>D.</b> <p>{23,17,14,7,13,10,1,12,5,7}</p>"
          ],
          "correct_answer": "<b>C.</b> <p>{23,17,14,7,13,10,1,5,6,12}</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3587/gate2006-it-44\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 45,
          "question": "<p>Suppose that we have numbers between 1 and 100 in a binary search tree and want to search for the number 55. Which of the following sequences CANNOT be the sequence of nodes examined?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>{10,75,64,43,60,57,55}</p>",
            "<b>B.</b> <p>{90,12,68,34,62,45,55}</p>",
            "<b>C.</b> <p>{9,85,47,68,43,57,55}</p>",
            "<b>D.</b> <p>{79,14,72,56,16,53,55}</p>"
          ],
          "correct_answer": "<b>C.</b> <p>{9,85,47,68,43,57,55}</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3588/gate2006-it-45\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 46,
          "question": "<p>Which of the following is the correct decomposition of the directed graph given below into its strongly connected components?<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\yearWiseImages\\GATE_IT_2006\\q46_ea67eee2.jpg\"><br></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\left \\{ P, Q, R, S \\right \\}, \\left \\{ T \\right \\},\\left \\{ U \\right \\}, \\left \\{ V \\right \\}\\)</p>",
            "<b>B.</b> <p>\\(\\left \\{ P,Q, R, S, T, V \\right \\}, \\left \\{ U \\right \\}\\)</p>",
            "<b>C.</b> <p>\\(\\left \\{ P, Q, S, T, V \\right \\}, \\left \\{ R \\right \\},\\left \\{ U \\right \\}\\)</p>",
            "<b>D.</b> <p>\\(\\left \\{ P, Q, R, S, T, U, V \\right \\}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(\\left \\{ P,Q, R, S, T, V \\right \\}, \\left \\{ U \\right \\}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3589/gate2006-it-46\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 47,
          "question": "<p>Consider the depth-first-search of an undirected graph with 3 vertices P, Q, and R. Let discovery time d(u) represent the time instant when the vertex u is first visited, and finish time f(u) represent the time instant when the vertex u is last visited. Given that<br>\n\\(\\begin{array}{l|l}\\hline \\text{$d(P) = 5$ units } &amp; \\text{ $f(P) = 12$ units } \\\\\\hline \\text{$d(Q) = 6$ units} &amp; \\text{ $f(Q) = 10$ units} \\\\\\hline \\text{$d(R) = 14$ unit} &amp; \\text{$f(R) = 18$ units} \\\\\\hline \\end{array}\\)<br>\nWhich one of the following statements is TRUE about the graph?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>There is only one connected component</p>",
            "<b>B.</b> <p>There are two connected components, and P and R are connected</p>",
            "<b>C.</b> <p>There are two connected components, and Q and R are connected</p>",
            "<b>D.</b> <p>There are two connected components, and P and Q are connected</p>"
          ],
          "correct_answer": "<b>D.</b> <p>There are two connected components, and P and Q are connected</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3590/gate2006-it-47\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 48,
          "question": "<p>The characters a to h have the set of frequencies based on the first 8 Fibonacci numbers as follows <br>\na:1, b:1, c:2, d:3, e:5, f:8, g:13, h:21<br>\nA Huffman code is used to represent the characters. What is the sequence of characters corresponding to the following code?<br>\n110111100111010</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>fdheg</p>",
            "<b>B.</b> <p>ecgdf</p>",
            "<b>C.</b> <p>dchfg</p>",
            "<b>D.</b> <p>fehdg</p>"
          ],
          "correct_answer": "<b>A.</b> <p>fdheg</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3591/gate2006-it-48\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 49,
          "question": "<p>Which one of the choices given below would be printed when the following program is executed ?<br><pre><code> #include &lt; stdio.h &gt;\nstruct test {\n               int i;\n               char *c;\n}st[] = {5, \"become\", 4, \"better\", 6, \"jungle\", 8, \"ancestor\", 7, \"brother\"};\nmain ()\n{ \n    struct test *p = st;\n    p += 1;\n    ++p -&gt; c;\n    printf(\"%s,\", p++ -&gt; c);\n    printf(\"%c,\", *++p -&gt; c);\n    printf(\"%d,\", p[0].i);\n    printf(\"%s \\n\", p -&gt; c);\n}</code></pre></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>jungle, n, 8, nclastor</p>",
            "<b>B.</b> <p>etter, u, 6, ungle</p>",
            "<b>C.</b> <p>cetter, k, 6, jungle</p>",
            "<b>D.</b> <p>etter, u, 8, ncestor</p>"
          ],
          "correct_answer": "<b>B.</b> <p>etter, u, 6, ungle</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3592/gate2006-it-49\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 50,
          "question": "<p>Which one of the choices given below would be printed when the following program is executed?<br><pre><code>#include &lt; stdio.h &gt;\nvoid swap (int *x, int *y)\n{\n    static int *temp;\n    temp = x;\n    x = y;\n    y = temp;\n}\nvoid printab ()\n{\n    static int i, a = -3, b = -6;\n    i = 0;\n    while (i &lt;= 4)\n    {\n        if ((i++)%2 == 1) continue;\n        a = a + i;\n        b = b + i;\n    }\n    swap (&amp;a, &amp;b);\n    printf(\"a =  %d, b = %d\\n\", a, b);\n}\nmain()\n{\n    printab();\n    printab();\n} </code></pre></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>a = 0, b = 3\na = 0, b = 3</p>",
            "<b>B.</b> <p>a = 3, b = 0\na = 12, b = 9</p>",
            "<b>C.</b> <p>a = 3, b = 6\na = 3, b = 6</p>",
            "<b>D.</b> <p>a = 6, b = 3\na = 15, b = 12</p>"
          ],
          "correct_answer": "<b>D.</b> <p>a = 6, b = 3\na = 15, b = 12</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3593/gate2006-it-50\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 51,
          "question": "<p>Which one of the choices given below would be printed when the following program is executed?<br><pre><code> #include &lt; stdio.h &gt;\nint a1[] = {6, 7, 8, 18, 34, 67};\nint a2[] = {23, 56, 28, 29};\nint a3[] = {-12, 27, -31};\nint *x[] = {a1, a2, a3};\nvoid print(int *a[])\n{\n    printf(\"%d,\", a[0][2]);\n    printf(\"%d,\", *a[2]);\n    printf(\"%d,\", *++a[0]);\n    printf(\"%d,\", *(++a)[0]);\n    printf(\"%d\\n\", a[-1][+1]);\n}\nmain()\n{\n     print(x);\n}</code></pre></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>8, -12, 7, 23, 8</p>",
            "<b>B.</b> <p>8, 8, 7, 23, 7</p>",
            "<b>C.</b> <p>-12, -12, 27, -31, 23</p>",
            "<b>D.</b> <p>-12, -12, 27, -31, 56</p>"
          ],
          "correct_answer": "<b>A.</b> <p>8, -12, 7, 23, 8</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3594/gate2006-it-51\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 52,
          "question": "<p>The following function computes the value of  \\(\\binom{m}{n}\\) correctly for all legal values \\(m\\) and \\(n\\) \\( (m \\geq 1, n \\geq 0 \\text{ and } m \\gt n)\\)<pre><code> int func(int m, int n)\n{\n    if (E) return 1;\n    else return(func(m -1, n) + func(m - 1, n - 1));\n}</code></pre>In the above function, which of the following is the correct expression for E?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>(n = = 0) || (m = = 1)</p>",
            "<b>B.</b> <p>(n = = 0) &amp;&amp; (m = = 1)</p>",
            "<b>C.</b> <p>(n = = 0) || (m = = n)</p>",
            "<b>D.</b> <p>(n = = 0) &amp;&amp; (m = = n)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>(n = = 0) || (m = = n)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3595/gate2006-it-52\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 53,
          "question": "<p>Match the following concepts and their best possible descriptions. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\yearWiseImages\\GATE_IT_2006\\q53_06595785.jpg\"><br></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>i-b, ii-d, iii-e, iv-f, v-g, vi-a</p>",
            "<b>B.</b> <p>i-c, ii-a, iii-e, iv-d, v-h, vi-f</p>",
            "<b>C.</b> <p>i-c, ii-f, iii-h, iv-a, v-g, vi-d</p>",
            "<b>D.</b> <p>i-b, ii-e, iii-c, iv-f, v-g, vi-s</p>"
          ],
          "correct_answer": "<b>A.</b> <p>i-b, ii-d, iii-e, iv-f, v-g, vi-a</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3596/gate2006-it-53\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 54,
          "question": "<p>The arrival time, priority, and duration of the CPU and I/O bursts for each of three processes \\(P_1, P_2\\) and \\(P_3\\) are given in the table below. Each process has a CPU burst followed by an I/O burst followed by another CPU burst. Assume that each process has its own I/O resource.<br>\n\\(\\begin{array}{|c|c|c|c|c|c|} \\hline \\textbf{Process} &amp; \\textbf{Arrival} &amp; \\textbf{Priority}&amp; \\textbf{Burst duration} &amp; \\textbf{Burst duration} &amp; \\textbf{Burst duration) }\\\\&amp; \\textbf{Time} &amp; &amp; \\textbf{(CPU)} &amp; \\textbf{(I/O)} &amp; \\textbf{(CPU) } \\\\\\hline \\text{$P_1$} &amp; 0 &amp; 2 &amp; 1 &amp; 5 &amp;3 \\\\\\hline \\text{$P_2$} &amp; 2 &amp; \\text{3 (lowest)}&amp; 3 &amp; 3 &amp; 1 \\\\\\hline \\text{$P_3$} &amp; 3 &amp; \\text{1 (highest)}&amp; 2 &amp; 3 &amp; 1 \\\\\\hline \\end{array}\\)<br> The multi-programmed operating system uses preemptive priority scheduling. What are the finish times of the processes \\(P_1, P_2\\) and \\(P_3\\)?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>11, 15, 9</p>",
            "<b>B.</b> <p>10, 15, 9</p>",
            "<b>C.</b> <p>11, 16, 10</p>",
            "<b>D.</b> <p>12, 17, 11</p>"
          ],
          "correct_answer": "<b>B.</b> <p>10, 15, 9</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3597/gate2006-it-54\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 55,
          "question": "<p>Consider the solution to the bounded buffer producer/consumer problem by using general semaphores S, F, and E. The semaphore S is the mutual exclusion semaphore initialized to 1. The semaphore F corresponds to the number of free slots in the buffer and is initialized to N. The semaphore E corresponds to the number of elements in the buffer and is initialized to 0. <br>\n\\(\\begin{array}{|l|l|}\\hline \\textbf{Producer Process} &amp; \\textbf{Consumer Process} \\\\\\hline \\text{Produce an item;} &amp; \\text{Wait(E);} \\\\ \\text{Wait(F);} &amp; \\text{Wait(S);} \\\\ \\text{Wait(S);} &amp; \\text{Remove an item from the buffer;} \\\\\\text{Append the item to the buffer;} &amp; \\text{Signal(S);} \\\\ \\text{Signal(S);} &amp; \\text{Signal(F);} \\\\ \\text{Signal(E);} &amp; \\text{Consume the item;} \\\\\\hline \\end{array}\\)<br><br>\nWhich of the following interchange operations may result in a deadlock?<br><br>\nI.  Interchanging Wait (F) and Wait (S) in the Producer process <br>\nII. Interchanging Signal (S) and Signal (F) in the Consumer process <br></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>(I) only</p>",
            "<b>B.</b> <p>(II) only</p>",
            "<b>C.</b> <p>Neither (I) nor (II)</p>",
            "<b>D.</b> <p>Both (I) and (II)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>(I) only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3598/gate2006-it-55\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 56,
          "question": "<p>For each of the four processes \\(P_1, P_2, P_3,\\) and \\(P_4\\). The total size in kilobytes (KB) and the number of segments are given below.<br>\n\\(\\begin{array}{|c|c|c|}\\hline \\textbf{Process} &amp; \\textbf{Total size (in KB)} &amp; \\textbf{Number of segments} \\\\\\hline \\text{$P_1$} &amp; \\text{195}&amp; \\text{4}\\\\\\hline \\text{$P_2$} &amp; \\text{254} &amp; \\text{5}\\\\\\hline \\text{$P_3$} &amp; \\text{45}&amp; \\text{3} \\\\\\hline \\text{$P_4$} &amp; \\text{364}&amp; \\text{8} \\\\\\hline \\end{array}\\)<br>\nThe page size is 1 KB. The size of an entry in the page table is 4 bytes. The size of an entry in the segment table is 8 bytes. The maximum size of a segment is 256 KB. The paging method for memory management uses two-level paging, and its storage overhead is P. The storage overhead for the segmentation method is S. The storage overhead for the segmentation and paging method is T. What is the relation among the overheads for the different methods of memory management in the concurrent execution of the above four processes?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(P  \\lt  S  \\lt  T\\)</p>",
            "<b>B.</b> <p>\\(S  \\lt  P  \\lt  T\\)</p>",
            "<b>C.</b> <p>\\(S  \\lt  T  \\lt  P\\)</p>",
            "<b>D.</b> <p>\\(T \\lt S  \\lt  P\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(S  \\lt  P  \\lt  T\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3600/gate2006-it-56\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 57,
          "question": "<p>The wait and signal operations of a monitor are implemented using semaphores as follows. In the following,<br>\nx is a condition variable,<br>\nmutex is a semaphore initialized to 1,<br>\nx_sem is a semaphore initialized to 0,<br>\nx_count is the number of processes waiting on semaphore x_sem, initially 0,<br>\nnext is a semaphore initialized to 0,<br>\nnext_count is the number of processes waiting on semaphore next, initially 0.<br>\nThe body of each procedure that is visible outside the monitor is replaced with the following:<br><pre><code> P(mutex);\n...\nbody of procedure\n...\nif (next_count &gt; 0)\n    V(next);\nelse\n    V(mutex);</code></pre> <br>\nEach occurrence of x.wait is replaced with the following:<br><pre><code> x_count = x_count + 1;\nif (next_count &gt; 0)\n    V(next);\nelse\n    V(mutex);\n------------------------------------------------------------ E1;\nx_count = x_count - 1;\n</code></pre> <br>Each occurrence of x.signal is replaced with the following:<br><pre><code>if (x_count &gt; 0)\n{\n    next_count = next_count + 1;\n    ------------------- E2;\n    P(next);\n    next_count = next_count - 1;\n} </code></pre> <br>\nFor correct implementation of the monitor, statements E1 and E2 are, respectively,</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(P(x\\_sem), V(next)\\)</p>",
            "<b>B.</b> <p>\\(V(next), P(x\\_sem)\\)</p>",
            "<b>C.</b> <p>\\(P(next), V(x\\_sem)\\)</p>",
            "<b>D.</b> <p>\\(P(x\\_sem), V(x\\_sem)\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(P(x\\_sem), V(x\\_sem)\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3601/gate2006-it-57\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 58,
          "question": "<p>A software program consists of two modules \\(M_1\\) and \\(M_2\\) that can fail independently, but never simultaneously. The program is considered to have failed if any of these modules fails. Both the modules are 'repairable' and so the program starts working again as soon as the repair is done. Assume that the mean time to failure (MTTF) of \\(M_1\\) is \\(T_1\\) with a mean time to repair (MTTR) of \\(R_1\\). The MTTF of \\(M_2\\) is \\(T_2\\) with an MTTR of \\(R_2\\). What is the availability of the overall program given that the failure and repair times are all exponentially distributed random variables?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(((T_1T_2)/(T_1R_1 + T_2R_2))\\)</p>",
            "<b>B.</b> <p>\\(((R_1R_2)/(T_1R_1 + T_2R_2))\\)</p>",
            "<b>C.</b> <p>\\(((T_1T_2)/(T_1T_2 + T_1R_1 + T_2R_2))\\)</p>",
            "<b>D.</b> <p>\\(((T_1T_2)/(T_1T_2 + T_1R_2 + T_2R_1))\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(((T_1T_2)/(T_1T_2 + T_1R_2 + T_2R_1))\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3602/gate2006-it-58\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 59,
          "question": "<p>Consider the following structure chart diagram. The boxes have function names embedded in them, while the variables are indicated along the arcs.<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\yearWiseImages\\GATE_IT_2006\\q59_d7190aa4.jpg\"><br><br>Given below are a set of statements relevant to the above diagram.<br><br>\nI. F3 and F6 can be in the same module.<br>\nII. F4 and F6 can be in the same module.<br>\nIII. A4 is both an output and a control variable.<br>\nIV. It is incorrect to pass A1 as data and use it as a control variable.<br><br>\nWhich combination of these statements is TRUE?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>III and IV</p>",
            "<b>B.</b> <p>I and IV</p>",
            "<b>C.</b> <p>II and IV</p>",
            "<b>D.</b> <p>I, II and IV</p>"
          ],
          "correct_answer": "<b>B.</b> <p>I and IV</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3603/gate2006-it-59\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 60,
          "question": "<p>Consider a relation R with five attributes V, W, X, Y, and Z. The following functional dependencies hold:<br>\n\\(VY \\rightarrow W, WX \\rightarrow Z, \\text{and }ZY \\rightarrow V\\).<br>\nWhich of the following is a candidate key for R?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>VXZ</p>",
            "<b>B.</b> <p>VXY</p>",
            "<b>C.</b> <p>VWXY</p>",
            "<b>D.</b> <p>VWXYZ</p>"
          ],
          "correct_answer": "<b>B.</b> <p>VXY</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3604/gate2006-it-60\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 61,
          "question": "<p>In a database file structure, the search key field is 9 bytes long, the block size is 512 bytes, a record pointer is 7 bytes and a block pointer is 6 bytes. The largest possible order of a non-leaf node in a B+ tree implementing this file structure is</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>23</p>",
            "<b>B.</b> <p>24</p>",
            "<b>C.</b> <p>34</p>",
            "<b>D.</b> <p>44</p>"
          ],
          "correct_answer": "<b>C.</b> <p>34</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3605/gate2006-it-61\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 62,
          "question": "<p>Consider the following XML DTD describing course information in a university:<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\yearWiseImages\\GATE_IT_2006\\q62_3ecb8310.jpg\"><br>\nWhat is returned by the following XQuery?<br><pre><code> let $as := / /@Score\nfor $c in /Univ/Course[Eval]\nlet $cs := $c/Eval?@Score\nwhere min($cs) &gt; avg($as)\nreturn $c</code></pre></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>The professor with the lowest course evaluation</p>",
            "<b>B.</b> <p>Professors who have all their course evaluations above the university average</p>",
            "<b>C.</b> <p>The course with the lowest evaluation</p>",
            "<b>D.</b> <p>Courses with all evaluations above the university average</p>"
          ],
          "correct_answer": "<b>C.</b> <p>The course with the lowest evaluation</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3606/gate2006-it-62\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 63,
          "question": "<p>A router uses the following routing table:<br>\n\\(\\begin{array}{|l|l|l|} \\hline \\textbf {Destination} &amp; \\textbf { Mask} &amp; \\textbf{Interface} \\\\\\hline \\text {144.16.0.0} &amp; \\text{255.255.0.0} &amp; \\text{eth$0$} \\\\\\hline\\text {144.16.64.0} &amp; \\text{255.255.224.0} &amp; \\text{eth$1$} \\\\\\hline\\text {144.16.68.0} &amp; \\text{255.255.255.0} &amp; \\text{eth$2$}\\\\\\hline \\text {144.16.68.64} &amp; \\text{255.255.255.224} &amp; \\text{eth$3$}\\\\\\hline\\end{array}\\)<br>\nPacket bearing a destination address 144.16.68.117 arrives at the router. On which interface will it be forwarded?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>eth0</p>",
            "<b>B.</b> <p>eth1</p>",
            "<b>C.</b> <p>eth2</p>",
            "<b>D.</b> <p>eth3</p>"
          ],
          "correct_answer": "<b>C.</b> <p>eth2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3607/gate2006-it-63-isro2015-57\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 64,
          "question": "<p>Suppose that it takes 1 unit of time to transmit a packet (of fixed size) on a communication link. The link layer uses a window flow control protocol with a window size of N packets. Each packet causes an ack or a nak to be generated by the receiver, and ack/nak transmission times are negligible. Further, the round trip time on the link is equal to N units. Consider time i &gt; N. If only acks have been received till time i(no naks), then the goodput evaluated at the transmitter at time i(in packets per unit time) is</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(1- \\dfrac{ N}{i}\\)</p>",
            "<b>B.</b> <p>\\(\\dfrac{i}{(N + i)}\\)</p>",
            "<b>C.</b> <p>1</p>",
            "<b>D.</b> <p>\\(1 - e^{\\left(\\frac{i}{N}\\right)}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(1- \\dfrac{ N}{i}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3608/gate2006-it-64\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 65,
          "question": "<p>In the 4B/5B encoding scheme, every 4 bits of data are encoded in a 5-bit codeword. <br>\nIt is required that the codewords have at most 1 leading and at most 1 trailing zero.<br>\nHow many are such codewords possible?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>14</p>",
            "<b>B.</b> <p>16</p>",
            "<b>C.</b> <p>18</p>",
            "<b>D.</b> <p>20</p>"
          ],
          "correct_answer": "<b>C.</b> <p>18</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3609/gate2006-it-65\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 66,
          "question": "<p>A router has two full-duplex Ethernet interfaces each operating at 100 Mb/s. Ethernet frames are at least 84 bytes long (including the Preamble and the Inter-Packet-Gap). The maximum packet processing time at the router for wirespeed forwarding to be possible is (in micro-seconds)</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0.01</p>",
            "<b>B.</b> <p>3.36</p>",
            "<b>C.</b> <p>6.72</p>",
            "<b>D.</b> <p>8</p>"
          ],
          "correct_answer": "<b>B.</b> <p>3.36</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3610/gate2006-it-66\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 67,
          "question": "<p>A link of capacity 100 Mbps is carrying traffic from a number of sources. Each source generates an on-off traffic stream; when the source is on, the rate of traffic is 10 Mbps, and when the source is off, the rate of traffic is zero. The duty cycle, which is the ratio of on-time to off-time, is 1:2. When there is no buffer at the link, the minimum number of sources that can be multiplexed on the link so that link capacity is not wasted and no data loss occurs is S1. Assuming that all sources are synchronized and that the link is provided with a large buffer, the maximum number of sources that can be multiplexed so that no data loss occurs is S2. The values of S1 and S2 are, respectively,</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>10 and 30</p>",
            "<b>B.</b> <p>12 and 25</p>",
            "<b>C.</b> <p>5 and 33</p>",
            "<b>D.</b> <p>15 and 22</p>"
          ],
          "correct_answer": "<b>A.</b> <p>10 and 30</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3611/gate2006-it-67\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 68,
          "question": "<p>On a wireless link, the probability of packet error is 0.2. A stop-and-wait protocol is used to transfer data across the link. The channel condition is assumed to be independent of transmission to transmission. What is the average number of transmission attempts required to transfer 100 packets?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>100</p>",
            "<b>B.</b> <p>125</p>",
            "<b>C.</b> <p>150</p>",
            "<b>D.</b> <p>200</p>"
          ],
          "correct_answer": "<b>B.</b> <p>125</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3612/gate2006-it-68\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 69,
          "question": "<p>A program on machine X attempts to open a UDP connection to port 5376 on a machine Y, and a TCP connection to port 8632 on machine Z. However, there are no applications listening at the corresponding ports on Y and Z. An ICMP Port Unreachable error will be generated by</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Y but not Z</p>",
            "<b>B.</b> <p>Z but not Y</p>",
            "<b>C.</b> <p>Neither Y nor Z</p>",
            "<b>D.</b> <p>Both Y and Z</p>"
          ],
          "correct_answer": "<b>D.</b> <p>Both Y and Z</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3613/gate2006-it-69\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 70,
          "question": "<p>A subnetted Class B network has the following broadcast address: 144.16.95.255 <br>\nIts subnet mask</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>is necessarily 255.255.224.0</p>",
            "<b>B.</b> <p>is necessarily 255.255.240.0</p>",
            "<b>C.</b> <p>is necessarily 255.255.248.0</p>",
            "<b>D.</b> <p>could be any one of 255.255.224.0, 255.255.240.0,255.255.248.0</p>"
          ],
          "correct_answer": "<b>D.</b> <p>could be any one of 255.255.224.0, 255.255.240.0,255.255.248.0</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3614/gate2006-it-70\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 71,
          "question": "<p>An array X of n distinct integers is interpreted as a complete binary tree. The index of the first element of the array is 0. The index of the parent of element\\(X[i], i \\neq 0\\), is?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\left \\lfloor \\dfrac i 2 \\right \\rfloor\\)</p>",
            "<b>B.</b> <p>\\(\\left \\lceil \\dfrac{i-1}{2} \\right \\rceil\\)</p>",
            "<b>C.</b> <p>\\(\\left \\lceil \\dfrac i 2 \\right \\rceil\\)</p>",
            "<b>D.</b> <p>\\(\\left \\lceil \\dfrac i 2 \\right \\rceil - 1\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(\\left \\lceil \\dfrac i 2 \\right \\rceil - 1\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3615/gate2006-it-71\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 72,
          "question": "<p>An array X of n distinct integers is interpreted as a complete binary tree. The index of the first element of the array is 0. If only the root node does not satisfy the heap property, the algorithm to convert the complete binary tree into a heap has the best asymptotic time complexity of</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(O (n)\\)</p>",
            "<b>B.</b> <p>\\(O (\\log n)\\)</p>",
            "<b>C.</b> <p>\\(O (n \\log n)\\)</p>",
            "<b>D.</b> <p>\\(O (n \\log \\log n)\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(O (\\log n)\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3616/gate2006-it-72\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 73,
          "question": "<p>An array X of n distinct integers is interpreted as a complete binary tree. The index of the first element of the array is 0. If the root node is at level 0, the level of element \\(X[i], i \\neq 0\\), is</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\left \\lfloor \\log _2 i \\right \\rfloor\\)</p>",
            "<b>B.</b> <p>\\(\\left \\lceil \\log _2 (i+1)\\right \\rceil\\)</p>",
            "<b>C.</b> <p>\\(\\left \\lfloor \\log _2 (i+1) \\right \\rfloor\\)</p>",
            "<b>D.</b> <p>\\(\\left \\lceil \\log _2 i \\right \\rceil\\)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(\\left \\lfloor \\log _2 (i+1) \\right \\rfloor\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3617/gate2006-it-73\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 74,
          "question": "<p><pre><code> void swap(float* A1, float* A2)\n{\n    float temp;\n    if (*A1 = = *A2) return;\n    temp = *A1;\n    *A1 = *A2;\n    *A2 = temp;\n    return;\n}</code></pre><br> The program volume for the above module using Halstead's method is</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>60</p>",
            "<b>B.</b> <p>63</p>",
            "<b>C.</b> <p>66</p>",
            "<b>D.</b> <p>69</p>"
          ],
          "correct_answer": "<b>B.</b> <p>63</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3618/gate2006-it-74\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 75,
          "question": "<p><pre><code> void swap(float* A1, float* A2)\n{\n    float temp;\n    if (*A1 = = *A2) return;\n    temp = *A1;\n    *A1 = *A2;\n    *A2 = temp;\n    return;\n}</code></pre><br> The program effort for the above module using Halstead's method is</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>315</p>",
            "<b>B.</b> <p>330</p>",
            "<b>C.</b> <p>393</p>",
            "<b>D.</b> <p>403</p>"
          ],
          "correct_answer": "<b>C.</b> <p>393</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3619/gate2006-it-75\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 76,
          "question": "<p>x+y/2=9 <br>\n3x+y=10<br>\nThe value of the Frobenius norm for the above system of equations is</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0.5</p>",
            "<b>B.</b> <p>0.75</p>",
            "<b>C.</b> <p>1.5</p>",
            "<b>D.</b> <p>2</p>"
          ],
          "correct_answer": "<b>D.</b> <p>2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3620/gate2006-it-76\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 77,
          "question": "<p>x+y/2=9 <br>\n3x+y=10<br>\nWhat can be said about the Gauss-Siedel iterative method for solving the above set of linear equations?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>it will converge</p>",
            "<b>B.</b> <p>It will diverse</p>",
            "<b>C.</b> <p>It will neither converge nor diverse</p>",
            "<b>D.</b> <p>It is not applicable</p>"
          ],
          "correct_answer": "<b>A.</b> <p>it will converge</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3621/gate2006-it-77\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 78,
          "question": "<p>A pipelined processor uses a 4-stage instruction pipeline with the following stages: Instruction fetch (IF), Instruction decode (ID), Execute (EX) and Writeback (WB). The arithmetic operations as well as the load and store operations are carried out in the EX stage. The sequence of instructions corresponding to the statement \\(X = (S - R * (P + Q))/T\\) is given below. The values of variables P, Q, R, S and T are available in the registers R0, R1, R2, R3 and R4 respectively, before the execution of the instruction sequence.<br><br>\n\\(\\begin{array}{lll} \\text{ADD} &amp; \\text{$R5,R0,R1$} &amp; \\text{$;R5$} \\leftarrow \\text{R0 + R1} \\\\ \\text{MUL}&amp; \\text{$R6,R2,R5$} &amp; \\text{$;R6$} \\leftarrow \\text{R2 * R5} \\\\ \\text{SUB} &amp; \\text{$R5,R3,R6$} &amp; \\text{$;R5$} \\leftarrow \\text{R3 -R6} \\\\ \\text{DIV} &amp;\\text{$R6,R5,R4$} &amp; \\text{$;R6$} \\leftarrow \\text{R5/R4} \\\\ \\text{STORE} &amp;\\text{$R6,X$}&amp; \\text{$;X$} \\leftarrow \\text{R6} \\\\ \\end{array}\\) <br><br>The number of Read-After-Write (RAW) dependencies, Write-After-Read( WAR) dependencies, and Write-After-Write (WAW) dependencies in the sequence of instructions are, respectively,</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>2,2,4</p>",
            "<b>B.</b> <p>3,2,3</p>",
            "<b>C.</b> <p>4,2,2</p>",
            "<b>D.</b> <p>3,3,2</p>"
          ],
          "correct_answer": "<b>C.</b> <p>4,2,2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3622/gate2006-it-78\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 79,
          "question": "<p>A pipelined processor uses a 4-stage instruction pipeline with the following stages: Instruction fetch (IF), Instruction decode (ID), Execute (EX) and Writeback (WB). The arithmetic operations as well as the load and store operations are carried out in the EX stage. The sequence of instructions corresponding to the statement \\(X = (S - R * (P + Q))/T\\) is given below. The values of variables P, Q, R, S and T are available in the registers R0, R1, R2, R3 and R4 respectively, before the execution of the instruction sequence.<br><br>\n\\(\\begin{array}{lll} \\text{ADD} &amp; \\text{$R5,R0,R1$} &amp; \\text{$;R5$} \\leftarrow \\text{R0 + R1} \\\\ \\text{MUL}&amp; \\text{$R6,R2,R5$} &amp; \\text{$;R6$} \\leftarrow \\text{R2 * R5} \\\\ \\text{SUB} &amp; \\text{$R5,R3,R6$} &amp; \\text{$;R5$} \\leftarrow \\text{R3 -R6} \\\\ \\text{DIV} &amp;\\text{$R6,R5,R4$} &amp; \\text{$;R6$} \\leftarrow \\text{R5/R4} \\\\ \\text{STORE} &amp;\\text{$R6,X$}&amp; \\text{$;X$} \\leftarrow \\text{R6} \\\\ \\end{array}\\) <br><br>The IF, ID and WB stages take 1 clock cycle each. The EX stage takes 1 clock cycle each for the ADD, SUB and STORE operations, and 3 clock cycles each for MUL and DIV operations. Operand forwarding from the EX stage to the ID stage is used. The number of clock cycles required to complete the sequence of instructions is</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>10</p>",
            "<b>B.</b> <p>12</p>",
            "<b>C.</b> <p>14</p>",
            "<b>D.</b> <p>16</p>"
          ],
          "correct_answer": "<b>B.</b> <p>12</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3623/gate2006-it-79\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 80,
          "question": "<p>Let L be a regular language. Consider the constructions on L below:<br>\nI. \\(\\text{repeat} (L) = \\{ww \\mid w \\in L\\}\\)<br>\nII. \\(\\text{prefix} (L) = \\{u \\mid \\exists v : uv \\in L\\}\\)<br>\nIII. \\(\\text{suffix} (L) = \\{v \\mid \\exists u: uv \\in L\\}\\)<br>\nIV. \\(\\text{half} (L) = \\{u \\mid \\exists v: | v | = | u | \\text{ and } uv \\in L\\}\\)<br>Which of the constructions could lead to a non-regular language?<br></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Both I and IV</p>",
            "<b>B.</b> <p>Only 1</p>",
            "<b>C.</b> <p>Only IV</p>",
            "<b>D.</b> <p>Both II and III</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Only 1</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3624/gate2006-it-80\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 81,
          "question": "<p>Let L be a regular language. Consider the constructions on L below:<br>\nI. \\(\\text{repeat} (L) = \\{ww \\mid w \\in L\\}\\)<br>\nII. \\(\\text{prefix} (L) = \\{u \\mid \\exists v : uv \\in L\\}\\)<br>\nIII. \\(\\text{suffix} (L) = \\{v \\mid \\exists u: uv \\in L\\}\\)<br>\nIV. \\(\\text{half} (L) = \\{u \\mid \\exists v: | v | = | u | \\text{ and } uv \\in L\\}\\)<br>Which choice of L is best suited to support your answer above?</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((a + b)^*\\)</p>",
            "<b>B.</b> <p>\\(\\{\\epsilon, a, ab, bab\\}\\)</p>",
            "<b>C.</b> <p>\\((ab)^*\\)</p>",
            "<b>D.</b> <p>\\(\\{a^nb^n \\mid n \\geq 0\\}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\((a + b)^*\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3637/gate2006-it-81\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 82,
          "question": "<p>A software project has four phases P1, P2, P3 and P4. Of these phases, P1 Is the first one and needs to be completed before any other phase can commence. Phases P2 and P3 can be executed in parallel. Phase P4 cannot commence until both P2 and P3 are completed. The optimistic, most likely, and pessimistic estimates of the phase completion times in days, for Pl, P2, P3 and P4 are, respectively, (11, 15, 25), (7, 8, 15), (8, 9, 22), and (3, 8, 19).The critical path for the above project and the slack of P2 are, respectively,</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>P1-P2-P4, 1 day</p>",
            "<b>B.</b> <p>P1-P3-P4, 1 day</p>",
            "<b>C.</b> <p>P1-P3-P4, 2 days</p>",
            "<b>D.</b> <p>P1-P2-P4, 2 days</p>"
          ],
          "correct_answer": "<b>C.</b> <p>P1-P3-P4, 2 days</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3638/gate2006-it-82\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 83,
          "question": "<p>A software project has four phases P1, P2, P3 and P4. Of these phases, P1 Is the first one and needs to be completed before any other phase can commence. Phases P2 and P3 can be executed in parallel. Phase P4 cannot commence until both P2 and P3 are completed. The optimistic, most likely, and pessimistic estimates of the phase completion times in days, for Pl, P2, P3 and P4 are, respectively, (11, 15, 25), (7, 8, 15), (8, 9, 22), and (3, 8, 19).The costs (in Rupees per day) of crashing the expected phase completion times for the four phases, respectively, are 100, 2000, 50, and 1000. Assume that the expected phase completion times of the phases cannot be crashed below their respective most likely completion times. The minimum and the maximum amounts (in Rupees) that can be spent on crashing so that ALL paths are critical are, respectively.</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>100 and 1000</p>",
            "<b>B.</b> <p>100 and 1200</p>",
            "<b>C.</b> <p>150 and 1200</p>",
            "<b>D.</b> <p>200 and 2000</p>"
          ],
          "correct_answer": "<b>D.</b> <p>200 and 2000</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3639/gate2006-it-83\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 84,
          "question": "<p>Consider a database with three relation instances shown below. The primary keys for the Drivers and Cars relation are did and cid respectively and the records are stored in ascending order of these primary keys as given in the tables. No indexing is available in the database.<br><br>\n\\(\\overset{\\text{D: Drivers relation}}{\\begin{array}{|c|l|r|c|}\\hline \\textbf{did}&amp; \\textbf{dname}&amp; \\textbf{rating}&amp; \\textbf{age} \\\\\\hline 22&amp; \\text{Karthikeyan}&amp; 7&amp; 25 \\\\ \\hline 29&amp; \\text{Salman}&amp; 1&amp; 33 \\\\ \\hline 31&amp; \\text{Boris}&amp; 8&amp; 55 \\\\\\hline 32&amp; \\text{Amoldt}&amp; 8&amp; 25 \\\\\\hline 58&amp; \\text{Schumacher}&amp; 10&amp; 35 \\\\\\hline 64&amp; \\text{Sachin}&amp; 7&amp; 35 \\\\\\hline 71&amp; \\text{Senna}&amp; 10&amp; 16 \\\\\\hline 74&amp; \\text{Sachin}&amp; 9&amp; 35 \\\\\\hline 85&amp; \\text{Rahul}&amp; 3&amp; 25 \\\\\\hline 95&amp; \\text{Ralph}&amp; 3&amp; 53 \\\\\\hline \\end{array}} \\qquad \\overset{\\text{R: Reserves relation}}{\\begin{array}{|c|c|c|}\\hline \\textbf {did} &amp; \\textbf {Cid} &amp; \\textbf {day} \\\\\\hline 22 &amp; 101 &amp; 10-10-06 \\\\ \\hline 22 &amp; 102 &amp; 10-10-06\\\\ \\hline 22 &amp; 103 &amp; 08-10-06 \\\\\\hline 22 &amp; 104 &amp; 07-10-06 \\\\\\hline 31 &amp; 102 &amp; 10-11-16 \\\\\\hline 31&amp;103 &amp;06-11-16 \\\\\\hline 31 &amp; 104&amp;12-11-16 \\\\\\hline 64 &amp; 101 &amp;05-09-06 \\\\\\hline 64&amp; 102 &amp; 08-09-06 \\\\\\hline 74 &amp; 103 &amp; 08-09-06 \\\\\\hline \\end{array}}\\)<br><br>\n\\(\\overset{\\text{C: Cars relation}}{\\begin{array}{|c|c|c|c|}\\hline \\textbf {Cid} &amp; \\textbf {Cname} &amp; \\textbf{colour} \\\\\\hline 101 &amp; \\text{Renault} &amp; \\text{blue} \\\\ \\hline 102 &amp; \\text{Renault} &amp; \\text{red} \\\\ \\hline 103 &amp; \\text{Ferrari} &amp; \\text{green} \\\\\\hline 104 &amp; \\text{Jaguar} &amp; \\text{red} \\\\\\hline \\end{array}}\\)<br><br>  What is the output of the following SQL query?<pre><code> \nselect D.dname\nfrom Drivers D\nwhere D.did in  (\n                  select R.did\n                  from Cars C, Reserves R\n                  where R.cid = C.cid and C.colour = 'red'\n                  intersect\n                  select R.did\n                  from Cars C, Reserves R\n                  where R.cid  = C.cid and C.colour = 'green'\n                   )</code></pre><br></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Karthikeyan, Boris</p>",
            "<b>B.</b> <p>Sachin, Salman</p>",
            "<b>C.</b> <p>Karthikeyan, Boris, Sachin</p>",
            "<b>D.</b> <p>Schumacher, Senna</p>"
          ],
          "correct_answer": "<b>A.</b> <p>Karthikeyan, Boris</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3640/gate2006-it-84\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 85,
          "question": "<p>Consider a database with three relation instances shown below. The primary keys for the Drivers and Cars relation are did and cid respectively and the records are stored in ascending order of these primary keys as given in the tables. No indexing is available in the database.<br><br>\n\\(\\overset{\\text{D: Drivers relation}}{\\begin{array}{|c|l|r|c|}\\hline \\textbf{did}&amp; \\textbf{dname}&amp; \\textbf{rating}&amp; \\textbf{age} \\\\\\hline 22&amp; \\text{Karthikeyan}&amp; 7&amp; 25 \\\\ \\hline 29&amp; \\text{Salman}&amp; 1&amp; 33 \\\\ \\hline 31&amp; \\text{Boris}&amp; 8&amp; 55 \\\\\\hline 32&amp; \\text{Amoldt}&amp; 8&amp; 25 \\\\\\hline 58&amp; \\text{Schumacher}&amp; 10&amp; 35 \\\\\\hline 64&amp; \\text{Sachin}&amp; 7&amp; 35 \\\\\\hline 71&amp; \\text{Senna}&amp; 10&amp; 16 \\\\\\hline 74&amp; \\text{Sachin}&amp; 9&amp; 35 \\\\\\hline 85&amp; \\text{Rahul}&amp; 3&amp; 25 \\\\\\hline 95&amp; \\text{Ralph}&amp; 3&amp; 53 \\\\\\hline \\end{array}} \\qquad \\overset{\\text{R: Reserves relation}}{\\begin{array}{|c|c|c|}\\hline \\textbf {did} &amp; \\textbf {Cid} &amp; \\textbf {day} \\\\\\hline 22 &amp; 101 &amp; 10-10-06 \\\\ \\hline 22 &amp; 102 &amp; 10-10-06\\\\ \\hline 22 &amp; 103 &amp; 08-10-06 \\\\\\hline 22 &amp; 104 &amp; 07-10-06 \\\\\\hline 31 &amp; 102 &amp; 10-11-16 \\\\\\hline 31&amp;103 &amp;06-11-16 \\\\\\hline 31 &amp; 104&amp;12-11-16 \\\\\\hline 64 &amp; 101 &amp;05-09-06 \\\\\\hline 64&amp; 102 &amp; 08-09-06 \\\\\\hline 74 &amp; 103 &amp; 08-09-06 \\\\\\hline \\end{array}}\\)<br><br>\n\\(\\overset{\\text{C: Cars relation}}{\\begin{array}{|c|c|c|c|}\\hline \\textbf {Cid} &amp; \\textbf {Cname} &amp; \\textbf{colour} \\\\\\hline 101 &amp; \\text{Renault} &amp; \\text{blue} \\\\ \\hline 102 &amp; \\text{Renault} &amp; \\text{red} \\\\ \\hline 103 &amp; \\text{Ferrari} &amp; \\text{green} \\\\\\hline 104 &amp; \\text{Jaguar} &amp; \\text{red} \\\\\\hline \\end{array}}\\) <br><pre><code> \nselect D.dname\nfrom Drivers D\nwhere D.did in  (\n                  select R.did\n                  from Cars C, Reserves R\n                  where R.cid = C.cid and C.colour = 'red'\n                  intersect\n                  select R.did\n                  from Cars C, Reserves R\n                  where R.cid  = C.cid and C.colour = 'green'\n                  )</code></pre><br> Let n be the number of comparisons performed when the above SQL query is optimally executed. If linear search is used to locate a tuple in a relation using primary key, then n lies in the range:</p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>36-40</p>",
            "<b>B.</b> <p>44-48</p>",
            "<b>C.</b> <p>60-64</p>",
            "<b>D.</b> <p>100-104</p>"
          ],
          "correct_answer": "<b>B.</b> <p>44-48</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3641/gate2006-it-85\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
