window.__examLoadCallback({
  "title": "Computer_Organization - Computer_Organization - Slot 18",
  "duration": 42,
  "sections": [
    {
      "name": "Computer_Organization",
      "questions": [
        {
          "id": 1,
          "question": "<p>A CPU generates 32-bit virtual addresses. The page size is 4 KB. The processor\nhas a translation look-aside buffer (TLB) which can hold a total of 128 page table\nentries and is 4-way set associative. The minimum size of the TLB tag is <br><br><strong>(GATE CSE 2006)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>11bits</p>",
            "<b>B.</b> <p>13bits</p>",
            "<b>C.</b> <p>15bits</p>",
            "<b>D.</b> <p>20bits</p>"
          ],
          "correct_answer": "<b>C.</b> <p>15bits</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1840/gate2006-62#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Consider these two functions and two statements S1 and S2 about them. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Computer_Organization\\q55_f6311440.jpg\"><br>  S1 : The transformation from work 1 to work 2 is valid, i.e., for any program state\nand input arguments, work 2 will compute the same output and have the same\neffect on program state as work 1 <br>\nS2 : All the transformations applied to work 1 to get work 2 will always improve\nthe performance (i.e. reduce CPU time) of work 2 compared to work 1 <br><br><strong>(GATE CSE 2006)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>S1 is false and S2 is false</p>",
            "<b>B.</b> <p>S1 is false and S2 is true</p>",
            "<b>C.</b> <p>S1 is true and S2 is false</p>",
            "<b>D.</b> <p>S1 is true and S2 is true</p>"
          ],
          "correct_answer": "<b>A.</b> <p>S1 is false and S2 is false</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1833/gate2006-55#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Consider a new instruction named branch-on-bit-set (mnemonic bbs). The\ninstruction \"bbs reg, pos, labbel\" jumps to label if bit in position pos of register\noperand reg is one. a register is 32 bits wide and the bits are numbered 0 to 31,\nbit in position 0 being the least significant. Consider the following emulation of\nthis instruction on a processor that does not have bbs implemented. <br><br>\ntemp\\(\\leftarrow\\)reg &amp; mask <br>\nBranch to label if temp is non-zero<br><br>\nThe variable temp is a temporary register. For correct emulation the variable\nmask must be generated by <br><br><strong>(GATE CSE 2006)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>mask \\(\\leftarrow 0 \\times 1 \\lt \\lt pos\\)</p>",
            "<b>B.</b> <p>musk \\(\\leftarrow 0 \\times ffffffff \\gt \\gt  pos\\)</p>",
            "<b>C.</b> <p>mask \\(\\leftarrow\\) pos</p>",
            "<b>D.</b> <p>msdk \\(\\leftarrow 0 \\times f\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>mask \\(\\leftarrow 0 \\times 1 \\lt \\lt pos\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1819/gate2006-43#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>A CPU has five-stages pipeline and runs at 1GHz frequency. Instruction fetch\nhappens in the first stage of the pipeline. A conditional branch instruction\ncomputes the target address and evaluates the condition in the third stage of the\npipeline. The processor stops fetching new instructions following a conditional\nbranch until the branch outcome is known. A program executes \\(10^{9}\\) instructions\nout of which 20% are conditional branches. If each instruction takes one cycle to\ncomplete on average, then total execution time of the program is <br><br><strong>(GATE CSE 2006)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>1.0 second</p>",
            "<b>B.</b> <p>1.2 seconds</p>",
            "<b>C.</b> <p>1.4 seconds</p>",
            "<b>D.</b> <p>1.6 seconds</p>"
          ],
          "correct_answer": "<b>C.</b> <p>1.4 seconds</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1818/gate2006-42#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>A CPU has a cache with block size 64 bytes. The main memory has k banks, each\nbank being c bytes wide. Consecutive c-byte chunks are mapped on consecutive\nbanks with warp-around. All the k banks can be accessed in parallel, but two\naccesses to the same bank must be serialized. A cache block access may involve\nmultiple iterations of parallel bank accesses depending on the amount of data\nobtained by accessing all the k banks in parallel. Each iteration requires decoding\nthe bank numbers to be accessed in parallel and this takes k/2 ns . The latency of\none bank access is 80 ns . If c = 2 and k=24, then latency of retrieving a cache\nblock starting at address zero from main memory is <br><br><strong>(GATE CSE 2006)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>92ns</p>",
            "<b>B.</b> <p>104ns</p>",
            "<b>C.</b> <p>172ns</p>",
            "<b>D.</b> <p>184ns</p>"
          ],
          "correct_answer": "<b>D.</b> <p>184ns</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1817/gate2006-41#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>A CPU has 24-bit instructions. A program starts at address 300 (in decimal). Which one of the following is a legal program counter (all values in decimal)? <br><br><strong>(GATE CSE 2006)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>400</p>",
            "<b>B.</b> <p>500</p>",
            "<b>C.</b> <p>600</p>",
            "<b>D.</b> <p>700</p>"
          ],
          "correct_answer": "<b>C.</b> <p>600</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/888/gate2006-9#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>A disk has 8 equidistant tracks. The diameters of the innermost and outermost tracks are 1 cm and 8 cm respectively. The innermost track has a storage capacity of 10 MB.<br>If the disk has 20 sectors per track and is currently at the end of the \\(5^{th}\\) sector of the inner-most track and the head can move at a speed of 10 meters/sec and it is rotating at constant angular velocity of 6000 RPM, how much time will it take to read 1 MB contiguous data starting from the sector 4 of the outer-most track? <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>13.5 ms</p>",
            "<b>B.</b> <p>10  ms</p>",
            "<b>C.</b> <p>9.5 ms</p>",
            "<b>D.</b> <p>20 ms</p>"
          ],
          "correct_answer": "<b>B.</b> <p>10  ms</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3846/gate2005-it-81-b\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>A disk has 8 equidistant tracks. The diameters of the innermost and outermost tracks are 1 cm and 8 cm respectively. The innermost track has a storage capacity of 10 MB.<br>\nWhat is the total amount of data that can be stored on the disk if it is used with a drive that rotates it with<br>\nI.Constant Linear Velocity<br>\nII.Constant Angular Velocity?<br> <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(I. 80 \\ \\text{MB}; \\;  II. 2040 \\ \\text{MB}\\)</p>",
            "<b>B.</b> <p>\\(I. 2040 \\ \\text{MB}; \\;  II 80 \\ \\text{MB}\\)</p>",
            "<b>C.</b> <p>\\(I. 80 \\ \\text{MB}; \\; II. 360 \\ \\text{MB}\\)</p>",
            "<b>D.</b> <p>\\(I. 360 \\ \\text{MB};  \\; II. 80 \\ \\text{MB}\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(I. 360 \\ \\text{MB};  \\; II. 80 \\ \\text{MB}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3845/gate2005-it-81-a\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>Consider a 2-way set associative cache memory with 4 sets and total 8 cache blocks (0-7) and a main memory with 128 blocks (0-127). What memory blocks will be present in the cache after the following sequence of memory block references if LRU policy is used for cache block replacement?<br><br> 0 5 3 9 7 0 16 55\n<br>Assuming that initially the cache did not have any memory block from the current job? <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0 3 5 7 16 55</p>",
            "<b>B.</b> <p>0 3 5 7 9 16 55</p>",
            "<b>C.</b> <p>0 5 7 9 16 55</p>",
            "<b>D.</b> <p>3 5 7 9 16 55</p>"
          ],
          "correct_answer": "<b>C.</b> <p>0 5 7 9 16 55</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3822/gate2005-it-61\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>An instruction set of a processor has 125 signals which can be divided into 5 groups of mutually exclusive signals as follows: <br>\nGroup 1 : 20 signals, Group 2 : 70 signals, Group 3 : 2 signals, Group 4 : 10 signals, Group 5 : 23 signals.<br>\nHow many bits of the control words can be saved by using vertical microprogramming over horizontal microprogramming? <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0</p>",
            "<b>B.</b> <p>103</p>",
            "<b>C.</b> <p>22</p>",
            "<b>D.</b> <p>55</p>"
          ],
          "correct_answer": "<b>B.</b> <p>103</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3810/gate2005-it-49\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>A hardwired CPU uses 10 control signals \\(S_1\\) to \\(S_{10}\\), in various time steps \\(T_1\\) to \\(T_5\\), to implement 4 instructions \\(I_1\\) to \\(I_4\\) as shown below: <br><br>\n\\(\\begin{array}{|c|c|c|c|c|c|}\\hline&amp;\\bf{T_1}&amp;\\bf{T_2}&amp;\\bf{T_3}&amp;\\bf{T_4}&amp;\\bf{T_5}\\\\\\hline\\bf{I_1}&amp;S_1,S_3,S_5&amp;S_2,S_4,S_6&amp;S_1,S_7&amp;S_{10}&amp;S_3,S_8\\\\\\hline\\bf{I_2}&amp;S_1,S_3,S_5&amp;S_8,S_9,S_{10}&amp;S_5,S_6S_7&amp;S_{6}&amp;S_{10}\\\\\\hline\\bf{I_3}&amp;S_1,S_3,S_5&amp;S_7,S_8,S_{10}&amp;S_2,S_6,S_{9}&amp;S_{10}&amp;S_1,S_3\\\\\\hline\\bf{I_4}&amp;S_1,S_3,S_5&amp;S_2,S_6,S_7&amp;S_5,S_{10}&amp;S_{6},S_9&amp;S_{10}\\\\\\hline\\end{array}\\) <br><br>\nWhich of the following pairs of expressions represent the circuit for generating control signals \\(S_5\\) and \\(S_{10}\\) respectively?<br><br>\n\\(((I_j + I_k)T_n\\) indicates that the control signal should be generated in time step \\(T_n\\) if the instruction being executed is \\(l_j\\) or \\(l_k\\)) <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(S_5 = T_1 + I_2 \\cdot T_3\\) and \\(S_{10} = (I_1 + I_3) \\cdot T_4 + (I_2 + I_4) \\cdot T_5\\)</p>",
            "<b>B.</b> <p>\\(S_5 = T_1 + (I_2 + I_4) \\cdot T_3\\) and \\(S_{10} = (I_1 + I_3) \\cdot T_4 + (I_2 + I_4) \\cdot T_5\\)</p>",
            "<b>C.</b> <p>\\(S_5 = T_1 + (I_2 + I_4) \\cdot T_3\\) and \\(S_{10} = (I_2 + I_3 + I_4) \\cdot T_2 + (I_1 + I_3) \\cdot T_4 + (I_2 + I_4) \\cdot T_5\\)</p>",
            "<b>D.</b> <p>\\(S_5 = T_1 + (I_2 + I_4) \\cdot T_3\\) and \\(S_{10} = (I_2 + I_3) \\cdot T_2 + I_4 \\cdot T_3 + (I_1 + I_3) \\cdot T_4 + (I_2 + I_4) \\cdot T_5\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(S_5 = T_1 + (I_2 + I_4) \\cdot T_3\\) and \\(S_{10} = (I_2 + I_3) \\cdot T_2 + I_4 \\cdot T_3 + (I_1 + I_3) \\cdot T_4 + (I_2 + I_4) \\cdot T_5\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3806/gate2005-it-45\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>We have two designs D1 and D2 for a synchronous pipeline processor. D1 has 5 pipeline stages with execution times of 3 nsec, 2 nsec, 4 nsec, 2 nsec and 3 nsec while the design D2 has 8 pipeline stages each with 2 nsec execution time How much time can be saved using design D2 over design D1 for executing 100 instructions? <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>214 nsec</p>",
            "<b>B.</b> <p>202 nsec</p>",
            "<b>C.</b> <p>86 nsec</p>",
            "<b>D.</b> <p>-200 nsec</p>"
          ],
          "correct_answer": "<b>B.</b> <p>202 nsec</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3805/gate2005-it-44\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>A dynamic RAM has a memory cycle time of 64 nsec. It has to be refreshed 100 times per msec and each refresh takes 100 nsec. What percentage of the memory cycle time is used for refreshing? <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>10</p>",
            "<b>B.</b> <p>6.4</p>",
            "<b>C.</b> <p>1</p>",
            "<b>D.</b> <p>0.64</p>"
          ],
          "correct_answer": "<b>C.</b> <p>1</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3754/gate2005-it-9\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>Consider the following data path of a CPU.  <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Computer_Organization\\q79_570ada15.jpg\"> <br> ALU, the bus and all the registers in the data path are of identical size. All operations including incrementation of the PC and the GPRs are to be carried out in the ALU. Two clock cycles are needed for memory read operation - the first one for loading address in the MAR and the next one for loading data from the memory bus into the MDR. <br><br> The instruction \"call Rn, sub\" is a two word instruction. Assuming that PC is incremented during the fetch cycle of the first word of the instruction, its register transfer interpretation is<pre><code> Rn &lt; = PC + 1;\nPC &lt; = M[PC];</code></pre>    The minimum number of CPU clock cycles needed during the execution cycle of this instruction is: <br><br><strong>(GATE CSE 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>2</p>",
            "<b>B.</b> <p>3</p>",
            "<b>C.</b> <p>4</p>",
            "<b>D.</b> <p>5</p>"
          ],
          "correct_answer": "<b>B.</b> <p>3</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43568/gate2005-80#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>Consider the following data path of a CPU.  <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Computer_Organization\\q79_570ada15.jpg\"> <br>ALU, the bus and all the registers in the data path are of identical size. All operations including incrementation of the PC and the GPRs are to be carried out in the ALU. Two clock cycles are needed for memory read operation - the first one for loading address in the MAR and the next one for loading data from the memory bus into the MDR. <br><br> The instruction \"add R0, R1\" has the register transfer interpretation R0&lt;=R0+R1. The minimum number of clock cycles needed for execution cycle of this instruction is. <br><br><strong>(GATE CSE 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>2</p>",
            "<b>B.</b> <p>3</p>",
            "<b>C.</b> <p>4</p>",
            "<b>D.</b> <p>5</p>"
          ],
          "correct_answer": "<b>B.</b> <p>3</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1402/gate2005-79#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
