window.__examLoadCallback({
  "title": "Digital_Logic - Digital_Logic - Slot 1",
  "duration": 42,
  "sections": [
    {
      "name": "Digital_Logic",
      "questions": [
        {
          "id": 1,
          "question": "<p>A new flipflop with inputs X and Y, has the following property<br>\\(\\begin{array}{|c|c|c|c|} \\hline \\mathbf{X} &amp; \\mathbf{Y} &amp; \\text { Current state } &amp; \\text { Next state } \\\\ \\hline 0 &amp; 0 &amp; Q &amp; 1 \\\\ 0 &amp; 1 &amp; Q &amp; \\bar{Q} \\\\ 1 &amp; 1 &amp; Q &amp; 0 \\\\ 1 &amp; 0 &amp; Q &amp; Q \\\\ \\hline \\end{array}\\)<br>Which of the following expresses the next state in terms of X,Y, current state? <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((\\bar{X} \\wedge \\bar{Q}) \\vee(\\bar{Y} \\wedge Q)\\)</p>",
            "<b>B.</b> <p>\\((\\bar{X} \\wedge {Q}) \\vee(\\bar{Y} \\wedge \\bar{Q})\\)</p>",
            "<b>C.</b> <p>\\(({X} \\wedge \\bar{Q}) \\vee({Y} \\wedge {Q})\\)</p>",
            "<b>D.</b> <p>\\(({X} \\wedge \\bar{Q}) \\vee(\\bar{Y} \\wedge {Q})\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\((\\bar{X} \\wedge \\bar{Q}) \\vee(\\bar{Y} \\wedge Q)\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331388/isro2020-80\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Consider the following circuit<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q77_a8d99d4d.jpg\"><br>  The function by the network above is <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\overline{A B} E+E F+\\overline{C D} F\\)</p>",
            "<b>B.</b> <p>\\((\\bar{E}+A B \\bar{F})(C+D+\\bar{F})\\)</p>",
            "<b>C.</b> <p>\\((\\overline{A B}+E)(\\bar{E}+\\bar{F})(C+D+\\bar{F})\\)</p>",
            "<b>D.</b> <p>\\((A+B) \\bar{E}+\\overline{E F}+C D \\bar{F}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\((\\bar{E}+A B \\bar{F})(C+D+\\bar{F})\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331309/isro2020-77\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>The following circuit compares two 2-bit binary numbers, X and Y represented by \\(X_{1}X_{0}\\) and \\(Y_{1}Y_{0}\\) respectively. (\\(X_{0}\\) and \\(Y_{0}\\) represent Least Significant Bits)<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q66_f241f6da.jpg\"><br>Under what conditions Z will be 1? <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>X &gt; Y</p>",
            "<b>B.</b> <p>X &lt; Y</p>",
            "<b>C.</b> <p>X=Y</p>",
            "<b>D.</b> <p>X!=Y</p>"
          ],
          "correct_answer": "<b>A.</b> <p>X &gt; Y</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331492/isro2020-66\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>If ABCD is a 4-bit binary number, then what is the code generated by the following circuit?<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q12_ecd1ed47.jpg\"><br> <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>BCD code</p>",
            "<b>B.</b> <p>Gray code</p>",
            "<b>C.</b> <p>8421 code</p>",
            "<b>D.</b> <p>Excess-3 code</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Gray code</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331372/isro2020-12\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Minimum number of NAND gates required to implement the following binary equation\\(Y=(\\bar{A}+\\bar{B})(C+D)\\) <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>4</p>",
            "<b>B.</b> <p>5</p>",
            "<b>C.</b> <p>3</p>",
            "<b>D.</b> <p>6</p>"
          ],
          "correct_answer": "<b>A.</b> <p>4</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331369/isro2020-11\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Following Multiplexer circuit is equivalent to<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q10_9ef75cf4.jpg\"><br> <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Sum equation of full adder</p>",
            "<b>B.</b> <p>Carry equation of full adder</p>",
            "<b>C.</b> <p>Borrow equation for full subtractor</p>",
            "<b>D.</b> <p>Difference equation of a full subtractor</p>"
          ],
          "correct_answer": "<b>A.</b> <p>Sum equation of full adder</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331299/isro2020-10\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>In a 8-bit ripple carry adder using identical full adders, each full adder takes 34 ns for computing sum. If the time taken for 8-bit addition is 90 ns, find time taken by each full adder to find carry. <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>6  ns</p>",
            "<b>B.</b> <p>7 ns</p>",
            "<b>C.</b> <p>10 ns</p>",
            "<b>D.</b> <p>8 ns</p>"
          ],
          "correct_answer": "<b>D.</b> <p>8 ns</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331294/isro2020-9\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>Any set of Boolean operation that is sufficient to represent all Boolean expression is said to be complete. Which of the following is not complete ? <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>{AND, OR}</p>",
            "<b>B.</b> <p>{AND, NOT}</p>",
            "<b>C.</b> <p>{NOT, OR}</p>",
            "<b>D.</b> <p>{NOR}</p>"
          ],
          "correct_answer": "<b>A.</b> <p>{AND, OR}</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213526/isro2018-62\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>A computer uses ternary system instead of the traditional systen, An n bit string in the binary system will occupy <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>3+n ternary digits</p>",
            "<b>B.</b> <p>2n/3 ternary digits</p>",
            "<b>C.</b> <p>\\(n \\log _{2} 3\\) ternary digits</p>",
            "<b>D.</b> <p>\\(n \\log _{3} 2\\) ternary digits</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(n \\log _{3} 2\\) ternary digits</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213556/isro2018-32\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>Given \\(\\sqrt{224_{r}}=13_{r}\\) the value of radix r is <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>10</p>",
            "<b>B.</b> <p>8</p>",
            "<b>C.</b> <p>6</p>",
            "<b>D.</b> <p>5</p>"
          ],
          "correct_answer": "<b>D.</b> <p>5</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213569/isro2018-19\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q9_7cd2ae9c.jpg\"><br>  In the diagram above, the inverter (NOT gate) and the AND-gates labeled 1 and 2 have delays of 9, 10 and 12 nanoseconds (ns), respectively. Wire delays are negligible. For certain values a and c, together with certain transition of b, a glitch (spurious output) is generated for a short time, after which the output assumes its correct value. The duration of glitch is: <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>7 ns</p>",
            "<b>B.</b> <p>9 ns</p>",
            "<b>C.</b> <p>11 ns</p>",
            "<b>D.</b> <p>13 ns</p>"
          ],
          "correct_answer": "<b>A.</b> <p>7 ns</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213579/isro2018-9\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>If a variable can take only integral values from 0 to n, where n is an integer, then the variable can be represented as a bit-field whose width is (the log in the answer are to the base 2, and \\(\\lceil\\log n\\rceil\\) means the floor of \\(\\log_{}{n}\\) ) <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\left \\lceil \\log (n) \\right \\rceil + 1 \\text{ bits}\\)</p>",
            "<b>B.</b> <p>\\(\\left \\lceil \\log (n-1) \\right \\rceil + 1 \\text{ bits}\\)</p>",
            "<b>C.</b> <p>\\(\\left \\lceil \\log (n+1) \\right \\rceil + 1\\text{ bits}\\)</p>",
            "<b>D.</b> <p>None of the above</p>"
          ],
          "correct_answer": "<b>D.</b> <p>None of the above</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213585/isro2018-3\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>\\((1217)_{8}\\) is equivalent to <br><br><strong>(ISRO CSE 2017)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((1217)_{16}\\)</p>",
            "<b>B.</b> <p>\\((028F)_{16}\\)</p>",
            "<b>C.</b> <p>\\((2297)_{10}\\)</p>",
            "<b>D.</b> <p>\\((0B17)_{16}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\((028F)_{16}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1297/gate2009-5-isro2017-57\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>Advantage of synchronous sequential circuits over asynchronous one is : <br><br><strong>(ISRO CSE 2017)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Lower hardware requirement</p>",
            "<b>B.</b> <p>Better noise immunity</p>",
            "<b>C.</b> <p>Faster operation</p>",
            "<b>D.</b> <p>All of the above</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Faster operation</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/128643/isro2017-26\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>The 2-input XOR has a high output only when the input values are <br><br><strong>(ISRO CSE 2017)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>low</p>",
            "<b>B.</b> <p>high</p>",
            "<b>C.</b> <p>same</p>",
            "<b>D.</b> <p>different</p>"
          ],
          "correct_answer": "<b>D.</b> <p>different</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/128642/isro-2017-25\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
