window.__examLoadCallback({
  "title": "Digital_Logic - Digital_Logic - Slot 11",
  "duration": 42,
  "sections": [
    {
      "name": "Digital_Logic",
      "questions": [
        {
          "id": 1,
          "question": "<p>Consider the following circuit involving three D-type flip-flops used in a certain type of counter configuration. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q50_9b1eb674.jpg\"> <br> If all the flip-flops were reset to 0 at power on, what is the total number of\ndistinct outputs (states) represented by PQR generated by the counter? <br><br><strong>(GATE CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>3</p>",
            "<b>B.</b> <p>4</p>",
            "<b>C.</b> <p>5</p>",
            "<b>D.</b> <p>6</p>"
          ],
          "correct_answer": "<b>B.</b> <p>4</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/43318/gate2011-51#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Consider the following circuit involving three D-type flip-flops used in a certain type of counter configuration. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q50_9b1eb674.jpg\"> <br>If at some instance prior to the occurrence of the clock edge, P. Q and R have a\nvalue 0, 1 and 0 respectively, what shall be the value of PQR after the clock\nedge? <br><br><strong>(GATE CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(000\\)</p>",
            "<b>B.</b> <p>\\(001\\)</p>",
            "<b>C.</b> <p>\\(010\\)</p>",
            "<b>D.</b> <p>\\(011\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(011\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/2157/gate2011-50#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>The minimum number of D flip-flops needed to design a mod-258 counter is <br><br><strong>(GATE CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>9</p>",
            "<b>B.</b> <p>8</p>",
            "<b>C.</b> <p>512</p>",
            "<b>D.</b> <p>258</p>"
          ],
          "correct_answer": "<b>A.</b> <p>9</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2117/gate2011-15#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>The simplified SOP (Sum of Product) form of the Boolean Algebra \\((P+\\bar{Q}+\\bar{R})\\cdot (P+\\bar{Q}+R)\\cdot (P+Q+\\bar{R})\\) is <br><br><strong>(GATE CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((\\bar{P}Q+\\bar{R})\\)</p>",
            "<b>B.</b> <p>\\((P+\\bar{Q}\\bar{R})\\)</p>",
            "<b>C.</b> <p>\\((\\bar{P}Q+R)\\)</p>",
            "<b>D.</b> <p>(PQ+R)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\((P+\\bar{Q}\\bar{R})\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2116/gate2011-14#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Which one of the following circuits is NOT equivalent to a 2-input XNOR\n(exclusive NOR) gate? <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q2_aea01d42.jpg\"> <br><br><strong>(GATE CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A</p>",
            "<b>B.</b> <p>B</p>",
            "<b>C.</b> <p>C</p>",
            "<b>D.</b> <p>D</p>"
          ],
          "correct_answer": "<b>D.</b> <p>D</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2115/gate2011-13#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>In the sequential circuit shown below, if the initial value of the output \\(Q_{1}Q_{0}\\) is 00,\nwhat are the next four values of  \\(Q_{1}Q_{0}\\) ? <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q32_3fa4a72d.jpg\"> <br><br><strong>(GATE CSE 2010)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>11,10,01,00</p>",
            "<b>B.</b> <p>10,11,01,00</p>",
            "<b>C.</b> <p>10,00,01,11</p>",
            "<b>D.</b> <p>11,10,00,01</p>"
          ],
          "correct_answer": "<b>A.</b> <p>11,10,01,00</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/2206/gate2010-32#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>What is the Boolean Algebra for the output f of the combinational logic circuit\nof NOR gates given below? <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q31_95d89936.jpg\"> <br><br><strong>(GATE CSE 2010)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\overline{Q+R}\\)</p>",
            "<b>B.</b> <p>\\(\\overline{P+Q}\\)</p>",
            "<b>C.</b> <p>\\(\\overline{P+R}\\)</p>",
            "<b>D.</b> <p>\\(\\overline{P+Q+R}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(\\overline{Q+R}\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/2205/gate2010-31#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>The Boolean expression for the output f of the multiplexer shown below is <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q9_a0a5ecab.jpg\"> <br><br><strong>(GATE CSE 2010)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\overline{P\\bigoplus Q\\bigoplus R}\\)</p>",
            "<b>B.</b> <p>\\(P\\bigoplus Q\\bigoplus R\\)</p>",
            "<b>C.</b> <p>P+Q+R</p>",
            "<b>D.</b> <p>\\(\\overline{P+Q+R}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(P\\bigoplus Q\\bigoplus R\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2182/gate2010-9#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>P is a 16-bit signed integer. The 2's complement representation of P is \\((F87B)_{16}\\).\nThe 2's complement representation of 8*P is <br><br><strong>(GATE CSE 2010)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((C3D8)_{16}\\)</p>",
            "<b>B.</b> <p>\\((187B)_{16}\\)</p>",
            "<b>C.</b> <p>\\((F878)_{16}\\)</p>",
            "<b>D.</b> <p>\\((987B)_{16}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\((C3D8)_{16}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2179/gate2010-8#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>The minterm expansion of f(P,Q,R)=PQ+QR'+PR' is <br><br><strong>(GATE CSE 2010)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(m_{2}+m_{4}+m_{6}+m_{7}\\)</p>",
            "<b>B.</b> <p>\\(m_{0}+m_{1}+m_{3}+m_{5}\\)</p>",
            "<b>C.</b> <p>\\(m_{0}+m_{1}+m_{6}+m_{7}\\)</p>",
            "<b>D.</b> <p>\\(m_{2}+m_{3}+m_{4}+m_{5}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(m_{2}+m_{4}+m_{6}+m_{7}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2177/gate2010-6#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>The addition of 4-bit, two's complement, binary numbers 1101 and 0100 results in <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0001 and an overflow</p>",
            "<b>B.</b> <p>1001 and no overflow</p>",
            "<b>C.</b> <p>0001 and no overflow</p>",
            "<b>D.</b> <p>1001 and an overflow</p>"
          ],
          "correct_answer": "<b>C.</b> <p>0001 and no overflow</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3546/gate2006-it-7-isro2009-41\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>The two numbers given below are multiplied using the Booth's algorithm <br>\nMultiplicand: 0101 1010 1110 1110<br>\nMultiplier: 0111 0111 1011 1101<br>\nHow many additions/subtractions are required for the multiplication of the above two numbers? <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>6</p>",
            "<b>B.</b> <p>8</p>",
            "<b>C.</b> <p>10</p>",
            "<b>D.</b> <p>12</p>"
          ],
          "correct_answer": "<b>B.</b> <p>8</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48065/isro2009-40-gate2008-it_42\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>Consider the following boolean function of four variables \\(f(w,x,y,z) = \\Sigma(1,3,4,6,9,11,12,14)\\), the function is <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Independent of one variable</p>",
            "<b>B.</b> <p>Independent of two variables</p>",
            "<b>C.</b> <p>Independent of three variables</p>",
            "<b>D.</b> <p>Dependent on all variables</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Independent of two variables</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50345/isro2009-20\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>The switching expression corresponding to \\(f(A, B, C, D) = \\Sigma(1, 4, 5, 9, 11, 12)\\) is <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>BC'D' + A'C'D + AB'D</p>",
            "<b>B.</b> <p>ABC' + ACD + B'C'D</p>",
            "<b>C.</b> <p>ACD' + A'BC' + AC'D'</p>",
            "<b>D.</b> <p>A'BD + ACD' + BCD'</p>"
          ],
          "correct_answer": "<b>A.</b> <p>BC'D' + A'C'D + AB'D</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48039/isro2009-19\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>The range of integers that can be represented by an n bit 2's complement number system is: <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(-2^{n-1} \\text{ to } (2^{n-1} -1)\\)</p>",
            "<b>B.</b> <p>\\(-(2^{n-1} -1) \\text{ to } (2^{n-1} -1)\\)</p>",
            "<b>C.</b> <p>\\(-2^{n-1} \\text{ to } 2^{n-1}\\)</p>",
            "<b>D.</b> <p>\\(-(2^{n-1} +1) \\text{ to } (2^{n-1} -1)\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(-2^{n-1} \\text{ to } (2^{n-1} -1)\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1352/gate2005-16-isro2009-18-isro2015-2\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
