window.__examLoadCallback({
  "title": "Data_Structure - Hashing",
  "duration": 66,
  "sections": [
    {
      "name": "Hashing",
      "questions": [
        {
          "id": 1,
          "question": "<p>In a double hashing scheme, \\( h_1(k) = k \\mod 11 \\) and \\( h_2(k) = 1 + (k \\mod 7) \\) are the auxiliary hash functions. The size \\( m \\) of the hash table is 11. The hash function for the \\( i \\)-th probe in the open address table is  \\(\n[h_1(k) + i h_2(k)] \\mod m \\)\nThe following keys are inserted in the given order: 63, 50, 25, 79, 67, 24.\n<br><br>\nThe slot at which key 24 gets stored is _________. (Answer in integer) <br><br><strong>(GATE CSE 2025 SET-1)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "10",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/460025/gate-cse-2025-set-1-question-55#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>An algorithm has to store several keys generated by an adversary in a hash\ntable. The adversary is malicious who tries to maximize the number of collisions.\nLet \\( k\\) be the number of keys, \\( m\\) be the number of slots in the hash table, and \\( k \\gt m\\).<br>\nWhich one of the following is the best hashing strategy to counteract the adversary? <br><br><strong>(GATE CSE 2023)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Division method, i.e., use the hash function \\(h(k) = k\\;  mod \\; m\\)</p>",
            "<b>B.</b> <p>Multiplication method, i.e., use the hash function \\( h(k) =  \\left \\lfloor m(kA -\\left \\lfloor kA \\right \\rfloor ) \\right \\rfloor\\), where\n\\(A\\) is a carefully chosen constant.</p>",
            "<b>C.</b> <p>Universal hashing method.</p>",
            "<b>D.</b> <p>If \\(k\\) is a prime number, use Division method. Otherwise, use Multiplication method</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Universal hashing method.</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/399302/gate-cse-2023-question-10#a_list_title\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Suppose we are given \\(n\\) keys, \\(m\\) hash table slots, and two simple uniform hash functions \\(h_1\\) and \\(h_2\\). Further suppose our hashing scheme uses \\(h_1\\) for the odd keys\nand \\(h_2\\) for the even keys. What is the expected number of keys in a slot? <br><br><strong>(GATE CSE 2022)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\frac{m}{n}\\)</p>",
            "<b>B.</b> <p>\\(\\frac{n}{m}\\)</p>",
            "<b>C.</b> <p>\\(\\frac{2n}{m}\\)</p>",
            "<b>D.</b> <p>\\(\\frac{n}{2m}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(\\frac{n}{m}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/371930/Gate-cse-2022-question-6#a_list_title\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>Consider a dynamic hashing approach for 4-bit integer keys:\n<br><br>\n1. There is a main hash table of size 4.<br>\n2. The 2 least significant bits of a key is used to index into the main hash table.<br>\n3. Initially, the main hash table entries are empty.<br>\n4. Thereafter, when more keys are hashed into it, to resolve collisions, the set of all keys corresponding to a main hash table. entry is organized as a binary tree that grows on demand.<br>\n5. First, the 3rd least significant bit is used to divide the keys into left and right subtrees.<br>\n6. To resolve more collisions, each node of the binary tree is further sub-divided into left and right subtrees based on the 4th least significant bit.<br>\n7. A split is done only if it is needed, i.e., only when there is a collision.<br><br>\nConsider the following state of the hash table.  <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Hashing\\q47_ec8a2570.jpg\"><br>\nWhich of the following sequences of key insertions can cause the above state of the hash table (assume the keys are in decimal notation)? <br><br><strong>(GATE CSE 2021 SET-1)</strong></p>",
          "type": "multiple",
          "options": [
            "<b>A.</b> <p>5,9,4,13,10,7</p>",
            "<b>B.</b> <p>9,5,10,6,7,1</p>",
            "<b>C.</b> <p>10,9,6,7,5,13</p>",
            "<b>D.</b> <p>9,5,13,6,10,14</p>"
          ],
          "correct_answer": [
            "<b>C.</b> <p>10,9,6,7,5,13</p>"
          ],
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/357404/gate-cse-2021-set-1-question-47#a_list_title\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>In linear hashing, if blocking factor bfr, loading factor i and file buckets N are known, the number of records will be <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>r=i+bfr+N</p>",
            "<b>B.</b> <p>r=i-bfr-N</p>",
            "<b>C.</b> <p>r=i+bfr-N</p>",
            "<b>D.</b> <p>r=i*bfr*N</p>"
          ],
          "correct_answer": "<b>D.</b> <p>r=i*bfr*N</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331276/isro2020-24\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Consider a double hashing scheme in which the primary hash function is \\(h_1(k)=k\\; mod \\; 23\\), and the secondary hash function is \\(h_2(k)=1+(k\\; mod \\; 19)\\). Assume that the table size is 23. Then the address returned by probe 1 in the probe sequence (assume that the probe sequence begins at probe 0) for key value k=90 is_____________. <br><br><strong>(GATE CSE 2020)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "13",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/333208/gate2020-cs-23#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>A hash table with 10 buckets with one slot pet per bucket is depicted here. The symbols, S1 to S7 are initially entered using a hashing function with linear probing. The maximum number of comparisons needed in searching an item that is not present is:<br>\\(\\begin{array}{|c|c|} \\hline 0 &amp; S 7 \\\\ \\hline 1 &amp; S 1 \\\\ \\hline 2 &amp; \\\\ \\hline 3 &amp; S 4 \\\\ \\hline 4 &amp; S 2 \\\\ \\hline 5 &amp; \\\\ \\hline 6 &amp; S 5 \\\\ \\hline 7 &amp; \\\\ \\hline 8 &amp; S 6 \\\\ \\hline 9 &amp; S 3 \\\\ \\hline \\end{array}\\) <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>4</p>",
            "<b>B.</b> <p>5</p>",
            "<b>C.</b> <p>6</p>",
            "<b>D.</b> <p>3</p>"
          ],
          "correct_answer": "<b>B.</b> <p>5</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213552/isro2018-36\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>A Hash Function f defined as f(key)=keymod7. With linear probing while inserting the keys 37,38,72,48,98,11,56 into a table indexed from 0, in which location key 11 will be stored (Count table index 0 as \\(0^{th}\\) location)? <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>3</p>",
            "<b>B.</b> <p>4</p>",
            "<b>C.</b> <p>5</p>",
            "<b>D.</b> <p>6</p>"
          ],
          "correct_answer": "<b>C.</b> <p>5</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/51315/isro2016-29\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>A hash table with ten buckets with one slot per bucket is shown in the following figure. The symbols S1 to S7 initially entered using a hashing function with linear probing. The maximum number of comparisons needed in searching an item that is not present is<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Hashing\\q14_8c271a02.jpg\"><br> <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>4</p>",
            "<b>B.</b> <p>5</p>",
            "<b>C.</b> <p>6</p>",
            "<b>D.</b> <p>3</p>"
          ],
          "correct_answer": "<b>B.</b> <p>5</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/10905/gate1989-1-vii-isro2015-14\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>Given a hash table T with 25 slots that stores 2000 elements, the load factor \\(\\alpha\\) for T is ____________. <br><br><strong>(GATE CSE 2015 SET-3)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "80",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/8414/gate2015-3-12#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>Which one of the following hash functions on integers will distribute keys most uniformly over 10 buckets numbered 0 to 9 for i ranging from 0 to 2020? <br><br><strong>(GATE CSE 2015 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>h(i)= \\(i^{2}\\) mod 10</p>",
            "<b>B.</b> <p>h(i)= \\(i^{3}\\) mod 10</p>",
            "<b>C.</b> <p>h(i)=(11*\\(i^{2}\\)) mod 10</p>",
            "<b>D.</b> <p>h(i)=(12*\\(i^{2}\\)) mod 10</p>"
          ],
          "correct_answer": "<b>B.</b> <p>h(i)= \\(i^{3}\\) mod 10</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/8152/gate2015-2-40#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>Consider a 13 element hash table for which f(key)=key mod 13 is used with integer keys. Assuming linear probing is used for collision resolution, at which location would the key 103 be inserted, if the keys 661, 182, 24 and 103 are inserted in that order? <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0</p>",
            "<b>B.</b> <p>1</p>",
            "<b>C.</b> <p>11</p>",
            "<b>D.</b> <p>12</p>"
          ],
          "correct_answer": "<b>B.</b> <p>1</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55021/isro2014-64\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>Consider a hash table with 100 slots. Collisions are resolved using chaining. Assuming\nsimple uniform hashing, what is the probability that the first 3 slots are unfilled after the first 3 insertions? <br><br><strong>(GATE CSE 2014 SET-3)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>(97 x 97 x 97)/\\(100^{3}\\)</p>",
            "<b>B.</b> <p>(99 x 98 x 97)/\\(100^{3}\\)</p>",
            "<b>C.</b> <p>(97 x 96 x 95)/\\(100^{3}\\)</p>",
            "<b>D.</b> <p>(97 x 96 x 95)/(3! x \\(100^{3}\\))</p>"
          ],
          "correct_answer": "<b>A.</b> <p>(97 x 97 x 97)/\\(100^{3}\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/2074/gate2014-3-40#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>Consider a hash table with 9 slots. The hash function is h(k)=k mod 9.  The collisions are\nresolved by chaining. The following 9 keys are inserted in the order: 5, 28, 19, 15, 20, 33, 12,\n17, 10. The maximum, minimum, and average chain lengths in the hash table, respectively, are <br><br><strong>(GATE CSE 2014 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>3, 0, and 1</p>",
            "<b>B.</b> <p>3, 3, and 3</p>",
            "<b>C.</b> <p>4, 0, and 1</p>",
            "<b>D.</b> <p>3, 0, and 2</p>"
          ],
          "correct_answer": "<b>A.</b> <p>3, 0, and 1</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/1918/gate2014-1-40#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>A hash table of length 10 uses open addressing with hash function h(k)=k mod 10, and linear probing. After inserting 6 values into an empty hash table,\nthe table is as shown below<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Hashing\\q52_6208e194.jpg\"><br>How many different insertion sequences of the key values using the same hash\nfunction and linear probing will result in the hash table shown above? <br><br><strong>(GATE CSE 2010)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>10</p>",
            "<b>B.</b> <p>20</p>",
            "<b>C.</b> <p>30</p>",
            "<b>D.</b> <p>40</p>"
          ],
          "correct_answer": "<b>C.</b> <p>30</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/43327/gate2010-53#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 16,
          "question": "<p>A hash table of length 10 uses open addressing with hash function h(k)=k mod 10, and linear probing. After inserting 6 values into an empty hash table,\nthe table is as shown below<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Hashing\\q52_6208e194.jpg\"><br>\nWhich one of the following choices gives a possible order in which the key values\ncould have been inserted in the table? <br><br><strong>(GATE CSE 2010)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>46, 42, 34, 52, 23, 33</p>",
            "<b>B.</b> <p>34, 42, 23, 52, 33, 46</p>",
            "<b>C.</b> <p>46, 34, 42, 23, 52, 33</p>",
            "<b>D.</b> <p>42, 46, 33, 23, 34, 52</p>"
          ],
          "correct_answer": "<b>C.</b> <p>46, 34, 42, 23, 52, 33</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/2360/gate2010-52#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 17,
          "question": "<p>The keys 12, 18, 13, 2, 3, 23, 5 and 15 are inserted into an initially empty hash table of length 10 using open addressing with hash function h(k) = k mod 10 and linear probing. What is the resultant hash table?<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Hashing\\q36_a0accceb.jpg\"> <br><br><strong>(GATE CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A</p>",
            "<b>B.</b> <p>B</p>",
            "<b>C.</b> <p>C</p>",
            "<b>D.</b> <p>D</p>"
          ],
          "correct_answer": "<b>C.</b> <p>C</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/1322/gate2009-36#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 18,
          "question": "<p>Consider a hash table of size 11 that uses open addressing with linear probing. Let h(k)=kmod 11 be the hash function used. A sequence of records with keys <br>\n43 36 92 87 11 4 71 13 14 <br>\nis inserted into an initially empty hash table, the bins of which are indexed from zero to ten. What is the index of the bin into which the last record is inserted? <br><br><strong>(GATE IT 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>3</p>",
            "<b>B.</b> <p>4</p>",
            "<b>C.</b> <p>6</p>",
            "<b>D.</b> <p>7</p>"
          ],
          "correct_answer": "<b>D.</b> <p>7</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/3358/gate2008-it-48\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 19,
          "question": "<p>Consider a hash function that distributes keys uniformly. The hash table size is 20. After hashing of how many keys will the probability that any new key hashed collides with an existing one exceed 0.5. <br><br><strong>(GATE IT 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>5</p>",
            "<b>B.</b> <p>6</p>",
            "<b>C.</b> <p>7</p>",
            "<b>D.</b> <p>10</p>"
          ],
          "correct_answer": "<b>B.</b> <p>6</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3461/gate2007-it-28\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 20,
          "question": "<p>Consider a hash table of size seven, with starting index zero, and a hash function\n(3x + 4)mod7. Assuming the hash table is initially empty, which of the following\nis the contents of the table when the sequence 1, 3, 8, 10 is inserted into the\ntable using closed hashing? Note that '-' denotes an empty location in the table. <br><br><strong>(GATE CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>8, -, -, -, -, -, 10</p>",
            "<b>B.</b> <p>1, 8, 10, -, -, -, 3</p>",
            "<b>C.</b> <p>1, -, -, -, -, -, 3</p>",
            "<b>D.</b> <p>1, 10, 8, -, -, -, 3</p>"
          ],
          "correct_answer": "<b>B.</b> <p>1, 8, 10, -, -, -, 3</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1238/gate2007-40#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 21,
          "question": "<p>A hash table contains 10 buckets and uses linear probing to resolve collisions. The key values are integers and the hash function used is key % 10. If the values 43, 165, 62, 123, 142 are inserted in the table, in what location would the key value 142 be inserted? <br><br><strong>(GATE IT 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>2</p>",
            "<b>B.</b> <p>3</p>",
            "<b>C.</b> <p>4</p>",
            "<b>D.</b> <p>6</p>"
          ],
          "correct_answer": "<b>D.</b> <p>6</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3761/gate2005-it-16\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 22,
          "question": "<p>Given the following input (4322, 1334, 1471, 9679, 1989, 6171, 6173, 4199) and the hash function x\nmod 10, which of the following statements are true?  <br>\ni)   9679, 1989, 4199 hash to the same value <br>\nii)  1471, 6171 has to the same value <br>\niii) All elements hash to the same value <br>\niv) Each element hashes to a different value <br><br><strong>(GATE CSE 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>i only</p>",
            "<b>B.</b> <p>ii only</p>",
            "<b>C.</b> <p>i and ii only</p>",
            "<b>D.</b> <p>iii or iv</p>"
          ],
          "correct_answer": "<b>C.</b> <p>i and ii only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1004/gate2004-7#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 23,
          "question": "<p>An advantage of chained hash table (external hashing) over the open addressing scheme is <br><br><strong>(GATE CSE 1996)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Worst case complexity of search operations is less</p>",
            "<b>B.</b> <p>Space used is less</p>",
            "<b>C.</b> <p>Deletion is easier</p>",
            "<b>D.</b> <p>None of the above</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Deletion is easier</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2717/gate1996-1-13\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 24,
          "question": "<p>A hash table with ten buckets with one slot per bucket is shown in the following figure. The symbols S1 to S7 initially entered using a hashing function with linear probing. The maximum number of comparisons needed in searching an item that is not present is<br>\\(\\begin{array}{|l|l|} \\hline 0 &amp; \\text { S7 } \\\\ \\hline 1 &amp; \\text { S1 } \\\\ \\hline 2 &amp; \\\\ \\hline 3 &amp; \\text { S4 } \\\\ \\hline 4 &amp; \\text { S2 } \\\\ \\hline 5 &amp; \\text { } \\\\ \\hline 6 &amp; \\text { S5 } \\\\ \\hline 7 &amp; \\\\ \\hline 8 &amp; \\text { S6 } \\\\ \\hline 9 &amp; \\text { S3 } \\\\ \\hline \\end{array}\\) <br><br><strong>(GATE CSE 1989)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>4</p>",
            "<b>B.</b> <p>5</p>",
            "<b>C.</b> <p>6</p>",
            "<b>D.</b> <p>3</p>"
          ],
          "correct_answer": "<b>B.</b> <p>5</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/10905/gate1989-1-vii-isro2015-14\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
