window.__examLoadCallback({
  "title": "Data Structures - Binary Search Tree",
  "duration": 100,
  "sections": [
    {
      "name": "Binary Search Tree",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"2743\"></a><div itemprop=\"text\"><p>A binary search tree is generated by inserting in order the following integers:</p>\n\n<p>\\[ 50, 15, 62, 5, 20, 58, 91, 3, 8, 37, 60, 24 \\]</p>\n\n<p>The number of nodes in the left subtree and right subtree of the root respectively is</p>\n\n</div><br><br><b>GATE CSE 1996 | Question: 2.14</b></p>",
          "type": "single",
          "options": [
            "<p>\\( (4, 7) \\)</p>",
            "<p>\\( (7, 4) \\)</p>",
            "<p>\\( (8, 3) \\)</p>",
            "<p>\\( (3, 8) \\)</p>"
          ],
          "correct_answer": "<p>\\( (7, 4) \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/2743/gate-cse-1996-question-2-14\" target=\"_blank\">https://gateoverflow.in/2743/gate-cse-1996-question-2-14</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"2756\"></a><div itemprop=\"text\">A binary search tree is used to locate the number \\( 43 \\). Which of the following probe sequences are possible and which are not? Explain.<br>\n<br>\n\\( \\begin{array}{llllll} \\text{(a)} &nbsp;&amp; &nbsp;\\text{61} &amp; \\text{52} &amp; \\text{14} &amp; &nbsp;\\text{17} &amp; \\text{40} &amp; \\text{43} \\\\<br>\n&nbsp;\\text{(b)} &nbsp;&amp; &nbsp;\\text{2}&amp; &nbsp;\\text{3} &amp; \\text{50} &amp; &nbsp;\\text{40} &amp; \\text{60} &amp; \\text{43} \\\\<br>\n&nbsp;\\text{(c)} &nbsp;&amp; &nbsp;\\text{10} &amp; \\text{65} &amp; \\text{31} &amp; &nbsp;\\text{48}&amp; &nbsp;\\text{37} &amp; \\text{43} \\\\<br>\n&nbsp;\\text{(d)} &nbsp;&amp; &nbsp;\\text{81} &nbsp;&amp;\\text{61} &amp; \\text{52} &amp; &nbsp;\\text{14} &amp; \\text{41} &amp; \\text{43} \\\\<br>\n&nbsp;\\text{(e)} &nbsp;&amp; &nbsp;\\text{17} &amp; \\text{77} &amp; \\text{27} &amp; &nbsp;\\text{66}&amp; &nbsp;\\text{18} &amp; \\text{43} &nbsp;&nbsp;\\end{array} \\)</div><br><br><b>GATE CSE 1996 | Question: 4</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "N/A",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/2756/gate-cse-1996-question-4\" target=\"_blank\">https://gateoverflow.in/2756/gate-cse-1996-question-4</a></p>"
        },
        {
          "id": 3,
          "question": "<p><a name=\"2246\"></a><div itemprop=\"text\"><p>A binary search tree contains the value \\( 1, 2, 3, 4, 5, 6, 7, 8 \\). The tree is traversed in pre-order and the values are printed out. Which of the following sequences is a valid output?</p>\n\n</div><br><br><b>GATE CSE 1997 | Question: 4.5</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 5 \\ 3 \\ 1 \\ 2 \\ 4 \\ 7 \\ 8 \\ 6 \\)</p>",
            "<p>\\( 5 \\ 3 \\ 1 \\ 2 \\ 6 \\ 4 \\ 8 \\ 7 \\)</p>",
            "<p>\\( 5 \\ 3 \\ 2 \\ 4 \\ 1 \\ 6 \\ 7 \\ 8 \\)</p>",
            "<p>\\( 5 \\ 3 \\ 1 \\ 2 \\ 4 \\ 7 \\ 6 \\ 8 \\)</p>"
          ],
          "correct_answer": "<p>\\( 5 \\ 3 \\ 1 \\ 2 \\ 4 \\ 7 \\ 6 \\ 8 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/2246/gate-cse-1997-question-4-5\" target=\"_blank\">https://gateoverflow.in/2246/gate-cse-1997-question-4-5</a></p>"
        },
        {
          "id": 4,
          "question": "<p><a name=\"755\"></a><div itemprop=\"text\"></div><br><br><b>GATE CSE 2001 | Question: 14</b></p>",
          "type": "numeric",
          "options": [
            "<p>Insert the following keys one by one into a binary search tree in the order specified.\\[ 15, 32, 20, 9, 3, 25, 12, 1 \\]Show the final binary search tree after the insertions.</p>",
            "<p>Draw the binary search tree after deleting \\( 15 \\) from it.</p>",
            "<p>Complete the statements \\( S1 \\), \\( S2 \\)&nbsp;and \\( S3 \\) in the following function so that the function computes the depth of a binary tree rooted at \\( t \\).\n\t<pre class=\"prettyprint lang-c_cpp\">typedef struct tnode{\n    int key;\n    struct tnode *left, *right;\n} *Tree;\n\nint depth (Tree t)\n{\n    int x, y;\n    if (t == NULL) return 0;\n    x = depth (t -&gt; left);\nS1:     ___________;\n\nS2:     if (x &gt; y) return __________;\n\nS3:     else return _______;\n\n}\n</pre></p>"
          ],
          "correct_answer": "N/A",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/755/gate-cse-2001-question-14\" target=\"_blank\">https://gateoverflow.in/755/gate-cse-2001-question-14</a></p>"
        },
        {
          "id": 5,
          "question": "<p><a name=\"909\"></a><div itemprop=\"text\"><p>Suppose the numbers \\( 7, 5, 1, 8, 3, 6, 0, 9, 4, 2 \\) are inserted in that order into an initially empty binary search tree. The binary search tree uses the usual ordering on natural numbers. What is the in-order traversal sequence of the resultant tree?</p></div><br><br><b>GATE CSE 2003 | Question: 19, ISRO2009-24</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 7 \\&nbsp;5&nbsp; \\ 1 \\ 0 \\ 3 \\ 2 \\ 4 \\ 6 \\ 8 \\ 9 \\)</p>",
            "<p>\\( 0 \\ 2 \\&nbsp;4 \\ 3 \\ 1 \\ 6 \\&nbsp;5&nbsp; \\ 9&nbsp; \\ 8&nbsp; \\ 7 \\)</p>",
            "<p>\\( 0 \\ 1 \\ 2 \\ 3 \\ 4 \\ 5 \\ 6 \\ 7 \\ 8 \\ 9 \\)</p>",
            "<p>\\( 9 \\ 8 \\ 6 \\ 4&nbsp; \\ 2&nbsp; \\ 3 \\ 0 \\ 1 \\ 5 \\ 7 \\)</p>"
          ],
          "correct_answer": "<p>\\( 0 \\ 1 \\ 2 \\ 3 \\ 4 \\ 5 \\ 6 \\ 7 \\ 8 \\ 9 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/909/gate-cse-2003-question-19-isro2009-24\" target=\"_blank\">https://gateoverflow.in/909/gate-cse-2003-question-19-isro2009-24</a></p>"
        },
        {
          "id": 6,
          "question": "<p><a name=\"897\"></a><div itemprop=\"text\"><p>Let \\( T(n) \\) be the number of different binary search trees on \\( n \\) distinct elements.</p>\n\n<p>Then \\( T(n) = \\sum_{k=1}^{n} T(k-1)T(x) \\), where \\( x \\) is&nbsp;</p>\n\n</div><br><br><b>GATE CSE 2003 | Question: 6</b></p>",
          "type": "single",
          "options": [
            "<p>\\( n-k+1 \\)</p>",
            "<p>\\( n-k \\)</p>",
            "<p>\\( n-k-1 \\)</p>",
            "<p>\\( n-k-2 \\)</p>"
          ],
          "correct_answer": "<p>\\( n-k \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/897/gate-cse-2003-question-6\" target=\"_blank\">https://gateoverflow.in/897/gate-cse-2003-question-6</a></p>"
        },
        {
          "id": 7,
          "question": "<p><a name=\"950\"></a><div itemprop=\"text\"><p>A data structure is required for storing a set of integers such that each of the following operations can be done in \\( O(\\log n) \\) time, where \\( n \\) is the number of elements in the set.</p>\n\n<ol style=\"list-style-type:upper-roman\">\n\t<li>\n\t<p>Deletion of the smallest element</p>\n\t</li>\n\t<li>Insertion of an element if it is not already present in the set</li>\n</ol>\n\n<p>Which of the following data structures can be used for this purpose?</p>\n\n</div><br><br><b>GATE CSE 2003 | Question: 63, ISRO2009-25</b></p>",
          "type": "single",
          "options": [
            "<p>A heap can be used but not a balanced binary search tree</p>",
            "<p>A balanced binary search tree can be used but not a heap</p>",
            "<p>Both balanced binary search tree and heap can be used</p>",
            "<p>Neither balanced search tree nor heap can be used</p>"
          ],
          "correct_answer": "<p>A balanced binary search tree can be used but not a heap</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/950/gate-cse-2003-question-63-isro2009-25\" target=\"_blank\">https://gateoverflow.in/950/gate-cse-2003-question-63-isro2009-25</a></p>"
        },
        {
          "id": 8,
          "question": "<p><a name=\"1001\"></a><div itemprop=\"text\"><p>The following numbers are inserted into an empty binary search tree in the given order: \\( 10, 1, 3, 5, 15, 12, 16 \\). What is the height of the binary search tree (the height is the maximum distance of a leaf node from the root)?</p>\n\n\n\n</div><br><br><b>GATE CSE 2004 | Question: 4, ISRO2009-26</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 2 \\)</p>",
            "<p>\\( 3 \\)</p>",
            "<p>\\( 4 \\)</p>",
            "<p>\\( 6 \\)</p>"
          ],
          "correct_answer": "<p>\\( 3 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/1001/gate-cse-2004-question-4-isro2009-26\" target=\"_blank\">https://gateoverflow.in/1001/gate-cse-2004-question-4-isro2009-26</a></p>"
        },
        {
          "id": 9,
          "question": "<p><a name=\"1079\"></a><div itemprop=\"text\"><p>A program takes as input a balanced binary search tree with \\( n \\)&nbsp;leaf nodes and computes the value of a function \\( g(x) \\) for each node \\( x \\). If the cost of computing \\( g(x) \\) is:&nbsp;\\[ \\Large \\min \\left ( \\substack{\\text{number of leaf-nodes}\\\\\\text{in left-subtree of \\( x \\)}}\\;,\\; \\substack{\\text{number of leaf-nodes}\\\\\\text{in right-subtree of \\( x \\)}}\\right ) \\]</p>\n\n<p>Then the worst-case time complexity of the program is?</p>\n\n</div><br><br><b>GATE CSE 2004 | Question: 85</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\Theta&nbsp;(n) \\)</p>",
            "<p>\\( \\Theta&nbsp;(n \\log n) \\)</p>",
            "<p>\\( \\Theta(n^2) \\)</p>",
            "<p>\\( \\Theta&nbsp;(n^2\\log n) \\)</p>"
          ],
          "correct_answer": "<p>\\( \\Theta&nbsp;(n \\log n) \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/1079/gate-cse-2004-question-85\" target=\"_blank\">https://gateoverflow.in/1079/gate-cse-2004-question-85</a></p>"
        },
        {
          "id": 10,
          "question": "<p><a name=\"1369\"></a><div itemprop=\"text\"><p>Postorder traversal of a given binary search tree, \\( T \\) produces the following sequence of keys</p>\n\n<p>\\( 10, 9, 23, 22, 27, 25, 15, 50, 95, 60, 40, 29 \\)</p>\n\n<p>Which one of the following sequences of keys can be the result of an in-order traversal of the tree \\( T \\)?</p>\n\n</div><br><br><b>GATE CSE 2005 | Question: 33</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 9, 10, 15, 22, 23, 25, 27, 29, 40, 50, 60, 95 \\)</p>",
            "<p>\\( 9, 10, 15, 22, 40, 50, 60, 95, 23, 25, 27, 29 \\)</p>",
            "<p>\\( 29, 15, 9, 10, 25, 22, 23, 27, 40, 60, 50, 95 \\)</p>",
            "<p>\\( 95, 50, 60, 40, 27, 23, 22, 25, 10, 9, 15, 29 \\)</p>"
          ],
          "correct_answer": "<p>\\( 9, 10, 15, 22, 23, 25, 27, 29, 40, 50, 60, 95 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/1369/gate-cse-2005-question-33\" target=\"_blank\">https://gateoverflow.in/1369/gate-cse-2005-question-33</a></p>"
        },
        {
          "id": 11,
          "question": "<p><a name=\"1371\"></a><div itemprop=\"text\"><p>How many distinct binary search trees can be created out of \\( 4 \\) distinct keys?</p>\n\n</div><br><br><b>GATE CSE 2005 | Question: 35</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 5 \\)</p>",
            "<p>\\( 14 \\)</p>",
            "<p>\\( 24 \\)</p>",
            "<p>\\( 42 \\)</p>"
          ],
          "correct_answer": "<p>\\( 14 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/1371/gate-cse-2005-question-35\" target=\"_blank\">https://gateoverflow.in/1371/gate-cse-2005-question-35</a></p>"
        },
        {
          "id": 12,
          "question": "<p><a name=\"458\"></a><div itemprop=\"text\"><p>You are given the postorder traversal, \\( P \\),&nbsp; of a binary search tree on the \\( n \\) elements \\( 1, 2, \\dots,&nbsp;n \\). You have to determine the unique binary search tree that has \\( P \\) as its postorder traversal. What is the time complexity of the most efficient algorithm for doing this?</p>\n\n</div><br><br><b>GATE CSE 2008 | Question: 46</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\Theta(\\log n) \\)</p>",
            "<p>\\( \\Theta(n) \\)</p>",
            "<p>\\( \\Theta(n\\log n) \\)</p>",
            "<p>None of the above, as the tree cannot be uniquely determined</p>"
          ],
          "correct_answer": "<p>\\( \\Theta(n) \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/458/gate-cse-2008-question-46\" target=\"_blank\">https://gateoverflow.in/458/gate-cse-2008-question-46</a></p>"
        },
        {
          "id": 13,
          "question": "<p><a name=\"37\"></a><div itemprop=\"text\"><p>The worst case running time to search for an element in a balanced binary search tree with \\( n2^{n} \\) elements is</p>\n\n</div><br><br><b>GATE CSE 2012 | Question: 5</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\Theta(n\\log n) \\)</p>",
            "<p>\\( \\Theta(n2^n) \\)</p>",
            "<p>\\( \\Theta(n) \\)</p>",
            "<p>\\( \\Theta(\\log n) \\)</p>"
          ],
          "correct_answer": "<p>\\( \\Theta(n) \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/37/gate-cse-2012-question-5\" target=\"_blank\">https://gateoverflow.in/37/gate-cse-2012-question-5</a></p>"
        },
        {
          "id": 14,
          "question": "<p><a name=\"1554\"></a><div itemprop=\"text\"><p>The preorder traversal sequence of a binary search tree is \\( 30, 20, 10, 15, 25, 23, 39, 35, 42 \\). Which one of the following is the postorder traversal sequence of the same tree?</p>\n\n</div><br><br><b>GATE CSE 2013 | Question: 43</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 10, 20, 15, 23, 25, 35, 42, 39, 30 \\)</p>",
            "<p>\\( 15, 10, 25, 23, 20, 42, 35, 39, 30 \\)</p>",
            "<p>\\( 15, 20, 10, 23, 25, 42, 35, 39, 30 \\)</p>",
            "<p>\\( 15, 10, 23, 25, 20, 35, 42, 39, 30 \\)</p>"
          ],
          "correct_answer": "<p>\\( 15, 10, 23, 25, 20, 35, 42, 39, 30 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/1554/gate-cse-2013-question-43\" target=\"_blank\">https://gateoverflow.in/1554/gate-cse-2013-question-43</a></p>"
        },
        {
          "id": 15,
          "question": "<p><a name=\"1416\"></a><div itemprop=\"text\"><p>Which one of the following is the tightest upper bound that represents the time complexity of inserting an object into a binary search tree of \\( n \\) nodes?</p>\n\n</div><br><br><b>GATE CSE 2013 | Question: 7</b></p>",
          "type": "single",
          "options": [
            "<p>\\( O(1) \\)</p>",
            "<p>\\( O(\\log n) \\)</p>",
            "<p>\\( O(n) \\)</p>",
            "<p>\\( O(n&nbsp;\\log n) \\)</p>"
          ],
          "correct_answer": "<p>\\( O(n) \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/1416/gate-cse-2013-question-7\" target=\"_blank\">https://gateoverflow.in/1416/gate-cse-2013-question-7</a></p>"
        },
        {
          "id": 16,
          "question": "<p><a name=\"2073\"></a><div itemprop=\"text\">Suppose we have a balanced binary search tree \\( T \\) holding \\( n \\) numbers. We are given two numbers \\( L \\) and \\( H \\) and wish to sum up all the numbers in \\( T \\) that lie between \\( L \\) and \\( H \\). Suppose there are \\( m \\) such numbers in \\( T \\). If the tightest upper bound on the time to compute the sum is \\( O(n^a\\log^bn+m^c\\log^dn) \\), the value of \\( a+10b+100c+1000d \\) is ______.</div><br><br><b>GATE CSE 2014 Set 3 | Question: 39</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "110",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/2073/gate-cse-2014-set-3-question-39\" target=\"_blank\">https://gateoverflow.in/2073/gate-cse-2014-set-3-question-39</a></p>"
        },
        {
          "id": 17,
          "question": "<p><a name=\"8129\"></a><div itemprop=\"text\"><p>Which of the following is/are correct in order traversal sequence(s) of binary search tree(s)?</p>\n\n<ol style=\"list-style-type:upper-roman\">\n\t<li>\\( 3, 5, 7, 8, 15, 19, 25 \\)</li>\n\t<li>\\( 5, 8, 9, 12, 10, 15, 25 \\)</li>\n\t<li>\\( 2, 7, 10, 8, 14, 16, 20 \\)</li>\n\t<li>\\( 4, 6, 7, 9, 18, 20, 25 \\)</li>\n</ol>\n\n\n\n</div><br><br><b>GATE CSE 2015 Set 1 | Question: 10</b></p>",
          "type": "single",
          "options": [
            "<p>I and IV only</p>",
            "<p>II and III only</p>",
            "<p>II and IV only</p>",
            "<p>II only</p>"
          ],
          "correct_answer": "<p>I and IV only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/8129/gate-cse-2015-set-1-question-10\" target=\"_blank\">https://gateoverflow.in/8129/gate-cse-2015-set-1-question-10</a></p>"
        },
        {
          "id": 18,
          "question": "<p><a name=\"8221\"></a><div itemprop=\"text\"><p>What are the worst-case complexities of insertion and deletion of a key in a binary search tree?</p>\n\n</div><br><br><b>GATE CSE 2015 Set 1 | Question: 23</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\Theta(\\log n) \\) for both insertion and deletion</p>",
            "<p>\\( \\Theta(n) \\) for both insertion and deletion</p>",
            "<p>\\( \\Theta(n) \\) for insertion and&nbsp;\\( \\Theta(\\log n) \\) for deletion</p>",
            "<p>\\( \\Theta(\\log n) \\) for insertion and&nbsp;\\( \\Theta(n) \\) for deletion</p>"
          ],
          "correct_answer": "<p>\\( \\Theta(n) \\) for both insertion and deletion</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/8221/gate-cse-2015-set-1-question-23\" target=\"_blank\">https://gateoverflow.in/8221/gate-cse-2015-set-1-question-23</a></p>"
        },
        {
          "id": 19,
          "question": "<p><a name=\"8409\"></a><div itemprop=\"text\"><p>While inserting the elements \\( 71, 65, 84, 69, 67, 83 \\) in an empty binary search tree (BST) in the sequence shown, the element in the lowest level is</p>\n\n</div><br><br><b>GATE CSE 2015 Set 3 | Question: 13</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 65 \\)</p>",
            "<p>\\( 67 \\)</p>",
            "<p>\\( 69 \\)</p>",
            "<p>\\( 83 \\)</p>"
          ],
          "correct_answer": "<p>\\( 67 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/8409/gate-cse-2015-set-3-question-13\" target=\"_blank\">https://gateoverflow.in/8409/gate-cse-2015-set-3-question-13</a></p>"
        },
        {
          "id": 20,
          "question": "<p><a name=\"39586\"></a><div itemprop=\"text\">The number of ways in which the numbers \\( 1, 2, 3, 4, 5, 6, 7 \\) can be inserted in an empty binary search tree, such that the resulting tree has height \\( 6 \\), is _________.<br>\n<br>\nNote: The height of a tree with a single node is \\( 0 \\).</div><br><br><b>GATE CSE 2016 Set 2 | Question: 40</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "64",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/39586/gate-cse-2016-set-2-question-40\" target=\"_blank\">https://gateoverflow.in/39586/gate-cse-2016-set-2-question-40</a></p>"
        },
        {
          "id": 21,
          "question": "<p><a name=\"118286\"></a><div itemprop=\"text\"><p>Let \\( T \\) be a binary search tree with \\( 15 \\) nodes. The minimum and maximum possible heights of \\( T \\) are:</p>\n\n<p><em>Note: The height of a tree with a single node is </em>\\( 0 \\)<em>.</em></p>\n\n</div><br><br><b>GATE CSE 2017 Set 1 | Question: 6</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 4 \\) and \\( 15 \\) respectively.</p>",
            "<p>\\( 3 \\) and \\( 14 \\) respectively.</p>",
            "<p>\\( 4 \\) and \\( 14 \\) respectively.</p>",
            "<p>\\( 3 \\) and \\( 15 \\) respectively.</p>"
          ],
          "correct_answer": "<p>\\( 3 \\) and \\( 14 \\) respectively.</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/118286/gate-cse-2017-set-1-question-6\" target=\"_blank\">https://gateoverflow.in/118286/gate-cse-2017-set-1-question-6</a></p>"
        },
        {
          "id": 22,
          "question": "<p><a name=\"118378\"></a><div itemprop=\"text\"><p>The pre-order traversal of a binary search tree is given by \\( 12, 8, 6, 2, 7, 9, 10, 16, 15, 19, 17, 20 \\). Then the post-order traversal of this tree is</p>\n\n</div><br><br><b>GATE CSE 2017 Set 2 | Question: 36</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 2, 6, 7, 8, 9, 10, 12, 15, 16, 17, 19, 20 \\)</p>",
            "<p>\\( 2, 7, 6, 10, 9, 8, 15, 17, 20, 19, 16, 12 \\)</p>",
            "<p>\\( 7, 2, 6, 8, 9, 10,&nbsp;20, 17, 19, 15, 16, 12 \\)</p>",
            "<p>\\( 7, 6, 2, 10, 9, 8, 15, 16, 17, 20, 19, 12 \\)</p>"
          ],
          "correct_answer": "<p>\\( 2, 7, 6, 10, 9, 8, 15, 17, 20, 19, 16, 12 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/118378/gate-cse-2017-set-2-question-36\" target=\"_blank\">https://gateoverflow.in/118378/gate-cse-2017-set-2-question-36</a></p>"
        },
        {
          "id": 23,
          "question": "<p><a name=\"333190\"></a><div itemprop=\"text\"><p>In a balanced binary search tree with \\( n \\) elements, what is the worst case time complexity of reporting all elements in range \\( [a,b] \\)? Assume that the number of reported elements is \\( k \\).</p>\n\n</div><br><br><b>GATE CSE 2020 | Question: 41</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\Theta (\\log n) \\)</p>",
            "<p>\\( \\Theta (\\log n +k) \\)</p>",
            "<p>\\( \\Theta (k \\log n) \\)</p>",
            "<p>\\( \\Theta ( n \\log k) \\)</p>"
          ],
          "correct_answer": "<p>\\( \\Theta (\\log n +k) \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/333190/gate-cse-2020-question-41\" target=\"_blank\">https://gateoverflow.in/333190/gate-cse-2020-question-41</a></p>"
        },
        {
          "id": 24,
          "question": "<p><a name=\"333226\"></a><div itemprop=\"text\"><p>The preorder traversal of a binary search tree is \\( 15, 10, 12, 11, 20, 18, 16, 19 \\). Which one of the following is the postorder&nbsp;traversal of the tree?</p>\n\n</div><br><br><b>GATE CSE 2020 | Question: 5</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 10,11,12,15,16,18,19,20 \\)</p>",
            "<p>\\( 11,12,10,16,19,18,20,15 \\)</p>",
            "<p>\\( 20,19,18,16,15,12,11,10 \\)</p>",
            "<p>\\( 19,16,18,20,11,12,10,15 \\)</p>"
          ],
          "correct_answer": "<p>\\( 11,12,10,16,19,18,20,15 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/333226/gate-cse-2020-question-5\" target=\"_blank\">https://gateoverflow.in/333226/gate-cse-2020-question-5</a></p>"
        },
        {
          "id": 25,
          "question": "<p><a name=\"357442\"></a><div itemprop=\"text\"><p>A binary search tree \\( T \\) contains \\( n \\) distinct elements. What is the time complexity of picking an element in \\( T \\) that is smaller than the maximum element in \\( T \\)?</p>\n\n</div><br><br><b>GATE CSE 2021 Set 1 | Question: 10</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\Theta(n\\log n) \\)</p>",
            "<p>\\( \\Theta(n) \\)</p>",
            "<p>\\( \\Theta(\\log n) \\)</p>",
            "<p>\\( \\Theta (1) \\)</p>"
          ],
          "correct_answer": "<p>\\( \\Theta (1) \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/357442/gate-cse-2021-set-1-question-10\" target=\"_blank\">https://gateoverflow.in/357442/gate-cse-2021-set-1-question-10</a></p>"
        },
        {
          "id": 26,
          "question": "<p><a name=\"371918\"></a><div itemprop=\"text\">Suppose a binary search tree with \\( 1000 \\) distinct elements is also a complete binary tree. The tree is stored using the array representation of binary heap trees. Assuming that the array indices start with \\( 0, \\) the \\( 3^{\\text{rd}} \\) largest element of the tree is stored at index ______________ .</div><br><br><b>GATE CSE 2022 | Question: 18</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "509",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/371918/gate-cse-2022-question-18\" target=\"_blank\">https://gateoverflow.in/371918/gate-cse-2022-question-18</a></p>"
        },
        {
          "id": 27,
          "question": "<p><a name=\"422868\"></a><div itemprop=\"text\"><p>​​​​​​You are given a set \\( V \\) of distinct integers. A binary search tree \\( T \\) is created by inserting all elements of \\( V \\) one by one, starting with an empty tree. The tree \\( T \\) follows the convention that, at each node, all values stored in the left subtree of the node are smaller than the value stored at the node. You are not aware of the sequence in which these values were inserted into \\( T \\), and you do not have access to \\( T \\).</p><p>Which one of the following statements is TRUE?</p></div><br><br><b>GATE CSE 2024 | Set 2 | Question: 29</b></p>",
          "type": "single",
          "options": [
            "<p>Inorder traversal of \\( T \\) can be determined from \\( V \\)</p>",
            "<p>Root node of \\( T \\) can be determined from \\( V \\)</p>",
            "<p>Preorder traversal of \\( T \\) can be determined from \\( V \\)</p>",
            "<p>Postorder traversal of \\( T \\) can be determined from \\( V \\)</p>"
          ],
          "correct_answer": "<p>Inorder traversal of \\( T \\) can be determined from \\( V \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/422868/gate-cse-2024-set-2-question-29\" target=\"_blank\">https://gateoverflow.in/422868/gate-cse-2024-set-2-question-29</a></p>"
        },
        {
          "id": 28,
          "question": "<p><a name=\"460064\"></a><div itemprop=\"text\"><p>Which of the following statement(s) is/are TRUE for any binary search tree (BST) having \\( n \\) distinct integers?</p></div><br><br><b>GATE CSE 2025 | Set 1 | Question: 16</b></p>",
          "type": "multiple",
          "options": [
            "<p>The maximum length of a path from the root node to any other node is \\( (n-1) \\).</p>",
            "<p>An inorder traversal will always produce a sorted sequence of elements.</p>",
            "<p>Finding an element takes \\( O\\left(\\log _{2} n\\right) \\) time in the worst case.</p>",
            "<p>Every BST is also a Min-Heap.</p>"
          ],
          "correct_answer": [
            "<p>The maximum length of a path from the root node to any other node is \\( (n-1) \\).</p>",
            "<p>An inorder traversal will always produce a sorted sequence of elements.</p>"
          ],
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/460064/gate-cse-2025-set-1-question-16\" target=\"_blank\">https://gateoverflow.in/460064/gate-cse-2025-set-1-question-16</a></p>"
        },
        {
          "id": 29,
          "question": "<p><a name=\"460810\"></a><div itemprop=\"text\">Suppose the values \\( 10,-4,15,30,20,5,60,19 \\) are inserted in that order into an initially empty binary search tree. Let \\( T \\) be the resulting binary search tree. The number of edges in the path from the node containing \\( 19 \\) to the root node of \\( T \\) is _________. (Answer in integer)</div><br><br><b>GATE CSE 2025 | Set 2 | Question: 25</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "4:4",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/460810/gate-cse-2025-set-2-question-25\" target=\"_blank\">https://gateoverflow.in/460810/gate-cse-2025-set-2-question-25</a></p>"
        },
        {
          "id": 30,
          "question": "<p><a name=\"3757\"></a><div itemprop=\"text\"><p>The numbers \\( 1, 2, .\\dots n \\) are inserted in a binary search tree in some order. In the resulting tree, the right subtree of the root contains \\( p \\) nodes. The first number to be inserted in the tree must be</p>\n\n</div><br><br><b>GATE IT 2005 | Question: 12</b></p>",
          "type": "single",
          "options": [
            "<p>\\( p \\)</p>",
            "<p>\\( p + 1 \\)</p>",
            "<p>\\( n - p \\)</p>",
            "<p>\\( n - p + 1 \\)</p>"
          ],
          "correct_answer": "<p>\\( n - p \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/3757/gate-it-2005-question-12\" target=\"_blank\">https://gateoverflow.in/3757/gate-it-2005-question-12</a></p>"
        },
        {
          "id": 31,
          "question": "<p><a name=\"3816\"></a><div itemprop=\"text\"><p>A binary search tree contains the numbers \\( 1, 2, 3, 4, 5, 6, 7, 8. \\)&nbsp;When the tree is traversed in pre-order and the values in each node printed out, the sequence of values obtained is \\( 5, 3, 1, 2, 4, 6, 8, 7. \\) If the tree is traversed in post-order, the sequence obtained would be</p>\n\n</div><br><br><b>GATE IT 2005 | Question: 55</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 8, 7, 6, 5, 4, 3, 2, 1 \\)</p>",
            "<p>\\( 1, 2, 3, 4, 8, 7, 6, 5 \\)</p>",
            "<p>\\( 2, 1, 4, 3, 6, 7, 8, 5 \\)</p>",
            "<p>\\( 2, 1, 4, 3, 7, 8, 6, 5 \\)</p>"
          ],
          "correct_answer": "<p>\\( 2, 1, 4, 3, 7, 8, 6, 5 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/3816/gate-it-2005-question-55\" target=\"_blank\">https://gateoverflow.in/3816/gate-it-2005-question-55</a></p>"
        },
        {
          "id": 32,
          "question": "<p><a name=\"3588\"></a><div itemprop=\"text\"><p>Suppose that we have numbers between \\( 1 \\) and \\( 100 \\) in a binary search tree and want to search for the number \\( 55 \\). Which of the following sequences CANNOT be the sequence of nodes examined?</p>\n\n</div><br><br><b>GATE IT 2006 | Question: 45</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\{10, 75, 64, 43, 60, 57, 55\\} \\)</p>",
            "<p>\\( \\{90, 12, 68, 34, 62, 45, 55\\} \\)</p>",
            "<p>\\( \\{9, 85, 47, 68, 43, 57, 55\\} \\)</p>",
            "<p>\\( \\{79, 14, 72, 56, 16, 53, 55\\} \\)</p>"
          ],
          "correct_answer": "<p>\\( \\{9, 85, 47, 68, 43, 57, 55\\} \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/3588/gate-it-2006-question-45\" target=\"_blank\">https://gateoverflow.in/3588/gate-it-2006-question-45</a></p>"
        },
        {
          "id": 33,
          "question": "<p><a name=\"3462\"></a><div itemprop=\"text\"><p>When searching for the key value \\( 60 \\) in a binary search tree, nodes containing the key values \\( 10, 20, 40, 50, 70, 80, 90 \\) are traversed, not necessarily in the order given. How many different orders are possible in which these key values can occur on the search path from the root to the node containing the value \\( 60 \\)?</p>\n\n</div><br><br><b>GATE IT 2007 | Question: 29</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 35 \\)</p>",
            "<p>\\( 64 \\)</p>",
            "<p>\\( 128 \\)</p>",
            "<p>\\( 5040 \\)</p>"
          ],
          "correct_answer": "<p>\\( 35 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/3462/gate-it-2007-question-29\" target=\"_blank\">https://gateoverflow.in/3462/gate-it-2007-question-29</a></p>"
        },
        {
          "id": 34,
          "question": "<p><a name=\"3385\"></a><div itemprop=\"text\"><p>A Binary Search Tree (BST) stores values in the range \\( 37 \\) to \\( 573 \\). Consider the following sequence of keys.</p>\n\n<ol style=\"list-style-type:upper-roman\">\n\t<li>\\( 81, 537, 102, 439, 285, 376, 305 \\)</li>\n\t<li>\\( 52, 97, 121, 195, 242, 381, 472 \\)</li>\n\t<li>\\( 142, 248, 520, 386, 345, 270, 307 \\)</li>\n\t<li>\\( 550, 149, 507, 395, 463, 402, 270 \\)</li>\n</ol>\n\n<p>Suppose the BST has been unsuccessfully searched for key \\( 273 \\). Which all of the above sequences list nodes in the order in which we could have encountered them in the search?</p>\n\n</div><br><br><b>GATE IT 2008 | Question: 71</b></p>",
          "type": "single",
          "options": [
            "<p>II and III only</p>",
            "<p>I and III only</p>",
            "<p>III and IV only</p>",
            "<p>III only</p>"
          ],
          "correct_answer": "<p>III only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/3385/gate-it-2008-question-71\" target=\"_blank\">https://gateoverflow.in/3385/gate-it-2008-question-71</a></p>"
        },
        {
          "id": 35,
          "question": "<p><a name=\"3386\"></a><div itemprop=\"text\"><p>A Binary Search Tree (BST) stores values in the range \\( 37 \\) to \\( 573 \\). Consider the following sequence of keys.</p>\n\n<ol style=\"list-style-type:upper-roman\">\n\t<li>\\( 81, 537, 102, 439, 285, 376, 305 \\)</li>\n\t<li>\\( 52, 97, 121, 195, 242, 381, 472 \\)</li>\n\t<li>\\( 142, 248, 520, 386, 345, 270, 307 \\)</li>\n\t<li>\\( 550, 149, 507, 395, 463, 402, 270 \\)</li>\n</ol>\n\n<p>Which of the following statements is TRUE?</p>\n\n</div><br><br><b>GATE IT 2008 | Question: 72</b></p>",
          "type": "single",
          "options": [
            "<p>I, II and IV are inorder sequences of three different BSTs</p>",
            "<p>I is a preorder sequence of some BST with \\( 439 \\) as the root</p>",
            "<p>II is an inorder sequence of some BST where \\( 121 \\) is the root and \\( 52 \\) is a leaf</p>",
            "<p>IV is a postorder sequence of some BST with \\( 149 \\) as the root</p>"
          ],
          "correct_answer": "<p>II is an inorder sequence of some BST where \\( 121 \\) is the root and \\( 52 \\) is a leaf</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/3386/gate-it-2008-question-72\" target=\"_blank\">https://gateoverflow.in/3386/gate-it-2008-question-72</a></p>"
        },
        {
          "id": 36,
          "question": "<p><a name=\"3387\"></a><div itemprop=\"text\"><p>How many distinct BSTs can be constructed with \\( 3 \\) distinct keys?</p>\n\n</div><br><br><b>GATE IT 2008 | Question: 73</b></p>",
          "type": "single",
          "options": [
            "<p>\\( 4 \\)</p>",
            "<p>\\( 5 \\)</p>",
            "<p>\\( 6 \\)</p>",
            "<p>\\( 9 \\)</p>"
          ],
          "correct_answer": "<p>\\( 5 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/3387/gate-it-2008-question-73\" target=\"_blank\">https://gateoverflow.in/3387/gate-it-2008-question-73</a></p>"
        }
      ]
    }
  ]
});
