window.__examLoadCallback({
  "title": "Process - Process - Slot 1",
  "duration": 39,
  "sections": [
    {
      "name": "Process",
      "questions": [
        {
          "id": 1,
          "question": "<p>Dispatch latency is defined as <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>the speed of dispatching a process from running to the ready state</p>",
            "<b>B.</b> <p>the time of dispatching a process from running to ready state and keeping the CPU idle</p>",
            "<b>C.</b> <p>the time to stop one process and start running another one</p>",
            "<b>D.</b> <p>none of these</p>"
          ],
          "correct_answer": "<b>C.</b> <p>the time to stop one process and start running another one</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331250/isro2020-28\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>The operating system and the other processes are protected from being modified by an already running process because <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>they run at different time instants and not in parallel</p>",
            "<b>B.</b> <p>they are in different logical addresses</p>",
            "<b>C.</b> <p>they use a protection algorithm in the scheduler</p>",
            "<b>D.</b> <p>every address generated by the CPU is being checked against the relocation and limit parameters</p>"
          ],
          "correct_answer": "<b>D.</b> <p>every address generated by the CPU is being checked against the relocation and limit parameters</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331282/isro2020-26\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Working Set (t,k) at an instant of time t is <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>the set of k future references that the OS will make</p>",
            "<b>B.</b> <p>the set of future references that the OS will make in next t unit of time</p>",
            "<b>C.</b> <p>the set of k references with high frequency</p>",
            "<b>D.</b> <p>the k set of pages that have been referenced in the last t time units</p>"
          ],
          "correct_answer": "<b>D.</b> <p>the k set of pages that have been referenced in the last t time units</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55554/isro2016-49\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>Suppose a system contains n processes and system uses the round-robin algorithm for CPU scheduling then which data structure is best suited ready queue of the process <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>stack</p>",
            "<b>B.</b> <p>queue</p>",
            "<b>C.</b> <p>circular queue</p>",
            "<b>D.</b> <p>tree</p>"
          ],
          "correct_answer": "<b>C.</b> <p>circular queue</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/51692/isro2015-33\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>The state of a process after it encounters an I/O instruction is? <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Ready</p>",
            "<b>B.</b> <p>Blocked</p>",
            "<b>C.</b> <p>Idle</p>",
            "<b>D.</b> <p>Running</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Blocked</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/44406/isro-2013-60\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>There are three processes in the ready queue. When the currently running process requests for I/O how many process switches take place? <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>1</p>",
            "<b>B.</b> <p>2</p>",
            "<b>C.</b> <p>3</p>",
            "<b>D.</b> <p>4</p>"
          ],
          "correct_answer": "<b>B.</b> <p>2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/51339/isro2011-55\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>Process is <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A program in high level language kept on disk</p>",
            "<b>B.</b> <p>Contents of main memory</p>",
            "<b>C.</b> <p>A program in execution</p>",
            "<b>D.</b> <p>A job in secondary memory</p>"
          ],
          "correct_answer": "<b>C.</b> <p>A program in execution</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50574/isro2009-76\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>Special software to create a job queue is called a <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Driver</p>",
            "<b>B.</b> <p>Spooler</p>",
            "<b>C.</b> <p>Interpreter</p>",
            "<b>D.</b> <p>Linkage editor</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Spooler</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/47649/isro2009-75\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>Which is the correct definition of a valid process transition in an operating system? <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Wake Up: ready \\(\\rightarrow\\) running</p>",
            "<b>B.</b> <p>Dispatch: ready \\(\\rightarrow\\) running</p>",
            "<b>C.</b> <p>Block: ready \\(\\rightarrow\\) running</p>",
            "<b>D.</b> <p>Timer runout: ready \\(\\rightarrow\\) block</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Dispatch: ready \\(\\rightarrow\\) running</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48031/isro2009-9\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>Which of the following need not necessarily be saved on a Context Switch between processes? <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>General purpose registers</p>",
            "<b>B.</b> <p>Translation look-aside buffer</p>",
            "<b>C.</b> <p>Program counter</p>",
            "<b>D.</b> <p>Stack pointer</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Translation look-aside buffer</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50003/isro2008-64\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>Checkpointing a job <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>allows it to be completed successfully</p>",
            "<b>B.</b> <p>allows it to continue executing later</p>",
            "<b>C.</b> <p>prepares it for finishing</p>",
            "<b>D.</b> <p>occurs only when there is an error in it</p>"
          ],
          "correct_answer": "<b>B.</b> <p>allows it to continue executing later</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50000/isro2008-58\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>Which of the following need not necessarily be saved on a context switch between processes? <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>General purpose registers</p>",
            "<b>B.</b> <p>Translation look-aside buffer</p>",
            "<b>C.</b> <p>Program counter</p>",
            "<b>D.</b> <p>All of the above</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Translation look-aside buffer</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/644/gate2000-1-20-isro2008-47\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>A task in a blocked state <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>is executable</p>",
            "<b>B.</b> <p>is running</p>",
            "<b>C.</b> <p>must still be placed in the run queues</p>",
            "<b>D.</b> <p>is waiting for some temporarily unavailable resources</p>"
          ],
          "correct_answer": "<b>D.</b> <p>is waiting for some temporarily unavailable resources</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49516/isro2007-41\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>What is the name of the technique in which the operating system of a computer executes several programs concurrently by switching back and forth between them? <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Partitioning</p>",
            "<b>B.</b> <p>Multi-tasking</p>",
            "<b>C.</b> <p>Windowing</p>",
            "<b>D.</b> <p>Paging</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Multi-tasking</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49498/isro2007-25\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
