window.__examLoadCallback({
  "title": "Theory of Computation - Context Free Grammar",
  "duration": 6,
  "sections": [
    {
      "name": "Context Free Grammar",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"333126\"></a><div itemprop=\"text\"><p>Consider the context-free grammar below (\\( \\epsilon \\) denotes the empty string, alphabet is \\( \\{a,b\\} \\)):</p>\n\n<p>\\[ S\\rightarrow \\epsilon \\mid aSb \\mid bSa \\mid SS. \\]</p>\n\n<p>What language does it generate?</p>\n\n</div><br><br><b>Theory of Computation: TIFR CSE 2020 | Part B | Question: 6</b></p>",
          "type": "numeric",
          "options": [
            "<p>\\( (ab)^{\\ast} + (ba)^{\\ast} \\)</p>",
            "<p>\\( (abba) {\\ast} + (baab)^{\\ast} \\)</p>",
            "<p>\\( (aabb)^{\\ast} + (bbaa)^{\\ast} \\)</p>",
            "<p>Strings of the form \\( a^{n}b^{n} \\) or \\( b^{n}a^{n},n \\) any positive integer</p>",
            "<p>Strings with equal numbers of \\( a \\) and \\( b \\)</p>"
          ],
          "correct_answer": "E",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/333126/tifr-cse-2020-part-b-question-6\" target=\"_blank\">https://gateoverflow.in/333126/tifr-cse-2020-part-b-question-6</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"358944\"></a><div itemprop=\"text\"><p>Let \\( L \\) be a context-free language generated by the context-free grammar \\( G = (V, \\Sigma, R, S) \\) where \\( V \\) is the finite set of variables, \\( \\Sigma \\) the finite set of terminals (disjoints from \\( V \\)), \\( R \\) the finite set of rules and \\( S \\in V \\) the start variable. Consider the context-free grammar \\( {G}' \\) obtained by adding \\( S \\rightarrow SS \\) to the set of rules in \\( G \\). What must be true for the language \\( {L}’ \\) generated by \\( {G}’ \\)?</p>\n\n</div><br><br><b>Theory of Computation: TIFR CSE 2021 | Part B | Question: 9</b></p>",
          "type": "numeric",
          "options": [
            "<p>\\( {L}'=LL \\)</p>",
            "<p>\\( {L}'=L \\)</p>",
            "<p>\\( {L}'=L^{\\ast } \\)</p>",
            "<p>\\( {L}'=\\left \\{ xx \\mid x \\in L \\right \\} \\)</p>",
            "<p>None of the above</p>"
          ],
          "correct_answer": "E",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/358944/tifr-cse-2021-part-b-question-9\" target=\"_blank\">https://gateoverflow.in/358944/tifr-cse-2021-part-b-question-9</a></p>"
        }
      ]
    }
  ]
});
