window.__examLoadCallback({
  "title": "Digital_Logic - Digital_Logic",
  "duration": 252,
  "sections": [
    {
      "name": "Digital_Logic",
      "questions": [
        {
          "id": 1,
          "question": "<p>A new flipflop with inputs X and Y, has the following property<br>\\(\\begin{array}{|c|c|c|c|} \\hline \\mathbf{X} &amp; \\mathbf{Y} &amp; \\text { Current state } &amp; \\text { Next state } \\\\ \\hline 0 &amp; 0 &amp; Q &amp; 1 \\\\ 0 &amp; 1 &amp; Q &amp; \\bar{Q} \\\\ 1 &amp; 1 &amp; Q &amp; 0 \\\\ 1 &amp; 0 &amp; Q &amp; Q \\\\ \\hline \\end{array}\\)<br>Which of the following expresses the next state in terms of X,Y, current state? <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((\\bar{X} \\wedge \\bar{Q}) \\vee(\\bar{Y} \\wedge Q)\\)</p>",
            "<b>B.</b> <p>\\((\\bar{X} \\wedge {Q}) \\vee(\\bar{Y} \\wedge \\bar{Q})\\)</p>",
            "<b>C.</b> <p>\\(({X} \\wedge \\bar{Q}) \\vee({Y} \\wedge {Q})\\)</p>",
            "<b>D.</b> <p>\\(({X} \\wedge \\bar{Q}) \\vee(\\bar{Y} \\wedge {Q})\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\((\\bar{X} \\wedge \\bar{Q}) \\vee(\\bar{Y} \\wedge Q)\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331388/isro2020-80\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Consider the following circuit<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q77_a8d99d4d.jpg\"><br>  The function by the network above is <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\overline{A B} E+E F+\\overline{C D} F\\)</p>",
            "<b>B.</b> <p>\\((\\bar{E}+A B \\bar{F})(C+D+\\bar{F})\\)</p>",
            "<b>C.</b> <p>\\((\\overline{A B}+E)(\\bar{E}+\\bar{F})(C+D+\\bar{F})\\)</p>",
            "<b>D.</b> <p>\\((A+B) \\bar{E}+\\overline{E F}+C D \\bar{F}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\((\\bar{E}+A B \\bar{F})(C+D+\\bar{F})\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331309/isro2020-77\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>The following circuit compares two 2-bit binary numbers, X and Y represented by \\(X_{1}X_{0}\\) and \\(Y_{1}Y_{0}\\) respectively. (\\(X_{0}\\) and \\(Y_{0}\\) represent Least Significant Bits)<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q66_f241f6da.jpg\"><br>Under what conditions Z will be 1? <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>X &gt; Y</p>",
            "<b>B.</b> <p>X &lt; Y</p>",
            "<b>C.</b> <p>X=Y</p>",
            "<b>D.</b> <p>X!=Y</p>"
          ],
          "correct_answer": "<b>A.</b> <p>X &gt; Y</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331492/isro2020-66\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>If ABCD is a 4-bit binary number, then what is the code generated by the following circuit?<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q12_ecd1ed47.jpg\"><br> <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>BCD code</p>",
            "<b>B.</b> <p>Gray code</p>",
            "<b>C.</b> <p>8421 code</p>",
            "<b>D.</b> <p>Excess-3 code</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Gray code</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331372/isro2020-12\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Minimum number of NAND gates required to implement the following binary equation\\(Y=(\\bar{A}+\\bar{B})(C+D)\\) <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>4</p>",
            "<b>B.</b> <p>5</p>",
            "<b>C.</b> <p>3</p>",
            "<b>D.</b> <p>6</p>"
          ],
          "correct_answer": "<b>A.</b> <p>4</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331369/isro2020-11\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Following Multiplexer circuit is equivalent to<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q10_9ef75cf4.jpg\"><br> <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Sum equation of full adder</p>",
            "<b>B.</b> <p>Carry equation of full adder</p>",
            "<b>C.</b> <p>Borrow equation for full subtractor</p>",
            "<b>D.</b> <p>Difference equation of a full subtractor</p>"
          ],
          "correct_answer": "<b>A.</b> <p>Sum equation of full adder</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331299/isro2020-10\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>In a 8-bit ripple carry adder using identical full adders, each full adder takes 34 ns for computing sum. If the time taken for 8-bit addition is 90 ns, find time taken by each full adder to find carry. <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>6  ns</p>",
            "<b>B.</b> <p>7 ns</p>",
            "<b>C.</b> <p>10 ns</p>",
            "<b>D.</b> <p>8 ns</p>"
          ],
          "correct_answer": "<b>D.</b> <p>8 ns</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331294/isro2020-9\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>Any set of Boolean operation that is sufficient to represent all Boolean expression is said to be complete. Which of the following is not complete ? <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>{AND, OR}</p>",
            "<b>B.</b> <p>{AND, NOT}</p>",
            "<b>C.</b> <p>{NOT, OR}</p>",
            "<b>D.</b> <p>{NOR}</p>"
          ],
          "correct_answer": "<b>A.</b> <p>{AND, OR}</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213526/isro2018-62\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>A computer uses ternary system instead of the traditional systen, An n bit string in the binary system will occupy <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>3+n ternary digits</p>",
            "<b>B.</b> <p>2n/3 ternary digits</p>",
            "<b>C.</b> <p>\\(n \\log _{2} 3\\) ternary digits</p>",
            "<b>D.</b> <p>\\(n \\log _{3} 2\\) ternary digits</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(n \\log _{3} 2\\) ternary digits</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213556/isro2018-32\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>Given \\(\\sqrt{224_{r}}=13_{r}\\) the value of radix r is <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>10</p>",
            "<b>B.</b> <p>8</p>",
            "<b>C.</b> <p>6</p>",
            "<b>D.</b> <p>5</p>"
          ],
          "correct_answer": "<b>D.</b> <p>5</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213569/isro2018-19\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q9_7cd2ae9c.jpg\"><br>  In the diagram above, the inverter (NOT gate) and the AND-gates labeled 1 and 2 have delays of 9, 10 and 12 nanoseconds (ns), respectively. Wire delays are negligible. For certain values a and c, together with certain transition of b, a glitch (spurious output) is generated for a short time, after which the output assumes its correct value. The duration of glitch is: <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>7 ns</p>",
            "<b>B.</b> <p>9 ns</p>",
            "<b>C.</b> <p>11 ns</p>",
            "<b>D.</b> <p>13 ns</p>"
          ],
          "correct_answer": "<b>A.</b> <p>7 ns</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213579/isro2018-9\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>If a variable can take only integral values from 0 to n, where n is an integer, then the variable can be represented as a bit-field whose width is (the log in the answer are to the base 2, and \\(\\lceil\\log n\\rceil\\) means the floor of \\(\\log_{}{n}\\) ) <br><br><strong>(ISRO CSE 2018)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\left \\lceil \\log (n) \\right \\rceil + 1 \\text{ bits}\\)</p>",
            "<b>B.</b> <p>\\(\\left \\lceil \\log (n-1) \\right \\rceil + 1 \\text{ bits}\\)</p>",
            "<b>C.</b> <p>\\(\\left \\lceil \\log (n+1) \\right \\rceil + 1\\text{ bits}\\)</p>",
            "<b>D.</b> <p>None of the above</p>"
          ],
          "correct_answer": "<b>D.</b> <p>None of the above</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/213585/isro2018-3\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>\\((1217)_{8}\\) is equivalent to <br><br><strong>(ISRO CSE 2017)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((1217)_{16}\\)</p>",
            "<b>B.</b> <p>\\((028F)_{16}\\)</p>",
            "<b>C.</b> <p>\\((2297)_{10}\\)</p>",
            "<b>D.</b> <p>\\((0B17)_{16}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\((028F)_{16}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1297/gate2009-5-isro2017-57\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>Advantage of synchronous sequential circuits over asynchronous one is : <br><br><strong>(ISRO CSE 2017)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Lower hardware requirement</p>",
            "<b>B.</b> <p>Better noise immunity</p>",
            "<b>C.</b> <p>Faster operation</p>",
            "<b>D.</b> <p>All of the above</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Faster operation</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/128643/isro2017-26\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>The 2-input XOR has a high output only when the input values are <br><br><strong>(ISRO CSE 2017)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>low</p>",
            "<b>B.</b> <p>high</p>",
            "<b>C.</b> <p>same</p>",
            "<b>D.</b> <p>different</p>"
          ],
          "correct_answer": "<b>D.</b> <p>different</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/128642/isro-2017-25\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 16,
          "question": "<p>When two n-bit binary numbers are added the sum will contain at the most <br><br><strong>(ISRO CSE 2017)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>n  bits</p>",
            "<b>B.</b> <p>n+2 bits</p>",
            "<b>C.</b> <p>n+3 bits</p>",
            "<b>D.</b> <p>n+1 bits</p>"
          ],
          "correct_answer": "<b>D.</b> <p>n+1 bits</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/128641/isro2017-24\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 17,
          "question": "<p>What is the minimum number of two-input NAND gates used to perform the function of two-input OR gate? <br><br><strong>(ISRO CSE 2017)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>One</p>",
            "<b>B.</b> <p>Two</p>",
            "<b>C.</b> <p>Three</p>",
            "<b>D.</b> <p>Four</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Three</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/129118/isro2017-23\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 18,
          "question": "<p>The functional difference between SR flip-flop and J-K flip-flop is that : <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>J -K flip-flop is faster than SR flip-flop</p>",
            "<b>B.</b> <p>J-K flip-flop has a feedback path</p>",
            "<b>C.</b> <p>J-K flip-flop accepts both inputs 1</p>",
            "<b>D.</b> <p>None of them</p>"
          ],
          "correct_answer": "<b>C.</b> <p>J-K flip-flop accepts both inputs 1</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55462/isro2016-18\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 19,
          "question": "<p>Which of the following binary number is the same as its 2's complement ? <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>1010</p>",
            "<b>B.</b> <p>\\(0101\\)</p>",
            "<b>C.</b> <p>1000</p>",
            "<b>D.</b> <p>1001</p>"
          ],
          "correct_answer": "<b>C.</b> <p>1000</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55458/isro2016-17\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 20,
          "question": "<p>The simplified SOP (Sum of Product) from the Boolean expression<br>\\((P + \\bar{Q} + \\bar{R}) . (P + {Q} + R) . (P + Q +\\bar{R})\\)<br>is <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((\\bar{P}.Q+\\bar{R})\\)</p>",
            "<b>B.</b> <p>\\((P+{Q}.\\bar{R})\\)</p>",
            "<b>C.</b> <p>\\(({P}.\\bar{Q}+R)\\)</p>",
            "<b>D.</b> <p>\\((P.Q+R)\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\((P+{Q}.\\bar{R})\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55660/isro2016-16\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 21,
          "question": "<p>The Excess-3 code is also called <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Cyclic Redundancy Code</p>",
            "<b>B.</b> <p>Weighted Code</p>",
            "<b>C.</b> <p>Self-Complementing Code</p>",
            "<b>D.</b> <p>Algebraic Code</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Self-Complementing Code</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/56034/isro2016-15\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 22,
          "question": "<p>If \\((12A7C)_{16} = (X)_8\\) then the value of X is <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>224174</p>",
            "<b>B.</b> <p>425174</p>",
            "<b>C.</b> <p>6173</p>",
            "<b>D.</b> <p>225174</p>"
          ],
          "correct_answer": "<b>D.</b> <p>225174</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/56071/isro2016-14\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 23,
          "question": "<p>The circuit given in the figure below is<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q13_3e8c97a6.jpg\"><br> <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>An oscillating circuit and its output is square wave</p>",
            "<b>B.</b> <p>The one whose output remains stable in '1' state</p>",
            "<b>C.</b> <p>The one having output remains stable in '0' state</p>",
            "<b>D.</b> <p>has a single pulse of three times propagation delay</p>"
          ],
          "correct_answer": "<b>A.</b> <p>An oscillating circuit and its output is square wave</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55965/isro2016-13\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 24,
          "question": "<p>The logic circuit given below converts a binary code y1, y2, y3 into<br><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q12_4469eeb2.jpg\"><br> <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Excess-3 code</p>",
            "<b>B.</b> <p>Gray code</p>",
            "<b>C.</b> <p>BCD code</p>",
            "<b>D.</b> <p>Hamming code</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Gray code</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/56070/isro2016-12\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 25,
          "question": "<p>Consider the following gate network<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q10_1f8baeab.jpg\"><br>Which one of the following gates is redundant? <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Gate No. 1</p>",
            "<b>B.</b> <p>Gate No. 2</p>",
            "<b>C.</b> <p>Gate No. 3</p>",
            "<b>D.</b> <p>Gate No. 4</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Gate No. 2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55959/isro2016-10\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 26,
          "question": "<p>For a binary half-subtractor having two inputs A and B, the correct set of logical outputs D(=A minus B) and X(=borrow) are <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(D=AB+\\bar{A}B, X=\\bar{A}B\\)</p>",
            "<b>B.</b> <p>\\(D=\\bar{A}B+A\\bar{B}, X=A\\bar{B}\\)</p>",
            "<b>C.</b> <p>\\(D=\\bar{A}B+A\\bar{B}, X=\\bar{A} B\\)</p>",
            "<b>D.</b> <p>\\(D=AB+\\bar{A}B, X=A\\bar{B}\\)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(D=\\bar{A}B+A\\bar{B}, X=\\bar{A} B\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55958/isro2016-9\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 27,
          "question": "<p>The minimum Boolean expression for the following circuit is<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q8_ae4ca5cf.jpg\"><br> <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>AB+AC+BC</p>",
            "<b>B.</b> <p>A+BC</p>",
            "<b>C.</b> <p>A+B</p>",
            "<b>D.</b> <p>A+B+C</p>"
          ],
          "correct_answer": "<b>A.</b> <p>AB+AC+BC</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55951/isro2016-8\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 28,
          "question": "<p>The minimum number of \\(\\text{NAND}\\) gates required to implement the Boolean function \\(A + A\\bar{B} + A\\bar{B}C\\) is equal to <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0 (Zero)</p>",
            "<b>B.</b> <p>1</p>",
            "<b>C.</b> <p>4</p>",
            "<b>D.</b> <p>7</p>"
          ],
          "correct_answer": "<b>A.</b> <p>0 (Zero)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/41842/isro2016-7\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 29,
          "question": "<p>The decimal number has 64 digits. The number of bits needed for its equivalent binary representation is? <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>200</p>",
            "<b>B.</b> <p>213</p>",
            "<b>C.</b> <p>246</p>",
            "<b>D.</b> <p>277</p>"
          ],
          "correct_answer": "<b>B.</b> <p>213</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50363/isro2015-78\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 30,
          "question": "<p>The boolean expression \\(A B+A B^{\\prime}+A^{\\prime} C+A C\\) is independent of the boolean variable <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A</p>",
            "<b>B.</b> <p>B</p>",
            "<b>C.</b> <p>C</p>",
            "<b>D.</b> <p>None of these</p>"
          ],
          "correct_answer": "<b>B.</b> <p>B</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/51074/isro2015-10\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 31,
          "question": "<p>The number of 1's in the binary representation of \\((3*4096 + 15*256 + 5*16 + 3)\\) are: <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>8</p>",
            "<b>B.</b> <p>9</p>",
            "<b>C.</b> <p>10</p>",
            "<b>D.</b> <p>12</p>"
          ],
          "correct_answer": "<b>C.</b> <p>10</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2624/gate1995-2-12-isro2015-9\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 32,
          "question": "<p>Minimum number of 2x1 multiplexers required to realize the following function, \\(f=\\bar{A} \\bar{B} C+\\bar{A} \\bar{B} \\bar{C}\\)<br>Assume that inputs are available only in true form and Boolean a constant 1 and 0 are available. <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>1</p>",
            "<b>B.</b> <p>2</p>",
            "<b>C.</b> <p>3</p>",
            "<b>D.</b> <p>7</p>"
          ],
          "correct_answer": "<b>B.</b> <p>2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50782/isro2015-8\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 33,
          "question": "<p>If half adders and full adders are implements using gates, then for the addition of two 17 bit numbers (using minimum gates) the number of half adders and full adders required will be <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0,17</p>",
            "<b>B.</b> <p>16,1</p>",
            "<b>C.</b> <p>1,16</p>",
            "<b>D.</b> <p>8,8</p>"
          ],
          "correct_answer": "<b>C.</b> <p>1,16</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/19462/isro2015-7\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 34,
          "question": "<p>The code which uses 7 bits to represent a character is : <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>ASCII</p>",
            "<b>B.</b> <p>BCD</p>",
            "<b>C.</b> <p>EBCDIC</p>",
            "<b>D.</b> <p>Gray</p>"
          ],
          "correct_answer": "<b>A.</b> <p>ASCII</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/46690/isro2015-6\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 35,
          "question": "<p>The complement of the Boolean expression \\(A B(\\bar{B} C+A C)\\) is <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((\\bar{A}+\\bar{B})+(B+\\bar{C}) \\cdot(\\bar{A}+\\bar{C})\\)</p>",
            "<b>B.</b> <p>\\((\\bar{A} \\cdot \\bar{B})+(B \\bar{C}+\\bar{A} \\bar{C})\\)</p>",
            "<b>C.</b> <p>\\((\\bar{A}+\\bar{B}) \\cdot(B+\\bar{C})+(A+\\bar{C})\\)</p>",
            "<b>D.</b> <p>\\((A+B) \\cdot(\\bar{B}+C)(A+C)\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\((\\bar{A}+\\bar{B})+(B+\\bar{C}) \\cdot(\\bar{A}+\\bar{C})\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50778/isro2015-5\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 36,
          "question": "<p>A modulus -12 ring counter requires a minimum of <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>10  flip-flops</p>",
            "<b>B.</b> <p>12 flip-flops</p>",
            "<b>C.</b> <p>8 flip-flops</p>",
            "<b>D.</b> <p>6 flip-flops</p>"
          ],
          "correct_answer": "<b>B.</b> <p>12 flip-flops</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/19487/isro2015-4\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 37,
          "question": "<p>The range of integers that can be represented by an n bit 2's complement number system is: <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(-2^{n-1} \\text { to }\\left(2^{n-1}-1\\right)\\)</p>",
            "<b>B.</b> <p>\\(-\\left(2^{n-1}-1\\right) \\text { to }\\left(2^{n-1}-1\\right)\\)</p>",
            "<b>C.</b> <p>\\(-2^{n-1} \\text { to } 2^{n-1}\\)</p>",
            "<b>D.</b> <p>\\(-\\left(2^{n-1}+1\\right) \\text { to }\\left(2^{n-1}-1\\right)\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(-2^{n-1} \\text { to }\\left(2^{n-1}-1\\right)\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1352/gate2005-16-isro2009-18-isro2015-2\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 38,
          "question": "<p>Which of the given number has its IEEE-754 32-bit floating point representation as (0 10000000 110 0000 0000 0000 0000 0000) <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>2.5</p>",
            "<b>B.</b> <p>3</p>",
            "<b>C.</b> <p>3.5</p>",
            "<b>D.</b> <p>4.5</p>"
          ],
          "correct_answer": "<b>C.</b> <p>3.5</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50581/isro2015-1\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 39,
          "question": "<p>Which of the following is not valid Boolean algebra rule ? <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(X . X=X\\)</p>",
            "<b>B.</b> <p>\\((X+Y) . X=X\\)</p>",
            "<b>C.</b> <p>\\(\\bar{X}+X Y=Y\\)</p>",
            "<b>D.</b> <p>\\((X+Y) \\cdot(X+Z)=X+Y Z\\)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(\\bar{X}+X Y=Y\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/52781/isro2014-56\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 40,
          "question": "<p>Consider the logic circuit given below.<br><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q53_ae983511.jpg\"><br>The inverter, AND and OR gates have delays of 6, 10 and 11 nanoseconds respectively. Assuming that wire delays are negligible, what is the duration of glitch for Q before it becomes stable? <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>5</p>",
            "<b>B.</b> <p>11</p>",
            "<b>C.</b> <p>16</p>",
            "<b>D.</b> <p>27</p>"
          ],
          "correct_answer": "<b>A.</b> <p>5</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/55003/isro2014-53\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 41,
          "question": "<p>How many different BCD numbers can be stored in 12 switches ? (Assume two position or on-off switches). <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(2^{12}\\)</p>",
            "<b>B.</b> <p>\\(2^{12}-1\\)</p>",
            "<b>C.</b> <p>\\(10^{12}\\)</p>",
            "<b>D.</b> <p>\\(10^{3}\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(10^{3}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50455/isro2014-27\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 42,
          "question": "<p>The output of a tristate buffer when the enable input in 0 is <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Always 0</p>",
            "<b>B.</b> <p>Always 1</p>",
            "<b>C.</b> <p>Retains the last value when enable input was high</p>",
            "<b>D.</b> <p>Disconnected state</p>"
          ],
          "correct_answer": "<b>D.</b> <p>Disconnected state</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/54950/isro2014-26\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 43,
          "question": "<p>What are the final values of Q1 and Q0 after 4 clock cycles, if initial values are 00 in the sequential circuit shown below:<br><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q21_8a077758.jpg\"><br> <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>11</p>",
            "<b>B.</b> <p>1</p>",
            "<b>C.</b> <p>10</p>",
            "<b>D.</b> <p>0</p>"
          ],
          "correct_answer": "<b>D.</b> <p>0</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/13385/isro2014-21-ugcnet-dec2012-iii-23-ugcnet-dec2013-iii-22\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 44,
          "question": "<p>Consider the logic circuit given below:<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q15_4b90dfc8.jpg\"><br>Q=__________? <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\bar{A} C+B \\bar{C}+C D\\)</p>",
            "<b>B.</b> <p>\\(A B C+\\bar{C} D\\)</p>",
            "<b>C.</b> <p>\\(A B+B \\bar{C}+B \\bar{D}\\)</p>",
            "<b>D.</b> <p>\\(A \\bar{B}+A \\bar{C}+\\bar{C} D\\)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(A B+B \\bar{C}+B \\bar{D}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/54948/isro2014-15\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 45,
          "question": "<p>In the standard IEEE 754 single precision floating point representation, there is 1 bit for sign, 23 bits for fraction and 8 bits for exponent. What is the precision in terms of the number of decimal digits? <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>5</p>",
            "<b>B.</b> <p>6</p>",
            "<b>C.</b> <p>7</p>",
            "<b>D.</b> <p>8</p>"
          ],
          "correct_answer": "<b>C.</b> <p>7</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/15030/isro2014-8\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 46,
          "question": "<p>The binary equivalent of the decimal number 42.75 is <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>101010 . 110</p>",
            "<b>B.</b> <p>100110 . 101</p>",
            "<b>C.</b> <p>101010 . 101</p>",
            "<b>D.</b> <p>100110 . 110</p>"
          ],
          "correct_answer": "<b>A.</b> <p>101010 . 110</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/45672/isro-2013-77\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 47,
          "question": "<p>In a three stage counter, using RS flip flops what will be the value of the counter after giving 9 pulses to its input ? Assume that the value of counter before giving any pulses is 1 : <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>1</p>",
            "<b>B.</b> <p>2</p>",
            "<b>C.</b> <p>9</p>",
            "<b>D.</b> <p>10</p>"
          ],
          "correct_answer": "<b>B.</b> <p>2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43965/isro-2013-30\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 48,
          "question": "<p>How many programmable fuses are required in a PLA which takes 16 inputs and gives 8 outputs? It has to use 8 OR gates and 32 AND gates. <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>1032</p>",
            "<b>B.</b> <p>776</p>",
            "<b>C.</b> <p>1284</p>",
            "<b>D.</b> <p>1536</p>"
          ],
          "correct_answer": "<b>C.</b> <p>1284</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43964/isro-2013-29\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 49,
          "question": "<p>The most simplified form of the Boolean function<br>\n\\(x (A, B, C, D) = \\sum (7, 8, 9, 10, 11, 12, 13, 14, 15)\\)<br>\n(expressed in sum of minterms) is? <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A + A'BCD</p>",
            "<b>B.</b> <p>AB + CD</p>",
            "<b>C.</b> <p>A + BCD</p>",
            "<b>D.</b> <p>ABC + D</p>"
          ],
          "correct_answer": "<b>C.</b> <p>A + BCD</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43963/isro-2013-28\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 50,
          "question": "<p>Any set of Boolean operators that is sufficient to represent all Boolean expressions is said to be complete. Which of the following is not complete ? <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>{NOT, OR}</p>",
            "<b>B.</b> <p>{NOR}</p>",
            "<b>C.</b> <p>{AND, OR}</p>",
            "<b>D.</b> <p>{AND, NOT}</p>"
          ],
          "correct_answer": "<b>C.</b> <p>{AND, OR}</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43845/isro-2013-22\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 51,
          "question": "<p>Two eight bit bytes 11000011 and 01001100 are added. What are the values of the overflow, carry and zero flags respectively, if the arithmetic unit of the CPU uses 2's complement form? <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0,1,1</p>",
            "<b>B.</b> <p>1,1,0</p>",
            "<b>C.</b> <p>1,0,1</p>",
            "<b>D.</b> <p>0,1,0</p>"
          ],
          "correct_answer": "<b>D.</b> <p>0,1,0</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43814/isro-2013-17\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 52,
          "question": "<p>The number 1102 in base 3 is equivalent to 123 in which base system? <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>4</p>",
            "<b>B.</b> <p>5</p>",
            "<b>C.</b> <p>6</p>",
            "<b>D.</b> <p>8</p>"
          ],
          "correct_answer": "<b>B.</b> <p>5</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43803/isro-2013-13\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 53,
          "question": "<p>When two BCD numbers \\(0\\times14\\) and \\(0\\times08\\) are added what is the binary representation of the resultant number ? <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(0\\times22\\)</p>",
            "<b>B.</b> <p>\\(0\\times1c\\)</p>",
            "<b>C.</b> <p>\\(0\\times16\\)</p>",
            "<b>D.</b> <p>results in overflow</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(0\\times22\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43801/isro-2013-11\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 54,
          "question": "<p>Which logic gate is used to detect overflow in 2's compliment arithmetic? <br><br><strong>(ISRO CSE 2013)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>OR gate</p>",
            "<b>B.</b> <p>AND gate</p>",
            "<b>C.</b> <p>NAND gate</p>",
            "<b>D.</b> <p>XOR gate</p>"
          ],
          "correct_answer": "<b>D.</b> <p>XOR gate</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43765/isro-2013-8\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 55,
          "question": "<p>In an RS flip-flop, if the S line (Set line) is set high (1) and the R line (Reset line) is set low (0), then the state of the flip-flop is : <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Set to 1</p>",
            "<b>B.</b> <p>Set to 0</p>",
            "<b>C.</b> <p>No change in state</p>",
            "<b>D.</b> <p>Forbidden</p>"
          ],
          "correct_answer": "<b>A.</b> <p>Set to 1</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/52873/isro2011-74\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 56,
          "question": "<p>The output expression of the following gate network is <br><br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q47_ff3adc84.jpg\"><br> <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(X.Y + \\bar{X} . \\bar{Y}\\)</p>",
            "<b>B.</b> <p>X.Y + X.Y</p>",
            "<b>C.</b> <p>X.Y</p>",
            "<b>D.</b> <p>X+Y</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(X.Y + \\bar{X} . \\bar{Y}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/52572/isro2011-47\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 57,
          "question": "<p>How many 3-to-8 line decoders with an enable input are needed to construct a 6-to-64 line decoder without using any other logic gates? <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>7</p>",
            "<b>B.</b> <p>8</p>",
            "<b>C.</b> <p>9</p>",
            "<b>D.</b> <p>10</p>"
          ],
          "correct_answer": "<b>C.</b> <p>9</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1206/gate2007-8-isro2011-31\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 58,
          "question": "<p>In Boolean algebra, rule \\(\\left ( X+Y \\right )\\left ( X+Z \\right ) =\\) <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Y+XZ</p>",
            "<b>B.</b> <p>X+YZ</p>",
            "<b>C.</b> <p>XY+Z</p>",
            "<b>D.</b> <p>XZ+Y</p>"
          ],
          "correct_answer": "<b>B.</b> <p>X+YZ</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/52477/isro2011-30\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 59,
          "question": "<p>What is the decimal value of the floating-point number C1D00000 (hexadecimal notation)? (Assume 32-bit, single precision floating point IEEE representation) <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>28</p>",
            "<b>B.</b> <p>-15</p>",
            "<b>C.</b> <p>-26</p>",
            "<b>D.</b> <p>-28</p>"
          ],
          "correct_answer": "<b>C.</b> <p>-26</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/52248/isro2011-8\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 60,
          "question": "<p>Evaluate (X xor Y) xor Y? <br><br><strong>(ISRO CSE 2011)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>All 1's</p>",
            "<b>B.</b> <p>All 0's</p>",
            "<b>C.</b> <p>X</p>",
            "<b>D.</b> <p>Y</p>"
          ],
          "correct_answer": "<b>C.</b> <p>X</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/19328/isro2011-6\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 61,
          "question": "<p>The addition of 4-bit, two's complement, binary numbers 1101 and 0100 results in <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0001 and an overflow</p>",
            "<b>B.</b> <p>1001 and no overflow</p>",
            "<b>C.</b> <p>0001 and no overflow</p>",
            "<b>D.</b> <p>1001 and an overflow</p>"
          ],
          "correct_answer": "<b>C.</b> <p>0001 and no overflow</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3546/gate2006-it-7-isro2009-41\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 62,
          "question": "<p>The two numbers given below are multiplied using the Booth's algorithm <br>\nMultiplicand: 0101 1010 1110 1110<br>\nMultiplier: 0111 0111 1011 1101<br>\nHow many additions/subtractions are required for the multiplication of the above two numbers? <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>6</p>",
            "<b>B.</b> <p>8</p>",
            "<b>C.</b> <p>10</p>",
            "<b>D.</b> <p>12</p>"
          ],
          "correct_answer": "<b>B.</b> <p>8</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48065/isro2009-40-gate2008-it_42\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 63,
          "question": "<p>Consider the following boolean function of four variables \\(f(w,x,y,z) = \\Sigma(1,3,4,6,9,11,12,14)\\), the function is <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Independent of one variable</p>",
            "<b>B.</b> <p>Independent of two variables</p>",
            "<b>C.</b> <p>Independent of three variables</p>",
            "<b>D.</b> <p>Dependent on all variables</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Independent of two variables</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50345/isro2009-20\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 64,
          "question": "<p>The switching expression corresponding to \\(f(A, B, C, D) = \\Sigma(1, 4, 5, 9, 11, 12)\\) is <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>BC'D' + A'C'D + AB'D</p>",
            "<b>B.</b> <p>ABC' + ACD + B'C'D</p>",
            "<b>C.</b> <p>ACD' + A'BC' + AC'D'</p>",
            "<b>D.</b> <p>A'BD + ACD' + BCD'</p>"
          ],
          "correct_answer": "<b>A.</b> <p>BC'D' + A'C'D + AB'D</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48039/isro2009-19\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 65,
          "question": "<p>The range of integers that can be represented by an n bit 2's complement number system is: <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(-2^{n-1} \\text{ to } (2^{n-1} -1)\\)</p>",
            "<b>B.</b> <p>\\(-(2^{n-1} -1) \\text{ to } (2^{n-1} -1)\\)</p>",
            "<b>C.</b> <p>\\(-2^{n-1} \\text{ to } 2^{n-1}\\)</p>",
            "<b>D.</b> <p>\\(-(2^{n-1} +1) \\text{ to } (2^{n-1} -1)\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(-2^{n-1} \\text{ to } (2^{n-1} -1)\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1352/gate2005-16-isro2009-18-isro2015-2\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 66,
          "question": "<p>Repeated execution of simple computation may cause compounding of <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>round-off errors</p>",
            "<b>B.</b> <p>syntax errors</p>",
            "<b>C.</b> <p>run-time errors</p>",
            "<b>D.</b> <p>logic errors</p>"
          ],
          "correct_answer": "<b>A.</b> <p>round-off errors</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/50147/isro2008-79\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 67,
          "question": "<p>Which of the following is termed as minimum error code ? <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Binary code</p>",
            "<b>B.</b> <p>Gray code</p>",
            "<b>C.</b> <p>Excess-3 code</p>",
            "<b>D.</b> <p>Octal code</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Gray code</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/17266/isro2008-48\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 68,
          "question": "<p>Which of the following is not a valid rule of XOR? <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0 XOR 0=0</p>",
            "<b>B.</b> <p>1 XOR 1=1</p>",
            "<b>C.</b> <p>1 XOR 0=1</p>",
            "<b>D.</b> <p>B XOR B=0</p>"
          ],
          "correct_answer": "<b>B.</b> <p>1 XOR 1=1</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49907/isro2008-28\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 69,
          "question": "<p>The output Y of the given circuit<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q27_a307e416.jpg\"><br> <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>1</p>",
            "<b>B.</b> <p>0</p>",
            "<b>C.</b> <p>X</p>",
            "<b>D.</b> <p>X'</p>"
          ],
          "correct_answer": "<b>C.</b> <p>X</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49905/isro2008-27\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 70,
          "question": "<p>The logic operations of two combinational circuits in Figure-I and Figure -II are<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q26_7e078718.jpg\"><br> <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>entirely different</p>",
            "<b>B.</b> <p>identical</p>",
            "<b>C.</b> <p>complementary</p>",
            "<b>D.</b> <p>dual</p>"
          ],
          "correct_answer": "<b>A.</b> <p>entirely different</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49903/isro2008-26\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 71,
          "question": "<p>In the expression \\(\\bar{A}(\\bar{A}+\\bar{B})\\)by writing the first term A as A+0, the expression is best simplified as <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A+AB</p>",
            "<b>B.</b> <p>AB</p>",
            "<b>C.</b> <p>A</p>",
            "<b>D.</b> <p>A+B</p>"
          ],
          "correct_answer": "<b>C.</b> <p>A</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49899/isro2008-25\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 72,
          "question": "<p>The Boolean expression \\((A+\\bar{C})(\\bar{B} + \\bar{C})\\) simplifies to <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\bar{C} + A \\bar{B}\\)</p>",
            "<b>B.</b> <p>\\(\\bar{C} (\\bar{A} +B)\\)</p>",
            "<b>C.</b> <p>\\(\\bar{B}\\bar{C} + A\\bar{B}\\)</p>",
            "<b>D.</b> <p>None of these</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(\\bar{C} + A \\bar{B}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49896/isro2008-24\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 73,
          "question": "<p>A computer uses 8 digit mantissa and 2 digit exponent. If a=0.052 and b=28E+11 then b+a-b will : <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>result in an overflow error</p>",
            "<b>B.</b> <p>result in an underflow error</p>",
            "<b>C.</b> <p>be 0</p>",
            "<b>D.</b> <p>be 5.28E+11</p>"
          ],
          "correct_answer": "<b>C.</b> <p>be 0</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/45540/isro2008-23\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 74,
          "question": "<p>How many 2-input multiplexers are required to construct a \\(2^{10}\\)-input multiplexer? <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>1023</p>",
            "<b>B.</b> <p>31</p>",
            "<b>C.</b> <p>10</p>",
            "<b>D.</b> <p>127</p>"
          ],
          "correct_answer": "<b>A.</b> <p>1023</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49891/isro2008-22\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 75,
          "question": "<p>If \\((12x)_3 = (123)_x\\), then the value of x is <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>3</p>",
            "<b>B.</b> <p>3 or 4</p>",
            "<b>C.</b> <p>2</p>",
            "<b>D.</b> <p>None of these</p>"
          ],
          "correct_answer": "<b>D.</b> <p>None of these</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49888/isro2008-20\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 76,
          "question": "<p>If \\(N^2 = (7601)_8\\) where N is a positive integer, then the value of N is <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((241)_5\\)</p>",
            "<b>B.</b> <p>\\((143)_6\\)</p>",
            "<b>C.</b> <p>\\((165)_7\\)</p>",
            "<b>D.</b> <p>\\((39)_{16}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\((143)_6\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49802/isro2008-13\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 77,
          "question": "<p>In the given network of AND and OR gates f can be written as<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q12_9957c677.jpg\"><br> <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(X_0X_1X_2 \\dots X_n + X_1X_2 \\dots X_n + X_2X_3 \\dots X_n + \\dots + X_n\\)</p>",
            "<b>B.</b> <p>\\(X_0X_1 + X_2X_3+ \\dots X_{n-1}X_n\\)</p>",
            "<b>C.</b> <p>\\(X_0+X_1 + X_2+ \\dots +X_n\\)</p>",
            "<b>D.</b> <p>\\(X_0X_1 + X_3 \\dots X_{n-1}+ X_2X_3 + X_5 \\dots X_{n-1} + \\dots +X_{n-2} X_{n-1} +X_n\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(X_0X_1X_2 \\dots X_n + X_1X_2 \\dots X_n + X_2X_3 \\dots X_n + \\dots + X_n\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49796/isro2008-12\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 78,
          "question": "<p>The Boolean theorem \\(AB+\\bar{A}C +BC = AB + \\bar{A}C\\) corresponds to <br><br><strong>(ISRO CSE 2008)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((A+B) \\bullet (\\bar{A} +C) \\bullet (B+C) = (A+B) \\bullet (\\bar{A} +C)\\)</p>",
            "<b>B.</b> <p>\\(AB+\\bar{A}C +BC =AB+BC\\)</p>",
            "<b>C.</b> <p>\\(AB+\\bar{A}C +BC =(A+B) \\bullet (\\bar{A} +C) \\bullet (B+C)\\)</p>",
            "<b>D.</b> <p>\\((A+B) \\bullet (\\bar{A} +C) \\bullet (B+C) = AB + \\bar{A}C\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\((A+B) \\bullet (\\bar{A} +C) \\bullet (B+C) = (A+B) \\bullet (\\bar{A} +C)\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49677/isro2008-11\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 79,
          "question": "<p>One approach to handling fuzzy logic data might be to design a computer using ternary (base-3) logic so that data could be stored as \"true,\" \"false,\" and \"unknown.\" If each ternary logic element is called a flit, how many flits are required to represent at least 256 different values? <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>4</p>",
            "<b>B.</b> <p>5</p>",
            "<b>C.</b> <p>6</p>",
            "<b>D.</b> <p>7</p>"
          ],
          "correct_answer": "<b>C.</b> <p>6</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49529/isro2007-49\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 80,
          "question": "<p>The Hexadecimal equivalent of 01111100110111100011 is <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>CD73E</p>",
            "<b>B.</b> <p>ABD3F</p>",
            "<b>C.</b> <p>7CDE3</p>",
            "<b>D.</b> <p>FA4CD</p>"
          ],
          "correct_answer": "<b>C.</b> <p>7CDE3</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49513/isro2007-38\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 81,
          "question": "<p>Consider a computer system that stores a floating-point numbers with 16-bit mantissa and an 8-bit exponent, each in two's complement. The smallest and largest positive values which can be stored are : <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(1 \\times 10^{-128} \\text{ and } 2^{15} \\times 10^{128}\\)</p>",
            "<b>B.</b> <p>\\(1 \\times 10^{-256} \\text{ and } 2^{15} \\times 10^{255}\\)</p>",
            "<b>C.</b> <p>\\(1 \\times 10^{-128} \\text{ and } 2^{15} \\times 10^{127}\\)</p>",
            "<b>D.</b> <p>\\(1 \\times 10^{-128} \\text{ and } (2^{15}-1) \\times 10^{127}\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(1 \\times 10^{-128} \\text{ and } (2^{15}-1) \\times 10^{127}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49511/isro2007-36\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 82,
          "question": "<p>The output 0 and 1 level for TTL Logic family is approximately <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0.1 and 5V</p>",
            "<b>B.</b> <p>0.6 and 3.5 V</p>",
            "<b>C.</b> <p>0.9 and 1.75 V</p>",
            "<b>D.</b> <p>-1.75 and 0.9 V</p>"
          ],
          "correct_answer": "<b>B.</b> <p>0.6 and 3.5 V</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49510/isro2007-35\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 83,
          "question": "<p>Ring counter is analogous to <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Toggle Switch</p>",
            "<b>B.</b> <p>Latch</p>",
            "<b>C.</b> <p>Stepping Switch</p>",
            "<b>D.</b> <p>S-R flip flop</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Stepping Switch</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49508/isro2007-34\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 84,
          "question": "<p>In an SR latch made by cross-coupling two NAND gates, if both S and R inputs are set to 0, then it will result in <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Q = 0, Q' = 1</p>",
            "<b>B.</b> <p>Q = 1, Q' = 0</p>",
            "<b>C.</b> <p>Q = 1, Q' = 1</p>",
            "<b>D.</b> <p>Indeterminate states</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Q = 1, Q' = 1</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1015/gate2004-18-isro2007-31\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 85,
          "question": "<p>0.75 decimal system is equivalent to ____ in octal system <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0.6</p>",
            "<b>B.</b> <p>0.52</p>",
            "<b>C.</b> <p>0.54</p>",
            "<b>D.</b> <p>0.5</p>"
          ],
          "correct_answer": "<b>A.</b> <p>0.6</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49504/isro2007-30\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 86,
          "question": "<p>The number of digit 1 present in the binary representation of <br>\n\\(3 \\times 512 + 7 \\times 64 + 5 \\times 8 + 3\\) is <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>8</p>",
            "<b>B.</b> <p>9</p>",
            "<b>C.</b> <p>10</p>",
            "<b>D.</b> <p>12</p>"
          ],
          "correct_answer": "<b>B.</b> <p>9</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49490/isro2007-18\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 87,
          "question": "<p>The characteristic equation of an SR flip-flop is given by : <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(Q_{n+1}=S+RQ_n\\)</p>",
            "<b>B.</b> <p>\\(Q_{n+1}=R\\bar{Q}_n + \\bar{S}Q_n\\)</p>",
            "<b>C.</b> <p>\\(Q_{n+1}=\\bar{S}+RQ_n\\)</p>",
            "<b>D.</b> <p>\\(Q_{n+1}=S+\\bar{R}Q_n\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(Q_{n+1}=S+\\bar{R}Q_n\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49475/isro2007-05\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 88,
          "question": "<p>When two numbers are added in excess-3 code and the sum is less than 9, then in order to get the correct answer it is necessary to <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>subtract 0011 from the sum</p>",
            "<b>B.</b> <p>add 0011 to the sum</p>",
            "<b>C.</b> <p>subtract 0110 from the sum</p>",
            "<b>D.</b> <p>add 0110 to the sum</p>"
          ],
          "correct_answer": "<b>A.</b> <p>subtract 0011 from the sum</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49474/isro2007-04\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 89,
          "question": "<p>The circuit shown in the given figure is a <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q3_2cdef408.jpg\"><br> <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>full adder</p>",
            "<b>B.</b> <p>full subtracter</p>",
            "<b>C.</b> <p>shift register</p>",
            "<b>D.</b> <p>decade counter</p>"
          ],
          "correct_answer": "<b>B.</b> <p>full subtracter</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48451/isro2007-03\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 90,
          "question": "<p>The circuit shown in the following figure realizes the function. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Digital_Logic\\q2_6dcd75de.jpg\"><br> <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((\\overline{A+B}+C)(\\bar{D}\\bar{E})\\)</p>",
            "<b>B.</b> <p>\\((\\overline{A+B}+C)(D\\bar{E})\\)</p>",
            "<b>C.</b> <p>\\((A+ \\overline{B+C})(\\bar{D}E)\\)</p>",
            "<b>D.</b> <p>\\((A+ B+\\bar{C})(\\bar{D} \\bar{E})\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\((\\overline{A+B}+C)(\\bar{D}\\bar{E})\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48446/isro2007-02\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 91,
          "question": "<p>The Boolean expression \\(Y=(A+\\bar{B}+\\bar{A}B)\\bar{C}\\) is given by <br><br><strong>(ISRO CSE 2007)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(A\\bar{C}\\)</p>",
            "<b>B.</b> <p>\\(B\\bar{C}\\)</p>",
            "<b>C.</b> <p>\\(\\bar{C}\\)</p>",
            "<b>D.</b> <p>AB</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(\\bar{C}\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48443/isro2007-01\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
