window.__examLoadCallback({
  "title": "Stack - Stack - Slot 1",
  "duration": 42,
  "sections": [
    {
      "name": "Stack",
      "questions": [
        {
          "id": 1,
          "question": "<p>Consider a stack data structure into which we can PUSH and POP records. Assume that each record pushed in the stack has a positive integer key and that all keys are distinct.  <br>\nWe wish to augment the stack data structure with an \\(O(1) \\) time MIN operation that returns a pointer to the record with the smallest key present in the stack  <br><br>\n1) without deleting the corresponding record, and  <br>\n2) without increasing the complexities of the standard stack operations.  <br><br>\nWhich one or more of the following approach(es) can achieve it? <br><br><strong>(GATE CSE 2025 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Keep with every record in the stack, a pointer to the record with the smallest key below it.</p>",
            "<b>B.</b> <p>Keep a pointer to the record with the smallest key in the stack.</p>",
            "<b>C.</b> <p>Keep an auxiliary array in which the key values of the records in the stack are maintained in sorted order.</p>",
            "<b>D.</b> <p>Keep a Min-Heap in which the key values of the records in the stack are maintained.</p>"
          ],
          "correct_answer": "<b>A.</b> <p>Keep with every record in the stack, a pointer to the record with the smallest key below it.</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/460800/gate-cse-2025-set-2-question-35#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Let S1 and S2 be two stacks. S1 has capacity of 4 elements. S2 has capacity of\n2 elements. S1 already has 4 elements: 100, 200, 300, and 400, whereas S2 is\nempty, as shown below.<br><br>\n\\(\n\\begin{array}{|c|}\n\\hline  400 (Top)  \\\\\n\\hline  300 \\\\\n\\hline  200\\\\\n\\hline  100 \\\\\n\\hline\n\\end{array}\\)<br>Stack S1\n<br>\n<br>\n\\(\n\\begin{array}{|c|}\n\\hline    \\\\\n\\hline    \\\\\n\\hline\n\\end{array}\\)<br>Stack S2\n<br><br>\nOnly the following three operations are available:<br>\n<br>PushToS2: Pop the top element from S1 and push it on S2.\n<br>PushToS1: Pop the top element from S2 and push it on S1.\n<br>GenerateOutput: Pop the top element from S1 and output it to the\nuser.<br><br>\nNote that the pop operation is not allowed on an empty stack and the push operation\nis not allowed on a full stack.\n<br><br>Which of the following output sequences can be generated by using the above\noperations? <br><br><strong>(GATE CSE 2024 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>100, 200, 400, 300</p>",
            "<b>B.</b> <p>200, 300, 400, 100</p>",
            "<b>C.</b> <p>400, 200, 100, 300</p>",
            "<b>D.</b> <p>300, 200, 400, 100</p>"
          ],
          "correct_answer": "<b>B.</b> <p>200, 300, 400, 100</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/422859/gate-cse-2024-set-2-question-38#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Consider the operator precedence and associativity rules for the integer arithmetic operators given in the table below.<br>\n\\(\\begin{array}{|c|l|l|}\n\\hline Operator &amp; Precedence &amp; Associativity \\\\\n\\hline+ &amp; Highest &amp; Left \\\\\n\\hline- &amp; High &amp; Right \\\\\n\\hline* &amp; Medium &amp; Right \\\\\n\\hline  /  &amp; Low &amp; Right \\\\\n\\hline\n\\end{array}\n\\)<br>\nThe value of the expression \\(3+1+5 * 2 / 7+2-4-7-6 / 2 \\) as per the above rules is _____ <br><br><strong>(GATE CSE 2024 SET-1)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "6",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/422819/gate-cse-2024-set-1-question-23#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>Consider the following sequence of operations on an empty stack.<br><br>push(54); push(52); pop(); push(55); push(62); s=pop();<br><br>\nConsider the following sequence of operations on an empty queue.\n<br><br>\nenqueue(21); enqueue(24); dequeue(); enqueue(28); enqueue(32); q=dequeue();<br><br>\nThe value of s+q is ___________. <br><br><strong>(GATE CSE 2021 SET-1)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "86",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/357430/gate-cse-2021-set-1-question-21#a_list_title\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>A stack is implemented with an array of \\({ }^{\\prime} A[0 \\ldots N-1]^{\\prime}\\) and a variable \\(\\text { 'pos'. }\\) The push and pop operations are defined by the following code.<br><pre><code> push (x)\n    A[pos] &lt;- x\n    pos &lt;- pos -1\nend push\npop()\n    pos &lt;- pos+1\n    return A[pos]\nend pop</code></pre><br>Which of the following will initialize an empty stack with capacity N for the above implementation? <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\text { pos } \\leftarrow-1\\)</p>",
            "<b>B.</b> <p>\\(\\text { pos } \\leftarrow 0\\)</p>",
            "<b>C.</b> <p>\\(\\text { pos } \\leftarrow 1\\)</p>",
            "<b>D.</b> <p>\\(\\text { pos } \\leftarrow N-1\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(\\text { pos } \\leftarrow N-1\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331311/isro2020-72\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Convert the pre-fix expression to in-fix \\(-^{*}+A B C^{*}-D E+F G\\) <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((A-B)^{*} C+\\left(D^{*} E\\right)-(F+G)\\)</p>",
            "<b>B.</b> <p>\\((A+B)^{*} C-(D-E)^{*}(F-G)\\)</p>",
            "<b>C.</b> <p>\\((A+B-C)^{*}(D-E)^{*}(F+G)\\)</p>",
            "<b>D.</b> <p>\\((((A+B)*C)-((D-E)*(F+G)))\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\((((A+B)*C)-((D-E)*(F+G)))\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "Originally all Options are wrong. We have modified one option.<br><a href=\"https://gateoverflow.in/331339/isro2020-4\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>Choose the equivalent prefix form of the following expression<br>\\((a+(b-c))^{\\star}((d-e) /(f+g-h))\\) <br><br><strong>(ISRO CSE 2017)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\({ }^{\\star}+a-b c /-d e-+f g h\\)</p>",
            "<b>B.</b> <p>\\({ }^{\\star}+a-b c -/d e-+f g h\\)</p>",
            "<b>C.</b> <p>\\({ }^{\\star}+a-b c /-ed-+f g h\\)</p>",
            "<b>D.</b> <p>\\({ }^{*}+\\mathrm{ab}-\\mathrm{c} /-\\mathrm{de}-+\\mathrm{fgh}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\({ }^{\\star}+a-b c /-d e-+f g h\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/128769/isro2017-69\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>The best data structure to check whether an arithmetic expression has  balanced parenthesis is  a: <br><br><strong>(ISRO CSE 2017)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Queue</p>",
            "<b>B.</b> <p>Stack</p>",
            "<b>C.</b> <p>Tree</p>",
            "<b>D.</b> <p>List</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Stack</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/128743/isro2017-59\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>The following postfix expression with single digit operands is evaluated using a stack:<br>\\(8 \\ 2 \\ 3 \\ \\;\\hat{}\\; / \\ 2 \\ 3 * + 5 \\ 1 * -\\)<br>Note that \\(\\hat{}\\;\\) is the exponentiation operator. The top two elements of the stack after the first * is evaluated are <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>6,1</p>",
            "<b>B.</b> <p>5,7</p>",
            "<b>C.</b> <p>3,2</p>",
            "<b>D.</b> <p>1,5</p>"
          ],
          "correct_answer": "<b>A.</b> <p>6,1</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1236/gate2007-38-isro2016-27\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>If the sequence of operations - push (1), push (2), pop, push (1), push (2), pop, pop, pop, push (2), pop are performed on a stack, the sequence of popped out values <br><br><strong>(ISRO CSE 2015)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>2,2,1,1,2</p>",
            "<b>B.</b> <p>2,2,1,2,2</p>",
            "<b>C.</b> <p>2,1,2,2,1</p>",
            "<b>D.</b> <p>2,1,2,2,2</p>"
          ],
          "correct_answer": "<b>A.</b> <p>2,2,1,1,2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/51080/isro2015-11\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>The result evaluating the postfix expression 10    5  +  60     6   /  *  8 -   is <br><br><strong>(GATE CSE 2015 SET-3)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>284</p>",
            "<b>B.</b> <p>213</p>",
            "<b>C.</b> <p>142</p>",
            "<b>D.</b> <p>71</p>"
          ],
          "correct_answer": "<b>C.</b> <p>142</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/8408/gate2015-3-18#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>The five items: A, B, C, D, and E are pushed in a stack, one after other starting from A. The stack is popped four items and each element is inserted in a queue. The two elements are deleted from the queue and pushed back on the stack. Now one item is popped from the stack. The popped item is <br><br><strong>(ISRO CSE 2014)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A</p>",
            "<b>B.</b> <p>B</p>",
            "<b>C.</b> <p>C</p>",
            "<b>D.</b> <p>D</p>"
          ],
          "correct_answer": "<b>D.</b> <p>D</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49487/isro2007-16-isro2009-30-isro2014-43\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>Suppose a stack implementation supports an instruction REVERSE, which reverses the order\nof elements on the stack, in addition to the PUSH and POP instructions. Which one of the\nfollowing statements is TRUE with respect to this modified stack? <br><br><strong>(GATE CSE 2014 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A queue cannot be implemented using this stack.</p>",
            "<b>B.</b> <p>A queue can be implemented where ENQUEUE takes a single instruction and\nDEQUEUE takes a sequence of two instructions.</p>",
            "<b>C.</b> <p>A queue can be implemented where ENQUEUE takes a sequence of three instructions\nand DEQUEUE takes a single instruction</p>",
            "<b>D.</b> <p>A queue can be implemented where both ENQUEUE and DEQUEUE take a single\ninstruction each.</p>"
          ],
          "correct_answer": "<b>C.</b> <p>A queue can be implemented where ENQUEUE takes a sequence of three instructions\nand DEQUEUE takes a single instruction</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/2007/gate2014-2-41#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>The five items: A, B, C, D, and E are pushed in a stack, one after other starting from A. The stack is popped four items and each element is inserted in a queue. The two elements are deleted from the queue and pushed back on the stack. Now one item is popped from the stack. The popped item is <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A</p>",
            "<b>B.</b> <p>B</p>",
            "<b>C.</b> <p>C</p>",
            "<b>D.</b> <p>D</p>"
          ],
          "correct_answer": "<b>D.</b> <p>D</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/49487/isro2007-16-isro2009-30-isro2014-43\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>The expression \\(1 * 2 \\wedge 3 * 4 \\wedge 5 * 6\\) will be evaluated as <br><br><strong>(ISRO CSE 2009)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(32^{30}\\)</p>",
            "<b>B.</b> <p>\\(162^{30}\\)</p>",
            "<b>C.</b> <p>49152</p>",
            "<b>D.</b> <p>173458</p>"
          ],
          "correct_answer": "<b>C.</b> <p>49152</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/48052/isro2009-32\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
