window.__examLoadCallback({
  "title": "Theory_of_Computation - Theory_of_Computation - Slot 6",
  "duration": 42,
  "sections": [
    {
      "name": "Theory_of_Computation",
      "questions": [
        {
          "id": 1,
          "question": "<p>Consider the language L given by the regular expression (a+b )* b (a+b )  over the alphabet {a, b}. The smallest number of states needed in a deterministic finite-state automation (DFA) accepting L is ___________. <br><br><strong>(GATE CSE 2017 SET-1)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "4",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/118302/gate2017-1-22#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Consider the following grammar.<br><br>\nP\\(\\rightarrow\\)xQRS <br>\nQ\\(\\rightarrow\\)yz|z<br>R\\(\\rightarrow\\)w|\\(\\varepsilon\\) <br>S\\(\\rightarrow\\)y<br><br>What is FOLLOW (Q) ? <br><br><strong>(GATE CSE 2017 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>{R}</p>",
            "<b>B.</b> <p>{w}</p>",
            "<b>C.</b> <p>{w, y}</p>",
            "<b>D.</b> <p>{w, $}</p>"
          ],
          "correct_answer": "<b>C.</b> <p>{w, y}</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/118297/gate2017-1-17#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Consider the following context-free grammar over the alphabet  \\(\\sum\\) = {a,b,c} with S as the start\nsymbol. <br><br>\nS\\(\\rightarrow\\)abScT|abcT <br>\nT\\(\\rightarrow\\)bT|b<br><br>\nWhich one of the following represents the language generated by the above grammar ? <br><br><strong>(GATE CSE 2017 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>{\\((ab)^{n}(cb)^{n}|n\\geq 1\\)}</p>",
            "<b>B.</b> <p>{\\((ab)^{n}cb^{m_{1}}cb^{m_{2}}...cb^{m_{n}}|n,m_{1},m_{2},...,m_{n}\\geq 1\\)}</p>",
            "<b>C.</b> <p>\\((ab)^{n}(cb^{m})^{n}|n,m\\geq 1\\)</p>",
            "<b>D.</b> <p>\\((ab)^{n}(cb^{n})^{m}|n,m\\geq 1\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>{\\((ab)^{n}cb^{m_{1}}cb^{m_{2}}...cb^{m_{n}}|n,m_{1},m_{2},...,m_{n}\\geq 1\\)}</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/118290/gate2017-1-10#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>Which one of the following grammars is free from left recursion? <br><br><strong>(GATE CSE 2016 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(S\\rightarrow AB \\) <br> \\(A\\rightarrow Aa|b\\)<br> \\(B\\rightarrow c\\)</p>",
            "<b>B.</b> <p>\\(S\\rightarrow Ab|Bb|c \\) <br> \\( A\\rightarrow Bb|\\varepsilon \\) <br> \\(B\\rightarrow e\\)</p>",
            "<b>C.</b> <p>\\(S\\rightarrow Aa|B \\) <br> \\(A\\rightarrow Bb|Sc|\\varepsilon \\) <br> \\(B\\rightarrow d\\)</p>",
            "<b>D.</b> <p>\\(S\\rightarrow Aa|Bb|c \\) <br> \\(A\\rightarrow Bd|\\varepsilon \\) <br> \\(B\\rightarrow Ae|\\varepsilon\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(S\\rightarrow Ab|Bb|c \\) <br> \\( A\\rightarrow Bb|\\varepsilon \\) <br> \\(B\\rightarrow e\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/39594/gate2016-2-45#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Consider the following languages.<br>\nL1 = {\\(\\lt\\)M\\(\\gt\\) |M takes at least 2016 steps on some input},<br>\nL2 = {\\(\\lt\\)M\\(\\gt\\)| M takes at least 2016 steps on all inputs} and <br>\nL3 = {\\(\\lt\\)M|M accepts \\(\\varepsilon\\)},<br>\nwhere for each Turing machine M, \\(\\lt\\)M\\(\\gt\\) denotes a specific encoding of M. Which one of the following is TRUE? <br><br><strong>(GATE CSE 2016 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>L1 is recursive and L2,L3 are notrecursive</p>",
            "<b>B.</b> <p>L2 is recursiveand L1,L3 are notrecursive</p>",
            "<b>C.</b> <p>L1,L2 are recursiveand L3 is notrecursive</p>",
            "<b>D.</b> <p>L1,L2,L3 are recursive</p>"
          ],
          "correct_answer": "<b>C.</b> <p>L1,L2 are recursiveand L3 is notrecursive</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/39596/gate2016-2-44#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Consider the following languages: <br>\\(L_{1}=\\{a^{n}b^{m}c^{n+m}:m,n\\geq 1\\}\\)<br> \\(L_{2}=\\{a^{n}b^{n}c^{2n}:n\\geq 1\\}\\) <br>Which one of the following is TRUE? <br><br><strong>(GATE CSE 2016 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Both L1 and L2 are context-free.</p>",
            "<b>B.</b> <p>L1 is context-free while L2 is not context-free.</p>",
            "<b>C.</b> <p>L2 is context-free while L1 is not context-free.</p>",
            "<b>D.</b> <p>Neither L1 nor L2 is context-free.</p>"
          ],
          "correct_answer": "<b>B.</b> <p>L1 is context-free while L2 is not context-free.</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/39605/gate2016-2-43#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>Consider the following two statements:<br>\nI. If all states of an NFA are accepting states then the language accepted by the NFA is \\(\\sum ^{*}\\) .<br>\nII. There exists a regular language A such that for all languages B, A\\(\\cap\\)B is regular. <br>\nWhich one of the following is CORRECT? <br><br><strong>(GATE CSE 2016 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Only I is true</p>",
            "<b>B.</b> <p>Only II is true</p>",
            "<b>C.</b> <p>Both I and II are true</p>",
            "<b>D.</b> <p>Both I and II are false</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Only II is true</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/39591/gate2016-2-42#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>Consider the following types of languages: \\(L_{1}\\):Regular, \\(L_{2}\\):Context-free, \\(L_{3}\\):Recursive, \\(L_{4}\\):Recursively enumerable. <br>Which of the following is/are TRUE? <br>\nI. \\(\\bar{L}_{3}\\cup L_{4}\\) is recursivelyenumerable<br>\nII. \\(\\bar{L}_{2}\\cup L_{3}\\) is recursive <br>\nIII. \\(L_{1}^{*}\\cup L_{2}\\) is context-free <br>\nIV. \\(L_{1}\\cup \\bar{L}_{2}\\) is context-free <br><br><strong>(GATE CSE 2016 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>I only</p>",
            "<b>B.</b> <p>I and III only</p>",
            "<b>C.</b> <p>I and IV only</p>",
            "<b>D.</b> <p>I, II and III only</p>"
          ],
          "correct_answer": "<b>D.</b> <p>I, II and III only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/39574/gate2016-2-18#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>Language L1 is defined by the grammar: \\(S_{1}\\rightarrow aS_{1}b|\\varepsilon \\)<br>\nLanguage L2 is defined by the grammar: \\(S_{2}\\rightarrow abS_{2}|\\varepsilon\\)<br>\nConsider the following statements:<br>\nP: L1 is regular <br>\nQ: L2 is regular<br>\nWhich one of the following is TRUE? <br><br><strong>(GATE CSE 2016 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Both P and Q are true</p>",
            "<b>B.</b> <p>P is true and Q is false</p>",
            "<b>C.</b> <p>P is false and Q is true</p>",
            "<b>D.</b> <p>Both P and Q are false</p>"
          ],
          "correct_answer": "<b>C.</b> <p>P is false and Q is true</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/39542/gate2016-2-17#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>The number of states in the minimum sized DFA that accepts the language defined by the regular expression <br>(0+1)* (0+1)(0+1)* <br> is _______. <br><br><strong>(GATE CSE 2016 SET-2)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "2",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/39562/gate2016-2-16#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>Let X be a recursive language and Y be a recursively enumerable but not recursive language. Let W and Z be two languages such that \\(\\bar{Y}\\)  reduces to W, and Z reduces to \\(\\bar{X}\\) (reduction means the standard many-one-reduction). Which one of the following statements is TRUE? <br><br><strong>(GATE CSE 2016 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>W can be recursively enumerable and Z is recursive.</p>",
            "<b>B.</b> <p>W can be recursive and Z is recursively enumerable</p>",
            "<b>C.</b> <p>W is not recursively enumerable and Z is recursive</p>",
            "<b>D.</b> <p>W is not recursively enumerable and Z is not recursive.</p>"
          ],
          "correct_answer": "<b>C.</b> <p>W is not recursively enumerable and Z is recursive</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/39721/gate2016-1-44#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>Consider the transition diagram of a PDA given below with input alphabet \\(\\Sigma \\)={a,b} and stack alphabet \\(\\Gamma\\)={X,Z}. Z is the initial stack symbol. Let L denote the language accepted by the PDA. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Theory_of_Computation\\q43_b54e1db2.jpg\"> <br>Which one of the following is TRUE? <br><br><strong>(GATE CSE 2016 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(L=\\{a^{n}b^{n}|n\\geq 0\\}\\) is not accepted by any finite automata</p>",
            "<b>B.</b> <p>\\(L=\\{a^{n}|n\\geq 0\\}\\cup \\{a^{n}b^{n}|n\\geq 0\\}\\) is not accepted by any deterministic PDA</p>",
            "<b>C.</b> <p>L is not accepted by any Turing machine that halts one very input</p>",
            "<b>D.</b> <p>\\(L=\\{a^{n}|n\\geq 0\\}\\cup \\{a^{n}b^{n}|n\\geq 0\\}\\) is deterministic context-free</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(L=\\{a^{n}|n\\geq 0\\}\\cup \\{a^{n}b^{n}|n\\geq 0\\}\\) is deterministic context-free</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/39732/gate2016-1-43#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>Consider the following context-free grammars:<br><br>\nG1: S\\(\\rightarrow\\)aS|B,<br> B\\(\\rightarrow\\)b|bB <br>\nG2: S\\(\\rightarrow\\)aA|bB, <br> A\\(\\rightarrow\\)aA|B|\\(\\varepsilon\\), <br>  B\\(\\rightarrow\\)bB|\\(\\varepsilon\\) <br><br> Which one of the following pair of languages is generated by G1 and G2, respectively? <br><br><strong>(GATE CSE 2016 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(\\{a^{m}b^{n}|m \\gt 0 \\; or \\;  n \\gt 0\\} \\) and \\(\\{a^{m}b^{n}|m\\gt 0  \\;  and  \\;  n\\gt 0\\}\\)</p>",
            "<b>B.</b> <p>\\(\\{a^{m}b^{n}|m\\gt 0  \\; or \\;  n\\gt 0\\}\\) and  \\(\\{a^{m}b^{n}|m\\gt 0  \\; and  \\; n \\geq  0\\}\\)</p>",
            "<b>C.</b> <p>\\(\\{a^{m}b^{n}|m\\geq 0  \\;  or   \\; n\\gt 0\\} \\) and \\(\\{a^{m}b^{n}|m\\gt 0  \\;  and  \\;  n\\gt  0\\}\\)</p>",
            "<b>D.</b> <p>\\(\\{a^{m}b^{n}|m\\geq 0  \\; and  \\;  n\\gt 0\\} \\) and \\(\\{a^{m}b^{n}|m\\gt 0  \\;  or  \\;  n\\gt 0\\}\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(\\{a^{m}b^{n}|m\\geq 0  \\; and  \\;  n\\gt 0\\} \\) and \\(\\{a^{m}b^{n}|m\\gt 0  \\;  or  \\;  n\\gt 0\\}\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/39705/gate2016-1-42#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>Which one of the following regular expressions represents the language: the set of all binary strings having two consecutive 0s and two consecutive 1s? <br><br><strong>(GATE CSE 2016 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>(0+1)*0011(0+1)*+(0+1)*1100(0+1)*</p>",
            "<b>B.</b> <p>(0+1)*(00(0+1)*11+11(0+1)*00)(0+1)*</p>",
            "<b>C.</b> <p>(0+1)*00(0+1)*+(0+1)*11(0+1)*</p>",
            "<b>D.</b> <p>00(0+1)*11+11(0+1)*00</p>"
          ],
          "correct_answer": "<b>B.</b> <p>(0+1)*(00(0+1)*11+11(0+1)*00)(0+1)*</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/39647/gate2016-1-18#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>Which  of the following decision problems are undecidable?<br>\nI. Given NFAs N1 and N2, is L(N1)\\(\\cap\\)L(N2) = \\(\\phi\\)?<br>\nII. Given a CFG G = (N,\\(\\Sigma \\),P,S)  and a string  \\(x \\in\\Sigma ^*\\), does  \\(x \\in\\) L(G)?<br>\nIII. Given CFGs G1 and G2, is L(G1) = L(G2)?<br>\nIV. Given a TM M, is L(M) = \\(\\phi\\)? <br><br><strong>(GATE CSE 2016 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>I and IV only</p>",
            "<b>B.</b> <p>II and III only</p>",
            "<b>C.</b> <p>III and IV only</p>",
            "<b>D.</b> <p>II and IV only</p>"
          ],
          "correct_answer": "<b>C.</b> <p>III and IV only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/39651/gate2016-1-17#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
