window.__examLoadCallback({
  "title": "Context_Free_Language - Context_Free_Language - Slot 1",
  "duration": 3,
  "sections": [
    {
      "name": "Context_Free_Language",
      "questions": [
        {
          "id": 1,
          "question": "<p>\\(S \\rightarrow a S a|b S b| a \\mid b\\)<br>The language generated by the above grammar over the alphabet {a,b} is the set of: <br><br><strong>(ISRO CSE 2016)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>all palindromes</p>",
            "<b>B.</b> <p>all odd length palindromes</p>",
            "<b>C.</b> <p>strings that begin and end with the same symbol</p>",
            "<b>D.</b> <p>all even length palindromes</p>"
          ],
          "correct_answer": "<b>B.</b> <p>all odd length palindromes</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1304/gate2009-12-isro2016-37\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
