window.__examLoadCallback({
  "title": "Operating_System - Operating_System - Slot 4",
  "duration": 42,
  "sections": [
    {
      "name": "Operating_System",
      "questions": [
        {
          "id": 1,
          "question": "<p>The operating system and the other processes are protected from being modified by an already running process because <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>they run at different time instants and not in parallel</p>",
            "<b>B.</b> <p>they are in different logical addresses</p>",
            "<b>C.</b> <p>they use a protection algorithm in the scheduler</p>",
            "<b>D.</b> <p>every address generated by the CPU is being checked against the relocation and limit parameters</p>"
          ],
          "correct_answer": "<b>D.</b> <p>every address generated by the CPU is being checked against the relocation and limit parameters</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331282/isro2020-26\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>What is compaction refers to <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>a technique for overcoming internal fragmentation</p>",
            "<b>B.</b> <p>a paging technique</p>",
            "<b>C.</b> <p>a technique for overcoming external fragmentation</p>",
            "<b>D.</b> <p>a technique for compressing the data</p>"
          ],
          "correct_answer": "<b>C.</b> <p>a technique for overcoming external fragmentation</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331280/isro2020-25\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Raymonds tree based algorithm ensures <br><br><strong>(ISRO CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>no starvation, but deadlock may occur in rare cases</p>",
            "<b>B.</b> <p>no deadlock, but starvation may occur</p>",
            "<b>C.</b> <p>neither deadlock nor starvation can occur</p>",
            "<b>D.</b> <p>deadlock may occur in cases where the process is already starved</p>"
          ],
          "correct_answer": "<b>B.</b> <p>no deadlock, but starvation may occur</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/331328/isro2020-22\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>Consider a paging system that uses 1-level page table residing in main memory and a TLB for address translation. Each main memory access takes 100 ns and TLB lookup takes 20 ns. Each page transfer to/from the disk takes 5000 ns. Assume that the TLB hit ratio is 95%, page fault rate is 10%. Assume that for 20% of the total page faults, a dirty page has to be written back to disk before the required page is read from disk. TLB update time is negligible. The average memory access time in ns (round off to 1 decimal places) is ___________ <br><br><strong>(GATE CSE 2020)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "154.5",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/333178/gate2020-cs-53#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Consider the following set of processes, assumed to have arrived at time 0. Consider the CPU scheduling algorithms Shortest Job First (SJF) and Round Robin (RR). For RR, assume that the processes are scheduled in the order \\(P_1,P_2,P_3,P_4\\). <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Operating_System\\q50_bc55af2e.jpg\"><br>If the time quantum for RR is 4 ms, then the absolute value of the difference between the average turnaround times (in ms) of SJF and RR  (round off to 2 decimal places is_______ <br><br><strong>(GATE CSE 2020)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "5.25",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/333181/gate2020-cs-50#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Consider the following five disk five disk access requests of the form (request id, cylinder number) that are present in the disk scheduler queue at a given time.<br><br>\n(P,155),(Q,85),(R,110),(S,30),(T,115)<br><br>\nAssume the head is positioned at cylinder 100. The scheduler follows Shortest Seek Time First scheduling to service the requests.\n<br><br>\nWhich one of the following statements is FALSE? <br><br><strong>(GATE CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>T is serviced before P.</p>",
            "<b>B.</b> <p>Q is serviced after S, but before T.</p>",
            "<b>C.</b> <p>The head reverses its direction of movement between servicing of Q and P.</p>",
            "<b>D.</b> <p>R is serviced before P.</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Q is serviced after S, but before T.</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/333196/gate2020-cs-35#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>Each of a set of n processes executes the following code using two semaphores a and b initialized to 1 and 0, respectively. Assume that count is a shared variable initialized to 0 and not used in CODE SECTION P.<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Operating_System\\q34_ded3142a.jpg\"><br> What does the code achieve? <br><br><strong>(GATE CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>It ensures that no process executes CODE SECTION Q before every process has finished CODE SECTION P.</p>",
            "<b>B.</b> <p>It ensures that two processes are in CODE SECTION Q at any time.</p>",
            "<b>C.</b> <p>It ensures that all processes execute CODE SECTION P mutually exclusively.</p>",
            "<b>D.</b> <p>It ensures that at most n-1 processes are in CODE SECTION P at any time.</p>"
          ],
          "correct_answer": "<b>A.</b> <p>It ensures that no process executes CODE SECTION Q before every process has finished CODE SECTION P.</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/333197/gate2020-cs-34#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>Consider the following statements about process state transitions for a system using preemptive scheduling. <br><br>\nI. A running process can move to ready state.<br>\nII. A ready process can move to running state.<br>\nIII. A blocked process can move to running state.<br>\nIV. A blocked process can move to ready state.<br><br>\nWhich of the above statements are TRUE? <br><br><strong>(GATE CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>I, II and III only</p>",
            "<b>B.</b> <p>II and III only</p>",
            "<b>C.</b> <p>I, II and IV only</p>",
            "<b>D.</b> <p>I, II, III and IV only</p>"
          ],
          "correct_answer": "<b>C.</b> <p>I, II and IV only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/333219/gate2020-cs-12#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>Consider allocation of memory to a new process. Assume that none of the existing holes in the memory will exactly fit the process's memory requirement. Hence, a new hole of smaller size will be created if allocation is made in any of the existing holes. Which one of the following statement is TRUE? <br><br><strong>(GATE CSE 2020)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>The hole created by first fit is always larger than the hole created by next fit.</p>",
            "<b>B.</b> <p>The hole created by worst fit is always larger than the hole created by first fit.</p>",
            "<b>C.</b> <p>The hole created by best fit is never larger than the hole created by first fit.</p>",
            "<b>D.</b> <p>The hole created by next fit is never larger than the hole created by best fit.</p>"
          ],
          "correct_answer": "<b>C.</b> <p>The hole created by best fit is never larger than the hole created by first fit.</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/333220/gate2020-cs-11#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>The index node (inode) of a Unix-like file system has 12 direct, one single-indirect and one double-indirect pointer The disk block size is 4 kB and the disk block addresses 32-bits long. The maximum possible file size is (rounded off to 1 decimal place) __________ GB. <br><br><strong>(GATE CSE 2019)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "4",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/302806/gate2019-cs-42#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>Consider the following four processes with arrival times (in milliseconds) and their length of CPU burst (in milliseconds) as shown below:\n<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Operating_System\\q41_98bc91e9.jpg\">\nThese processes are run on a single processor using preemptive Shortest Remaining Time First scheduling algorithm. If the average waiting time of the processes is 1 millisecond, then the value of Z is __________. <br><br><strong>(GATE CSE 2019)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "2",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/302807/gate2019-cs-41#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>Consider the following snapshot of a system running n concurrent processes. Process \\(i\\) is holding \\(X_i\\) instances of a resource R, \\( 1\\leq i\\leq n\\). Assume that all instances of R are currently in use. Further, for all \\(i\\), process \\(i\\) can place a request for at most \\(Y_i\\) additional instances of R while holding the \\(X_i\\) instances it already has. Of the n processes, there are exactly two processes p and q such that \\(Y_p=Y_q=0\\). Which one of the following conditions guarantees that no other process apart from p and q can complete execution? <br><br><strong>(GATE CSE 2019)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(X_p+X_q \\lt Min \\{Y_k|1\\leq k\\leq n,k\\neq p,k\\neq q\\}\\)</p>",
            "<b>B.</b> <p>\\(X_p+X_q \\lt Max \\{Y_k|1\\leq k\\leq n,k\\neq p,k\\neq q\\}\\)</p>",
            "<b>C.</b> <p>\\(Min(X_p,X_q)\\geq Min \\{Y_k|1\\leq k\\leq n,k\\neq p,k\\neq q\\}\\)</p>",
            "<b>D.</b> <p>\\(Min(X_p,X_q)\\leq Max \\{Y_k|1\\leq k\\leq n,k\\neq p,k\\neq q\\}\\)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>\\(X_p+X_q \\lt Min \\{Y_k|1\\leq k\\leq n,k\\neq p,k\\neq q\\}\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/302809/gate2019-cs-39#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>Assume that in a certain computer, the virtual addresses are 64 bits long and the physical addresses are 48 bits long. The memory is word addressable. The page size is 8kB and the word size is 4 bytes. The Translation Look-aside Buffer (TLB) in the address translation path has 128 valid entries. At most how many distinct virtual addresses can be translated without any TLB miss? <br><br><strong>(GATE CSE 2019)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(16 \\times 2^{10}\\)</p>",
            "<b>B.</b> <p>\\(256 \\times 2^{10}\\)</p>",
            "<b>C.</b> <p>\\(4 \\times 2^{20}\\)</p>",
            "<b>D.</b> <p>\\(8 \\times 2^{20}\\)</p>"
          ],
          "correct_answer": "<b>B.</b> <p>\\(256 \\times 2^{10}\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/302815/gate2019-cs-33#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>Consider three concurrent processes P1, P2 and P3 as shown below, which access a shared variable D that has been initialized to 100. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Operating_System\\q23_e3e5dd62.jpg\"><br>\nThe process are executed on a uniprocessor system running a time-shared operating system. If the minimum and maximum possible values of D after the three processes have completed execution are X and Y respectively, then the value of Y-X is __________. <br><br><strong>(GATE CSE 2019)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "80",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/302825/gate2019-cs-23#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>The following C program is executed on a Unix / Linux system:<pre><code>#include &lt; unistd.h &gt;\n  int main() {\n    int i;\n    for (i = 0; i &lt; 10; i++)\n      if (i % 2 == 0) fork();\n    return 0;\n  }</code></pre>\nThe total number of child process created is __________ . <br><br><strong>(GATE CSE 2019)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "31",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/302831/gate2019-cs-17#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
