window.__examLoadCallback({
  "title": "Theory of Computation - Identify Class Language",
  "duration": 86,
  "sections": [
    {
      "name": "Identify Class Language",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"80293\"></a><div itemprop=\"text\"><p>FORTRAN is a:</p>\n\n</div><br><br><b>GATE CSE 1987 | Question: 1-xiii</b></p>",
          "type": "single",
          "options": [
            "<p>Regular language.</p>",
            "<p>Context-free language.</p>",
            "<p>Context-senstive language.</p>",
            "<p>None of the above.</p>"
          ],
          "correct_answer": "<p>Context-senstive language.</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/80293/gate-cse-1987-question-1-xiii\" target=\"_blank\">https://gateoverflow.in/80293/gate-cse-1987-question-1-xiii</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"93949\"></a><div itemprop=\"text\">What is the type of the language \\( L \\), where \\( L=\\{a^n b^n \\mid 0 &lt; n &lt; 327 \\text{-th prime number} \\} \\)</div><br><br><b>GATE CSE 1988 | Question: 2ix</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "N/A",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/93949/gate-cse-1988-question-2ix\" target=\"_blank\">https://gateoverflow.in/93949/gate-cse-1988-question-2ix</a></p>"
        },
        {
          "id": 3,
          "question": "<p><a name=\"26653\"></a><div itemprop=\"text\">Show that the Turing machines, which have a read only input tape and constant size work tape, recognize precisely the class of regular languages.</div><br><br><b>GATE CSE 1991 | Question: 17,a</b></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "N/A",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/26653/gate-cse-1991-question-17-a\" target=\"_blank\">https://gateoverflow.in/26653/gate-cse-1991-question-17-a</a></p>"
        },
        {
          "id": 4,
          "question": "<p><a name=\"2515\"></a><div itemprop=\"text\">\n\n<p>\\[ S = \\left\\{x \\mid \\text{ there is an x-block of 5's in the decimal expansion of } \\pi\\right\\} \\]<br>\n(Note: \\( x \\)-\\( block \\) is a maximal block of \\( x \\) successive \\( 5 \\)'s)<br>\nWhich of the following statements is true with respect to \\( S \\)? No reason to be given for the answer.&nbsp;</p>\n\n<ol style=\"list-style-type:lower-roman\">\n\t<li>\\( S \\) is regular</li>\n\t<li>\\( S \\) is recursively enumerable</li>\n\t<li>\\( S \\) is not recursively enumerable</li>\n\t<li>\\( S \\) is recursive</li>\n</ol>\n\n<ol start=\"2\" style=\"list-style-type:upper-alpha\">\n\t<li>Given that a language \\( L_1 \\) is regular and that the language \\( L_1 \\cup L_2 \\) is regular, is the language \\( L_2 \\) always regular? Prove your answer.</li>\n</ol></div><br><br><b>GATE CSE 1994 | Question: 19</b></p>",
          "type": "numeric",
          "options": [
            "<p>Given a set:</p>"
          ],
          "correct_answer": "N/A",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<p><a href=\"https://gateoverflow.in/2515/gate-cse-1994-question-19\" target=\"_blank\">https://gateoverflow.in/2515/gate-cse-1994-question-19</a></p>"
        },
        {
          "id": 5,
          "question": "<p><a name=\"1482\"></a><div itemprop=\"text\"><p>If \\( L1 \\) is context free language and \\( L2 \\) is a regular language which of the following is/are false?</p>\n\n</div><br><br><b>GATE CSE 1999 | Question: 2.4</b></p>",
          "type": "multiple",
          "options": [
            "<p>\\( L1-L2 \\) is not context free</p>",
            "<p>\\( L1 \\cap L2 \\) is context free</p>",
            "<p>\\( \\sim L1 \\) is context free</p>",
            "<p>\\( \\sim L2 \\) is regular</p>"
          ],
          "correct_answer": [
            "<p>\\( L1-L2 \\) is not context free</p>",
            "<p>\\( \\sim L1 \\) is context free</p>"
          ],
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/1482/gate-cse-1999-question-2-4\" target=\"_blank\">https://gateoverflow.in/1482/gate-cse-1999-question-2-4</a></p>"
        },
        {
          "id": 6,
          "question": "<p><a name=\"628\"></a><div itemprop=\"text\"><p>Let \\( L \\) denote the languages generated by the grammar \\( S \\to 0S0 \\mid 00 \\).<br>\nWhich of the following is TRUE?</p>\n\n</div><br><br><b>GATE CSE 2000 | Question: 1.5</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L = 0^+ \\)</p>",
            "<p>\\( L \\) is regular but not \\( 0^+ \\)</p>",
            "<p>\\( L \\) is context free but not regular</p>",
            "<p>\\( L \\) is not context free</p>"
          ],
          "correct_answer": "<p>\\( L \\) is regular but not \\( 0^+ \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/628/gate-cse-2000-question-1-5\" target=\"_blank\">https://gateoverflow.in/628/gate-cse-2000-question-1-5</a></p>"
        },
        {
          "id": 7,
          "question": "<p><a name=\"811\"></a><div itemprop=\"text\"><p>The language accepted by a Pushdown Automaton in which the stack is limited to \\( 10 \\) items is best described as</p>\n\n</div><br><br><b>GATE CSE 2002 | Question: 1.7</b></p>",
          "type": "single",
          "options": [
            "<p>Context free</p>",
            "<p>Regular</p>",
            "<p>Deterministic Context free</p>",
            "<p>Recursive</p>"
          ],
          "correct_answer": "<p>Regular</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/811/gate-cse-2002-question-1-7\" target=\"_blank\">https://gateoverflow.in/811/gate-cse-2002-question-1-7</a></p>"
        },
        {
          "id": 8,
          "question": "<p><a name=\"1081\"></a><div itemprop=\"text\"><p>The language \\( \\left\\{a^mb^nc^{m+n} \\mid&nbsp;m, n \\geq1\\right\\} \\) is</p>\n\n</div><br><br><b>GATE CSE 2004 | Question: 87</b></p>",
          "type": "single",
          "options": [
            "<p>regular</p>",
            "<p>context-free but not regular</p>",
            "<p>context-sensitive but not context free</p>",
            "<p>type-0 but not context sensitive</p>"
          ],
          "correct_answer": "<p>context-free but not regular</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/1081/gate-cse-2004-question-87\" target=\"_blank\">https://gateoverflow.in/1081/gate-cse-2004-question-87</a></p>"
        },
        {
          "id": 9,
          "question": "<p><a name=\"1378\"></a><div itemprop=\"text\"><p>Consider the languages:</p>\n\n<p>\\( L_1 = \\left\\{ a^nb^nc^m \\mid&nbsp;n,m &gt;0\\right\\} \\) &nbsp;and \\( &nbsp;L_2 = \\left\\{a^nb^mc^m\\mid&nbsp;n, m &gt; 0\\right\\} \\)</p>\n\n<p>Which one of the following statements is FALSE?</p>\n\n</div><br><br><b>GATE CSE 2005 | Question: 55</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L_1 \\cap L_2 \\) is a context-free language</p>",
            "<p>\\( L_1 \\cup L_2 \\) is a context-free language</p>",
            "<p>\\( L_1 \\text{ and } L_2 \\) are&nbsp;context-free languages</p>",
            "<p>\\( L_1 \\cap L_2 \\) is a context sensitive language</p>"
          ],
          "correct_answer": "<p>\\( L_1 \\cap L_2 \\) is a context-free language</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/1378/gate-cse-2005-question-55\" target=\"_blank\">https://gateoverflow.in/1378/gate-cse-2005-question-55</a></p>"
        },
        {
          "id": 10,
          "question": "<p><a name=\"993\"></a><div itemprop=\"text\"><p>For \\( s\\in (0+1)^{*} \\) let \\( d(s) \\) denote the decimal value of \\( s&nbsp;( \\)e.g. \\( d (101) = 5&nbsp;). \\) Let<br>\n\\[ L=\\left \\{ s\\in (0+1)^*\\mid d(s) \\text{ mod } 5=2 \\text{ and }d(s) \\text{ mod } 7\\neq 4 \\right \\} \\]Which one of the following statements is true?</p>\n\n</div><br><br><b>GATE CSE 2006 | Question: 30</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L \\) is recursively enumerable, but not recursive</p>",
            "<p>\\( L \\) is recursive, but not context-free</p>",
            "<p>\\( L \\) is context-free, but not regular</p>",
            "<p>\\( L \\) is regular</p>"
          ],
          "correct_answer": "<p>\\( L \\) is regular</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/993/gate-cse-2006-question-30\" target=\"_blank\">https://gateoverflow.in/993/gate-cse-2006-question-30</a></p>"
        },
        {
          "id": 11,
          "question": "<p><a name=\"996\"></a><div itemprop=\"text\"><p>Let \\( L_1 \\) be a regular language, \\( L_2 \\) be a deterministic context-free language and \\( L_3 \\) a &nbsp;recursively enumerable, but not recursive, language. Which one of the following statements is false?</p>\n\n</div><br><br><b>GATE CSE 2006 | Question: 33</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L_1 \\cap L_2 \\) &nbsp;is a deterministic CFL</p>",
            "<p>\\( L_3 \\cap L_1 \\) &nbsp;is recursive</p>",
            "<p>\\( L_1 \\cup L_2 \\) &nbsp;is context free</p>",
            "<p>\\( L_1 \\cap L_2 \\cap L_3 \\) &nbsp;is recursively enumerable</p>"
          ],
          "correct_answer": "<p>\\( L_3 \\cap L_1 \\) &nbsp;is recursive</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/996/gate-cse-2006-question-33\" target=\"_blank\">https://gateoverflow.in/996/gate-cse-2006-question-33</a></p>"
        },
        {
          "id": 12,
          "question": "<p><a name=\"1228\"></a><div itemprop=\"text\"><p>The language \\( L=\\left\\{0^i21^i \\mid&nbsp;i \\geq 0\\right\\} \\) over the alphabet \\( \\left\\{0, 1, 2\\right\\} \\) is:</p>\n\n</div><br><br><b>GATE CSE 2007 | Question: 30</b></p>",
          "type": "single",
          "options": [
            "<p>not recursive</p>",
            "<p>is recursive and is a deterministic CFL</p>",
            "<p>is a regular language</p>",
            "<p>is not a deterministic CFL but a CFL</p>"
          ],
          "correct_answer": "<p>is recursive and is a deterministic CFL</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/1228/gate-cse-2007-question-30\" target=\"_blank\">https://gateoverflow.in/1228/gate-cse-2007-question-30</a></p>"
        },
        {
          "id": 13,
          "question": "<p><a name=\"463\"></a><div itemprop=\"text\"><p>Match the following:<br>\\[ \\small{\\begin{array}{|ll|ll|}\\hline \\text{E.}&nbsp; &amp;&nbsp; \\text{Checking that identifiers are declared before their use} &amp; \\text{P.} &amp; \\text{\\( L \\: = \\: \\left\\{a^nb^mc^nd^m \\mid&nbsp;n\\: \\geq1, m \\geq 1\\right\\} \\)} \\\\\\hline&nbsp;\\text{F.}&nbsp; &amp;&nbsp; \\text{Number of formal parameters in the declaration of a } &amp; \\text{Q.} &amp; \\text{\\( X\\: \\rightarrow XbX \\mid XcX \\mid dXf &nbsp;\\mid g \\)} \\\\ \\text{} &amp; \\text{function agrees with the number of actual parameters}&nbsp;\\\\ \\text{} &amp; \\text{in a use of that function} \\\\\\hline&nbsp;\\text{G.}&nbsp; &amp;&nbsp; \\text{Arithmetic expressions with matched pairs of } &amp; \\text{R.} &amp; \\text{\\( L\\: = \\left\\{wcw\\mid w \\: \\in \\left(a\\mid b\\right)^* \\right\\} \\)} \\\\ \\text{} &amp; \\text{parentheses} \\\\\\hline&nbsp;\\text{H.}&nbsp; &amp;&nbsp; \\text{Palindromes} &amp; \\text{S.} &amp; \\text{\\( X \\: \\rightarrow \\: bXb \\mid \\:cXc \\: \\mid \\epsilon  \\)} \\\\\\hline&nbsp; \\end{array}} \\]</p></div><br><br><b>GATE CSE 2008 | Question: 51</b></p>",
          "type": "single",
          "options": [
            "<p>\\( \\text{E-P, F-R, G-Q, H-S} \\)</p>",
            "<p>\\( \\text{E-R, F-P, G-S, H-Q} \\)</p>",
            "<p>\\( \\text{E-R, F-P, G-Q, H-S} \\)</p>",
            "<p>\\( \\text{E-P, F-R, G-S, H-Q} \\)</p>"
          ],
          "correct_answer": "<p>\\( \\text{E-R, F-P, G-Q, H-S} \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/463/gate-cse-2008-question-51\" target=\"_blank\">https://gateoverflow.in/463/gate-cse-2008-question-51</a></p>"
        },
        {
          "id": 14,
          "question": "<p><a name=\"407\"></a><div itemprop=\"text\"><p>Which of the following is true for the language<br>\n<br>\n\\[ \\left\\{ a^p \\mid p \\text{ is a prime } \\right \\}? \\]</p>\n\n</div><br><br><b>GATE CSE 2008 | Question: 9</b></p>",
          "type": "single",
          "options": [
            "<p>It is not accepted by a Turing Machine</p>",
            "<p>It is regular but not context-free</p>",
            "<p>It is context-free but not regular</p>",
            "<p>It is neither regular nor context-free, but accepted by a Turing machine</p>"
          ],
          "correct_answer": "<p>It is neither regular nor context-free, but accepted by a Turing machine</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/407/gate-cse-2008-question-9\" target=\"_blank\">https://gateoverflow.in/407/gate-cse-2008-question-9</a></p>"
        },
        {
          "id": 15,
          "question": "<p><a name=\"1326\"></a><div itemprop=\"text\"><p>Let \\( L =&nbsp;L_1 \\cap L_2  \\), where \\( L_1 \\) and \\( L_2 \\)&nbsp;are languages as defined below:</p>\n\n<p>\\( L_1= \\left \\{ a^m b^mca^nb^n \\mid m,n \\geq 0 \\right \\} \\)</p>\n\n<p>\\( L_2=\\left \\{ a^i b^j c^k \\mid i,j,k&nbsp;\\geq 0 \\right \\} \\)</p>\n\n<p>Then \\( L \\) is</p>\n\n\n\n</div><br><br><b>GATE CSE 2009 | Question: 40</b></p>",
          "type": "single",
          "options": [
            "<p>Not recursive&nbsp;</p>",
            "<p>Regular</p>",
            "<p>Context free but not regular</p>",
            "<p>Recursively enumerable but not context free.</p>"
          ],
          "correct_answer": "<p>Context free but not regular</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/1326/gate-cse-2009-question-40\" target=\"_blank\">https://gateoverflow.in/1326/gate-cse-2009-question-40</a></p>"
        },
        {
          "id": 16,
          "question": "<p><a name=\"2341\"></a><div itemprop=\"text\"><p>Consider the languages</p>\n\n<p>\\( L1=\\{0^i1^j\\ \\mid i \\neq j\\},  \\)</p>\n\n<p>\\( L2=\\{0^i1^j\\mid i=j\\}, \\)</p>\n\n<p>\\( L3=\\{0^i1^j \\mid i=2j+1\\}, \\)</p>\n\n<p>\\( L4=\\{0^i1^j \\mid i\\neq2j\\} \\)</p>\n\n</div><br><br><b>GATE CSE 2010 | Question: 40</b></p>",
          "type": "single",
          "options": [
            "<p>Only \\( L2 \\) is context free.</p>",
            "<p>Only \\( L2 \\) and \\( L3 \\) are context free.</p>",
            "<p>Only \\( L1 \\) and \\( L2 \\) are context free.</p>",
            "<p>All are context free</p>"
          ],
          "correct_answer": "<p>All are context free</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/2341/gate-cse-2010-question-40\" target=\"_blank\">https://gateoverflow.in/2341/gate-cse-2010-question-40</a></p>"
        },
        {
          "id": 17,
          "question": "<p><a name=\"2128\"></a><div itemprop=\"text\"><p>Consider the languages \\( L1, \\:L2 \\:and \\: L3 \\) as given below.</p>\n\n<p>\\( L1=\\{0^p 1^q \\mid p, q \\in N\\}, \\\\ L2 = \\{0^p 1^q \\mid p, q \\in N \\:and \\:p=q\\} \\: and, \\\\ L3 = \\{0^p 1^q 0^r \\mid p, q, r \\in N\\: and \\: p=q=r\\}. \\)&nbsp;</p>\n\n<p>Which of the following statements is&nbsp;<strong>NOT TRUE</strong>?</p>\n\n</div><br><br><b>GATE CSE 2011 | Question: 26</b></p>",
          "type": "single",
          "options": [
            "<p>Push Down Automata (PDA) can be used to recognize \\( L1 \\) and \\( L2 \\)</p>",
            "<p>\\( L1 \\) is a regular language</p>",
            "<p>All the three languages are context free</p>",
            "<p>Turing machines can be used to recognize all the languages</p>"
          ],
          "correct_answer": "<p>All the three languages are context free</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/2128/gate-cse-2011-question-26\" target=\"_blank\">https://gateoverflow.in/2128/gate-cse-2011-question-26</a></p>"
        },
        {
          "id": 18,
          "question": "<p><a name=\"1543\"></a><div itemprop=\"text\"><p>Consider the following languages.</p>\n\n<p>\\( L_1 = \\left \\{ 0^p1^q0^r \\mid p,q,r \\geq 0 \\right \\} \\)</p>\n\n<p>\\( L_2 = \\left \\{ 0^p1^q0^r \\mid p,q,r \\geq 0, p\\neq r \\right \\} \\)</p>\n\n<p>Which one of the following statements is <strong>FALSE</strong>?</p>\n\n</div><br><br><b>GATE CSE 2013 | Question: 32</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L_2 \\) is context-free.</p>",
            "<p>\\( L_1\\cap L_2 \\) is context-free.</p>",
            "<p>Complement of \\( L_2 \\) is recursive.</p>",
            "<p>Complement of \\( L_1 \\) is context-free but not regular.</p>"
          ],
          "correct_answer": "<p>Complement of \\( L_1 \\) is context-free but not regular.</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/1543/gate-cse-2013-question-32\" target=\"_blank\">https://gateoverflow.in/1543/gate-cse-2013-question-32</a></p>"
        },
        {
          "id": 19,
          "question": "<p><a name=\"2070\"></a><div itemprop=\"text\"><p>Consider the following languages over the alphabet \\( \\sum = \\{0, 1, c\\} \\)</p>\n\n<p>\\( L_1 &nbsp;= \\left\\{0^n1^n\\mid n \\geq 0\\right\\} \\)</p>\n\n<p>\\( L_2 = \\left\\{wcw^r \\mid w \\in \\{0,1\\}^*\\right\\} \\)</p>\n\n<p>\\( L_3 = \\left\\{ww^r \\mid w \\in \\{0,1\\}^*\\right\\} \\)</p>\n\n<p>Here, \\( w^r \\) is the reverse of the string \\( w \\).&nbsp;Which of these languages are deterministic Context-free languages?</p>\n\n</div><br><br><b>GATE CSE 2014 Set 3 | Question: 36</b></p>",
          "type": "single",
          "options": [
            "<p>None of the languages</p>",
            "<p>Only \\( L_1 \\)</p>",
            "<p>Only \\( L_1 \\) and \\( L_2 \\)</p>",
            "<p>All the three languages</p>"
          ],
          "correct_answer": "<p>Only \\( L_1 \\) and \\( L_2 \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/2070/gate-cse-2014-set-3-question-36\" target=\"_blank\">https://gateoverflow.in/2070/gate-cse-2014-set-3-question-36</a></p>"
        },
        {
          "id": 20,
          "question": "<p><a name=\"118320\"></a><div itemprop=\"text\"><p>Consider the context-free grammars over the alphabet \\( \\left \\{ a, b, c \\right \\} \\) given below. \\( S \\) and \\( T \\) are non-terminals.</p>\n\n<p>\\( G_{1}:S\\rightarrow aSb \\mid T, T \\rightarrow cT \\mid \\epsilon \\)</p>\n\n<p>\\( G_{2}:S\\rightarrow bSa \\mid T, T \\rightarrow cT \\mid \\epsilon \\)</p>\n\n<p>The language \\( L\\left ( G_{1} \\right )\\cap L(G_{2}) \\) is</p>\n\n</div><br><br><b>GATE CSE 2017 Set 1 | Question: 37</b></p>",
          "type": "single",
          "options": [
            "<p>Finite</p>",
            "<p>Not finite but regular</p>",
            "<p>Context-Free but not regular</p>",
            "<p>Recursive but not context-free</p>"
          ],
          "correct_answer": "<p>Not finite but regular</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/118320/gate-cse-2017-set-1-question-37\" target=\"_blank\">https://gateoverflow.in/118320/gate-cse-2017-set-1-question-37</a></p>"
        },
        {
          "id": 21,
          "question": "<p><a name=\"118615\"></a><div itemprop=\"text\"><p>Consider the following languages.</p>\n\n<ul>\n\t<li>\\( L_1 = \\{a^p \\mid p \\text{ is a prime number} \\} \\)</li>\n\t<li>\\( L_2 = \\{ a^nb^mc^{2m} \\mid n \\geq 0, m \\geq 0 \\} \\)</li>\n\t<li>\\( L_3 = \\{a^n b^n c^{2n} \\mid n \\geq 0 \\} \\)</li>\n\t<li>\\( L_4 = \\{ a^n b^n \\mid n \\geq 1\\} \\)</li>\n</ul>\n\n<p>Which of the following are CORRECT?</p>\n\n<ol style=\"list-style-type:upper-roman\">\n\t<li>\\( L_1 \\) is context free but not regular</li>\n\t<li>\\( L_2 \\) is not context free</li>\n\t<li>\\( L_3 \\) is not context free but recursive</li>\n\t<li>\\( L_4 \\) is deterministic context free</li>\n</ol>\n\n\n\n</div><br><br><b>GATE CSE 2017 Set 2 | Question: 40</b></p>",
          "type": "single",
          "options": [
            "<p>I, II and IV only</p>",
            "<p>II and III only</p>",
            "<p>I and IV only</p>",
            "<p>III and IV only</p>"
          ],
          "correct_answer": "<p>III and IV only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/118615/gate-cse-2017-set-2-question-40\" target=\"_blank\">https://gateoverflow.in/118615/gate-cse-2017-set-2-question-40</a></p>"
        },
        {
          "id": 22,
          "question": "<p><a name=\"204109\"></a><div itemprop=\"text\"><p>Consider the following languages:</p>\n\n<ol style=\"list-style-type:upper-roman\">\n\t<li>\\( \\{a^mb^nc^pd^q \\mid m+p=n+q, \\text{ where } m, n, p, q \\geq 0 \\} \\)</li>\n\t<li>\\( \\{a^mb^nc^pd^q \\mid m=n \\text{ and }p=q, \\text{ where } m, n, p, q \\geq 0 \\} \\)</li>\n\t<li>\\( \\{a^mb^nc^pd^q \\mid m=n =p \\text{ and } p \\neq q, \\text{ where } m, n, p, q \\geq 0 \\} \\)</li>\n\t<li>\\( \\{a^mb^nc^pd^q \\mid mn =p+q, \\text{ where } m, n, p, q \\geq 0 \\} \\)</li>\n</ol>\n\n<p>Which of the above languages are context-free?</p>\n\n</div><br><br><b>GATE CSE 2018 | Question: 35</b></p>",
          "type": "single",
          "options": [
            "<p>I and IV only</p>",
            "<p>I and II only</p>",
            "<p>II and III only</p>",
            "<p>II and IV only</p>"
          ],
          "correct_answer": "<p>I and II only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/204109/gate-cse-2018-question-35\" target=\"_blank\">https://gateoverflow.in/204109/gate-cse-2018-question-35</a></p>"
        },
        {
          "id": 23,
          "question": "<p><a name=\"333221\"></a><div itemprop=\"text\"><p>Consider the language \\( L&nbsp;= \\{a^{n}\\mid n \\geq 0\\}&nbsp;\\cup \\{a^{n}b^{n}\\mid n \\geq 0\\} \\) and the following statements.</p>\n\n<ol start=\"1\" style=\"list-style-type:upper-roman\">\n\t<li>\\( L \\) is deterministic context-free.</li>\n\t<li>\\( L \\) is context-free but not deterministic context-free.</li>\n\t<li>\\( L \\) is not \\( LL(k) \\) for any \\( k \\).</li>\n</ol>\n\n<p>&nbsp;Which of the above statements is/are TRUE?</p>\n\n</div><br><br><b>GATE CSE 2020 | Question: 10</b></p>",
          "type": "single",
          "options": [
            "<p>Ⅰ only</p>",
            "<p>Ⅱ only&nbsp;</p>",
            "<p>Ⅰ and&nbsp;Ⅲ only</p>",
            "<p>Ⅲ only</p>"
          ],
          "correct_answer": "<p>Ⅰ and&nbsp;Ⅲ only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/333221/gate-cse-2020-question-10\" target=\"_blank\">https://gateoverflow.in/333221/gate-cse-2020-question-10</a></p>"
        },
        {
          "id": 24,
          "question": "<p><a name=\"333199\"></a><div itemprop=\"text\"><p>Consider the following languages.</p>\n\n<p>\\[ \\begin{array}{ll} L_1= \\{ wxyx&nbsp;\\mid w,x,y&nbsp;\\in (0+1)^{+}&nbsp;\\} \\\\&nbsp;L_2= \\{xy \\mid x,y&nbsp;\\in (a+b)^{*}, \\mid x \\mid=\\mid y \\mid, x \\neq&nbsp;y \\} \\end{array} \\]</p>\n\n<p>Which one of the following is TRUE?</p>\n\n</div><br><br><b>GATE CSE 2020 | Question: 32</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L_1 \\) is regular and \\( L_2 \\) is context- free.</p>",
            "<p>\\( L_1 \\)&nbsp;context- free but not regular and&nbsp;\\( L_2 \\) is context-free.</p>",
            "<p>Neither \\( L_1 \\) nor \\( L_2 \\) is context- free.</p>",
            "<p>\\( L_1 \\)&nbsp;context- free but&nbsp; \\( L_2 \\) is not context-free.</p>"
          ],
          "correct_answer": "<p>\\( L_1 \\) is regular and \\( L_2 \\) is context- free.</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/333199/gate-cse-2020-question-32\" target=\"_blank\">https://gateoverflow.in/333199/gate-cse-2020-question-32</a></p>"
        },
        {
          "id": 25,
          "question": "<p><a name=\"357528\"></a><div itemprop=\"text\"><p>Let \\( L_1 \\) be a regular language and \\( L_2 \\) be a context-free language. Which&nbsp;of the following languages is/are context-free?</p></div><br><br><b>GATE CSE 2021 Set 2 | Question: 12</b></p>",
          "type": "multiple",
          "options": [
            "<p>\\( L_1 \\cap \\overline{L_2} \\)</p>",
            "<p>\\( \\overline{\\overline{L_1} \\cup \\overline{L_2}} \\)</p>",
            "<p>\\( L_1 \\cup (L_2 \\cup \\overline{L_2}) \\)</p>",
            "<p>\\( (L_1 \\cap L_2) \\cup (\\overline{L_1} \\cap L_2) \\)</p>"
          ],
          "correct_answer": [
            "<p>\\( \\overline{\\overline{L_1} \\cup \\overline{L_2}} \\)</p>",
            "<p>\\( L_1 \\cup (L_2 \\cup \\overline{L_2}) \\)</p>",
            "<p>\\( (L_1 \\cap L_2) \\cup (\\overline{L_1} \\cap L_2) \\)</p>"
          ],
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/357528/gate-cse-2021-set-2-question-12\" target=\"_blank\">https://gateoverflow.in/357528/gate-cse-2021-set-2-question-12</a></p>"
        },
        {
          "id": 26,
          "question": "<p><a name=\"371923\"></a><div itemprop=\"text\"><p>Which of the following statements is/are \\( \\text{TRUE}? \\)</p>\n\n</div><br><br><b>GATE CSE 2022 | Question: 13</b></p>",
          "type": "multiple",
          "options": [
            "<p>Every subset of a recursively enumerable language is recursive.</p>",
            "<p>If a language \\( \\textit{L} \\) and its complement \\( \\overline{\\textit{L}} \\) are both recursively enumerable, then \\( \\textit{L} \\) must be recursive.</p>",
            "<p>Complement of a context-free language must be recursive.</p>",
            "<p>If \\( \\textit{L}_{1} \\) and \\( \\textit{L}_{2} \\) are regular, then \\( \\textit{L}_{1} \\cap \\textit{L}_{2} \\) must be deterministic context-free.</p>"
          ],
          "correct_answer": [
            "<p>If a language \\( \\textit{L} \\) and its complement \\( \\overline{\\textit{L}} \\) are both recursively enumerable, then \\( \\textit{L} \\) must be recursive.</p>",
            "<p>Complement of a context-free language must be recursive.</p>",
            "<p>If \\( \\textit{L}_{1} \\) and \\( \\textit{L}_{2} \\) are regular, then \\( \\textit{L}_{1} \\cap \\textit{L}_{2} \\) must be deterministic context-free.</p>"
          ],
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/371923/gate-cse-2022-question-13\" target=\"_blank\">https://gateoverflow.in/371923/gate-cse-2022-question-13</a></p>"
        },
        {
          "id": 27,
          "question": "<p><a name=\"371899\"></a><div itemprop=\"text\"><p>Consider the following languages:</p>\n\n<p>\\( L_{1} = \\{ a^{n} wa^{n} | w \\in \\{a,b\\}^{\\ast}\\} \\)</p>\n\n<p>\\( L_{2} = \\{wxw^{R} | w, x \\in \\{a,b\\}^{*}, |w|, |x| &gt; 0 \\} \\)</p>\n\n<p>Note that \\( w^{R} \\) is the reversal of the string \\( w. \\) Which of the following is/are \\( \\text{TRUE}? \\)</p>\n\n</div><br><br><b>GATE CSE 2022 | Question: 37</b></p>",
          "type": "multiple",
          "options": [
            "<p>\\( L_{1} \\) and \\( L_{2} \\) are regular.</p>",
            "<p>\\( L_{1} \\) and \\( L_{2} \\) are context-free.</p>",
            "<p>\\( L_{1} \\) is regular and \\( L_{2} \\) is context-free.</p>",
            "<p>\\( L_{1} \\) and \\( L_{2} \\) are context-free but not regular.</p>"
          ],
          "correct_answer": [
            "<p>\\( L_{1} \\) and \\( L_{2} \\) are regular.</p>",
            "<p>\\( L_{1} \\) and \\( L_{2} \\) are context-free.</p>",
            "<p>\\( L_{1} \\) is regular and \\( L_{2} \\) is context-free.</p>"
          ],
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/371899/gate-cse-2022-question-37\" target=\"_blank\">https://gateoverflow.in/371899/gate-cse-2022-question-37</a></p>"
        },
        {
          "id": 28,
          "question": "<p><a name=\"399298\"></a><div itemprop=\"text\"><p>Which of the following statements is/are \\( \\text{CORRECT}? \\)</p>\n\n</div><br><br><b>GATE CSE 2023 | Question: 14</b></p>",
          "type": "multiple",
          "options": [
            "<p>The intersection of two regular languages is regular.</p>",
            "<p>The intersection of two context-free languages is context-free.</p>",
            "<p>The intersection of two recursive languages is recursive.</p>",
            "<p>The intersection of two recursively enumerable languages is recursively enumerable.</p>"
          ],
          "correct_answer": [
            "<p>The intersection of two regular languages is regular.</p>",
            "<p>The intersection of two recursive languages is recursive.</p>",
            "<p>The intersection of two recursively enumerable languages is recursively enumerable.</p>"
          ],
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/399298/gate-cse-2023-question-14\" target=\"_blank\">https://gateoverflow.in/399298/gate-cse-2023-question-14</a></p>"
        },
        {
          "id": 29,
          "question": "<p><a name=\"3748\"></a><div itemprop=\"text\"><p>Let \\( L \\) be a regular language and \\( M \\) be a context-free language, both over the alphabet \\( Σ \\). Let \\( L^c \\) and \\( M^c \\) denote the complements of \\( L \\) and \\( M \\) respectively. Which of the following statements about the language \\( L^c\\cup M^c \\) is TRUE?</p>\n\n</div><br><br><b>GATE IT 2005 | Question: 4</b></p>",
          "type": "single",
          "options": [
            "<p>It is necessarily regular but not necessarily context-free.</p>",
            "<p>It is necessarily context-free.</p>",
            "<p>It is necessarily non-regular.</p>",
            "<p>None of the above</p>"
          ],
          "correct_answer": "<p>None of the above</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/3748/gate-it-2005-question-4\" target=\"_blank\">https://gateoverflow.in/3748/gate-it-2005-question-4</a></p>"
        },
        {
          "id": 30,
          "question": "<p><a name=\"3751\"></a><div itemprop=\"text\"><p>The language \\( \\{0^n 1^n 2^n \\mid 1 \\leq n \\leq 10^6\\} \\) is</p>\n\n</div><br><br><b>GATE IT 2005 | Question: 6</b></p>",
          "type": "single",
          "options": [
            "<p>regular</p>",
            "<p>context-free but not regular</p>",
            "<p>context-free but its complement is not context-free</p>",
            "<p>not context-free</p>"
          ],
          "correct_answer": "<p>regular</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/3751/gate-it-2005-question-6\" target=\"_blank\">https://gateoverflow.in/3751/gate-it-2005-question-6</a></p>"
        },
        {
          "id": 31,
          "question": "<p><a name=\"3343\"></a><div itemprop=\"text\"><p>Consider the following languages.</p>\n\n<ul>\n\t<li>\\( L_1 = \\{a^i b^j c^k \\mid&nbsp;i = j, k \\geq&nbsp;1\\} \\)</li>\n\t<li>\\( L_2 = \\{a^i b^j \\mid&nbsp;j = 2i, i \\geq 0\\} \\)</li>\n</ul>\n\n<p>Which of the following is true?</p>\n\n</div><br><br><b>GATE IT 2008 | Question: 33</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L_1 \\) is not a CFL but \\( L_2 \\) is</p>",
            "<p>\\( L_1 \\cap&nbsp;L_2 = \\varnothing&nbsp; \\)&nbsp;and \\( L_1 \\) is non-regular</p>",
            "<p>\\( L_1 \\cup&nbsp;L_2 \\) is not a CFL but \\( L_2 \\) is</p>",
            "<p>There is a \\( 4 \\)-state PDA that accepts \\( L_1 \\), but there is no DPDA that accepts \\( L_2 \\).</p>"
          ],
          "correct_answer": "<p>\\( L_1 \\cap&nbsp;L_2 = \\varnothing&nbsp; \\)&nbsp;and \\( L_1 \\) is non-regular</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/3343/gate-it-2008-question-33\" target=\"_blank\">https://gateoverflow.in/3343/gate-it-2008-question-33</a></p>"
        }
      ]
    }
  ]
});
