window.__examLoadCallback({
  "title": "Theory of Computation - Context Free Grammar",
  "duration": 6,
  "sections": [
    {
      "name": "Context Free Grammar",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"460071\"></a><div itemprop=\"text\"><p>Consider the following context-free grammar \\( G \\), where \\( S, A \\), and \\( B \\) are the variables (non-terminals), \\( a \\) and \\( b \\) are the terminal symbols, \\( S \\) is the start variable, and the rules of \\( G \\) are described as:<br>\\[ &nbsp;\\begin{array}{l} S \\rightarrow a a B \\mid A b b \\\\ A \\rightarrow a \\mid a A \\\\ B \\rightarrow b \\mid b B \\end{array} \\]<br>Which ONE of the languages \\( L(G) \\) is accepted by \\( G \\) ?</p></div><br><br><b>GATE CSE 2025 | Set 1 | Question: 9</b></p>",
          "type": "single",
          "options": [
            "<p>\\( L(G)=\\left\\{a^{2} b^{n} \\mid n \\geq 1\\right\\} \\cup\\left\\{a^{n} b^{2} \\mid n \\geq 1\\right\\} \\)</p>",
            "<p>\\( L(G)=\\left\\{a^{n} b^{2 n} \\mid n \\geq 1\\right\\} \\cup\\left\\{a^{2 n} b^{n} \\mid n \\geq 1\\right\\} \\)</p>",
            "<p>\\( L(G)=\\left\\{a^{n} b^{n} \\mid n \\geq 1\\right\\} \\)</p>",
            "<p>\\( L(G)=\\left\\{a^{2 n} b^{2 n} \\mid n \\geq 1\\right\\} \\)</p>"
          ],
          "correct_answer": "<p>\\( L(G)=\\left\\{a^{2} b^{n} \\mid n \\geq 1\\right\\} \\cup\\left\\{a^{n} b^{2} \\mid n \\geq 1\\right\\} \\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/460071/gate-cse-2025-set-1-question-9\" target=\"_blank\">https://gateoverflow.in/460071/gate-cse-2025-set-1-question-9</a></p>"
        },
        {
          "id": 2,
          "question": "<p><a name=\"460820\"></a><div itemprop=\"text\"><p>​​​​Let \\( G_{1}, G_{2} \\) be Context Free Grammars (CFGs) and \\( R \\) be a regular expression. For a grammar \\( G \\), let \\( L(G) \\) denote the language generated by \\( G \\).<br><br>Which ONE among the following questions is decidable?</p></div><br><br><b>GATE CSE 2025 | Set 2 | Question: 15</b></p>",
          "type": "single",
          "options": [
            "<p>Is \\( L\\left(G_{1}\\right)=L\\left(G_{2}\\right) ? \\)</p>",
            "<p>Is \\( L\\left(G_{1}\\right) \\cap L\\left(G_{2}\\right)=\\emptyset \\) ?</p>",
            "<p>Is \\( L\\left(G_{1}\\right)=L(R) ? \\)</p>",
            "<p>Is \\( L\\left(G_{1}\\right)=\\emptyset \\) ?</p>"
          ],
          "correct_answer": "<p>Is \\( L\\left(G_{1}\\right)=\\emptyset \\) ?</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/460820/gate-cse-2025-set-2-question-15\" target=\"_blank\">https://gateoverflow.in/460820/gate-cse-2025-set-2-question-15</a></p>"
        }
      ]
    }
  ]
});
