window.__examLoadCallback({
  "title": "Theory_of_Computation - Theory_of_Computation - Slot 16",
  "duration": 42,
  "sections": [
    {
      "name": "Theory_of_Computation",
      "questions": [
        {
          "id": 1,
          "question": "<p>Let \\(M=(K, \\Sigma, \\Gamma, \\Delta, s, F)\\) be a pushdown automaton, where<br>\n\\(K=(s, f), F=\\{f\\}, \\Sigma=\\{a, b\\}, \\Gamma=\\{a\\} \\text { and }\\)<br>\n\\(\\Delta=\\{((s, a, \\epsilon),(s, a)),((s, b, \\epsilon),(s, a)),((s, a, a),(f, \\epsilon)),((f, a, a),(f, \\epsilon)) ((f, b, a),(f, \\epsilon))\\}\\)<br>Which one of the following strings is not a member of L(M)? <br><br><strong>(GATE IT 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>aaa</p>",
            "<b>B.</b> <p>aabab</p>",
            "<b>C.</b> <p>baaba</p>",
            "<b>D.</b> <p>bab</p>"
          ],
          "correct_answer": "<b>D.</b> <p>bab</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3683/gate2004-it-40\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Which one of the following statements is FALSE? <br><br><strong>(GATE IT 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>There exist context-free languages such that all the context-free grammars generating them are ambiguous</p>",
            "<b>B.</b> <p>An unambiguous context-free grammar always has a unique parse tree for each string of the language generated by it</p>",
            "<b>C.</b> <p>Both deterministic and non-deterministic pushdown automata always accept the same set of languages</p>",
            "<b>D.</b> <p>A finite set of string from some alphabet is always a regular language</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Both deterministic and non-deterministic pushdown automata always accept the same set of languages</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3650/gate2004-it-9\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Which one of the following regular expressions is NOT equivalent to the regular expression \\((a + b + c)^*?\\) <br><br><strong>(GATE IT 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\((a^* + b^* + c^*)^*\\)</p>",
            "<b>B.</b> <p>\\((a^*b^*c^*)^*\\)</p>",
            "<b>C.</b> <p>\\(((ab)^* + c^*)^*\\)</p>",
            "<b>D.</b> <p>\\((a^*b^* + c^*)^*\\)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>\\(((ab)^* + c^*)^*\\)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3648/gate2004-it-7\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>L1 is a recursively enumerable language over \\(\\Sigma\\). An algorithm A effectively enumerates its words as w1, w2, w3, ... define another language L2 over \\(\\Sigma\\)U{#} as <br> {wi # wj : wi, wj \\(\\in\\) L1, i \\(\\lt\\) j}.<br>  Here # is a new symbol. Consider the following assertions.<pre><code> S1 :  L1 is recursive implies L2 is recursive\nS2 : L2 is recursive implies L1 is recursive </code></pre> Which of the following statements is true ? <br><br><strong>(GATE CSE 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Both S1 and S2 are true</p>",
            "<b>B.</b> <p>S1 is true but S2 is not necessarily true</p>",
            "<b>C.</b> <p>S2 is true but S1 is not necessarily true</p>",
            "<b>D.</b> <p>Neither is necessarily true</p>"
          ],
          "correct_answer": "<b>A.</b> <p>Both S1 and S2 are true</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1083/gate2004-89#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Consider the following grammar G: <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Theory_of_Computation\\q88_01955160.jpg\"><br> Let Na(w) and Nb(w) denote the number of a's and b's in a string w respectively. <br>The language \\(L(G)\\subseteq \\{a,b\\}^{+}\\) generated by G is <br><br><strong>(GATE CSE 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>{ w | Na(w) \\(\\gt\\) 3Nb(w)}</p>",
            "<b>B.</b> <p>{ w | Nb(w) \\(\\gt\\) 3Na(w)}</p>",
            "<b>C.</b> <p>{ w | Na(w) = 3k, k \\(\\in\\) {0, 1, 2, ...}}</p>",
            "<b>D.</b> <p>{ w | Nb(w) = 3k, k \\(\\in\\) {0, 1, 2, ...}}</p>"
          ],
          "correct_answer": "<b>C.</b> <p>{ w | Na(w) = 3k, k \\(\\in\\) {0, 1, 2, ...}}</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1082/gate2004-88#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>The language {\\(a^{m}b^{n}c^{m+n}|m,n\\geq 1\\)} is <br><br><strong>(GATE CSE 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>regular</p>",
            "<b>B.</b> <p>context-free but not regular</p>",
            "<b>C.</b> <p>context sensitive but not context free</p>",
            "<b>D.</b> <p>type-0 but not context sensitive</p>"
          ],
          "correct_answer": "<b>B.</b> <p>context-free but not regular</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1081/gate2004-87#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>The following finite state machine accepts all those binary strings in which the number of 1's and 0's are respectively.  <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Theory_of_Computation\\q86_69a22ade.jpg\"> <br><br><strong>(GATE CSE 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>divisible by 3 and 2</p>",
            "<b>B.</b> <p>odd and even</p>",
            "<b>C.</b> <p>even and odd</p>",
            "<b>D.</b> <p>divisible by 2 and 3</p>"
          ],
          "correct_answer": "<b>A.</b> <p>divisible by 3 and 2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1080/gate2004-86#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>Which of the following grammar rules violate the requirements of an operator grammar? P, Q, R are\nnonterminals, and r,s,t are terminals.  <br> \\((i)P\\rightarrow QR \\)  <br> \\( (ii)P\\rightarrow QsR \\)  <br> \\( (iii)P\\rightarrow \\varepsilon \\)  <br> \\( (iv)P\\rightarrow QtRr \\) <br><br><strong>(GATE CSE 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>(i) only</p>",
            "<b>B.</b> <p>(i) and (iii) only</p>",
            "<b>C.</b> <p>(ii) and (iii) only</p>",
            "<b>D.</b> <p>(iii) and (iv) only</p>"
          ],
          "correct_answer": "<b>B.</b> <p>(i) and (iii) only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1005/gate2004-8#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>Consider the grammar shown below. <br>\nS \\(\\rightarrow\\) C C <br>\nC \\(\\rightarrow\\) cC | d <br>\nThe grammar is <br><br><strong>(GATE CSE 2003)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>LL(1)</p>",
            "<b>B.</b> <p>LALR (1) but not SLR (1)</p>",
            "<b>C.</b> <p>SLR (1) but not LL (1)</p>",
            "<b>D.</b> <p>LR (1) but not LALR (1)</p>"
          ],
          "correct_answer": "<b>A.</b> <p>LL(1)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/945/gate2003-57#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>Consider the NFA M shown below.<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Theory_of_Computation\\q55_99884634.jpg\"><br>   Let the language accepted by M be L. Let L1 be the language accepted by the NFA M1, obtained by changing the accepting state of M to a non-accepting state and by changing the non-accepting state of M to accepting states. Which of the following statements is true ? <br><br><strong>(GATE CSE 2003)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>L1 = {0, 1}* - L</p>",
            "<b>B.</b> <p>L1 = {0, 1}*</p>",
            "<b>C.</b> <p>\\(L1\\subseteq L\\)</p>",
            "<b>D.</b> <p>L1 = L</p>"
          ],
          "correct_answer": "<b>B.</b> <p>L1 = {0, 1}*</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/943/gate2003-55#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>Define languages L0 and L1 as follows :<pre><code>  L0 = {&lt; M, w, 0 &gt; | M halts on w}\nL1 = {&lt; M, w, 1 &gt; | M does not halts on w}   </code></pre>  Here  \\(&lt; M, w, i &gt;\\)\nis a triplet, whose first component. M is an encoding of a Turing Machine, second component, w, is a  string, and third component, i, is a bit. Let \\(L=L0 \\cup L1\\). Which of the following is true ? <br><br><strong>(GATE CSE 2003)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>L is recursively enumerable, but L' is not</p>",
            "<b>B.</b> <p>L' is recursively enumerable, but L is not</p>",
            "<b>C.</b> <p>Both L and L' are recursive</p>",
            "<b>D.</b> <p>Neither L nor L' is recursively enumerable</p>"
          ],
          "correct_answer": "<b>D.</b> <p>Neither L nor L' is recursively enumerable</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/355/gate2003-54#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>A single tape Turing Machine M has two states q0 and q1, of which q0 is the starting state. The tape alphabet of M is {0, 1, B} and its input alphabet is {0, 1}. The symbol B is the blank symbol used to indicate end of an input string. The transition function of M is described in the following table   <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Theory_of_Computation\\q53_abd93de7.jpg\"><br> The table is interpreted as illustrated below. The entry (q1, 1, R) in row q0 and column 1 signifies that if M is in state q0 and reads 1 on the current tape square, then it writes 1 on the same tape square, moves its tape head one position to the right and transitions to state q1. Which of the following statements is true about M ? <br><br><strong>(GATE CSE 2003)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>M does not halt on any string in (0 + 1)+</p>",
            "<b>B.</b> <p>M does not halt on any string in (00 + 1)*</p>",
            "<b>C.</b> <p>M halts on all string ending in a 0</p>",
            "<b>D.</b> <p>M halts on all string ending in a 1</p>"
          ],
          "correct_answer": "<b>A.</b> <p>M does not halt on any string in (0 + 1)+</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/941/gate2003-53#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>Consider two languages L1 and L2 each on the alphabet \\(\\Sigma\\). Let \\(f:\\Sigma \\rightarrow \\Sigma\\) be a polynomial time computable bijection such that \\((\\forall x)[x \\in L1 \\; \\; if \\; \\; f(x) \\in L2]\\). Further, let \\(f^{-1}\\) be also polynomial time computable. Which of the following CANNOT be true? <br><br><strong>(GATE CSE 2003)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>L1 \\(\\in\\) P and L2 is finite</p>",
            "<b>B.</b> <p>L1 \\(\\in\\)\nNP and L2 \\(\\in\\) P</p>",
            "<b>C.</b> <p>L1 is undecidable and L2 is decidable</p>",
            "<b>D.</b> <p>L1 is recursively enumerable and L2 is recursive</p>"
          ],
          "correct_answer": "<b>C.</b> <p>L1 is undecidable and L2 is decidable</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/356/gate2003-52#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>Let G = ({S}, {a, b} R, S) be a context free grammar where the rule set R is \\(S\\rightarrow aSb|SS|\\epsilon\\)<br>\nWhich of the following statements is true? <br><br><strong>(GATE CSE 2003)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>G is not ambiguous</p>",
            "<b>B.</b> <p>There exist x, y, \\(\\in\\) L (G) such that xy \\(\\notin\\) L(G)</p>",
            "<b>C.</b> <p>There is a deterministic pushdown automaton that accepts L(G)</p>",
            "<b>D.</b> <p>We can find a deterministic finite state automaton that accepts L(G)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>There is a deterministic pushdown automaton that accepts L(G)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/940/gate2003-51#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>Consider the following deterministic finite state automaton M. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Theory_of_Computation\\q50_fa81a7bc.jpg\"><br>  Let S denote the set of seven bit binary strings in which the first, the fourth, and\nthe last bits are 1. <br>The number of strings in S that are accepted by M is <br><br><strong>(GATE CSE 2003)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>1</p>",
            "<b>B.</b> <p>5</p>",
            "<b>C.</b> <p>7</p>",
            "<b>D.</b> <p>8</p>"
          ],
          "correct_answer": "<b>C.</b> <p>7</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/939/gate2003-50#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
