window.__examLoadCallback({
  "title": "Function - Function - Slot 5",
  "duration": 42,
  "sections": [
    {
      "name": "Function",
      "questions": [
        {
          "id": 1,
          "question": "<p>What does the following C-statement declare?<pre><code>int ( * f) (int * ) ; </code></pre> <br><br><strong>(GATE CSE 2005)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A function that takes an integer pointer as argument and returns an integer</p>",
            "<b>B.</b> <p>A function that takes an integer as argument and returns an integer pointer</p>",
            "<b>C.</b> <p>A pointer to a function that takes an integer pointer as argument and returns an integer.</p>",
            "<b>D.</b> <p>A function that takes an integer pointer as argument and returns a function pointer</p>"
          ],
          "correct_answer": "<b>C.</b> <p>A pointer to a function that takes an integer pointer as argument and returns an integer.</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1343/gate2005-1#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Consider the following C program:<br><pre><code>#include &lt; stdio.h &gt;\ntypedef struct {\n    char *a;\n    char *b;\n    } t;\nvoid f1 (t s);\nvoid f2 (t *p);\nmain()\n{\n    static t s = {\"A\", \"B\"};\n    printf (\"%s %s\\n\", s.a, s.b);\n    f1(s);\n    printf (\"%s %s\\n\", s.a, s.b);\n    f2(&amp;s);\n}\nvoid f1 (t s)\n{\n    s.a = \"U\";\n    s.b = \"V\";\n    printf (\"%s %s\\n\", s.a, s.b);\n    return;\n}\nvoid f2(t *p)\n{\n    p -&gt; a  = \"V\";\n    p -&gt; b = \"W\";\n    printf(\"%s %s\\n\", p -&gt; a, p -&gt; b);\n    return;\n}</code></pre> What is the output generated by the program ? <br><br><strong>(GATE IT 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>A  B <br>\nU  V<br>\nV  W<br>\nV  W</p>",
            "<b>B.</b> <p>A  B<br>\nU  V<br>\nA  B<br>\nV  W</p>",
            "<b>C.</b> <p>A  B<br>\nU  V<br>\nU  V<br>\nV  W</p>",
            "<b>D.</b> <p>A  B<br>\nU  V<br>\nV  W<br>\nU  V</p>"
          ],
          "correct_answer": "<b>B.</b> <p>A  B<br>\nU  V<br>\nA  B<br>\nV  W</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3704/gate2004-it-61\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Choose the correct option to fill the ?1 and ?2 so that the program prints an input string in reverse order. Assume that the input string is terminated by a new line character.<br><pre><code>#include &lt; stdio.h &gt;\nvoid wrt_it (void);\nint main (void)\n{\n    printf(\"Enter Text\"); \n    printf (\"\\n\");\n    wrt_it();\n    printf (\"\\n\");\n    return 0;\n}\nvoid wrt_it (void)\n{\n    int c;\n    if (?1)\n        wrt_it();\n    ?2\n} </code></pre> <br><br><strong>(GATE IT 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>?1 is  getchar()!= '\\n' <br>?2 is  getchar(c);</p>",
            "<b>B.</b> <p>?1 is  (c=getchar());!= '\\n'<br>?2 is  getchar(c);</p>",
            "<b>C.</b> <p>?1 is  c!= '\\n'<br>?2 is  putchar(c);</p>",
            "<b>D.</b> <p>?1 is  (c=getchar())!= '\\n'<br>?2 is  putchar(c);</p>"
          ],
          "correct_answer": "<b>D.</b> <p>?1 is  (c=getchar())!= '\\n'<br>?2 is  putchar(c);</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3703/gate2004-it-60\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>What is the output of the following program?<br><pre><code>#include &lt; stdio.h &gt;\nint funcf (int x);\nint funcg (int y);\nmain ()\n{\n    int x = 5, y = 10, count;\n    for (count = 1; count &lt;= 2; ++count) {\n        y += funcf(x) + funcg(x);\n        printf (\"%d\", y);\n    }\n}\nfuncf (int x) {\n    int y;\n    y = funcg(x);\n    return (y);\n}\nfuncg (int x) {\n    static int y = 10;\n    y += 1;\n    return (y + x);\n}\n </code></pre> <br><br><strong>(GATE IT 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>43 80</p>",
            "<b>B.</b> <p>42 74</p>",
            "<b>C.</b> <p>33 37</p>",
            "<b>D.</b> <p>32 32</p>"
          ],
          "correct_answer": "<b>A.</b> <p>43 80</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/3702/gate2004-it-59\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Consider the following C function:<pre><code> int f(int n)\n{\n   static int i = 1;\n   if (n &gt; = 5)\n      return n;\n   n = n+i;\n   i++;\n   return f(n);\n}</code></pre>\nThe value returned by f(1) is <br><br><strong>(GATE CSE 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>5</p>",
            "<b>B.</b> <p>6</p>",
            "<b>C.</b> <p>7</p>",
            "<b>D.</b> <p>8</p>"
          ],
          "correct_answer": "<b>C.</b> <p>7</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1028/gate2004-31#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>Consider the following C function<pre><code> void swap (int a, int b)\n{\n   int temp;\n   temp = a;\n   a = b;\n   b = temp;\n}</code></pre>\nIn order to exchange the values of two variables x and y. <br><br><strong>(GATE CSE 2004)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>call swap (x, y)</p>",
            "<b>B.</b> <p>call swap (&amp;x, &amp;y)</p>",
            "<b>C.</b> <p>swap (x,y) cannot be used as it does not return any value</p>",
            "<b>D.</b> <p>swap (x,y) cannot be used as the parameters are passed by value</p>"
          ],
          "correct_answer": "<b>D.</b> <p>swap (x,y) cannot be used as the parameters are passed by value</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/999/gate2004-2#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>Consider the C program shown below.<pre><code>  #include &lt; stdio.h &gt; \n#define print(x) printf(\"%d \", x)\nint x;\nvoid Q(int z)\n{\n    z += x;\n    print(z);\n}\nvoid P(int *y)\n{\n    int x = *y + 2;\n    Q(x);\n    *y = x - 1;\n    print(x);\n}\nmain(void)\n{\n    x = 5;\n    P(&amp;x);\n    print(x);\n}</code></pre>\nThe output of this program is <br><br><strong>(GATE CSE 2003)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>12 7 6</p>",
            "<b>B.</b> <p>22 12 11</p>",
            "<b>C.</b> <p>14 6 6</p>",
            "<b>D.</b> <p>7 6 6</p>"
          ],
          "correct_answer": "<b>A.</b> <p>12 7 6</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/972/gate2003-89#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>The following program fragment is written in a programming language that allows\nvariables and does not allow nested declarations of functions.<pre><code> global int i = 100, j = 5;\nvoid P(x)\n{\n    int i = 10;\n    print(x + 10);\n    i = 200;\n    j = 20;\n    print(x);\n}\nmain()\n{\n    P(i + j);\n} </code></pre> If the programming language uses dynamic scoping and call by name parameter\npassing mechanism, the values printed by the above program are <br><br><strong>(GATE CSE 2003)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>115,220</p>",
            "<b>B.</b> <p>25,220</p>",
            "<b>C.</b> <p>25,15</p>",
            "<b>D.</b> <p>115,105</p>"
          ],
          "correct_answer": "<b>A.</b> <p>115,220</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/43575/gate2003-74#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>The following program fragment is written in a programming language that allows\nvariables and does not allow nested declarations of functions.<pre><code> global int i = 100, j = 5;\nvoid P(x)\n{\n    int i = 10;\n    print(x + 10);\n    i = 200;\n    j = 20;\n    print(x);\n}\nmain()\n{\n    P(i + j);\n} </code></pre>\nIf the programming language uses static scoping and call by need parameter\npassing mechanism, the values printed by the above program are <br><br><strong>(GATE CSE 2003)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>115,220</p>",
            "<b>B.</b> <p>25,220</p>",
            "<b>C.</b> <p>25,15</p>",
            "<b>D.</b> <p>115,105</p>"
          ],
          "correct_answer": "<b>D.</b> <p>115,105</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/960/gate2003-73#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>The results returned by function under value-result and reference parameter\npassing conventions <br><br><strong>(GATE CSE 2002)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Do not differ</p>",
            "<b>B.</b> <p>Differ in the presence of loops</p>",
            "<b>C.</b> <p>Differ in all cases</p>",
            "<b>D.</b> <p>May differ in the presence of exception</p>"
          ],
          "correct_answer": "<b>D.</b> <p>May differ in the presence of exception</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/823/gate2002-1-18#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>The value of j at the end of the execution of the following C program:<br><pre><code> int incr (int i)\n{ \n    static int count = 0;\n    count = count + i;\n    return (count);\n} \nmain () { \n    int i, j; \n    for (i = 0; i &lt;= 4; i++)\n       j = incr (i);\n} </code></pre>\nis: <br><br><strong>(GATE CSE 2000)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>10</p>",
            "<b>B.</b> <p>4</p>",
            "<b>C.</b> <p>6</p>",
            "<b>D.</b> <p>7</p>"
          ],
          "correct_answer": "<b>A.</b> <p>10</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/667/gate2000-2-20\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>Consider the following C function definition<br><pre><code>int Trial (int a, int b, int c)\n{\n    if ((a&gt;=b) &amp;&amp; (c &lt; b)) return b;\n    else if (a &gt;= b) return Trial(a, c, b);\n    else return Trial(b, a, c);\n} </code></pre>The functional Trial: <br><br><strong>(GATE CSE 1999)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Finds the maximum of a, b, and c</p>",
            "<b>B.</b> <p>Finds the minimum of a, b, and c</p>",
            "<b>C.</b> <p>Finds the middle number of a, b, c</p>",
            "<b>D.</b> <p>None of the above</p>"
          ],
          "correct_answer": "<b>D.</b> <p>None of the above</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1501/gate1999-2-24\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>Consider the following program in a language that has dynamic scooping:<br><pre><code>var x: real;\nprocedure show:\n    begin print(x);end;\nprocedure small;\n    var x: real;\n        begin x: = 0.125; show; end;\nbegin x:=0.25\n    show; small\n    end. </code></pre>\nThen the output of the program is: <br><br><strong>(GATE CSE 1999)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0.125 0.125</p>",
            "<b>B.</b> <p>0.25 0.25</p>",
            "<b>C.</b> <p>0.25 0.125</p>",
            "<b>D.</b> <p>0.125 0.25</p>"
          ],
          "correct_answer": "<b>C.</b> <p>0.25 0.125</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1491/gate1999-2-13\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>What is the result of the following program?<br><pre><code>    program side-effect (input, output);\n    var x, result: integer;\n    function f (var x:integer:integer;\n    begin\n        x:x+1;f:=x;\n    end\n    begin\n    x:=5;\n    result:=f(x)*f(x);\n    writeln(result);\n    end</code></pre> <br><br><strong>(GATE CSE 1998)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>5</p>",
            "<b>B.</b> <p>25</p>",
            "<b>C.</b> <p>36</p>",
            "<b>D.</b> <p>42</p>"
          ],
          "correct_answer": "<b>C.</b> <p>36</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1685/gate1998-2-13\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>What value would the following function return for the input x=95?<br><pre><code> Function fun (x:integer):integer;\nBegin\n    If x &gt; 100 then fun = x- 10\n    Else fun = fun(fun (x+11))\nEnd;</code></pre> <br><br><strong>(GATE CSE 1998)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>89</p>",
            "<b>B.</b> <p>90</p>",
            "<b>C.</b> <p>91</p>",
            "<b>D.</b> <p>92</p>"
          ],
          "correct_answer": "<b>C.</b> <p>91</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1684/gate1998-2-12\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
