window.__examLoadCallback({
  "title": "Digital Logic - Excess 3",
  "duration": 3,
  "sections": [
    {
      "name": "Excess 3",
      "questions": [
        {
          "id": 1,
          "question": "<p><a name=\"58786\"></a><div itemprop=\"text\"><p>The Excess-\\( 3 \\) decimal code is a self-complementing code because&nbsp;</p>\n\n</div><br><br><b>Digital Logic: UGC NET CSE | December 2014 | Part 2 | Question: 07</b></p>",
          "type": "single",
          "options": [
            "<p>The binary sum of a code and its \\( 9's \\) complement is equal to \\( 9 \\).&nbsp;</p>",
            "<p>It is a weighted code.&nbsp;</p>",
            "<p>Complement can be generated by inverting each bit pattern.</p>",
            "<p>The binary sum of a code and its \\( 10's \\) complement is equal to \\( 9 \\).&nbsp;</p>"
          ],
          "correct_answer": "<p>The binary sum of a code and its \\( 9's \\) complement is equal to \\( 9 \\).&nbsp;</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<p><a href=\"https://gateoverflow.in/58786/ugc-net-cse-december-2014-part-2-question-07\" target=\"_blank\">https://gateoverflow.in/58786/ugc-net-cse-december-2014-part-2-question-07</a></p>"
        }
      ]
    }
  ]
});
