window.__examLoadCallback({
  "title": "Computer_Network - Computer_Network - Slot 7",
  "duration": 42,
  "sections": [
    {
      "name": "Computer_Network",
      "questions": [
        {
          "id": 1,
          "question": "<p>Which one of the following fields of an IP header is NOT modified by a typical IP router? <br><br><strong>(GATE CSE 2015 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Checksum</p>",
            "<b>B.</b> <p>Source address</p>",
            "<b>C.</b> <p>Time to Live (TTL)</p>",
            "<b>D.</b> <p>Length</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Source address</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/8220/gate2015-1-16#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 2,
          "question": "<p>Suppose that everyone in a group of N people wants to communicate secretly with the N-1 others using symmetric key cryptographic system. The communication between any two persons should not be decodable by the others in the group. The number of keys required in the system as a whole to satisfy the confidentiality requirement is <br><br><strong>(GATE CSE 2015 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>2N</p>",
            "<b>B.</b> <p>N(N-1)</p>",
            "<b>C.</b> <p>N(N-1)/2</p>",
            "<b>D.</b> <p>\\((N-1)^{2}\\)</p>"
          ],
          "correct_answer": "<b>C.</b> <p>N(N-1)/2</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/8244/gate2015-1-14#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 3,
          "question": "<p>Suppose two hosts use a TCP connection to transfer a large file. Which of the following statements is/are FALSE with respect to the TCP connection?<br>\nI. If the sequence number of a segment is m, then the sequence number of the subsequent segment is always m+1.<br>\nII. If the estimated round trip time at any given point of time is t sec, the value of the retransmission timeout is always set to greater than or equal to t sec. <br>\nIII. The size of the advertised window never changes during the course of the TCP connection.<br>\nIV. The number of unacknowledged bytes at the sender is always less than or equal to the advertised window. <br><br><strong>(GATE CSE 2015 SET-1)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>III only</p>",
            "<b>B.</b> <p>I and III only</p>",
            "<b>C.</b> <p>I and IV only</p>",
            "<b>D.</b> <p>II and IV only</p>"
          ],
          "correct_answer": "<b>B.</b> <p>I and III only</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/8217/gate2015-1-13#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 4,
          "question": "<p>An IP router with a Maximum Transmission Unit (MTU) of 1500 bytes has received an IP packet of size 4404 bytes with an IP header of length 20 bytes. The values of the relevant fields in the header of the third IP fragment generated by the router for this packet are <br><br><strong>(GATE CSE 2014 SET-3)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>MF bit: 0, Datagram Length: 1444; Offset: 370</p>",
            "<b>B.</b> <p>MF bit: 1, Datagram Length: 1424; Offset: 185</p>",
            "<b>C.</b> <p>MF bit: 1, Datagram Length: 1500; Offset: 370</p>",
            "<b>D.</b> <p>MF bit: 0, Datagram Length: 1424; Offset: 2960</p>"
          ],
          "correct_answer": "<b>A.</b> <p>MF bit: 0, Datagram Length: 1444; Offset: 370</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/2062/gate2014-3-28#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 5,
          "question": "<p>Every host in an IPv4 network has a 1-second resolution real-time clock with battery backup. Each host needs to generate up to 1000 unique identifiers per second. Assume that each host has a globally unique IPv4 address. Design a 50-bit globally unique ID for this purpose. After what period (in seconds) will the identifiers generated by a host wrap around? <br><br><strong>(GATE CSE 2014 SET-3)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "256",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/2061/gate2014-3-27#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 6,
          "question": "<p>An IP router implementing Classless Inter-domain routing (CIDR) receives a packet with address 131.23.151.76. The router's routing table has the following entries:  <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Computer_Network\\q26_07b51d41.jpg\">  <br> The identifier of the output interface on which this packet will be forwarded is _____. <br><br><strong>(GATE CSE 2014 SET-3)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "1",
          "marks": 2,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/2060/gate2014-3-26#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 7,
          "question": "<p>Host A (on TCP/IP v4 network A) sends an IP datagram D to host B (also on TCP/IP V4\nnetwork B). Assume that no error occurred during the transmission of D. When D reaches B, which of the following IP header field(s) may be different from that of the original datagram D?<br>\n(i) TTL <br>(ii) Checksum <br> (iii) Fragment Offset <br><br><strong>(GATE CSE 2014 SET-3)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>(i) only</p>",
            "<b>B.</b> <p>(i) and (ii) only</p>",
            "<b>C.</b> <p>(ii) and (iii) only</p>",
            "<b>D.</b> <p>(i), (ii) and (iii)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>(i), (ii) and (iii)</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2059/gate2014-3-25#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 8,
          "question": "<p>A bit-stuffing based framing protocol uses an 8-bit delimiter pattern of 01111110. If the output bit-string after stuffing is 01111100101, then the input bit-string is <br><br><strong>(GATE CSE 2014 SET-3)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>0111110100</p>",
            "<b>B.</b> <p>0111110101</p>",
            "<b>C.</b> <p>0111111101</p>",
            "<b>D.</b> <p>0111111111</p>"
          ],
          "correct_answer": "<b>B.</b> <p>0111110101</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2058/gate2014-3-24#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 9,
          "question": "<p>In the following pairs of OSI protocol layer/sub-layer and its functionality, the\nINCORRECT pair is <br><br><strong>(GATE CSE 2014 SET-3)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Network layer and Routing</p>",
            "<b>B.</b> <p>Data Link Layer and Bit synchronization</p>",
            "<b>C.</b> <p>Transport layer and End-to-end process communication</p>",
            "<b>D.</b> <p>Medium Access Control sub-layer and Channel sharing</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Data Link Layer and Bit synchronization</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/2057/gate2014-3-23#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 10,
          "question": "<p>A graphical HTML browser resident at a network client machine Q accesses a static HTML\nwebpage from a HTTP server S. The static HTML page has exactly one static embedded\nimage which is also at S. Assuming no caching, which one of the following is correct about\nthe HTML webpage loading (including the embedded image)? <br><br><strong>(GATE CSE 2014 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Q needs to send at least 2 HTTP requests to S, each necessarily in a separate TCP\nconnection to server S</p>",
            "<b>B.</b> <p>Q needs to send at least 2 HTTP requests to S, but a single TCP connection to server S is sufficient</p>",
            "<b>C.</b> <p>A single HTTP request from Q to S is sufficient, and a single TCP connection between Q and S is necessary for this</p>",
            "<b>D.</b> <p>A single HTTP request from Q to S is sufficient, and this is possible without any TCP connection between Q and S</p>"
          ],
          "correct_answer": "<b>B.</b> <p>Q needs to send at least 2 HTTP requests to S, but a single TCP connection to server S is sufficient</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/1987/gate2014-2-28#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 11,
          "question": "<p>An IP machine Q has a path to another IP machine H via three IP routers R1, R2, and R3. <br>\nQ---R1---R2---R3---H  <br>\nH acts as an HTTP server, and Q connects to H via HTTP and downloads a file. Session layer\nencryption is used, with DES as the shared key encryption protocol. Consider the following\nfour pieces of information: <br>\n[I1] The URL of the file downloaded by Q <br>\n[I2] The TCP port numbers at Q and H <br>\n[I3] The IP addresses of Q and H <br>\n[I4] The link layer addresses of Q and H <br>\nWhich of I1, I2, I3, and I4 can an intruder learn through sniffing at R2 alone? <br><br><strong>(GATE CSE 2014 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>Only I1 and I2</p>",
            "<b>B.</b> <p>Only I1</p>",
            "<b>C.</b> <p>Only I2 and I3</p>",
            "<b>D.</b> <p>Only I3 and I4</p>"
          ],
          "correct_answer": "<b>C.</b> <p>Only I2 and I3</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/1986/gate2014-2-27#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 12,
          "question": "<p>Consider the store and forward packet switched network given below. Assume that the\nbandwidth of each link is \\(10^{6}\\) bytes / sec. A user on host A sends a file of size \\(10^{3}\\) bytes to\nhost B through routers R1 and R2 in three different ways. In the first case a single packet\ncontaining the complete file is transmitted from A to B. In the second case, the file is split\ninto 10 equal parts, and these packets are transmitted from A to B. In the third case, the file is split into 20 equal parts and these packets are sent from A to B. Each packet contains 100\nbytes of header information along with the user data. Consider only transmission time and\nignore processing, queuing and propagation delays. Also assume that there are no errors\nduring transmission. Let T1, T2 and T3 be the times taken to transmit the file in the first,\nsecond and third case respectively. Which one of the following is CORRECT?<br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Computer_Network\\q26_e2bbe577.jpg\"> <br><br><strong>(GATE CSE 2014 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>\\(T1 \\lt T2 \\lt T3\\)</p>",
            "<b>B.</b> <p>\\(T1 \\gt T2 \\gt T3\\)</p>",
            "<b>C.</b> <p>\\(T2=T3, T3 \\lt T1\\)</p>",
            "<b>D.</b> <p>\\(T1=T3, T3 \\gt T2\\)</p>"
          ],
          "correct_answer": "<b>D.</b> <p>\\(T1=T3, T3 \\gt T2\\)</p>",
          "marks": 2,
          "negative_marks": 0.67,
          "explanation": "<a href=\"https://gateoverflow.in/1985/gate2014-2-26#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 13,
          "question": "<p>In the diagram shown below, L1 is an Ethernet LAN and L2 is a Token-Ring LAN. An IP\npacket originates from sender S and traverses to R, as shown. The links within each ISP and\nacross the two ISPs, are all point-to-point' optical links. The initial value of the TTL field is\n32. The maximum possible value of the TTL field when R receives the datagram is\n____________. <br><img style=\"max-width:50%;height:auto;border-radius:8px;\" data-lazyloaded=\"1\" decoding=\"async\" src=\"images\\gatePYQ\\Computer_Network\\q25_4b42d41a.jpg\"> <br><br><strong>(GATE CSE 2014 SET-2)</strong></p>",
          "type": "numeric",
          "options": [],
          "correct_answer": "26",
          "marks": 1,
          "negative_marks": 0,
          "explanation": "<a href=\"https://gateoverflow.in/1983/gate2014-2-25#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 14,
          "question": "<p>Which one of the following socket API functions converts an unconnected active TCP socket\ninto a passive socket? <br><br><strong>(GATE CSE 2014 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>connect</p>",
            "<b>B.</b> <p>bind</p>",
            "<b>C.</b> <p>listen</p>",
            "<b>D.</b> <p>accept</p>"
          ],
          "correct_answer": "<b>C.</b> <p>listen</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1982/gate2014-2-24#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        },
        {
          "id": 15,
          "question": "<p>Which one of the following is TRUE about the interior gateway routing protocols - Routing\nInformation Protocol (RIP) and Open Shortest Path First (OSPF)? <br><br><strong>(GATE CSE 2014 SET-2)</strong></p>",
          "type": "single",
          "options": [
            "<b>A.</b> <p>RIP uses distance vector routing and OSPF uses link state routing</p>",
            "<b>B.</b> <p>OSPF uses distance vector routing and RIP uses link state routing</p>",
            "<b>C.</b> <p>Both RIP and OSPF use link state routing</p>",
            "<b>D.</b> <p>Both RIP and OSPF use distance vector routing</p>"
          ],
          "correct_answer": "<b>A.</b> <p>RIP uses distance vector routing and OSPF uses link state routing</p>",
          "marks": 1,
          "negative_marks": 0.33,
          "explanation": "<a href=\"https://gateoverflow.in/1981/gate2014-2-23#a_list\" targer=\"_blank\" target=\"_blank\" rel=\"noopener\">Click here for detail solution by gateoverflow</a>"
        }
      ]
    }
  ]
});
